### ISSUE TITLE
[Issue]: Settings don't save after changed

### ISSUE THREAD

**Issue by ngovandang** [vladmandic/automatic#1025]
### Issue Description

After upgraded today
I tried to turn off **Use full precision for model (--no-half)**, apply settings and restart server, even close and relaunch but this setting still on by default. **Use full precision for model (--no-half)** settings are reset back to default after applied and restarted server or relaunch.
I also have this error whenever I restart server

21:10:19-878707 WARNING  WebSocket closed (ignore asyncio.exceptions.CancelledError)
Traceback (most recent call last):
  File "C:\vladmandic\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "C:\vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\vladmandic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\vladmandic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError

### Version Platform Description

AMD Radeon RX 6600M
Google Chrome, Version 113.0.5672.93 (Official Build) (64-bit)
Windows 11, version 22H2.
Version: 554f2629 Wed May 17 08:46:57 2023 -0400

**Comment by vladmandic** [comment]
settting is forced if device does not pass fp16 test.
start `webui --debug` and you'll see something like this:

```log
10:48:25-759701 DEBUG    Verifying Torch settings
10:48:25-760737 DEBUG    Torch FP16 test passed
10:48:25-761271 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False
10:48:25-761845 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
10:48:25-762389 DEBUG    Torch default device: cuda
```

**Comment by ngovandang** [comment]
> setting is forced if device does not pass fp16 test. start `webui --debug` and you'll see something like this:
> 
> ```
> 10:48:25-759701 DEBUG    Verifying Torch settings
> 10:48:25-760737 DEBUG    Torch FP16 test passed
> 10:48:25-761271 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False
> 10:48:25-761845 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
> 10:48:25-762389 DEBUG    Torch default device: cuda
> ```

mine is:

```2023-05-17 22:48:21,388 | DEBUG | C:\vladmandic\modules\devices.py | Verifying Torch settings
2023-05-17 22:48:22,144 | DEBUG | C:\vladmandic\modules\devices.py | Torch FP16 test passed
2023-05-17 22:48:22,146 | DEBUG | C:\vladmandic\modules\devices.py | Desired Torch parameters: dtype=FP16 no-half=True no-half-vae=True upscast=True
2023-05-17 22:48:22,147 | INFO | C:\vladmandic\modules\devices.py | Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
2023-05-17 22:48:22,148 | DEBUG | C:\vladmandic\modules\devices.py | Torch default device: privateuseone:0```

**Comment by vladmandic** [comment]
ok. and when you change the setting and press apply, you should see the message in console:
> 12:10:10-710999 INFO     Settings changed: 1 ['no_half']

**Comment by vladmandic** [comment]
that is really strange. what are your command line parameters?

**Comment by ngovandang** [comment]
> that is really strange. what are your command line parameters?

--use-directml --autolaunch --medvram

**Comment by vladmandic** [comment]
nothing there. i though that maybe --share or --listen would lock config.json.
can you delete `config.json`? it will be recreated with defaults on the next startup.

**Comment by ngovandang** [comment]
> ah, sorry, just noticed `--use-directml` - this app forces **fp32** for directml as its really buggy in **fp16** because `directml` does not implement true `autocast`, it will stay forced. i just couldn't leave it enabled and deal with 10+ issues/day "why does my lora look bad", etc.

I see, I was generating everything fine for whole week before decided to upgrade to lastest repo

**Comment by vladmandic** [comment]
you were one of the lucky ones. i just cannot please all and there were truly too many issues with fp16 in directml.

**Comment by ngovandang** [comment]
> you were one of the lucky ones. i just cannot please all and there were truly too many issues with fp16 in directml.

so I remove directml and still they can't be disabled
I will give up then
literally still generating fine before upgrading
