### ISSUE TITLE
[Issue]: --device-id doesn't choose GPU, and SD defaults to CPU

### ISSUE THREAD

**Issue by pingpongching** [vladmandic/automatic#1047]
### Issue Description

I have 2 AMD GPUs, first-RX570 4gb, second-RX580 8gb. Have been successfully using a webui-user.bat with:
```
@echo off

set COMMANDLINE_ARGS= --device-id 1 --medvram

call webui.bat
```
to choose the RX580 as the GPU for interference till' May 12, today updated using "--upgrade", and interference is defaulting to CPU, even with --device-id 1 flag, changing the device id to 0 or 2 didn't do anything and it still went to CPU for interference.

Also tried adding "--use-directml" to flags, but it starts to curse at me for not having "torch_directml", here's the console during startup:
```
Using VENV: C:\Users\gololo\automatic\venv
04:36:00-872361 INFO     Starting SD.Next
04:36:00-876350 INFO     Python 3.10.11 on Windows
04:36:00-913252 INFO     Version: 1dffd114 Wed May 17 15:38:12 2023 -0400
04:36:01-292248 INFO     Setting environment tuning
04:36:01-293246 INFO     Using DirectML Backend
04:36:02-517509 INFO     Torch 2.0.1+cpu
04:36:02-519503 WARNING  Torch reports CUDA not available
04:36:02-520500 INFO     Verifying requirements
04:36:02-537455 INFO     Installing packages
04:36:02-559396 INFO     No changes detected: Quick launch active
04:36:02-560394 INFO     Running extension preloading
04:36:02-561391 INFO     Server arguments: ['--device-id', '1', '--medvram', '--use-directml']
No module 'xformers'. Proceeding without it.
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\gololo\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "C:\Users\gololo\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "C:\Users\gololo\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "C:\Users\gololo\automatic\launch.py", line 144, in <module>
    instance = start_server(immediate=True, server=None)
  File "C:\Users\gololo\automatic\launch.py", line 116, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\gololo\automatic\webui.py", line 30, in <module>
    from modules import import_hook # pylint: disable=W0611,C0411,C0412
  File "C:\Users\gololo\automatic\modules\import_hook.py", line 2, in <module>
    from modules.shared import opts, log
  File "C:\Users\gololo\automatic\modules\shared.py", line 615, in <module>
    devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan, devices.device_codeformer = (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_optimal_device() for x in ['sd', 'interrogate', 'gfpgan', 'esrgan', 'codeformer'])
  File "C:\Users\gololo\automatic\modules\shared.py", line 615, in <genexpr>
    devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan, devices.device_codeformer = (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_optimal_device() for x in ['sd', 'interrogate', 'gfpgan', 'esrgan', 'codeformer'])
  File "C:\Users\gololo\automatic\modules\devices.py", line 54, in get_optimal_device
    return torch.device(get_optimal_device_name())
  File "C:\Users\gololo\automatic\modules\devices.py", line 42, in get_optimal_device_name
    import torch_directml # pylint: disable=import-error
ModuleNotFoundError: No module named 'torch_directml'
```
Tried adding "pip install torch_directml" to webui-user.bat like this:
```
@echo off

set COMMANDLINE_ARGS= --device-id 1 --medvram --use-directml
pip install torch_directml
call webui.bat
```
It installed the torch_directml to venv, but the console still was cursing at me with "ModuleNotFoundError: No module named 'torch_directml'"

### Version Platform Description

Win 10 pro
Dual GPU, top slot:RX570 4gb, bottom slot:RX580 8gb
Python 3.10.11
Version: 1dffd114 Wed May 17 15:38:12 2023 -0400
AMD driver version: 23.4.3

**Comment by pingpongching** [comment]
This is what i mean't by "defaults to CPU" when not using --use-derectml:
```
Using VENV: C:\Users\gololo\automatic\venv
05:17:15-260406 INFO     Starting SD.Next
05:17:15-264396 INFO     Python 3.10.11 on Windows
05:17:15-301297 INFO     Version: 1dffd114 Wed May 17 15:38:12 2023 -0400
05:17:15-677301 INFO     Setting environment tuning
05:17:15-689269 INFO     Using CPU-only Torch
05:17:16-905048 INFO     Torch 2.0.1+cpu
05:17:16-907043 INFO     Verifying requirements
05:17:16-923504 INFO     Installing packages
05:17:16-946443 INFO     No changes detected: Quick launch active
05:17:16-947440 INFO     Running extension preloading
05:17:16-948437 INFO     Server arguments: ['--device-id', '1', '--medvram']
No module 'xformers'. Proceeding without it.
05:17:21-350280 INFO     Libraries loaded
05:17:21-355267 INFO     Available VAEs: C:\Users\gololo\automatic\models\VAE 4
05:17:21-368232 INFO     Available models: C:\Users\gololo\automatic\models\Stable-diffusion 8
05:17:23-154504 WARNING  Torch FP16 test failed: Forcing FP32 operations
05:17:23-156499 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
Loading weights: C:\Users\gololo\automatic\models\Stable-diffusion\AOM3-grapefruitv4_40.safetensors ----- 0.0/2… -:--:…
                                                                                                          GB
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
05:17:23-698565 INFO     Model created from config: C:\Users\gololo\automatic\configs\v1-inference.yaml
Loading weights: C:\Users\gololo\automatic\models\VAE\klF8Anime2VAE.ckpt ---------------- ------ 283.0/404.7 MB 0:00:00
05:17:24-457570 INFO     Applying sub-quadratic cross attention optimization
05:17:24-473527 INFO     Embeddings loaded: 10 ['bad-artist-anime', 'bad-hands-5', 'bad-image-v2-39000', 'bad_quality',
                         'badhandv4', 'easynegative', 'ng_deepnegative_v1_75t', 'PlanIt_diagrams', 'verybadimagenegative_v1.3',
                         'vile_prompt3']
05:17:24-482503 INFO     Model loaded in 1.6s (load=0.5s create=0.4s apply=0.5s vae=0.3s)
05:17:24-642580 INFO     Model load finished: {'ram': {'used': 7.25, 'total': 31.84}}
ControlNet v1.1.174
ControlNet v1.1.174
Image Browser: ImageReward is not installed, cannot be used.
05:17:25-842402 INFO     Loading UI theme: gradio/default
05:17:31-242603 ERROR    Exception refreshing UI themes
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
05:17:32-899217 INFO     Local URL: http://127.0.0.1:7860/
05:17:32-900719 INFO     API Docs: http://127.0.0.1:7860/docs
05:17:32-901716 INFO     Initializing middleware
05:17:33-369477 INFO     Startup time: 16.4s (torch=2.5s gradio=1.2s libraries=0.6s codeformer=0.1s scripts=4.3s opts onchange=0.1s ui=6.9s start=0.2s scripts
                         app_started_callback=0.1s checkpoint=0.4s)
05:17:33-372469 INFO     Memory used: 5.39 total: 31.84
```

**Comment by Maxime-Turin** [comment]
Hi, 
I had the same problem, it seems that there is a conflict between directml and torch.
It's ok in my case when i run webui.bat with those arguments : 

```
webui.bat --use-directml --skip-torch
```

I hope I've helped you !

**Comment by vladmandic** [comment]
this is not about device id at all, this is about wrong torch.

`torch-directml` was default only for a brief period. since 12th, you need to specify it explicitly using `use-directml`.
but the problem is that by running `webui` without `--use-directml`, it already installed **cpu-only** version of torch and it will not change torch version unless you specify `--reinstall` as well.

so in short, start `webui --use-directml --reinstall` to install correct torch once and then you can use `webui --use-directml --device-id 1`

**Comment by pingpongching** [comment]
Ah, got it, was just used to it automatically using GPU, without writing a flag. But anyways, this fixed my issue, thank you!

**Comment by vladmandic** [comment]
the thing is, if nvidia toolkit is detected, its safe to assume that user wants to use it. same if rocm toolkit is detect.
but if no gpu toolkit is detected, should we automatically go for directml? maybe user wants to use ipex instead? maybe he actually wants to use cpu? etc... that's why `--use-directml` needs to be explicit.
