### ISSUE TITLE
[Issue]: Maximum supported image dimension is 65500 pixels

### ISSUE THREAD

**Issue by tkittich** [vladmandic/automatic#1048]
### Issue Description

Got an error during X/Y/Z script generating a really large file. Then the program stops responding.

07:08:12-316067 WARNING  Image size: (142956, 6298) excedes 200.0 MPixels
Maximum supported image dimension is 65500 pixels
Exception in thread Thread-15 (atomically_save_image):
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\theera\aiart\automatic\modules\images.py", line 439, in atomically_save_image
    image.save(fn, format=image_format, quality=shared.opts.jpeg_quality, exif=exif_bytes)
  File "D:\theera\aiart\automatic\venv\lib\site-packages\PIL\Image.py", line 2432, in save
    save_handler(self, fp, filename)
  File "D:\theera\aiart\automatic\venv\lib\site-packages\PIL\JpegImagePlugin.py", line 806, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "D:\theera\aiart\automatic\venv\lib\site-packages\PIL\ImageFile.py", line 517, in _save
    _encode_tile(im, fp, tile, bufsize, fh)
  File "D:\theera\aiart\automatic\venv\lib\site-packages\PIL\ImageFile.py", line 547, in _encode_tile
    raise OSError(msg) from exc
OSError: encoder error -2 when writing image file

### Version Platform Description

Version: 6c271dcf Wed May 17 07:16:11 2023 -0400, Windows 11, Brave, RTX 3090

**Comment by ShyRed** [comment]
Seems to be expected behaviour as [JPEG supports a maximum image size of 65,535×65,535 pixels](https://en.wikipedia.org/wiki/JPEG#:~:text=JPEG%20files%20usually%20have%20a,aspect%20ratio%20of%201%3A1.).

**Comment by vladmandic** [comment]
its exactly like @ShyRed said.
additionally, app already printed a warning. i'll make modification so it aborts after it prints the warning instead of causing a runtime error. other than that, i cannot do anything.
