### ISSUE TITLE
[ControlNet]: Unable to Use

### ISSUE THREAD

**Issue by cwb78** [vladmandic/automatic#1061]
### Issue Description

ControlNet was working for me just a couple days ago. As of yesterday, however, I cannot generate images using ControlNet. I've tried several different preprocessors and models, including canny, depth, and reference_only. I can't even generate a preprocessor preview image. Below is a copy of the terminal output when I attempt a canny preview, for example. 

Traceback (most recent call last):
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:/VladMandic/automatic/extensions-builtin/sd-webui-controlnet\scripts\controlnet.py", line 424, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\components.py", line 1792, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\processing_utils.py", line 52, in decode_base64_to_image
    exif = img.getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\PngImagePlugin.py", line 1028, in getexif
    return super().getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 1455, in getexif
    self._exif.load(exif_info)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 3719, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v2(self.head)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\TiffImagePlugin.py", line 507, in __init__
    raise SyntaxError(msg)
SyntaxError: not a TIFF file (header b"b'Exif\\x" not valid)
Traceback (most recent call last):
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:/VladMandic/automatic/extensions-builtin/sd-webui-controlnet\scripts\controlnet.py", line 424, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\components.py", line 1792, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\processing_utils.py", line 52, in decode_base64_to_image
    exif = img.getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\PngImagePlugin.py", line 1028, in getexif
    return super().getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 1455, in getexif
    self._exif.load(exif_info)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 3719, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v2(self.head)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\TiffImagePlugin.py", line 507, in __init__
    raise SyntaxError(msg)
SyntaxError: not a TIFF file (header b"b'Exif\\x" not valid)
Traceback (most recent call last):
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:/VladMandic/automatic/extensions-builtin/sd-webui-controlnet\scripts\controlnet.py", line 424, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\components.py", line 1792, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\processing_utils.py", line 52, in decode_base64_to_image
    exif = img.getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\PngImagePlugin.py", line 1028, in getexif
    return super().getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 1455, in getexif
    self._exif.load(exif_info)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 3719, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v2(self.head)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\TiffImagePlugin.py", line 507, in __init__
    raise SyntaxError(msg)
SyntaxError: not a TIFF file (header b"b'Exif\\x" not valid)
Traceback (most recent call last):
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:/VladMandic/automatic/extensions-builtin/sd-webui-controlnet\scripts\controlnet.py", line 424, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\components.py", line 1792, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\processing_utils.py", line 52, in decode_base64_to_image
    exif = img.getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\PngImagePlugin.py", line 1028, in getexif
    return super().getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 1455, in getexif
    self._exif.load(exif_info)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 3719, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v2(self.head)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\TiffImagePlugin.py", line 507, in __init__
    raise SyntaxError(msg)
SyntaxError: not a TIFF file (header b"b'Exif\\x" not valid)
Traceback (most recent call last):
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:/VladMandic/automatic/extensions-builtin/sd-webui-controlnet\scripts\controlnet.py", line 424, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\components.py", line 1792, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\processing_utils.py", line 52, in decode_base64_to_image
    exif = img.getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\PngImagePlugin.py", line 1028, in getexif
    return super().getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 1455, in getexif
    self._exif.load(exif_info)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 3719, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v2(self.head)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\TiffImagePlugin.py", line 507, in __init__
    raise SyntaxError(msg)
SyntaxError: not a TIFF file (header b"b'Exif\\x" not valid)
Traceback (most recent call last):
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:/VladMandic/automatic/extensions-builtin/sd-webui-controlnet\scripts\controlnet.py", line 424, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\components.py", line 1792, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "C:\VladMandic\automatic\venv\lib\site-packages\gradio\processing_utils.py", line 52, in decode_base64_to_image
    exif = img.getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\PngImagePlugin.py", line 1028, in getexif
    return super().getexif()
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 1455, in getexif
    self._exif.load(exif_info)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\Image.py", line 3719, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v2(self.head)
  File "C:\VladMandic\automatic\venv\lib\site-packages\PIL\TiffImagePlugin.py", line 507, in __init__
    raise SyntaxError(msg)
SyntaxError: not a TIFF file (header b"b'Exif\\x" not valid)

### Version Platform Description

Program Version: 
updated: 2023-05-18
hash: 8b682183
url: https://github.com/vladmandic/automatic/tree/master

Using DirectML backend

Torch:
2.0.0+cpu Autocast  nohalf

System/OS:
arch: AMD64
cpu: AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD Ryzen 5 1600X
RAM: 16GB
gpu: AMD Radeon RX 6700XT
system: Windows
release: Windows-10-10.0.19044-SP0
python: 3.10.9

### URL link of the extension

https://github.com/Mikubill/sd-webui-controlnet.git

**Comment by vladmandic** [comment]
this is a very generic error saying that your input image is not a valid image file at all. and its happening deep inside controlnet without calling any of the app functions. if the problem persists, create issue on controlnet repo.

**Comment by cwb78** [comment]
Thanks. I tried a couple other input images and it worked. So weird. I've used that image before... Oh well. Thanks again!

**Comment by vladmandic** [comment]
btw, it would be a valid feature request to open on controlnet so it does some file checks instead of dumping this entire traceback which is meaningless to normal users.
