### ISSUE TITLE
[Issue]: Error when execute SadTalker

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#1076]
### Issue Description

**While execute got this error:**

AttributeError: module 'numpy' has no attribute 'float'.
np.float was a deprecated alias for the builtin float. To avoid this error in existing code, use float by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.float64 here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Here is the full list:**

C:\vlad\automatic\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
C:\vlad\automatic\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
C:\vlad\automatic\extensions\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
C:\Users\Public\Documents\Wondershare\CreatorTemp\gradio\e648b24cb5df7103ff5a4a7287b7affd98f1e794\tmpeck_h143.png
landmark Det:: 0%| | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
File "C:\vlad\automatic\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
output = await app.get_blocks().process_api(
File "C:\vlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
result = await self.call_function(
File "C:\vlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
prediction = await anyio.to_thread.run_sync(
File "C:\vlad\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "C:\vlad\automatic\venv\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread
return await future
File "C:\vlad\automatic\venv\lib\site-packages\anyio_backends_asyncio.py", line 867, in run
result = context.run(func, *args)
File "C:\vlad\automatic\modules\call_queue.py", line 15, in f
res = func(*args, **kwargs)
File "C:\vlad\automatic/extensions/SadTalker\src\gradio_demo.py", line 111, in test
first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess)
File "C:\vlad\automatic/extensions/SadTalker\src\utils\preprocess.py", line 122, in generate
lm = self.kp_extractor.extract_keypoint(frames_pil, landmarks_path)
File "C:\vlad\automatic/extensions/SadTalker\src\face3d\extract_kp_videos_safe.py", line 39, in extract_keypoint
current_kp = self.extract_keypoint(image)
File "C:\vlad\automatic/extensions/SadTalker\src\face3d\extract_kp_videos_safe.py", line 65, in extract_keypoint
keypoints = landmark_98_to_68(self.detector.get_landmarks(img)) # [0]
File "C:\vlad\automatic\venv\lib\site-packages\facexlib\alignment\awing_arch.py", line 373, in get_landmarks
pred = calculate_points(heatmaps).reshape(-1, 2)
File "C:\vlad\automatic\venv\lib\site-packages\facexlib\alignment\awing_arch.py", line 18, in calculate_points
preds = preds.astype(np.float, copy=False)
File "C:\vlad\automatic\venv\lib\site-packages\numpy_init_.py", line 305, in getattr
raise AttributeError(former_attrs[attr])
AttributeError: module 'numpy' has no attribute 'float'.
np.float was a deprecated alias for the builtin float. To avoid this error in existing code, use float by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.float64 here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### Version Platform Description

Version: 527dc0ee Thu May 18 19:46:11 2023 -0400

**Comment by ShmuelRonen** [comment]
https://github.com/OpenTalker/SadTalker

**Comment by ShmuelRonen** [comment]
Sorry that I no put it on Extensions

**Comment by vladmandic** [comment]
SadTalker extension is simply not compatible with newer `numpy` and needs to be updated by author. I cannot downgrade core dependencies to keep old extensions happy.

**Comment by ShmuelRonen** [comment]
I sent the error there as well. In the meantime, how can I downgrade Numpi so I can use the extension?

**Comment by vladmandic** [comment]
you can modify `requirements.txt`.

**Comment by ShmuelRonen** [comment]
To what version (If you know)?

**Comment by ShmuelRonen** [comment]
I downgrade numpy to 1.21.6 as in sadtalker requirements.txt, but thr error continue...

**Comment by ShmuelRonen** [comment]
Unfortunately I couldn't get it to work. Hopefully the SadTalker developers will start addressing the issues that are piling up.

**Comment by nathanisayas** [comment]
why is it showing error as it has been showing error for the last 3 days. i am using vinthony sad talker and every time i press generate it says application is too busy. i have attached a screenshot of my screen. please get back to me as soon as possible

<img width="1280" alt="Screenshot 2023-11-29 at 05 23 15" src="https://github.com/vladmandic/automatic/assets/152363868/60172177-8db6-463f-863e-74830b5c5318">

**Comment by vladmandic** [comment]
> why is it showing error as it has been showing error for the last 3 days. i am using vinthony sad talker and every time i press generate it says application is too busy. i have attached a screenshot of my screen. please get back to me as soon as possible
> 
> <img width="1280" alt="Screenshot 2023-11-29 at 05 23 15" src="https://github.com/vladmandic/automatic/assets/152363868/60172177-8db6-463f-863e-74830b5c5318">
> 

Don't post on unrelated issue that is closed for 6 months now.

**Comment by TijuanaKez** [comment]
Alright this was getting frustrating, but with a lil help from ChatGPT....

```
cd stable-diffusion-webui/extensions/SadTalker

find . -name "*.py" -exec sed -i 's/np\.float/float/g' {} \;
find . -name "*.py" -exec sed -i 's/np\.float32/np.dtype("float32")/g' {} \;
find . -name "*.py" -exec sed -i 's/np\.float64/np.dtype("float64")/g' {} \;
```

then in 
`stable-diffusion-webui/extensions/SadTalker/src/face3d/util/preprocess.py`
replace
`trans_params = np.array([w0, h0, s, t[0], t[1]])`
with
`trans_params = np.array([w0, h0, s, t[0].item(), t[1].item()])`

**Comment by kainatquaderee** [comment]
> Alright this was getting frustrating, but with a lil help from ChatGPT....
> 
> ```
> cd stable-diffusion-webui/extensions/SadTalker
> 
> find . -name "*.py" -exec sed -i 's/np\.float/float/g' {} \;
> find . -name "*.py" -exec sed -i 's/np\.float32/np.dtype("float32")/g' {} \;
> find . -name "*.py" -exec sed -i 's/np\.float64/np.dtype("float64")/g' {} \;
> ```
> 
> then in `stable-diffusion-webui/extensions/SadTalker/src/face3d/util/preprocess.py` replace `trans_params = np.array([w0, h0, s, t[0], t[1]])` with `trans_params = np.array([w0, h0, s, t[0].item(), t[1].item()])`

you forgot final part np\.float32 is wrong it should be np.float32 and for me I had to do a 
 find . -name "*.py" -exec sed -i 's/float32/float/g' {} \; in the end
