### ISSUE TITLE
[Issue]: Cannot create or train embeddings or hypernetworks

### ISSUE THREAD

**Issue by emiletetrt** [vladmandic/automatic#1111]
### Issue Description

I'm unsure when but I can no longer create embeddings or train embeddings/hypernetworks. When I press the button to create the following is produced in the command window:

Traceback (most recent call last):
  File "D:\automatic\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\automatic\modules\textual_inversion\ui.py", line 9, in create_embedding
    filename = modules.textual_inversion.textual_inversion.create_embedding(name, nvpt, overwrite_old, init_text=initialization_text)
  File "D:\automatic\modules\textual_inversion\textual_inversion.py", line 260, in create_embedding
    cond_model([""])  # will send cond model to GPU if lowvram/medvram is active
  File "D:\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\automatic\modules\sd_hijack_clip.py", line 181, in forward
    z = self.process_tokens(tokens, multipliers)
  File "D:\automatic\modules\sd_hijack_clip.py", line 203, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "D:\automatic\modules\sd_hijack_clip.py", line 246, in encode_with_transformers
    clip_skip = opts.data['clip_skip'] or 1
KeyError: 'clip_skip'

I have tried running with --safe but no difference.
Also attempted with all default settings but same, no difference.

Is there any way to fix this?
Thanks in advance!

### Version Platform Description

Version: 26b05ef8 Sun May 21 10:07:12 2023 -0400
OS: W11 22H2
RTX 2080Ti
Chrome Browser
Python 3.10

**Comment by vladmandic** [comment]
yeah, thats my issue. i'll fix it tomorrow.

**Comment by pinballelectronica** [comment]
Do you know what commit you broke it? :)

**Comment by vladmandic** [comment]
not from the top of my head, but it was in the last 2 days.

**Comment by pinballelectronica** [comment]
Gonna go with:

commit 8b682183e32ed533546c016491d20342c790bf56
Author: Vladimir Mandic <mandic00@live.com>
Date:   Thu May 18 10:41:24 2023 -0400

    update gradio

**Comment by pinballelectronica** [comment]
BTW, awesome work on this.

**Comment by vladmandic** [comment]
cause is in df65e8e, any older should work. i'll fix it tomorrow.

**Comment by vladmandic** [comment]
should be fixed now.
