### ISSUE TITLE
[Built-in Extension]: Tiled Diffusion Region Promt Control config

### ISSUE THREAD

**Issue by sebaxakerhtc** [vladmandic/automatic#1182]
### Issue Description

When click save in region prompt control it uses default path "extensions" instead of "extensions-builtin" and after restart there's an error about extensions duplicate
`WARNING  Extensions duplicates: ['multidiffusion-upscaler-for-automatic1111']`
Because from now we have a folder named `multidiffusion-upscaler-for-automatic1111` in both folders `extensions` and `extensions-builtin`

### Version Platform Description

Windows

### URL link of the extension

Built-in, but anyway
https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111

**Comment by vladmandic** [comment]
awaiting pr merge upstream: <https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/pull/221>

**Comment by vladmandic** [comment]
fixed.

**Comment by sebaxakerhtc** [comment]
Now savr doesn't wkrk at all...
![Screenshot_20230527_225516_Firefox](https://github.com/vladmandic/automatic/assets/32651506/15215944-17fd-488e-9d49-cb05cd8d792d)

**Comment by sebaxakerhtc** [comment]
Doesn't work for both:
Original auto1111
```
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 554, in load_regions
    fp = CFG_PATH / cfg_name
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
and your fork:
```
Traceback (most recent call last):
  File "D:\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 554, in load_regions
    fp = CFG_PATH / cfg_name
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

**Comment by sebaxakerhtc** [comment]
[Fixed](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/223#issuecomment-1566025411)
