### ISSUE TITLE
[Issue]: 299f1229 PSD Fails to Save

### ISSUE THREAD

**Issue by xedis** [vladmandic/automatic#1278]
### Issue Description

2023-06-02 19:34:48,062 | sd | INFO | installer | Version: 299f1229 Fri Jun 2 20:54:09 2023 -0400

When saving as PSD event fails. I was unable to find where in the code the functionality for PSD was explicitly added, figured it might be a component of another module or something as I didn't see it present in image.py

```
19:46:42-474456 DEBUG    gc: collected=17697 device=cuda {'ram': {'used': 3.3, 'total': 125.72}, 'gpu': {'used': 3.91, 'total': 11.76}, 'retries': 0, 'oom': 0}
19:46:42-831149 DEBUG    gc: collected=124 device=cuda {'ram': {'used': 3.3, 'total': 125.72}, 'gpu': {'used': 3.92, 'total': 11.76}, 'retries': 0, 'oom': 0}
19:46:42-832427 INFO     Startup time: 32.7s (torch=2.3s gradio=0.8s libraries=1.1s models=0.5s scripts=17.8s onchange=0.1s ui=8.6s launch=0.2s scripts app_started_callback=0.4s checkpoint=0.7s)
19:47:59-900688 DEBUG    Server alive: True Memory used: 3.3 total: 125.72
19:50:00-002978 DEBUG    Server alive: True Memory used: 3.3 total: 125.72
19:52:00-108371 DEBUG    Server alive: True Memory used: 3.3 total: 125.72
Authorization required, but no authorization protocol specified

19:52:14-137472 DEBUG    gc: collected=2260 device=cuda {'ram': {'used': 3.31, 'total': 125.72}, 'gpu': {'used': 4.01, 'total': 11.76}, 'retries': 0, 'oom': 0}
19:52:14-139467 DEBUG    txt2img:
                         id_task=task(ww2duszz0l3xf1h)|prompt=|negative_prompt=|prompt_styles=[]|steps=20|sampler_index=7|restore_faces=False|tiling=False|n_iter=1|batch_size=1|cfg_scale=6|clip_skip=1|seed=-1.0|subseed=-1.0|subseed_strength=0|seed_resize_from_h=0|seed_resize_from_w=0|seed_enable_extras=False|height=
                         512|width=512|enable_hr=False|denoising_strength=0.7|hr_scale=2|hr_upscaler=Latent|hr_second_pass_steps=0|hr_resize_x=0|hr_resize_y=0|override_settings_texts=[]args=(0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False,
                         False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 2048, 128, True, True, True, False, False, 7, 100, 'Constant', 0, 'Constant', 0,
                         4, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f817a3e26e0>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, 50)
19:52:14-147315 DEBUG    Script process: ['Tiled Diffusion', 'Tiled VAE', 'Dynamic Thresholding (CFG Scale Fix)', 'ControlNet']
19:52:14-148799 DEBUG    Script before-process-batch: ['Tiled Diffusion', 'Tiled VAE', 'Dynamic Thresholding (CFG Scale Fix)', 'ControlNet']
19:52:14-150037 DEBUG    Script process-batch: ['Tiled Diffusion', 'Tiled VAE', 'Dynamic Thresholding (CFG Scale Fix)', 'ControlNet']
Progress 3.9it/s ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:05
19:52:21-052422 DEBUG    Script postprocess-batch: ['Tiled Diffusion', 'Tiled VAE', 'Dynamic Thresholding (CFG Scale Fix)', 'ControlNet']
19:52:21-058555 DEBUG    Script postprocess-image: ['Tiled Diffusion', 'Tiled VAE', 'Dynamic Thresholding (CFG Scale Fix)', 'ControlNet']
19:52:21-063839 DEBUG    Saving image: JPEG /home/vlad/a2/automatic/outputs/text/01270-974271098-.jpg (512, 512)
19:52:21-452015 DEBUG    gc: collected=772 device=cuda {'ram': {'used': 5.54, 'total': 125.72}, 'gpu': {'used': 4.09, 'total': 11.76}, 'retries': 0, 'oom': 0}
19:52:21-453965 DEBUG    Script postprocess: ['Tiled Diffusion', 'Tiled VAE', 'Dynamic Thresholding (CFG Scale Fix)', 'ControlNet']
19:52:21-455175 DEBUG    Processed: 1 Memory: {'ram': {'used': 5.54, 'total': 125.72}, 'gpu': {'used': 4.09, 'total': 11.76}, 'retries': 0, 'oom': 0} txt
19:52:21-828454 DEBUG    gc: collected=271 device=cuda {'ram': {'used': 5.54, 'total': 125.72}, 'gpu': {'used': 4.1, 'total': 11.76}, 'retries': 0, 'oom': 0}
19:52:31-194393 INFO     Settings changed: 51 ['samples_format', 'grid_format', 'ldsr_steps', 'ldsr_cached', 'SWIN_tile', 'SWIN_tile_overlap', 'sd_lyco', 'sd_lora', 'lora_preferred_name', 'lora_add_hashes_to_infotext', 'lora_functional', 'queue_paused', 'queue_button_placement', 'queue_button_hide_checkpoint',
                         'control_net_model_config', 'control_net_model_adapter_config', 'control_net_detectedmap_dir', 'control_net_models_path', 'control_net_modules_path', 'control_net_max_models_num', 'control_net_model_cache_size', 'control_net_no_detectmap', 'control_net_detectmap_autosaving',
                         'control_net_allow_script_control', 'control_net_sync_field_args', 'controlnet_show_batch_images_in_ui', 'controlnet_increment_seed_during_batch', 'controlnet_disable_control_type', 'image_browser_active_tabs', 'image_browser_hidden_components', 'image_browser_with_subdirs',
                         'image_browser_preload', 'image_browser_copy_image', 'image_browser_delete_message', 'image_browser_txt_files', 'image_browser_debug_level', 'image_browser_delete_recycle', 'image_browser_scan_exif', 'image_browser_mod_shift', 'image_browser_mod_ctrl_shift', 'image_browser_enable_maint',
                         'image_browser_ranking_pnginfo', 'image_browser_page_columns', 'image_browser_page_rows', 'image_browser_pages_perload', 'image_browser_use_thumbnail', 'image_browser_thumbnail_size', 'image_browser_swipe', 'image_browser_img_tooltips', 'image_browser_scoring_type',
                         'image_browser_show_progress']
19:52:35-528833 DEBUG    gc: collected=612 device=cuda {'ram': {'used': 5.54, 'total': 125.72}, 'gpu': {'used': 4.11, 'total': 11.76}, 'retries': 0, 'oom': 0}
19:52:35-531049 DEBUG    txt2img:
                         id_task=task(5gf2aoeyfjfn5z2)|prompt=|negative_prompt=|prompt_styles=[]|steps=20|sampler_index=7|restore_faces=False|tiling=False|n_iter=1|batch_size=1|cfg_scale=6|clip_skip=1|seed=-1.0|subseed=-1.0|subseed_strength=0|seed_resize_from_h=0|seed_resize_from_w=0|seed_enable_extras=False|height=
                         512|width=512|enable_hr=False|denoising_strength=0.7|hr_scale=2|hr_upscaler=Latent|hr_second_pass_steps=0|hr_resize_x=0|hr_resize_y=0|override_settings_texts=[]args=(0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False,
                         False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 2048, 128, True, True, True, False, False, 7, 100, 'Constant', 0, 'Constant', 0,
                         4, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f817a4fad70>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, 50)
19:52:35-535945 DEBUG    Script process: ['Tiled Diffusion', 'Tiled VAE', 'Dynamic Thresholding (CFG Scale Fix)', 'ControlNet']
19:52:35-536800 DEBUG    Script before-process-batch: ['Tiled Diffusion', 'Tiled VAE', 'Dynamic Thresholding (CFG Scale Fix)', 'ControlNet']
19:52:35-537575 DEBUG    Script process-batch: ['Tiled Diffusion', 'Tiled VAE', 'Dynamic Thresholding (CFG Scale Fix)', 'ControlNet']
Progress 6.05it/s ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:03
19:52:39-046622 DEBUG    Script postprocess-batch: ['Tiled Diffusion', 'Tiled VAE', 'Dynamic Thresholding (CFG Scale Fix)', 'ControlNet']
19:52:39-052888 DEBUG    Script postprocess-image: ['Tiled Diffusion', 'Tiled VAE', 'Dynamic Thresholding (CFG Scale Fix)', 'ControlNet']
19:52:39-057048 DEBUG    Saving image: PSD /home/vlad/a2/automatic/outputs/text/01271-2722714277-.psd (512, 512)
Exception in thread Thread-2 (atomically_save_image):
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vlad/a2/automatic/modules/images.py", line 458, in atomically_save_image
    image.save(fn, format=image_format, quality=shared.opts.jpeg_quality)
  File "/home/vlad/a2/automatic/venv/lib/python3.10/site-packages/PIL/Image.py", line 2419, in save
    save_handler = SAVE[format.upper()]
KeyError: 'PSD'
19:53:59-591715 DEBUG    Server alive: True Memory used: 5.55 total: 125.72

```

### Version Platform Description

[webui.log](https://github.com/vladmandic/automatic/files/11641483/webui.log)
Freshly pulled recent commits and updated my system.
```

                   -`                    root@arch 
                  .o+`                   --------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 6.3.2-arch1-1 
               `+oooooo:                 Uptime: 2 days, 22 hours, 53 mins 
               -+oooooo+:                Packages: 2029 (pacman), 51 (flatpak) 
             `/:-:++oooo+:               Shell: zsh 5.9 
            `/++++/+++++++:              Resolution: 1920x1080, 2560x1440, 2560x1440 
           `/++++++++++++++:             DE: KDE 
          `/+++ooooooooooooo/`           WM: KWin 
         ./ooosssso++osssssso+`          Theme: [KDE], Adwaita [GTK2/3] 
        .oossssso-````/ossssss+`         Icons: [KDE], Adwaita [GTK2/3] 
       -osssssso.      :ssssssso.        Terminal: terminator 
      :osssssss/        osssso+++.       CPU: AMD Ryzen 5 3600 (12) @ 3.800GHz 
     /ossssssss/        +ssssooo/-       GPU: NVIDIA GeForce RTX 3060 
   `/ossssso+/:-        -:/+osssso+-     Memory: 26553MiB / 128732MiB 
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/                           
 .`                                 `/                           


```

**Comment by vladmandic** [comment]
i have to remove psd, it seems that on some systems, its read-only due to patents. other new formats work.
