### ISSUE TITLE
[Issue]: SyntaxError: invalid syntax, WEBUI won't start

### ISSUE THREAD

**Issue by TomerGadol** [vladmandic/automatic#1286]
### Issue Description

When launching the webui I get the following error: `SyntaxError: invalid syntax`.
Full error is 
`Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\tomer\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "C:\Users\tomer\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "C:\Users\tomer\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "C:\Users\tomer\automatic\launch.py", line 149, in <module>
    instance = start_server(immediate=True, server=None)
  File "C:\Users\tomer\automatic\launch.py", line 121, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\tomer\automatic\webui.py", line 36, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints # pylint: disable=C0411,C0412
  File "C:\Users\tomer\automatic\modules\ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "C:\Users\tomer\automatic\modules\ui_extra_networks.py", line 8, in <module>
    from modules.generation_parameters_copypaste import image_from_url_text
  File "C:\Users\tomer\automatic\modules\generation_parameters_copypaste.py", line 9, in <module>
    from modules import shared, ui_tempdir, script_callbacks, images
  File "C:\Users\tomer\automatic\modules\images.py", line 17, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors, paths
  File "C:\Users\tomer\automatic\modules\sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, sd_samplers_diffusors, shared
  File "C:\Users\tomer\automatic\modules\sd_samplers_kdiffusion.py", line 4, in <module>
    import k_diffusion.sampling
  File "C:\Users\tomer\automatic\repositories\k-diffusion\k_diffusion\__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "C:\Users\tomer\automatic\repositories\k-diffusion\k_diffusion\config.py", line 8, in <module>
    from . import augmentation, layers, models, utils
  File "C:\Users\tomer\automatic\repositories\k-diffusion\k_diffusion\layers.py", line 8, in <module>
    from . import sampling, utils
  File "C:\Users\tomer\automatic\repositories\k-diffusion\k_diffusion\sampling.py", line 609
    <<<<<<< Updated upstream
    ^^`

### Version Platform Description

Version: 42656925 Sat Jun 3 17:02:41 2023 +0300
Windows 10, Nvidia 1660TI.

**Comment by vladmandic** [comment]
something went really bad. delete `C:\Users\tomer\automatic\repositories\k-diffusion` and let it be reinitialized.

**Comment by TomerGadol** [comment]
Alright it's working again, thanks!
