### ISSUE TITLE
[Issue]: Lots and lots of errors upon starting up the server. Even more after trying to load up or refresh the ui.

### ISSUE THREAD

**Issue by dchatel** [vladmandic/automatic#1342]
### Issue Description

I'm trying to figure what's going on, but at first glance there could be two issues:
- one with the extension manager
- one with the task scheduler.

```
20:18:14-047749 INFO     Starting SD.Next
20:18:14-050750 INFO     Python 3.10.9 on Windows
20:18:14-080749 INFO     Version: aaa0d462 Wed Jun 7 13:26:19 2023 -0400
20:18:14-412859 INFO     Updating main repository
20:18:15-514145 INFO     Upgraded to version: eaeb5453 Wed Jun 7 21:16:11 2023 +0300
20:18:15-515147 INFO     Setting environment tuning
20:18:15-518145 INFO     nVidia CUDA toolkit detected
20:18:16-646145 INFO     Torch 2.0.0+cu118
20:18:16-661146 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8901
20:18:16-662145 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
20:18:16-664145 INFO     Verifying requirements
20:18:16-674146 INFO     Verifying packages
20:18:16-678145 INFO     Extension preload: 0.0s G:\ai\automatic\extensions-builtin
20:18:16-680146 INFO     Extension preload: 0.0s G:\ai\automatic\extensions
20:18:16-681145 INFO     Running setup
20:18:16-682148 INFO     Installing repositories
20:18:19-353003 INFO     Installing submodules
20:18:20-778003 INFO     Updating submodules
20:18:27-351951 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
20:18:43-764340 INFO     Enabled extensions: ['a1111-sd-webui-tagcomplete', 'adetailer', 'SD-CN-Animation', 'sd-webui-regional-prompter', 'sd-webui-supermerger', 'stable-diffusion-webui-embedding-merge',
                         'stable-diffusion-webui-model-toolkit', 'ultimate-upscale-for-automatic1111', 'vid-faceswap']
20:18:52-528682 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR', 'a1111-sd-webui-tagcomplete', 'adetailer', 'SD-CN-Animation', 'sd-webui-regional-prompter', 'sd-webui-supermerger', 'stable-diffusion-webui-embedding-merge',
                         'stable-diffusion-webui-model-toolkit', 'ultimate-upscale-for-automatic1111', 'vid-faceswap']
20:18:52-530681 INFO     Updating Wiki
20:18:53-723860 INFO     Server arguments: ['--upgrade']
No module 'xformers'. Proceeding without it.
20:18:59-192858 INFO     Libraries loaded
20:18:59-195858 INFO     Using data path: G:\ai\automatic
20:18:59-198859 INFO     Available VAEs: G:\ai\models\VAE 7
20:18:59-222858 INFO     Available models: G:\ai\models\Stable-diffusion 20
20:19:01-585860 INFO     ControlNet v1.1.219
ControlNet preprocessor location: G:\ai\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
20:19:01-718858 INFO     ControlNet v1.1.219
[-] ADetailer initialized. version: 23.6.2, num models: 8
20:19:03-705013 INFO     Libraries loaded
20:19:04-342013 INFO     Loading UI theme: name=gradio/default style=Auto
20:19:05-402014 ERROR    Calling script: G:\ai\automatic\extensions\sd-webui-regional-prompter\scripts\rp.py/ui: AttributeError
╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ G:\ai\automatic\modules\scripts.py:249 in wrap_call                                                                                                                                                  │
│                                                                                                                                                                                                      │
│   248 │   try:                                                                                                                                                                                       │
│ ❱ 249 │   │   res = func(*args, **kwargs)                                                                                                                                                            │
│   250 │   │   return res                                                                                                                                                                             │
│                                                                                                                                                                                                      │
│ G:\ai\automatic\extensions\sd-webui-regional-prompter\scripts\rp.py:323 in ui                                                                                                                        │
│                                                                                                                                                                                                      │
│   322 │   │   │   w, h = self.t2i_w, self.t2i_h                                                                                                                                                      │
│ ❱ 323 │   │   maketemp.click(fn=makeimgtmp, inputs =[ratios,mmode,usecom,usebase,w,h],outputs                                                                                                        │
│   324 │   │   applypresets.click(fn=setpreset, inputs = [availablepresets, *settings], outputs                                                                                                       │
│                                                                                                                                                                                                      │
│                                                                                       ... 1 frames hidden ...                                                                                        │
│                                                                                                                                                                                                      │
│ C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py:267 in set_event_trigger                                                                                                      │
│                                                                                                                                                                                                      │
│    266 │   │   │   "trigger": event_name,                                                                                                                                                            │
│ ❱  267 │   │   │   "inputs": [block._id for block in inputs],                                                                                                                                        │
│    268 │   │   │   "outputs": [block._id for block in outputs],                                                                                                                                      │
│                                                                                                                                                                                                      │
│ C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py:267 in <listcomp>                                                                                                             │
│                                                                                                                                                                                                      │
│    266 │   │   │   "trigger": event_name,                                                                                                                                                            │
│ ❱  267 │   │   │   "inputs": [block._id for block in inputs],                                                                                                                                        │
│    268 │   │   │   "outputs": [block._id for block in outputs],                                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute '_id'
20:19:05-889013 ERROR    Calling script: G:\ai\automatic\extensions\sd-webui-regional-prompter\scripts\rp.py/ui: AttributeError
╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ G:\ai\automatic\modules\scripts.py:249 in wrap_call                                                                                                                                                  │
│                                                                                                                                                                                                      │
│   248 │   try:                                                                                                                                                                                       │
│ ❱ 249 │   │   res = func(*args, **kwargs)                                                                                                                                                            │
│   250 │   │   return res                                                                                                                                                                             │
│                                                                                                                                                                                                      │
│ G:\ai\automatic\extensions\sd-webui-regional-prompter\scripts\rp.py:323 in ui                                                                                                                        │
│                                                                                                                                                                                                      │
│   322 │   │   │   w, h = self.t2i_w, self.t2i_h                                                                                                                                                      │
│ ❱ 323 │   │   maketemp.click(fn=makeimgtmp, inputs =[ratios,mmode,usecom,usebase,w,h],outputs                                                                                                        │
│   324 │   │   applypresets.click(fn=setpreset, inputs = [availablepresets, *settings], outputs                                                                                                       │
│                                                                                                                                                                                                      │
│                                                                                       ... 1 frames hidden ...                                                                                        │
│                                                                                                                                                                                                      │
│ C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py:267 in set_event_trigger                                                                                                      │
│                                                                                                                                                                                                      │
│    266 │   │   │   "trigger": event_name,                                                                                                                                                            │
│ ❱  267 │   │   │   "inputs": [block._id for block in inputs],                                                                                                                                        │
│    268 │   │   │   "outputs": [block._id for block in outputs],                                                                                                                                      │
│                                                                                                                                                                                                      │
│ C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py:267 in <listcomp>                                                                                                             │
│                                                                                                                                                                                                      │
│    266 │   │   │   "trigger": event_name,                                                                                                                                                            │
│ ❱  267 │   │   │   "inputs": [block._id for block in inputs],                                                                                                                                        │
│    268 │   │   │   "outputs": [block._id for block in outputs],                                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute '_id'
Loading weights: G:\ai\models\Stable-diffusion\endless_stage9fp16-0429-0721-0403.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/2.1 GB -:--:--
20:19:07-774013 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
20:19:08-044012 INFO     Model created from config: G:\ai\automatic\configs\v1-inference.yaml
Loading weights: G:\ai\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt ━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━ 210.6/334.7 MB 0:00:00
20:19:09-780013 INFO     Applying scaled dot product cross attention optimization
20:19:09-853014 INFO     Embeddings loaded: 95 ['akii_marie_rose', 'AS-Young', 'AS-Young-neg', 'AS-Younger', 'AS-Youngest', 'Asian-Less', 'Asian-Less-neg', 'Asian-Less-Toon', 'bad-artist', 'bad-artist-anime', 'bad-hands-5',
                         'bad-image-v2-39000', 'bad_pictures', 'bad_prompt', 'bad_prompt_version2', 'bad_quality', 'badq', 'bimbostyle', 'blowjobpose', 'bra_n', 'bukkakAI', 'corneo_bound_missionary',
                         'corneo_covering_breasts_arms_crossed', 'corneo_covering_breasts_one_arm', 'corneo_covering_breasts_two_hands', 'corneo_nipple_rings', 'corneo_side_doggy', 'corneo_tifa_dress', 'cvast',
                         'CyberRealistic_Negative-neg', 'dollienobodysd15', 'dpthrt', 'easynegative', 'ely_neg_prompt', 'evelynnobodysd15', 'evil_neg_prompt3', 'flower_style', 'fumio_8000', 'hades_8500', 'half-slip', 'jeans_n', 'kkw-bp',
                         'liah', 'liah-22100', 'liah-22100_n', 'liah_b', 'liah_n', 'luciesto', 'MangaHentaiStyleConceptv2', 'microkini', 'microwaistemb', 'morfyddclark', 'mwaist', 'NG_DeepNegative_V1_2T', 'NG_DeepNegative_V1_75T',
                         'night_elf', 'occsan', 'occsan1-2000', 'occsan1-2000_n', 'occsan2', 'occsan_old', 'occsan_r', 'occsanl', 'occsanred', 'ohmyfrick_yogapuss', 'panties_n', 'povblowjob3v3', 'pureerosface_v1', 'realcumAI',
                         'rfktr_bwmnga', 'rmadanegative402_sd15-neg', 'RSC', 'sarashil', 'schizo_neg_prompt', 'shirt_n', 'Style_Empire', 'Style_Empire_neg', 'Style_Glorious', 'Style_Glorious_neg', 'Style_Princess', 'Style_Psycho',
                         'Style_Psycho_neg', 'Style_Renaissance', 'Style_Renaissance_neg', 'Style_Winter', 'Style_Winter_neg', 'test_neg', 'test_neg2', 'thyri', 'Unspeakable_Horrors_Composition_4v', 'verybadimagenegative_v1.2-6400',
                         'white_n', 'wlop', 'yogapuss', 'zzzero']
20:19:09-857013 INFO     Embeddings skipped: 6 ['CinemaHelper', 'DaveSpaceFour', 'learned_embeds', 'liah21', 'PhotoHelper', 'PortraitHelper']
20:19:09-864013 INFO     Model loaded in 2.2s (load=0.1s create=0.3s apply=0.5s vae=0.6s move=0.6s embeddings=0.1s)
20:19:10-074015 INFO     Model load finished: {'ram': {'used': 3.28, 'total': 31.82}, 'gpu': {'used': 3.61, 'total': 23.99}, 'retries': 0, 'oom': 0}
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
20:19:10-570015 INFO     Local URL: http://127.0.0.1:7860/
20:19:10-571013 INFO     API Docs: http://127.0.0.1:7860/docs
20:19:10-572013 INFO     Initializing middleware
20:19:10-717013 INFO     [AgentScheduler] Task queue is empty
20:19:10-718013 INFO     [AgentScheduler] Registering APIs
20:19:11-391013 INFO     Startup time: 17.7s (torch=3.3s gradio=1.0s libraries=1.2s scripts=5.0s onchange=0.1s ui=5.9s launch=0.3s scripts app_started_callback=0.4s checkpoint=0.4s)
Traceback (most recent call last):
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\ai\automatic\extensions\SD-CN-Animation\scripts\core\utils.py", line 403, in export_settings
    args_dict = args_to_dict(*args)
  File "G:\ai\automatic\extensions\SD-CN-Animation\scripts\core\utils.py", line 103, in args_to_dict
    if (args[i] is None) and (args_list[i] in args_dict):
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\ai\automatic\modules\scripts.py", line 343, in select_script
    selected_script = self.selectable_scripts[script_index - 1] if script_index > 0 else None
TypeError: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler didn't receive enough output values (needed: 296, received: 1).
Wanted outputs:
    [dropdown, slider, slider, dropdown, dropdown, checkbox, checkbox, checkbox, radio, checkboxgroup, slider, slider, slider, radio, checkbox, checkbox, checkbox, slider, radio, slider, radio, radio, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, radio, checkbox, checkbox, checkbox, textbox, checkbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, checkbox, dropdown, textbox, checkbox, checkbox, dropdown, checkbox, checkbox, checkbox, slider, checkbox, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, slider, checkbox, number, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, checkbox, checkbox, colorpicker, slider, slider, slider, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, dropdown, radio, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, slider, textbox, dropdown, dropdown, textbox, textbox, textbox, textbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, radio, radio, number, checkboxgroup, dropdown, dropdown, slider, slider, radio, slider, slider, slider, slider, number, checkbox, radio, radio, slider, checkbox, dropdown, dropdown, slider, checkbox, checkbox, checkbox, checkbox, textbox, textbox, textbox, number, number, checkbox, checkbox, number, checkbox, checkbox, slider, slider, slider, number, checkboxgroup, slider, checkbox, checkbox, checkbox, textbox, dropdown, checkboxgroup, slider, slider, slider, slider, checkbox, checkbox, slider, checkbox, slider, slider, checkbox, checkbox, checkbox, radio, slider, checkbox, dropdown, slider, number, number, textbox, dropdown, dropdown, dropdown, radio, checkbox, checkbox, slider, checkbox, slider, checkbox, checkbox, checkbox, checkbox, radio, slider, slider, checkbox, radio, checkbox, radio, checkbox, radio, textbox, textbox, textbox, textbox, textbox, slider, slider, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, number, number, number, checkbox, number, checkbox, checkbox, dropdown, checkbox, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, dropdown, checkbox, number, checkbox, number, number, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, dropdown, checkbox, checkbox, checkbox, dropdown, dropdown, dropdown, code, code, html, slider, checkbox, checkbox, checkbox, textbox, radio, checkbox, checkbox, checkbox, checkbox]
Received outputs:
    [{'visible': False, '__type__': 'generic_update'}]
Traceback (most recent call last):
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\ai\automatic\extensions\vid-faceswap\scripts\vid_faceswap.py", line 64, in process_video
    frames_data, fps, audio = video_reader(video_input, max_fps=max_fps if max_fps > 0 else None)
TypeError: '>' not supported between instances of 'NoneType' and 'int'
20:19:54-476381 INFO     Models list: short hash missing for 0 out of 20 models
20:19:54-699381 INFO     Models list: full hash missing for 0 out of 20 models
20:19:54-701382 ERROR    model merge: TypeError
╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ G:\ai\automatic\modules\ui.py:1490 in modelmerger                                                                                                                                                    │
│                                                                                                                                                                                                      │
│   1489 │   │   │   try:                                                                                                                                                                              │
│ ❱ 1490 │   │   │   │   results = modules.extras.run_modelmerger(*args)                                                                                                                               │
│   1491 │   │   │   except Exception as e:                                                                                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: run_modelmerger() missing 13 required positional arguments: 'id_task', 'primary_model_name', 'secondary_model_name', 'tertiary_model_name', 'interp_method', 'multiplier', 'save_as_half', 'custom_name', 'checkpoint_format',
'config_source', 'bake_in_vae', 'discard_weights', and 'save_metadata'
Traceback (most recent call last):
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\ai\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 164, in f
    raise Exception("Invalid call")
Exception: Invalid call
20:19:54-888380 INFO     Available models: G:\ai\models\Stable-diffusion 20
Traceback (most recent call last):
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\dchat\miniconda3\envs\vlad\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\ai\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 164, in f
    raise Exception("Invalid call")
Exception: Invalid call
```

### Version Platform Description

Windows 10, conda environment.

**Comment by vladmandic** [comment]
@dchatel you've mentioned errors at the very end, but typically those are consequences of what happened earlier.
and first two errors are with `sd-webui-regional-prompter` and `SD-CN-Animation`
run with `--safe` flag and report again (that disables loading of user installed extensions).

@fcabanski "me too" doesn't help when your issue is not the same. and why say "many errors related to models" when there are no model related errors, all your errors are purely ui related.

**Comment by dchatel** [comment]
no errors with --safe.
But that doesn't change the fact that it has errors without --safe.

**Comment by vladmandic** [comment]
yes it does, that means error is in extension. now its really up to you to figure out which extension by installing one-by-one instead of having all-at-once.
and search for known issues regarding that extension.
you can open an issue using extensions template, but in majority of cases, issue needs to be addressed upstream, not in this repo. if issue is in this repo, yes, i'll fix it.

**Comment by dchatel** [comment]
Just to make sure I understand what you're saying...

If there is an error in just one extension, all the extensions break?

**Comment by vladmandic** [comment]
if extension has an issue and its contained within extension, that will print an error, but not cause app to fail.

only if exension does something really really bad - like patch application code, not just stay within extension - and then that patched code is buggy.

i've even seen extensions soooo bad that they modify some app files so you cant even uninstall it to get out of the problem, you need to reinstall entire app.

unfortunately, there is no way to limit what extension can do. by installing extension, you gave it all the rights to your entire pc - people forget that and like to try everything.

**Comment by dchatel** [comment]
I really wish more developers knew about haskell...

**Comment by vladmandic** [comment]
we don't have to go that far, but yeah, python is as insecure as it gets as everything is importable/overridable, it doesn't have concept of exports/privates/etc.

**Comment by fcabanski** [comment]
"@fcabanski "me too" doesn't help when your issue is not the same. and why say "many errors related to models" when there are no model related errors, all your errors are purely ui related."

Thanks for the reply. It was the regional prompter extension.
