### ISSUE TITLE
[Issue]: Newest Commit won't let me load models anymore

### ISSUE THREAD

**Issue by elchupacabrinski** [vladmandic/automatic#1345]
### Issue Description

Here's the error message that pops up whenever it'S trying to load a checkpoint:

`Traceback (most recent call last):
  File "/home/X/automatic/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/X/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/X/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/home/X/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler didn't receive enough output values (needed: 327, received: 2).
Wanted outputs:
    [dropdown, slider, slider, dropdown, dropdown, checkbox, checkbox, checkbox, radio, checkboxgroup, slider, slider, slider, radio, checkbox, checkbox, checkbox, slider, radio, slider, radio, radio, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, radio, checkbox, checkbox, checkbox, textbox, checkbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, checkbox, dropdown, textbox, checkbox, checkbox, dropdown, checkbox, checkbox, checkbox, slider, checkbox, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, slider, checkbox, number, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, checkbox, checkbox, colorpicker, slider, slider, slider, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, dropdown, radio, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, slider, textbox, dropdown, dropdown, textbox, textbox, textbox, textbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, radio, radio, number, checkboxgroup, dropdown, dropdown, slider, slider, radio, slider, slider, slider, slider, number, checkbox, radio, radio, slider, checkbox, dropdown, dropdown, slider, checkbox, checkbox, checkbox, checkbox, textbox, textbox, textbox, number, number, checkbox, checkbox, number, checkbox, checkbox, slider, slider, slider, number, checkboxgroup, slider, checkbox, checkbox, checkbox, textbox, dropdown, checkboxgroup, slider, slider, slider, slider, checkbox, checkbox, slider, checkbox, slider, slider, checkbox, checkbox, checkbox, radio, slider, checkbox, dropdown, slider, number, number, textbox, dropdown, dropdown, dropdown, radio, checkbox, checkbox, slider, checkbox, slider, checkbox, checkbox, checkbox, checkbox, radio, slider, slider, checkbox, radio, checkbox, radio, checkbox, radio, textbox, textbox, textbox, textbox, textbox, slider, slider, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, number, number, number, checkbox, number, checkbox, checkbox, dropdown, checkbox, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, dropdown, checkbox, number, checkbox, number, number, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, dropdown, checkbox, checkbox, checkbox, dropdown, dropdown, dropdown, code, code, html, checkbox, checkbox, textbox, textbox, slider, dropdown, checkbox, checkbox, checkbox, dropdown, checkbox, textbox, dropdown, checkbox, checkbox, dropdown, checkbox, slider, checkbox, slider, checkbox, checkbox, textbox, checkbox, textbox, dropdown, checkbox, checkbox, radio, radio, number, checkbox, checkbox, checkbox, textbox, textbox, textbox, checkbox, checkbox, dropdown, slider]
Received outputs:
    [{'value': '1.5-based/Anything-V3.0-pruned.ckpt [543bcbc212]', 'choices': ['1.5-based/analog-diffusion-1.0.ckpt [a9a1c90893]', '1.5-based/Anything-V3.0-pruned.ckpt [543bcbc212]', '1.5-based/anything-v4.0-pruned.safetensors [69528490df]', '1.5-based/Artius 1.5/artiusv15_v1.safetensors [f949a62901]', '1.5-based/Chromatische Abberation - Instancewort: ChromaV5.ckpt [ca620b55bd]', '1.5-based/deliberate_v2.safetensors [9aba26abdf]', '1.5-based/discodiffusion.ckpt [dbb082b872]', '1.5-based/dreamlike-photoreal-2.0.safetensors [92970aa785]', '1.5-based/dreamshaper_5BakedVae.safetensors [a60cfaa90d]', '1.5-based/Fantasy/chimeramix_v2.safetensors [f2d2b54765]', '1.5-based/Fantasy/wyvernmix_v8.safetensors [e4a56fa397]', '1.5-based/hassanblend1512AndPrevious_hassanblend1512.safetensors [f94d96ebdc]', '1.5-based/mdjrny-v4.ckpt [5d5ad06cc2]', '1.5-based/movieDiffusionV12_v12safetensors.safetensors [f321c2c996]', '1.5-based/nitroDiffusion-v1.ckpt [f0f1076e5e]', '1.5-based/openjourney-v2.ckpt [2fbe5ba6e2]', '1.5-based/openjourney-v4.ckpt [02e37aad9f]', '1.5-based/openjourneyLora.safetensors [75ef5457d3]', '1.5-based/PaperCut_v1.ckpt [8ee651e712]', '1.5-based/protogenV22AnimeOffi_22.safetensors [1254103966]', '1.5-based/protogenX34Photoreal_1.safetensors [44f90a0972]', '1.5-based/Realism-Focussed/Realistic Vision/realisticVisionV13_v13-inpainting.safetensors [10642fd1d2]', '1.5-based/Realism-Focussed/Realistic Vision/realisticVisionV13_v13.safetensors [c35782bad8]', '1.5-based/Realism-Focussed/Realistic Vision/realisticVisionV20_v20.safetensors [e6415c4892]', '1.5-based/Realism-Focussed/wyvernmix_v7.safetensors [b13ae9fe56]', '1.5-based/redshift-diffusion-v1 (1).ckpt [ed8c2ee432]', '1.5-based/RPG/rpg_V4.safetensors [e04b020012]', '1.5-based/v1-5-pruned-emaonly.safetensors [6ce0161689]', '1.5-based/vintedois 2.safetensors [cd95b823a4]', '1.5-based/vintedois-diffusion-v0-1.ckpt [fe2cf8a20b]', 'Obsolete/v1-5-pruned.safetensors [1a189f0be6]', 'SD 2.1/CKPT/v2-1_768-ema-pruned.ckpt [ad2a33c361]', 'SD 2.1/v2-1_512-ema-pruned.safetensors [df955bdf6b]', 'SD 2.1/v2-1_512-nonema-pruned.safetensors [fc4f9fe752]', 'SD 2.1/v2-1_768-ema-pruned.ckpt [ad2a33c361]', 'SD 2.1/v2-1_768-ema-pruned.safetensors [dcd690123c]', 'SD 2.1/v2-1_768-nonema-pruned.safetensors [ff144a4984]', 'Utilities/20-512-inpainting.ckpt [2a208a7ded]', 'Utilities/512-depth-ema.safetensors [59cb052d44]', 'Utilities/instruct-pix2pix-00-22000.safetensors [fbc31a67aa]'], '__type__': 'generic_update'}, "{"sd_model_checkpoint": "1.5-based/Anything-V3.0-pruned.ckpt [543bcbc212]", "sd_checkpoint_cache": 0, "sd_vae_checkpoint_cache": 0, "sd_vae": "Automatic", "sd_model_dict": "None", "sd_vae_sliced_encode": false, "stream_load": false, "model_reuse_dict": false, "cross_attention_optimization": "Scaled-Dot-Product", "cross_attention_options": [], "sub_quad_q_chunk_size": 512, "sub_quad_kv_chunk_size": 512, "sub_quad_chunk_threshold": 80, "prompt_attention": "Full parser", "prompt_mean_norm": true, "always_batch_cond_uncond": false, "enable_quantization": true, "comma_padding_backtrack": 20, "sd_backend": "Original", "memmon_poll_rate": 2, "precision": "Autocast", "cuda_dtype": "FP16", "no_half": false, "no_half_vae": false, "upcast_sampling": false, "upcast_attn": false, "disable_nan_check": true, "rollback_vae": false, "opt_channelslast": false, "cudnn_benchmark": false, "cuda_allow_tf32": true, "cuda_allow_tf16_reduced": true, "cuda_compile": false, "cuda_compile_mode": "none", "cuda_compile_verbose": false, "cuda_compile_errors": true, "disable_gc": false, "temp_dir": "", "clean_temp_dir_at_start": true, "ckpt_dir": "/home/X/automatic/models/Stable-diffusion", "diffusers_dir": "/home/X/automatic/models/Diffusers", "vae_dir": "/home/X/automatic/models/VAE", "lora_dir": "/home/X/automatic/models/Lora", "lyco_dir": "/home/X/automatic/models/LyCORIS", "styles_dir": "/home/X/automatic/styles.csv", "embeddings_dir": "/home/X/automatic/models/embeddings", "hypernetwork_dir": "/home/X/automatic/models/hypernetworks", "codeformer_models_path": "/home/X/automatic/models/Codeformer", "gfpgan_models_path": "/home/X/automatic/models/GFPGAN", "esrgan_models_path": "/home/X/automatic/models/ESRGAN", "bsrgan_models_path": "/home/X/automatic/models/BSRGAN", "realesrgan_models_path": "/home/X/automatic/models/RealESRGAN", "scunet_models_path": "/home/X/automatic/models/ScuNET", "swinir_models_path": "/home/X/automatic/models/SwinIR", "ldsr_models_path": "/home/X/automatic/models/LDSR", "clip_models_path": "/home/X/automatic/models/CLIP", "samples_save": true, "samples_format": "jpg", "samples_filename_pattern": "[seed]-[prompt_spaces]", "save_images_add_number": true, "grid_save": true, "grid_format": "jpg", "grid_extended_filename": true, "grid_only_if_multiple": true, "grid_prevent_empty_spots": true, "n_rows": -1, "save_txt": false, "save_log_fn": "", "save_images_before_face_restoration": false, "save_images_before_highres_fix": false, "save_images_before_color_correction": false, "save_mask": false, "save_mask_composite": false, "save_init_img": false, "jpeg_quality": 85, "webp_lossless": false, "img_max_size_mp": 250, "use_original_name_batch": true, "use_upscaler_name_as_suffix": true, "save_selected_only": true, "save_to_dirs": false, "grid_save_to_dirs": false, "use_save_to_dirs_for_ui": false, "directories_filename_pattern": "[date]", "directories_max_prompt_words": 8, "img2img_color_correction": false, "img2img_fix_steps": false, "img2img_background_color": "#ffffff", "inpainting_mask_weight": 1.0, "initial_noise_multiplier": 1.0, "CLIP_stop_at_last_layers": 1, "outdir_samples": "", "outdir_txt2img_samples": "/home/X/automatic/outputs/text", "outdir_img2img_samples": "/home/X/automatic/outputs/image", "outdir_extras_samples": "/home/X/automatic/outputs/extras", "outdir_grids": "", "outdir_txt2img_grids": "/home/X/automatic/outputs/grids", "outdir_img2img_grids": "/home/X/automatic/outputs/grids", "outdir_save": "/home/X/automatic/outputs/save", "outdir_init_images": "outputs/init-images", "gradio_theme": "black-orange", "theme_style": "Auto", "return_grid": true, "return_mask": false, "return_mask_composite": false, "disable_weights_auto_swap": true, "send_seed": true, "send_size": true, "font": "", "keyedit_precision_attention": 0.1, "keyedit_precision_extra": 0.05, "keyedit_delimiters": ".,\\/!?%^*;:{}=`~()", "quicksettings_list": ["sd_model_checkpoint"], "hidden_tabs": [], "ui_tab_reorder": "From Text, From Image, Process Image", "ui_scripts_reorder": "Enable Dynamic Thresholding, ControlNet", "ui_reorder": "inpaint, sampler, checkboxes, hires_fix, dimensions, cfg, seed, batch, override_settings, scripts", "ui_extra_networks_tab_reorder": "Checkpoints, Lora, LyCORIS, Textual Inversion, Hypernetworks", "show_progressbar": true, "live_previews_enable": true, "show_progress_grid": true, "notification_audio_enable": false, "notification_audio_path": "html/notification.mp3", "show_progress_every_n_steps": 1, "show_progress_type": "TAESD", "live_preview_content": "Combined", "live_preview_refresh_period": 250, "show_samplers": ["Euler a", "UniPC", "DDIM", "DPM++ 2M SDE", "DPM++ 2M SDE Karras", "DPM2 Karras", "DPM++ 2M Karras"], "fallback_sampler": "Euler a", "force_latent_sampler": "None", "eta_ancestral": 1.0, "eta_ddim": 0.0, "ddim_discretize": "uniform", "s_churn": 0.0, "s_min_uncond": 0, "s_tmin": 0.0, "s_noise": 1.0, "eta_noise_seed_delta": 0, "always_discard_next_to_last_sigma": false, "uni_pc_variant": "bh1", "uni_pc_skip_type": "time_uniform", "uni_pc_order": 3, "uni_pc_lower_order_final": true, "postprocessing_enable_in_main_ui": [], "postprocessing_operation_order": [], "upscaling_max_images_in_cache": 5, "unload_models_when_training": false, "pin_memory": true, "save_optimizer_state": false, "save_training_settings_to_txt": true, "dataset_filename_word_regex": "", "dataset_filename_join_string": " ", "embeddings_templates_dir": "/home/X/automatic/train/templates", "training_image_repeats_per_epoch": 1, "training_write_csv_every": 0, "training_enable_tensorboard": false, "training_tensorboard_save_images": false, "training_tensorboard_flush_every": 120, "interrogate_keep_models_in_memory": false, "interrogate_return_ranks": true, "interrogate_clip_num_beams": 1, "interrogate_clip_min_length": 32, "interrogate_clip_max_length": 192, "interrogate_clip_dict_limit": 2048, "interrogate_clip_skip_categories": ["artists", "movements", "flavors"], "interrogate_deepbooru_score_threshold": 0.65, "deepbooru_sort_alpha": false, "deepbooru_use_spaces": false, "deepbooru_escape": true, "deepbooru_filter_tags": "", "upscaler_for_img2img": "None", "realesrgan_enabled_models": ["R-ESRGAN 4x+", "R-ESRGAN 4x+ Anime6B"], "ESRGAN_tile": 192, "ESRGAN_tile_overlap": 8, "SCUNET_tile": 256, "SCUNET_tile_overlap": 8, "use_old_hires_fix_width_height": false, "dont_fix_second_order_samplers_schedule": false, "ldsr_steps": 100, "ldsr_cached": false, "SWIN_tile": 192, "SWIN_tile_overlap": 8, "lyco_patch_lora": false, "lora_disable": false, "lora_functional": false, "face_restoration_model": "CodeFormer", "code_former_weight": 0.2, "face_restoration_unload": false, "extra_networks_default_view": "cards", "extra_networks_default_multiplier": 1.0, "extra_networks_card_width": 0, "extra_networks_card_height": 0, "extra_networks_add_text_separator": " ", "sd_hypernetwork": "None", "sd_lyco": "None", "sd_lora": "None", "lora_preferred_name": "Alias from file", "lora_add_hashes_to_infotext": true, "token_merging": false, "token_merging_ratio": 0.5, "token_merging_hr_only": true, "token_merging_ratio_hr": 0.5, "token_merging_random": false, "token_merging_merge_attention": true, "token_merging_merge_cross_attention": false, "token_merging_merge_mlp": false, "token_merging_maximum_down_sampling": 1, "token_merging_stride_x": 2, "token_merging_stride_y": 2, "disabled_extensions": [], "disable_all_extensions": "none", "sd_checkpoint_hash": "543bcbc21294831c6245cd74c8a7707761e28812c690f946cb81fef930d54b5e", "aesthetic_scorer_enabled": false, "aesthetic_scorer_clip_model": "ViT-L/14", "queue_paused": false, "queue_button_placement": "Under Generate button", "queue_button_hide_checkpoint": true, "queue_history_retention_days": "30 days", "control_net_model_config": "models/cldm_v15.yaml", "control_net_model_adapter_config": "models/t2iadapter_sketch_sd14v1.yaml", "control_net_detectedmap_dir": "detected_maps", "control_net_models_path": "", "control_net_modules_path": "", "control_net_max_models_num": 3, "control_net_model_cache_size": 3, "control_net_no_detectmap": false, "control_net_detectmap_autosaving": false, "control_net_allow_script_control": false, "control_net_sync_field_args": false, "controlnet_show_batch_images_in_ui": false, "controlnet_increment_seed_during_batch": false, "controlnet_disable_control_type": false, "controlnet_disable_openpose_edit": false, "image_browser_active_tabs": "txt2img, img2img, txt2img-grids, img2img-grids, Extras, Favorites, Others, All, Maintenance", "image_browser_hidden_components": [], "image_browser_with_subdirs": true, "image_browser_preload": false, "image_browser_copy_image": false, "image_browser_delete_message": true, "image_browser_txt_files": true, "image_browser_debug_level": "0 - none", "image_browser_delete_recycle": true, "image_browser_scan_exif": true, "image_browser_mod_shift": false, "image_browser_mod_ctrl_shift": false, "image_browser_ranking_pnginfo": false, "image_browser_page_columns": 6.0, "image_browser_page_rows": 6.0, "image_browser_pages_perload": 20.0, "image_browser_use_thumbnail": false, "image_browser_thumbnail_size": 200.0, "image_browser_swipe": false, "image_browser_img_tooltips": true, "image_browser_scoring_type": "aesthetic_score", "image_browser_show_progress": true, "tac_tagFile": "danbooru.csv", "tac_active": true, "tac_activeIn.txt2img": true, "tac_activeIn.img2img": true, "tac_activeIn.negativePrompts": true, "tac_activeIn.thirdParty": true, "tac_activeIn.modelList": "", "tac_activeIn.modelListMode": "Blacklist", "tac_slidingPopup": true, "tac_maxResults": 5.0, "tac_showAllResults": false, "tac_resultStepLength": 100.0, "tac_delayTime": 100.0, "tac_useWildcards": true, "tac_useEmbeddings": true, "tac_useHypernetworks": true, "tac_useLoras": true, "tac_useLycos": true, "tac_showWikiLinks": false, "tac_replaceUnderscores": true, "tac_escapeParentheses": true, "tac_appendComma": true, "tac_alias.searchByAlias": true, "tac_alias.onlyShowAlias": false, "tac_translation.translationFile": "None", "tac_translation.oldFormat": false, "tac_translation.searchByTranslation": true, "tac_translation.liveTranslation": false, "tac_extra.extraFile": "extra-quality-tags.csv", "tac_extra.addMode": "Insert before", "tac_chantFile": "demo-chants.json", "tac_keymap": "{\n    \"MoveUp\": \"ArrowUp\",\n    \"MoveDown\": \"ArrowDown\",\n    \"JumpUp\": \"PageUp\",\n    \"JumpDown\": \"PageDown\",\n    \"JumpToStart\": \"Home\",\n    \"JumpToEnd\": \"End\",\n    \"ChooseSelected\": \"Enter\",\n    \"ChooseFirstOrSelected\": \"Tab\",\n    \"Close\": \"Escape\"\n}", "tac_colormap": "{\n    \"danbooru\": {\n        \"-1\": [\"red\", \"maroon\"],\n        \"0\": [\"lightblue\", \"dodgerblue\"],\n        \"1\": [\"indianred\", \"firebrick\"],\n        \"3\": [\"violet\", \"darkorchid\"],\n        \"4\": [\"lightgreen\", \"darkgreen\"],\n        \"5\": [\"orange\", \"darkorange\"]\n    },\n    \"e621\": {\n        \"-1\": [\"red\", \"maroon\"],\n        \"0\": [\"lightblue\", \"dodgerblue\"],\n        \"1\": [\"gold\", \"goldenrod\"],\n        \"3\": [\"violet\", \"darkorchid\"],\n        \"4\": [\"lightgreen\", \"darkgreen\"],\n        \"5\": [\"tomato\", \"darksalmon\"],\n        \"6\": [\"red\", \"maroon\"],\n        \"7\": [\"whitesmoke\", \"black\"],\n        \"8\": [\"seagreen\", \"darkseagreen\"]\n    }\n}", "tac_refreshTempFiles": "Refresh TAC temp files", "deforum_keep_3d_models_in_vram": false, "deforum_enable_persistent_settings": false, "deforum_persistent_settings_path": "models/Deforum/deforum_persistent_settings.txt", "deforum_ffmpeg_location": "/home/X/automatic/venv/lib/python3.10/site-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2", "deforum_ffmpeg_crf": 17, "deforum_ffmpeg_preset": "slow", "deforum_debug_mode_enabled": false, "deforum_save_gen_info_as_srt": false, "deforum_embed_srt": false, "deforum_save_gen_info_as_srt_params": ["Noise Schedule"], "arh_javascript_aspect_ratio_show": true, "arh_javascript_aspect_ratio": "1:1, 3:2, 4:3, 5:4, 16:9", "arh_ui_javascript_selection_method": "Aspect Ratios Dropdown", "arh_hide_accordion_by_default": true, "arh_expand_by_default": false, "arh_ui_component_order_key": "MaxDimensionScaler, MinDimensionScaler, PredefinedAspectRatioButtons, PredefinedPercentageButtons", "arh_show_max_width_or_height": false, "arh_max_width_or_height": 1024, "arh_show_min_width_or_height": false, "arh_min_width_or_height": 1024, "arh_show_predefined_aspect_ratios": false, "arh_predefined_aspect_ratio_use_max_dim": false, "arh_predefined_aspect_ratios": "1:1, 4:3, 16:9, 9:16, 21:9", "arh_show_predefined_percentages": false, "arh_predefined_percentages": "25, 50, 75, 125, 150, 175, 200", "arh_predefined_percentages_display_key": "Incremental/decremental percentage (-50%, +50%)", "regprp_debug": false, "regprp_hidepmask": false, "modelscope_deforum_keep_model_in_vram": "None", "modelscope_deforum_vae_settings": "GPU (half precision)", "modelscope_deforum_show_n_videos": -1.0, "dp_ignore_whitespace": false, "dp_write_raw_template": false, "dp_write_prompts_to_file": false, "dp_parser_variant_start": "{", "dp_parser_variant_end": "}", "dp_parser_wildcard_wrap": "__", "dp_limit_jinja_prompts": false, "dp_auto_purge_cache": false, "dp_magicprompt_default_model": "Gustavosta/MagicPrompt-Stable-Diffusion", "dp_magicprompt_batch_size": 1}"]
`

**Comment by Symbiomatrix** [comment]
@elchupacabrinski Can you please test the latest version?

**Comment by elchupacabrinski** [comment]
> @elchupacabrinski Can you please test the latest version?

works again!

**Comment by Symbiomatrix** [comment]
Great, thanks.
