### ISSUE TITLE
[Issue]: Restarting Server Causes Several Errors (eventually have to cold restart)

### ISSUE THREAD

**Issue by DoughyInTheMiddle** [vladmandic/automatic#1375]
### Issue Description

Recently, restarting the server results in a bombardment of errors. This occurs both when hitting Restart Server from Settings or from Extensions "Apply Changes & Restart Server".

The major error that sticks out is `ValueError: not enough values to unpack (expected 5, got 0)`

Just to test it, I disabled ALL extensions -- both user and system installed ones -- and hit restart. Still got the same list. Not sure when it started.

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "C:\Program Files\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\GitHub\Vladmandic\modules\call_queue.py", line 58, in f
    res = func(*args, **kwargs)
  File "G:\GitHub\Vladmandic\modules\ui.py", line 1307, in run_settings
    modules.shared.log.info(f'Settings changed: {len(changed)} {changed}')
Message: 'Settings changed: 0 []'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "C:\Program Files\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\GitHub\Vladmandic\modules\ui.py", line 1449, in <lambda>
    restart_submit.click(fn=lambda x: modules.shared.restart_server(restart=True), _js="restart_reload")
  File "G:\GitHub\Vladmandic\modules\shared.py", line 782, in restart_server
    log.info('Server shutdown requested')
Message: 'Server shutdown requested'
Arguments: ()
Traceback (most recent call last):
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
--- Logging error ---
Traceback (most recent call last):
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\GitHub\Vladmandic\modules\middleware.py", line 72, in exception_handling
    return await call_next(req)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\streams\memory.py", line 102, in receive
    await receive_event.wait()
  File "C:\Program Files\Python310\lib\asyncio\locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "G:\GitHub\Vladmandic\modules\middleware.py", line 74, in exception_handling
    log.warning('WebSocket closed (ignore asyncio.exceptions.CancelledError)')
Message: 'WebSocket closed (ignore asyncio.exceptions.CancelledError)'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "C:\Program Files\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\GitHub\Vladmandic\modules\ui.py", line 1449, in <lambda>
    restart_submit.click(fn=lambda x: modules.shared.restart_server(restart=True), _js="restart_reload")
  File "G:\GitHub\Vladmandic\modules\shared.py", line 793, in restart_server
    log.info('Server will restart')
Message: 'Server will restart'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 193, in <module>
    installer.log.info('Server restarting...')
Message: 'Server restarting...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 127, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\GitHub\Vladmandic\webui.py", line 67, in <module>
    log.info('Libraries loaded')
Message: 'Libraries loaded'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 290, in webui
    start_common()
  File "G:\GitHub\Vladmandic\webui.py", line 196, in start_common
    log.info(f'Using data path: {shared.cmd_opts.data_dir}')
Message: 'Using data path: G:\\GitHub\\Vladmandic'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 290, in webui
    start_common()
  File "G:\GitHub\Vladmandic\webui.py", line 199, in start_common
    initialize()
  File "G:\GitHub\Vladmandic\webui.py", line 93, in initialize
    modules.sd_vae.refresh_vae_list()
  File "G:\GitHub\Vladmandic\modules\sd_vae.py", line 79, in refresh_vae_list
    shared.log.info(f"Available VAEs: {vae_path} {len(vae_dict)}")
Message: 'Available VAEs: G:\\GitHub\\Vladmandic\\models\\VAE 3'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 290, in webui
    start_common()
  File "G:\GitHub\Vladmandic\webui.py", line 199, in start_common
    initialize()
  File "G:\GitHub\Vladmandic\webui.py", line 100, in initialize
    modules.sd_models.setup_model()
  File "G:\GitHub\Vladmandic\modules\sd_models.py", line 93, in setup_model
    list_models()
  File "G:\GitHub\Vladmandic\modules\sd_models.py", line 129, in list_models
    shared.log.info(f'Available models: {shared.opts.ckpt_dir} {len(checkpoints_list)}')
Message: 'Available models: G:\\GitHub\\Vladmandic\\models\\Stable-diffusion 35'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 290, in webui
    start_common()
  File "G:\GitHub\Vladmandic\webui.py", line 199, in start_common
    initialize()
  File "G:\GitHub\Vladmandic\webui.py", line 118, in initialize
    shared.opts.onchange("gradio_theme", shared.reload_gradio_theme)
  File "G:\GitHub\Vladmandic\modules\shared.py", line 643, in onchange
    func()
  File "G:\GitHub\Vladmandic\modules\shared.py", line 742, in reload_gradio_theme
    log.info(f'Loading UI theme: name={theme_name} style={opts.theme_style}')
Message: 'Loading UI theme: name=gradio/default style=Auto'
Arguments: ()
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 291, in webui
    start_ui()
  File "G:\GitHub\Vladmandic\webui.py", line 261, in start_ui
    shared.log.info(f'Local URL: {local_url}')
Message: 'Local URL: http://127.0.0.1:7860/'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 291, in webui
    start_ui()
  File "G:\GitHub\Vladmandic\webui.py", line 268, in start_ui
    setup_middleware(app, cmd_opts)
  File "G:\GitHub\Vladmandic\modules\middleware.py", line 21, in setup_middleware
    log.info('Initializing middleware')
Message: 'Initializing middleware'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 293, in webui
    log.info(f"Startup time: {startup_timer.summary()}")
Message: 'Startup time: 4.3s (vae=0.1s models=0.1s onchange=0.1s ui=2.7s launch=0.2s scripts app_started_callback=0.1s checkpoint=1.0s)'
```

### Version Platform Description

updated:  "2023-06-09",
hash:  "ec6d0548",
url:  "https://github.com/vladmandic/automatic/tree/master"

torch:  "2.0.1+cu118 Autocast half",

device:  "NVIDIA GeForce RTX 3060 (1) (compute_37) (8, 6)",
cuda:  "11.8",
cudnn:  8700

accelerate:  "0.19.0",
transformers:  "4.29.2"

Stable Diffusion:  "[cf1d67a] 2023-03-25",
Taming Transformers:  "[9e9981c] 2022-11-07",
CodeFormer:  "[7a584fd] 2023-01-18",
BLIP:  "[3a29b74] 2022-09-20",
k_diffusion:  "[c9fe758] 2023-05-21"

active:  "cuda",
dtype:  "torch.float16",
vae:  "torch.float16",
unet:  "torch.float32"

arch:  "AMD64",
cpu:  "Intel64 Family 6 Model 60 Stepping 3, GenuineIntel",
system:  "Windows",
release:  "Windows-10-10.0.19044-SP0",
python:  "3.10.6"

**Comment by vladmandic** [comment]
if an extension (or something else, but most likely extension) changed some parameters, hot-restart will simply not work, you need to do cold-restart. its just how python works, there is no way to unload some existing stuff from memory, so there is conflict when new stuff expects different params than ones previously expected.

**Comment by DoughyInTheMiddle** [comment]
> if an extension (or something else, but most likely extension) changed some parameters, hot-restart will simply not work, you need to do cold-restart. its just how python works, there is no way to unload some existing stuff from memory, so there is conflict when new stuff expects different params than ones previously expected.

OK, I unloaded everything except the system info extension, and completely shut down the server and restarted the console.

Reloaded the UI and hit shutdown again.

If there's a setting wrong, I have no idea what it is. I guess the only thing I can think of us to nuke /venv.

11:37:33-085101 INFO     Server shutdown requested
11:37:33-298208 WARNING  WebSocket closed (ignore asyncio.exceptions.CancelledError)
Traceback (most recent call last):
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
11:37:34-324196 INFO     Server will restart
11:37:35-119368 INFO     Server restarting...
11:37:38-401223 INFO     Libraries loaded
11:37:38-411177 INFO     Using data path: G:\GitHub\Vladmandic
11:37:38-459128 INFO     Available VAEs: G:\GitHub\Vladmandic\models\VAE 3
11:37:38-710120 INFO     Available models: G:\GitHub\Vladmandic\models\Stable-diffusion 35
11:37:38-935307 INFO     Loading UI theme: name=gradio/default style=Auto
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 294, in webui
    start_ui()
  File "G:\GitHub\Vladmandic\webui.py", line 264, in start_ui
    shared.log.info(f'Local URL: {local_url}')
Message: 'Local URL: http://127.0.0.1:7860/'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 294, in webui
    start_ui()
  File "G:\GitHub\Vladmandic\webui.py", line 271, in start_ui
    setup_middleware(app, cmd_opts)
  File "G:\GitHub\Vladmandic\modules\middleware.py", line 21, in setup_middleware
    log.info('Initializing middleware')
Message: 'Initializing middleware'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 296, in webui
    log.info(f"Startup time: {startup_timer.summary()}")
Message: 'Startup time: 3.9s (vae=0.1s models=0.2s scripts=0.1s onchange=0.1s ui=2.6s launch=0.1s scripts app_started_callback=0.1s checkpoint=0.5s)'
Arguments: ()

**Comment by DoughyInTheMiddle** [comment]
Disabled all extensions (system or otherwise).

Shutdown the console.

Nuked my venv folder.

Relaunched (recreating the venv folder).

Restarted.

Confirmed no extensions were loaded.

Clicked "Restart Server" from Settings tab:

```
13:33:53-617455 INFO     Server shutdown requested
13:33:53-836615 WARNING  WebSocket closed (ignore asyncio.exceptions.CancelledError)
Traceback (most recent call last):
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
13:33:54-857189 INFO     Server will restart
13:33:55-524631 INFO     Server restarting...
13:33:58-793610 INFO     Libraries loaded
13:33:58-799578 INFO     Using data path: G:\GitHub\Vladmandic
13:33:58-835870 INFO     Available VAEs: G:\GitHub\Vladmandic\models\VAE 3
13:33:59-019386 INFO     Available models: G:\GitHub\Vladmandic\models\Stable-diffusion 35
13:33:59-125272 INFO     Loading UI theme: name=gradio/default style=Auto
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 294, in webui
    start_ui()
  File "G:\GitHub\Vladmandic\webui.py", line 264, in start_ui
    shared.log.info(f'Local URL: {local_url}')
Message: 'Local URL: http://127.0.0.1:7860/'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 294, in webui
    start_ui()
  File "G:\GitHub\Vladmandic\webui.py", line 271, in start_ui
    setup_middleware(app, cmd_opts)
  File "G:\GitHub\Vladmandic\modules\middleware.py", line 21, in setup_middleware
    log.info('Initializing middleware')
Message: 'Initializing middleware'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "G:\GitHub\Vladmandic\venv\lib\site-packages\uvicorn\logging.py", line 104, in formatMessage
    (
ValueError: not enough values to unpack (expected 5, got 0)
Call stack:
  File "G:\GitHub\Vladmandic\launch.py", line 194, in <module>
    instance = start_server(immediate=False, server=instance)
  File "G:\GitHub\Vladmandic\launch.py", line 135, in start_server
    server = server.webui()
  File "G:\GitHub\Vladmandic\webui.py", line 296, in webui
    log.info(f"Startup time: {startup_timer.summary()}")
Message: 'Startup time: 3.4s (models=0.2s onchange=0.1s ui=2.4s launch=0.1s checkpoint=0.4s)'
Arguments: ()
```

**Comment by vladmandic** [comment]
yeah, i found what the problem was. fixed.

**Comment by DoughyInTheMiddle** [comment]
> yeah, i found what the problem was. fixed.

Thanks for fixing it.

You have a mostly thankless job here, and I just wanna say, I appreciate all you do for the AI community.
