### ISSUE TITLE
[Issue]: Dreambooth training error

### ISSUE THREAD

**Issue by velourlawsuits** [vladmandic/automatic#1383]
### Issue Description

When I hit "train" in the Dreambooth extension I get the following error:

Initializing dreambooth training...
Pre-processing images: classifiers_0: : 22it [00:01, 20.10it/s]
We need a total of 330 class images.                                                    | 1/11 [00:01<00:10,  1.09s/it]
Generating 330 class images for training...
                                                                                                                       Traceback (most recent call last): 0%|                                                          | 0/330 [00:00<?, ?it/s]
  File "D:\Stable Diffusion\Vlad1111\automatic\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 729, in start_training
    result = main(class_gen_method=class_gen_method)
  File "D:\Stable Diffusion\Vlad1111\automatic\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1548, in main
    return inner_loop()
  File "D:\Stable Diffusion\Vlad1111\automatic\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "D:\Stable Diffusion\Vlad1111\automatic\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 246, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(
  File "D:\Stable Diffusion\Vlad1111\automatic\extensions\sd_dreambooth_extension\dreambooth\utils\gen_utils.py", line 153, in generate_classifiers
    builder = ImageBuilder(
  File "D:\Stable Diffusion\Vlad1111\automatic\extensions\sd_dreambooth_extension\helpers\image_builder.py", line 110, in __init__
    self.image_pipe.enable_xformers_memory_efficient_attention()
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1448, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1474, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1464, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "D:\Stable Diffusion\Vlad1111\automatic\venv\lib\site-packages\diffusers\models\attention_processor.py", line 166, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers
Generating class images 0/330::   0%|                                                          | 0/330 [00:02<?, ?it/s]
Restored system models.
Duration: 00:00:05

### Version Platform Description

Python 3.10.6 on Windows
version: 81172bf5 Sat Jun 10 07:18:56 2023 -0400
Setting environment tuning
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 4080 VRAM 16376 Arch (8, 9) Cores 76

running the current version of Vlad1111

**Comment by vladmandic** [comment]
this is clearly extension related, so please use extension template.
dreambooth forces usage of xformers, so if you really want to use that extension, you must set cross-optimization in this app as well to be xformers. i don't like that extension is forcing it and for that reason i do not recomment that extension, but its your choice.

**Comment by velourlawsuits** [comment]
> this is clearly extension related, so please use extension template. dreambooth forces usage of xformers, so if you really want to use that extension, you must set cross-optimization in this app as well to be xformers. i don't like that extension is forcing it and for that reason i do not recommend that extension, but its your choice.

Do you have a recommendation for a comparable extension? If not can you point me to a tutorial on how to achieve cross-optimization? I have found it very difficult to find a way to implement xformers on my 4080. That's why I am using your webui build in the first place, it runs so much faster :)

**Comment by vladmandic** [comment]
this app does use cross-optimization and chooses recommended one depending on platform and gpu - for you, it chooses sdp.
if you set cross optimization to xformers in settings and restart server, it should install them and try to use them.
but realistically, there is no reason why dreambooth should require xformers in the first place.

and when you're done with dreambooth, you can set cross optimization back to sdp.

**Comment by velourlawsuits** [comment]
Thanks Vlad that was super easy, everything works now 😄

**Comment by mwhaite** [comment]
I dunno man,  when upstream breaks downstream with an anti-feature .... wasting end user time.... it is kinda a dick move, and as the aggressor it is worth considering as an upstream bug.  consider:  do you have a functional reason to delete this library from MY computer?

**Comment by vladmandic** [comment]
watch your language.

and yes, i do have the right and reason to do it - you didn't ask what the reason is, you assigned blame. you know how many times this extension broke core app? countless. because it doesn't install stuff for itself only, it install them globally so it changes how core app works even if you don't use extension (even if you disable it).
and talking about right? package is deleted from app managed venv, its not deleted from your system. and you have two options to keep it - set it as active in cross-attention  settings or use env variable to override. 

this conversation is closed.
