### ISSUE TITLE
[Issue]: Restarting SD by ui wont load  commandline arguments and cant use the webui from other pc after

### ISSUE THREAD

**Issue by omniusvujuha** [vladmandic/automatic#1388]
### Issue Description

After restarting the program from ui it gives an error and cant access from another device anymore despite being able to do it before restarting. Locally there is no problem but I need to use the webui from another pc so it is a bit problem. I always had a problem with ui restarts it isnt a new thing. After you fixed the restarts with commit 159d00d it fixed the most of the problem but this one persists. I think it doesnt register commandlines but I am not sure. Also --save command doesnt fix the problem.

Below is the log with --debug

```
Using VENV: D:\automatic\venv
06:31:40-663332 INFO     Starting SD.Next
06:31:40-663332 INFO     Python 3.10.9 on Windows
06:31:40-710207 INFO     Version: 76e54938 Sat Jun 10 19:51:35 2023 -0400
06:31:41-257087 INFO     Setting environment tuning
06:31:41-257087 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False
06:31:41-257087 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True
06:31:41-257087 INFO     nVidia CUDA toolkit detected
06:31:42-913317 INFO     Torch 2.0.1+cu118
06:31:42-944567 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
06:31:42-944567 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 Ti VRAM 8192 Arch (8, 6) Cores 48
06:31:43-069567 WARNING  Modified files: ['webui.bat']
06:31:43-100816 DEBUG    Repository update time: Sun Jun 11 02:51:35 2023
06:31:43-100816 DEBUG    Previous setup time: Sun Jun 11 06:15:44 2023
06:31:43-100816 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
06:31:43-100816 INFO     Enabled extensions: ['a1111-sd-webui-tagcomplete', 'a1111-sd-webui-tome', 'adetailer',
                         'openOutpaint-webUI-extension', 'sd-webui-ar', 'sd_civitai_extension']
06:31:43-116441 DEBUG    Latest extensions time: Sun Jun 11 06:15:40 2023
06:31:43-116441 DEBUG    Timestamps: version:1686441095 setup:1686453344 extension:1686453340
06:31:43-116441 INFO     No changes detected: Quick launch active
06:31:43-116441 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
06:31:43-116441 INFO     Enabled extensions: ['a1111-sd-webui-tagcomplete', 'a1111-sd-webui-tome', 'adetailer',
                         'openOutpaint-webUI-extension', 'sd-webui-ar', 'sd_civitai_extension']
06:31:43-132066 INFO     Extension preload: 0.0s D:\automatic\extensions-builtin
06:31:43-132066 INFO     Extension preload: 0.0s D:\automatic\extensions
06:31:43-132066 INFO     Server arguments: ['--listen', '--disable-queue', '--debug']
06:31:43-147691 DEBUG    Memory used: 0.33 total: 15.92 Collected 0
06:31:43-147691 DEBUG    Starting module: <module 'webui' from 'D:\\automatic\\webui.py'>
06:31:43-147691 DEBUG    Loading Torch
06:31:47-100789 DEBUG    Loading Gradio
06:31:48-257031 DEBUG    Loading Modules
No module 'xformers'. Proceeding without it.
06:31:49-944519 INFO     Libraries loaded
06:31:49-944519 DEBUG    Entering start sequence
06:31:50-069519 DEBUG    Version: {'app': 'sd.next', 'updated': '2023-06-10', 'hash': '76e54938', 'url':
                         'https://github.com/vladmandic/automatic/tree/master'}
06:31:50-069519 INFO     Using data path: D:\automatic
06:31:50-069519 DEBUG    Entering initialize
06:31:50-069519 INFO     Available VAEs: D:\automatic\models\VAE 5
06:31:50-132017 INFO     Available models: D:\automatic\models\Stable-diffusion 38
06:31:50-210142 DEBUG    Loading scripts
06:31:52-866374 INFO     ControlNet v1.1.224
ControlNet preprocessor location: D:\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
06:31:53-022622 INFO     ControlNet v1.1.224
[-] ADetailer initialized. version: 23.6.2, num models: 8
Civitai: API loaded
06:31:56-553857 INFO     Loading UI theme: name=black-orange style=Auto
06:31:56-553857 DEBUG    Creating UI
06:31:57-835098 DEBUG    Script: 0.55s ui_tabs
                         D:\automatic\extensions-builtin\stable-diffusion-webui-images-browser\scripts\image_browser.py
06:31:58-928834 DEBUG    Script: 1.09s ui_tabs D:\automatic\extensions\openOutpaint-webUI-extension\scripts\main.py
06:31:58-928834 DEBUG    Extensions list failed to load: D:\automatic\html\extensions.json
06:32:00-335073 DEBUG    Select checkpoint: seekArtMEGA_mega20.safetensors [99fd5c4b6f]
06:32:00-335073 DEBUG    Reload model weights: existing=False
                         target=D:\automatic\models\Stable-diffusion\seekArtMEGA_mega20.safetensors info=None
Loading weights: D:\automatic\models\Stable-diffusion\seekArtMEGA_mega20.safetensors --------------- 0.0/2.1 GB -:--:--
06:32:00-647570 DEBUG    Load model: name=D:\automatic\models\Stable-diffusion\seekArtMEGA_mega20.safetensors dict=True
06:32:00-647570 DEBUG    Verifying Torch settings
06:32:00-694445 DEBUG    Torch FP16 test passed
06:32:00-694445 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False
06:32:00-694445 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
06:32:00-694445 DEBUG    Torch default device: cuda
06:32:00-694445 DEBUG    Model dict loaded: {'ram': {'used': 0.99, 'total': 15.92}, 'gpu': {'used': 1.07, 'total':
                         8.0}, 'retries': 0, 'oom': 0}
06:32:00-710070 DEBUG    Model config loaded: {'ram': {'used': 0.99, 'total': 15.92}, 'gpu': {'used': 1.07, 'total':
                         8.0}, 'retries': 0, 'oom': 0}
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
06:32:01-116317 INFO     Model created from config: D:\automatic\configs\v1-inference.yaml
06:32:01-131942 DEBUG    Model weights loading: {'ram': {'used': 1.96, 'total': 15.92}, 'gpu': {'used': 1.07, 'total':
                         8.0}, 'retries': 0, 'oom': 0}
Loading weights: D:\automatic\models\VAE\vaeFtMse840000Ema_v100.pt ------------------ ---------- 210.6/334.7 MB 0:00:00
06:32:07-647521 DEBUG    Model weights loaded: {'ram': {'used': 5.16, 'total': 15.92}, 'gpu': {'used': 1.07, 'total':
                         8.0}, 'retries': 0, 'oom': 0}
06:32:08-600640 DEBUG    Model weights moved: {'ram': {'used': 3.17, 'total': 15.92}, 'gpu': {'used': 3.11, 'total':
                         8.0}, 'retries': 0, 'oom': 0}
06:32:08-616266 INFO     Applying split attention optimization
06:32:08-663140 INFO     Embeddings loaded: 14 ['advntr', 'bad-artist', 'BadDream', 'badhandv4', 'chihunhentai2-60000',
                         'cutesexyrobutts-100000', 'easynegative', 'FastNegativeEmbedding', 'ng_deepnegative_v1_75t',
                         'style-nebmagic', 'style-paintmagic', 'style-rustmagic', 'style-swirlmagic',
                         'style-sylvamagic']
06:32:08-663140 INFO     Model loaded in 8.3s (load=0.3s config=0.1s create=0.4s apply=5.4s vae=1.1s move=1.0s)
06:32:08-897513 DEBUG    gc: collected=1323 device=cuda {'ram': {'used': 3.2, 'total': 15.92}, 'gpu': {'used': 3.11,
                         'total': 8.0}, 'retries': 0, 'oom': 0}
06:32:08-897513 INFO     Model load finished: {'ram': {'used': 3.2, 'total': 15.92}, 'gpu': {'used': 3.11, 'total':
                         8.0}, 'retries': 0, 'oom': 0}
06:32:09-069387 INFO     Server queues disabled
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
06:32:13-334983 INFO     Local URL: http://localhost:7860/
06:32:13-350608 DEBUG    Gradio registered functions: 2028
06:32:13-350608 INFO     Initializing middleware
06:32:13-350608 DEBUG    Creating API
06:32:13-475607 INFO     [AgentScheduler] Task queue is empty
06:32:13-475607 INFO     [AgentScheduler] Registering APIs
Civitai: Check resources for missing preview images
06:32:13-584983 DEBUG    Script: 0.11s app_started
                         D:\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py
06:32:13-678733 DEBUG    Scripts setup: ['Tiled Diffusion:0.016s', 'Dynamic Thresholding (CFG Scale Fix):0.016s',
                         'ControlNet:0.047s', 'ADetailer:0.078s', 'Aspect Ratio picker:0.031s']s
06:32:13-678733 DEBUG    Scripts components: []s
06:32:13-897479 DEBUG    gc: collected=14301 device=cuda {'ram': {'used': 1.24, 'total': 15.92}, 'gpu': {'used': 3.11,
                         'total': 8.0}, 'retries': 0, 'oom': 0}
06:32:14-116227 DEBUG    gc: collected=124 device=cuda {'ram': {'used': 1.24, 'total': 15.92}, 'gpu': {'used': 3.11,
                         'total': 8.0}, 'retries': 0, 'oom': 0}
06:32:14-116227 INFO     Startup time: 31.0s (torch=4.0s gradio=1.2s libraries=1.7s vae=0.1s models=0.1s
                         codeformer=0.1s scripts=6.0s onchange=0.3s ui=12.5s launch=4.3s scripts
                         app_started_callback=0.3s checkpoint=0.4s)
Civitai: Found 53 resources missing preview images
Civitai: Found 49 hash matches
Civitai: Updated 0 preview images
06:32:51-009719 INFO     Server shutdown requested
Traceback (most recent call last):
  File "D:\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
06:32:51-237644 WARNING  WebSocket closed (ignore asyncio.exceptions.CancelledError)
06:32:51-240647 INFO     Server will restart
06:32:51-472625 INFO     Server restarting...
06:32:54-671016 DEBUG    Memory used: 1.24 total: 15.92 Collected 502
06:32:54-671016 DEBUG    Starting module: <module 'webui' from 'D:\\automatic\\webui.py'>
06:32:54-671016 DEBUG    Loading Torch
06:32:54-671016 DEBUG    Loading Gradio
06:32:54-671016 DEBUG    Loading Modules
06:32:54-671016 INFO     Libraries loaded
06:32:54-671016 DEBUG    Entering start sequence
06:32:54-780391 DEBUG    Version: {'app': 'sd.next', 'updated': '2023-06-10', 'hash': '76e54938', 'url':
                         'https://github.com/vladmandic/automatic/tree/master'}
06:32:54-780391 INFO     Using data path: D:\automatic
06:32:54-780391 DEBUG    Entering initialize
06:32:54-780391 INFO     Available VAEs: D:\automatic\models\VAE 5
06:32:54-842891 INFO     Available models: D:\automatic\models\Stable-diffusion 38
06:32:54-842891 DEBUG    Loading scripts
06:32:55-789765 INFO     ControlNet v1.1.224
[-] ADetailer initialized. version: 23.6.2, num models: 8
Civitai: API loaded

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Civitai: Check resources for missing preview images
Civitai: Found 53 resources missing preview images
Civitai: Found 49 hash matches
Civitai: Updated 0 preview images 
```

### Version Platform Description

Starting SD.Next
 Python 3.10.9 on Windows
Version: 76e54938 Sat Jun 10 19:51:35 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3070 Ti VRAM 8192 Arch (8, 6) Cores 48
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
 Enabled extensions: ['a1111-sd-webui-tagcomplete', 'a1111-sd-webui-tome', 'adetailer',
                         'openOutpaint-webUI-extension', 'sd-webui-ar', 'sd_civitai_extension']

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i've tried to reproduce, but it works for me.
i've just moved some messages around so args will be printed on each restart - can you try?

**Comment by vujuha** [comment]
My internet is down for awhile now I will try it once it is up.

**Comment by omniusvujuha** [comment]
It worked thanks. Sorry for delay btw my internet is comes and goes for some reason.

**Comment by omniusvujuha** [comment]
dgfrghtrjtykuk
