### ISSUE TITLE
[Extension]: 'sd-webui-train-tools' is not installed well

### ISSUE THREAD

**Issue by taxen** [vladmandic/automatic#1488]
### Issue Description

I tried to install [sd-webui-train-tools](https://github.com/liasece/sd-webui-train-tools) extension.
After installing it manually from webui's extension tab and restarting both webui and the server, I came across the following error.

```
> H:\vladmandic\automatic>webui.bat --upgrade --lowvram
Using VENV: H:\vladmandic\automatic\venv
20:47:30-406615 INFO     Starting SD.Next
20:47:30-415755 INFO     Python 3.10.6 on Windows
20:47:30-502758 INFO     Version: c02ccc4f Tue Jun 20 13:49:00 2023 +0300
20:47:31-051184 INFO     Updating main repository
20:47:35-082433 INFO     Upgraded to version: 9740b9d2 Thu Jun 22 07:46:48 2023 -0400
20:47:35-137285 INFO     Using CPU-only Torch
20:47:37-506274 INFO     Torch 2.0.0+cpu
20:47:37-725231 INFO     Verifying requirements
20:47:37-752159 INFO     Verifying packages
20:47:37-755152 INFO     Installing repositories
20:47:42-667844 INFO     Installing submodules
20:47:47-591243 INFO     Updating submodules
20:49:14-713510 INFO     Extension installed packages: sd-webui-train-tools
                         ['opencv-python-headless==4.7.0.72', 'albumentations==1.3.1',
                         'scikit-learn==1.2.2', 'joblib==1.2.0', 'diffusers==0.10.2',
                         'qudida==0.0.4']
20:49:21-844062 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext',
                         'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-rembg',
                         'SwinIR', 'sd-webui-infinite-image-browsing', 'sd-webui-train-tools',
                         'sd_civitai_extension']
20:49:21-859588 INFO     Updating Wiki
20:49:24-020204 INFO     Extension preload: 0.0s
                         H:\vladmandic\automatic\extensions-builtin
20:49:24-027076 INFO     Extension preload: 0.0s H:\vladmandic\automatic\extensions
20:49:24-049928 INFO     Server arguments: ['--upgrade', '--lowvram']
No module 'xformers'. Proceeding without it.
Error in sys.excepthook:
Traceback (most recent call last):
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "H:\vladmandic\automatic\launch.py", line 189, in <module>
    instance = start_server(immediate=True, server=None)
  File "H:\vladmandic\automatic\launch.py", line 136, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\vladmandic\automatic\webui.py", line 45, in <module>
    from modules import shared, extensions, extra_networks, ui_tempdir, ui_extra_networks, modelloader
  File "H:\vladmandic\automatic\modules\ui_extra_networks.py", line 8, in <module>
    from modules.generation_parameters_copypaste import image_from_url_text
  File "H:\vladmandic\automatic\modules\generation_parameters_copypaste.py", line 10, in <module>
    from modules import shared, ui_tempdir, script_callbacks, images
  File "H:\vladmandic\automatic\modules\images.py", line 17, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors, paths
  File "H:\vladmandic\automatic\modules\sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, sd_samplers_diffusors, shared
  File "H:\vladmandic\automatic\modules\sd_samplers_diffusors.py", line 1, in <module>
    from diffusers import (
ImportError: cannot import name 'DEISMultistepScheduler' from 'diffusers' (H:\vladmandic\automatic\venv\lib\site-packages\diffusers\__init__.py)
```
I guessed that the new install went wrong. So I deleted sd-webui-train-tools folder completely under automatic\extensions directory. Then I launched the server again and got this error.

```
>webui.bat --upgrade --lowvram
Using VENV: H:\vladmandic\automatic\venv
21:18:55-668066 INFO     Starting SD.Next
21:18:55-683684 INFO     Python 3.10.6 on Windows
21:18:55-777386 INFO     Version: 9740b9d2 Thu Jun 22 07:46:48 2023 -0400
21:18:56-183540 INFO     Using CPU-only Torch
21:18:58-401768 INFO     Torch 2.0.0+cpu
21:18:58-682952 INFO     Disabled extensions-builtin: ['stable-diffusion-webui-images-browser']
21:18:58-682952 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris',
                         'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-rembg',
                         'SwinIR']
21:18:58-714197 INFO     Disabled extensions: ['stable-diffusion-webui-images-browser']
21:18:58-714197 INFO     Enabled extensions: ['sd-webui-infinite-image-browsing',
                         'sd_civitai_extension']
21:18:58-714197 INFO     No changes detected: Quick launch active
21:18:58-729818 INFO     Extension preload: 0.0s
                         H:\vladmandic\automatic\extensions-builtin
21:18:58-729818 INFO     Extension preload: 0.0s H:\vladmandic\automatic\extensions
21:18:58-745440 INFO     Server arguments: ['--upgrade', '--lowvram']
No module 'xformers'. Proceeding without it.
Error in sys.excepthook:
Traceback (most recent call last):
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "H:\vladmandic\automatic\launch.py", line 189, in <module>
    instance = start_server(immediate=True, server=None)
  File "H:\vladmandic\automatic\launch.py", line 136, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\vladmandic\automatic\webui.py", line 45, in <module>
    from modules import shared, extensions, extra_networks, ui_tempdir, ui_extra_networks, modelloader
  File "H:\vladmandic\automatic\modules\ui_extra_networks.py", line 8, in <module>
    from modules.generation_parameters_copypaste import image_from_url_text
  File "H:\vladmandic\automatic\modules\generation_parameters_copypaste.py", line 10, in <module>
    from modules import shared, ui_tempdir, script_callbacks, images
  File "H:\vladmandic\automatic\modules\images.py", line 17, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors, paths
  File "H:\vladmandic\automatic\modules\sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, sd_samplers_diffusors, shared
  File "H:\vladmandic\automatic\modules\sd_samplers_diffusors.py", line 1, in <module>
    from diffusers import (
ImportError: cannot import name 'DEISMultistepScheduler' from 'diffusers' (H:\vladmandic\automatic\venv\lib\site-packages\diffusers\__init__.py)
```

Here is sdnext.log.

```
2023-06-22 20:45:39,008 | sd | INFO | ui_extensions | Installing extension: https://github.com/liasece/sd-webui-train-tools into H:\vladmandic\automatic\extensions\sd-webui-train-tools
2023-06-22 20:45:39,008 | sd | INFO | ui_extensions | Installing extension: https://github.com/liasece/sd-webui-train-tools into H:\vladmandic\automatic\extensions\sd-webui-train-tools
2023-06-22 20:46:11,843 | sd | ERROR | installer | Error running extension installer: H:\vladmandic\automatic\extensions\sd-webui-train-tools\install.py
2023-06-22 20:46:11,843 | sd | ERROR | installer | Error running extension installer: H:\vladmandic\automatic\extensions\sd-webui-train-tools\install.py
2023-06-22 20:47:01,725 | sd | INFO | webui | Exiting
2023-06-22 20:47:01,725 | sd | INFO | webui | Exiting
2023-06-22 20:47:30,406 | sd | INFO | launch | Starting SD.Next
2023-06-22 20:47:30,406 | sd | INFO | launch | Starting SD.Next
2023-06-22 20:47:30,415 | sd | INFO | installer | Python 3.10.6 on Windows
2023-06-22 20:47:30,415 | sd | INFO | installer | Python 3.10.6 on Windows
2023-06-22 20:47:30,502 | sd | INFO | installer | Version: c02ccc4f Tue Jun 20 13:49:00 2023 +0300
2023-06-22 20:47:30,502 | sd | INFO | installer | Version: c02ccc4f Tue Jun 20 13:49:00 2023 +0300
2023-06-22 20:47:31,051 | sd | INFO | installer | Updating main repository
2023-06-22 20:47:31,051 | sd | INFO | installer | Updating main repository
2023-06-22 20:47:35,082 | sd | INFO | installer | Upgraded to version: 9740b9d2 Thu Jun 22 07:46:48 2023 -0400
2023-06-22 20:47:35,082 | sd | INFO | installer | Upgraded to version: 9740b9d2 Thu Jun 22 07:46:48 2023 -0400
2023-06-22 20:47:35,095 | sd | DEBUG | installer | Setting environment tuning
2023-06-22 20:47:35,095 | sd | DEBUG | installer | Setting environment tuning
2023-06-22 20:47:35,096 | sd | DEBUG | installer | Torch overrides: cuda=False rocm=False ipex=False diml=False
2023-06-22 20:47:35,096 | sd | DEBUG | installer | Torch overrides: cuda=False rocm=False ipex=False diml=False
2023-06-22 20:47:35,096 | sd | DEBUG | installer | Torch allowed: cuda=True rocm=True ipex=True diml=True
2023-06-22 20:47:35,096 | sd | DEBUG | installer | Torch allowed: cuda=True rocm=True ipex=True diml=True
2023-06-22 20:47:35,137 | sd | INFO | installer | Using CPU-only Torch
2023-06-22 20:47:35,137 | sd | INFO | installer | Using CPU-only Torch
2023-06-22 20:47:37,506 | sd | INFO | installer | Torch 2.0.0+cpu
2023-06-22 20:47:37,506 | sd | INFO | installer | Torch 2.0.0+cpu
2023-06-22 20:47:37,725 | sd | INFO | installer | Verifying requirements
2023-06-22 20:47:37,725 | sd | INFO | installer | Verifying requirements
2023-06-22 20:47:37,752 | sd | INFO | installer | Verifying packages
2023-06-22 20:47:37,752 | sd | INFO | installer | Verifying packages
2023-06-22 20:47:37,755 | sd | INFO | installer | Installing repositories
2023-06-22 20:47:37,755 | sd | INFO | installer | Installing repositories
2023-06-22 20:47:42,667 | sd | INFO | installer | Installing submodules
2023-06-22 20:47:42,667 | sd | INFO | installer | Installing submodules
2023-06-22 20:47:45,452 | sd | DEBUG | installer | Submodules list: 025dea96720197dd4486a5bb8e2f4d72a95a3088 extensions-builtin/a1111-sd-webui-lycoris (heads/main)
 4d865c5476813d304b1321c25dea8ddb1844d1bd extensions-builtin/clip-interrogator-ext (heads/main)
 de4888103c03d88c0d32af6d453373b47291687a extensions-builtin/multidiffusion-upscaler-for-automatic1111 (sd-webui-v1.1.0-30-gde48881)
 fa12a88ea071d83c654a2bc67c05fef5c5f3bb0f extensions-builtin/sd-dynamic-thresholding (heads/master)
 14d5b61ae776ed7a19140deea4189ce8a105bd4b extensions-builtin/sd-extension-system-info (heads/main)
 b0a8d30c5a7443ee19576362a84c686669699eea extensions-builtin/sd-webui-agent-scheduler (heads/main)
 41011bea0490d1c61decef867d76d54f631dc28a extensions-builtin/sd-webui-controlnet (heads/main)
 b2f6e4cbe507078e3bf2b9d5fce6f83e2e233aa8 extensions-builtin/stable-diffusion-webui-images-browser (heads/main)
 3d9eedbbf0d585207f97d5b21e42f32c0042df70 extensions-builtin/stable-diffusion-webui-rembg (heads/master)
 c7fd336c5d5c0f05378dd34e7b5ca6ac8e972773 modules/lora (v0.6.4-121-gc7fd336)
 57d71913bf47a48dc7dd519b89dd30e09c937b83 modules/lycoris (heads/main)
 f941746c0ed2afcaa37c1ec77b86da4dee131bee wiki (heads/master)
2023-06-22 20:47:45,452 | sd | DEBUG | installer | Submodules list: 025dea96720197dd4486a5bb8e2f4d72a95a3088 extensions-builtin/a1111-sd-webui-lycoris (heads/main)
 4d865c5476813d304b1321c25dea8ddb1844d1bd extensions-builtin/clip-interrogator-ext (heads/main)
 de4888103c03d88c0d32af6d453373b47291687a extensions-builtin/multidiffusion-upscaler-for-automatic1111 (sd-webui-v1.1.0-30-gde48881)
 fa12a88ea071d83c654a2bc67c05fef5c5f3bb0f extensions-builtin/sd-dynamic-thresholding (heads/master)
 14d5b61ae776ed7a19140deea4189ce8a105bd4b extensions-builtin/sd-extension-system-info (heads/main)
 b0a8d30c5a7443ee19576362a84c686669699eea extensions-builtin/sd-webui-agent-scheduler (heads/main)
 41011bea0490d1c61decef867d76d54f631dc28a extensions-builtin/sd-webui-controlnet (heads/main)
 b2f6e4cbe507078e3bf2b9d5fce6f83e2e233aa8 extensions-builtin/stable-diffusion-webui-images-browser (heads/main)
 3d9eedbbf0d585207f97d5b21e42f32c0042df70 extensions-builtin/stable-diffusion-webui-rembg (heads/master)
 c7fd336c5d5c0f05378dd34e7b5ca6ac8e972773 modules/lora (v0.6.4-121-gc7fd336)
 57d71913bf47a48dc7dd519b89dd30e09c937b83 modules/lycoris (heads/main)
 f941746c0ed2afcaa37c1ec77b86da4dee131bee wiki (heads/master)
2023-06-22 20:47:47,591 | sd | INFO | installer | Updating submodules
2023-06-22 20:47:47,591 | sd | INFO | installer | Updating submodules
2023-06-22 20:48:02,232 | sd | DEBUG | installer | Installed packages: 226
2023-06-22 20:48:02,232 | sd | DEBUG | installer | Installed packages: 226
2023-06-22 20:48:02,232 | sd | DEBUG | installer | Extensions all: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-rembg', 'SwinIR']
2023-06-22 20:48:02,232 | sd | DEBUG | installer | Extensions all: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-rembg', 'SwinIR']
2023-06-22 20:48:04,489 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\clip-interrogator-ext\install.py
2023-06-22 20:48:04,489 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\clip-interrogator-ext\install.py
2023-06-22 20:48:20,685 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\sd-extension-system-info\install.py
2023-06-22 20:48:20,685 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\sd-extension-system-info\install.py
2023-06-22 20:48:22,608 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
2023-06-22 20:48:22,608 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
2023-06-22 20:48:24,524 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\sd-webui-controlnet\install.py
2023-06-22 20:48:24,524 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\sd-webui-controlnet\install.py
2023-06-22 20:48:28,193 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\seed_travel\install.py
2023-06-22 20:48:28,193 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\seed_travel\install.py
2023-06-22 20:48:30,069 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
2023-06-22 20:48:30,069 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
2023-06-22 20:48:31,267 | sd | DEBUG | installer | Extensions all: ['sd-webui-infinite-image-browsing', 'sd-webui-train-tools', 'sd_civitai_extension']
2023-06-22 20:48:31,267 | sd | DEBUG | installer | Extensions all: ['sd-webui-infinite-image-browsing', 'sd-webui-train-tools', 'sd_civitai_extension']
2023-06-22 20:48:32,302 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions\sd-webui-infinite-image-browsing\install.py
2023-06-22 20:48:32,302 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions\sd-webui-infinite-image-browsing\install.py
2023-06-22 20:48:41,453 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions\sd-webui-train-tools\install.py
2023-06-22 20:48:41,453 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions\sd-webui-train-tools\install.py
2023-06-22 20:49:14,713 | sd | INFO | installer | Extension installed packages: sd-webui-train-tools ['opencv-python-headless==4.7.0.72', 'albumentations==1.3.1', 'scikit-learn==1.2.2', 'joblib==1.2.0', 'diffusers==0.10.2', 'qudida==0.0.4']
2023-06-22 20:49:14,713 | sd | INFO | installer | Extension installed packages: sd-webui-train-tools ['opencv-python-headless==4.7.0.72', 'albumentations==1.3.1', 'scikit-learn==1.2.2', 'joblib==1.2.0', 'diffusers==0.10.2', 'qudida==0.0.4']
2023-06-22 20:49:15,788 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions\sd_civitai_extension\install.py
2023-06-22 20:49:15,788 | sd | DEBUG | installer | Running extension installer: H:\vladmandic\automatic\extensions\sd_civitai_extension\install.py
2023-06-22 20:49:21,844 | sd | INFO | installer | Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-rembg', 'SwinIR', 'sd-webui-infinite-image-browsing', 'sd-webui-train-tools', 'sd_civitai_extension']
2023-06-22 20:49:21,844 | sd | INFO | installer | Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-rembg', 'SwinIR', 'sd-webui-infinite-image-browsing', 'sd-webui-train-tools', 'sd_civitai_extension']
2023-06-22 20:49:21,859 | sd | INFO | installer | Updating Wiki
2023-06-22 20:49:21,859 | sd | INFO | installer | Updating Wiki
2023-06-22 20:49:24,014 | sd | DEBUG | launch | Setup complete without errors: 1687434564
2023-06-22 20:49:24,014 | sd | DEBUG | launch | Setup complete without errors: 1687434564
2023-06-22 20:49:24,020 | sd | INFO | installer | Extension preload: 0.0s H:\vladmandic\automatic\extensions-builtin
2023-06-22 20:49:24,020 | sd | INFO | installer | Extension preload: 0.0s H:\vladmandic\automatic\extensions-builtin
2023-06-22 20:49:24,027 | sd | INFO | installer | Extension preload: 0.0s H:\vladmandic\automatic\extensions
2023-06-22 20:49:24,027 | sd | INFO | installer | Extension preload: 0.0s H:\vladmandic\automatic\extensions
2023-06-22 20:49:24,049 | sd | INFO | launch | Server arguments: ['--upgrade', '--lowvram']
2023-06-22 20:49:24,049 | sd | INFO | launch | Server arguments: ['--upgrade', '--lowvram']
2023-06-22 21:18:55,668 | sd | INFO | launch | Starting SD.Next
2023-06-22 21:18:55,683 | sd | INFO | installer | Python 3.10.6 on Windows
2023-06-22 21:18:55,777 | sd | INFO | installer | Version: 9740b9d2 Thu Jun 22 07:46:48 2023 -0400
2023-06-22 21:18:56,121 | sd | DEBUG | installer | Setting environment tuning
2023-06-22 21:18:56,121 | sd | DEBUG | installer | Torch overrides: cuda=False rocm=False ipex=False diml=False
2023-06-22 21:18:56,121 | sd | DEBUG | installer | Torch allowed: cuda=True rocm=True ipex=True diml=True
2023-06-22 21:18:56,183 | sd | INFO | installer | Using CPU-only Torch
2023-06-22 21:18:58,401 | sd | INFO | installer | Torch 2.0.0+cpu
2023-06-22 21:18:58,682 | sd | DEBUG | installer | Repository update time: Thu Jun 22 20:46:48 2023
2023-06-22 21:18:58,682 | sd | DEBUG | installer | Previous setup time: Thu Jun 22 20:49:24 2023
2023-06-22 21:18:58,682 | sd | INFO | installer | Disabled extensions-builtin: ['stable-diffusion-webui-images-browser']
2023-06-22 21:18:58,682 | sd | INFO | installer | Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-rembg', 'SwinIR']
2023-06-22 21:18:58,714 | sd | INFO | installer | Disabled extensions: ['stable-diffusion-webui-images-browser']
2023-06-22 21:18:58,714 | sd | INFO | installer | Enabled extensions: ['sd-webui-infinite-image-browsing', 'sd_civitai_extension']
2023-06-22 21:18:58,714 | sd | DEBUG | installer | Latest extensions time: Thu Jun 22 20:49:16 2023
2023-06-22 21:18:58,714 | sd | DEBUG | installer | Timestamps: version:1687434408 setup:1687434564 extension:1687434556
2023-06-22 21:18:58,714 | sd | INFO | launch | No changes detected: Quick launch active
2023-06-22 21:18:58,729 | sd | INFO | installer | Extension preload: 0.0s H:\vladmandic\automatic\extensions-builtin
2023-06-22 21:18:58,729 | sd | INFO | installer | Extension preload: 0.0s H:\vladmandic\automatic\extensions
2023-06-22 21:18:58,745 | sd | INFO | launch | Server arguments: ['--upgrade', '--lowvram']
```

Other than installing the new extension and removing the files mentioned manually, I did nothing. The repo did not change during this operation though I launched with upgrade option. What went wrong with other files?
And thank you for your hard work! You are making my days.

### Version Platform Description

Version: 9740b9d2 Thu Jun 22 07:46:48 2023 -0400, Windows 10 Home 64bit, Chrome 114.0.5735.134（Official Build）
CPU Core i5-6200U, 12GB Mem, No GPU (just HD Graphics 520)

### URL link of the extension

https://github.com/liasece/sd-webui-train-tools

### URL link of the issue reported in the extension repository

https://github.com/liasece/sd-webui-train-tools/issues/35

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
extension installed very old (ancient to be honest) and incompatible version of `diffusers` package.
and after you deleted extension, app did not see any changes to the app, so it skipped checking requirements (so-called quick startup), so i never reinstalled correct version.

you can either force full reinstall of packages using `--reinstall` flag or simply fake that there are some changes so quick-startup is not used, for example open `requirements.txt` and save it, just so it has a new updated timestamp.

**Comment by taxen** [comment]
Thank you for quick reply with detailed explanation. I did want to start the server by any means, so I git cloned your latest repo and the server started without an error once again. I gave up installing the extension.
