### ISSUE TITLE
[Issue]: Token merging cannot be used with Intel Arc

### ISSUE THREAD

**Issue by cyatarow** [vladmandic/automatic#1565]
### Issue Description

When token merging is enabled, an error `scatter add only supports float, bfloat16, int, int64 and double type` occurs.

```
00:18:03-129367 INFO     Settings changed: 1 ['token_merging_ratio']
  0%|                                                                                                                                    | 0/20 [00:01<?, ?it/s]
00:18:06-926736 ERROR    Exception: scatter add only supports float, bfloat16, int, int64 and double type
00:18:06-929627 ERROR    Arguments: args=('task(oxpt31pl3dnooxb)', 'water', '', [], 20, 3, False, False, 1, 1, 6, 1, -1.0, -1.0, 0, 0, 0, False, 512, 576,
                         False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1,
                         64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background',
                         0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0,
                         False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 512, 64,
                         True, True, True, False, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit
                         object at 0x7fce475ac5b0>, False, False, 'positive', 'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '', [], True, False, False,
                         False, 0, False, None, None, False, 50) kwargs={}
00:18:06-933403 ERROR    gradio call: RuntimeError
╭───────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────╮
│ /home/sd_arc/2023.1-linux-hotfix/automatic/modules/call_queue.py:34 in f                                                                                     │
│                                                                                                                                                              │
│    33 │   │   │   try:                                                                                                                                       │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                                                            │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                                                                  │
│                                                                                                                                                              │
│ /home/sd_arc/2023.1-linux-hotfix/automatic/modules/txt2img.py:56 in txt2img                                                                                  │
│                                                                                                                                                              │
│   55 │   if processed is None:                                                                                                                               │
│ ❱ 56 │   │   processed = processing.process_images(p)                                                                                                        │
│   57 │   p.close()                                                                                                                                           │
│                                                                                                                                                              │
│                                                                   ... 29 frames hidden ...                                                                   │
│                                                                                                                                                              │
│ /home/sd_arc/2023.1-linux-hotfix/automatic/venv/lib/python3.10/site-packages/tomesd/patch.py:62 in _forward                                                  │
│                                                                                                                                                              │
│    61 │   │   │   # This is where the meat of the computation happens                                                                                        │
│ ❱  62 │   │   │   x = u_a(self.attn1(m_a(self.norm1(x)), context=context if self.disable_self_                                                               │
│    63 │   │   │   x = u_c(self.attn2(m_c(self.norm2(x)), context=context)) + x                                                                               │
│                                                                                                                                                              │
│ /home/sd_arc/2023.1-linux-hotfix/automatic/venv/lib/python3.10/site-packages/tomesd/merge.py:105 in merge                                                    │
│                                                                                                                                                              │
│   104 │   │   src = gather(src, dim=-2, index=src_idx.expand(n, r, c))                                                                                       │
│ ❱ 105 │   │   dst = dst.scatter_reduce(-2, dst_idx.expand(n, r, c), src, reduce=mode)                                                                        │
│   106                                                                                                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: scatter add only supports float, bfloat16, int, int64 and double type
```

### Version Platform Description
- OS: Windows 11 Pro x64
- WSL2, Ubuntu 22.04.2 LTS
- CPU: Intel Core i3-12100
- RAM: 48GB
- GPU: Intel Arc A750

```
23:49:12-635177 INFO     Starting SD.Next
23:49:12-637778 INFO     Python 3.10.6 on Linux
23:49:12-640100 INFO     Version: 875d0db1 Sun Jul 2 08:26:51 2023 -0400
23:49:12-642705 INFO     Intel OneAPI Toolkit detected
23:49:12-643452 INFO     Installing package: torch==1.13.0a0 torchvision==0.14.1a0 intel_extension_for_pytorch==1.13.120+xpu -f
                         https://developer.intel.com/ipex-whl-stable-xpu
00:03:28-304385 INFO     Torch 1.13.0a0+gitb1dde16
/home/sd_arc/2023.1-linux-hotfix/automatic/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
  warn(f"Failed to load image Python extension: {e}")
00:03:31-717515 INFO     Torch backend: Intel IPEX 1.13.120+xpu
00:03:31-892617 INFO     Intel(R) oneAPI DPC++/C++ Compiler 2023.1.0 (2023.1.0.20230320)
                         Target: x86_64-unknown-linux-gnu
                         Thread model: posix
                         InstalledDir: /opt/intel/oneapi/compiler/2023.1.0/linux/bin-llvm
                         Configuration file: /opt/intel/oneapi/compiler/2023.1.0/linux/bin-llvm/../bin/icpx.cfg
00:03:31-895851 INFO     Torch detected GPU: Intel(R) Graphics [0x56a1] VRAM 6477 Compute Units 448
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
cc: @Disty0

**Comment by Disty0** [comment]
Error explains itself. 
Set the Device precision type to BF16 in compute settings and restart the WebUI.
IPEX doesn't fully support FP16 yet.

**Comment by cyatarow** [comment]
BF16 didn't work.

```
07:53:20-422808 ERROR    Exception: scatter add only supports float, bfloat16, int, int64 and double type
07:53:20-423806 ERROR    Arguments: args=('task(1s00vzab5i7suxn)', 'water', '', [], 20, 3, False, False, 1, 1, 6, 1, 3181926690.0, -1.0, 0, 0, 0, False, 768,
                         576, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1,
                         1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background',
                         0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0,
                         False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 512, 64,
                         True, True, True, False, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit
                         object at 0x7f5422d3b7f0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f5422ee4070>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f544820da80>, False, False, 'positive', 'comma', 0, False,
                         False, '', 0, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None,
                         False, 50) kwargs={}
07:53:20-427145 ERROR    gradio call: RuntimeError
╭───────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────╮
│ /home/sd_arc/2023.1-linux-hotfix/automatic/modules/call_queue.py:34 in f                                                                                     │
│                                                                                                                                                              │
│    33 │   │   │   try:                                                                                                                                       │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                                                            │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                                                                  │
│                                                                                                                                                              │
│ /home/sd_arc/2023.1-linux-hotfix/automatic/modules/txt2img.py:56 in txt2img                                                                                  │
│                                                                                                                                                              │
│   55 │   if processed is None:                                                                                                                               │
│ ❱ 56 │   │   processed = processing.process_images(p)                                                                                                        │
│   57 │   p.close()                                                                                                                                           │
│                                                                                                                                                              │
│                                                                   ... 29 frames hidden ...                                                                   │
│                                                                                                                                                              │
│ /home/sd_arc/2023.1-linux-hotfix/automatic/venv/lib/python3.10/site-packages/tomesd/patch.py:62 in _forward                                                  │
│                                                                                                                                                              │
│    61 │   │   │   # This is where the meat of the computation happens                                                                                        │
│ ❱  62 │   │   │   x = u_a(self.attn1(m_a(self.norm1(x)), context=context if self.disable_self_                                                               │
│    63 │   │   │   x = u_c(self.attn2(m_c(self.norm2(x)), context=context)) + x                                                                               │
│                                                                                                                                                              │
│ /home/sd_arc/2023.1-linux-hotfix/automatic/venv/lib/python3.10/site-packages/tomesd/merge.py:105 in merge                                                    │
│                                                                                                                                                              │
│   104 │   │   src = gather(src, dim=-2, index=src_idx.expand(n, r, c))                                                                                       │
│ ❱ 105 │   │   dst = dst.scatter_reduce(-2, dst_idx.expand(n, r, c), src, reduce=mode)                                                                        │
│   106                                                                                                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: scatter add only supports float, bfloat16, int, int64 and double type
Traceback (most recent call last):
  File "/home/sd_arc/2023.1-linux-hotfix/automatic/venv/bin/ipexrun", line 8, in <module>
    sys.exit(main())
  File "/home/sd_arc/2023.1-linux-hotfix/automatic/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 880, in main
    launcher.launch(args)
  File "/home/sd_arc/2023.1-linux-hotfix/automatic/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 542, in launch
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd_s)
subprocess.CalledProcessError: Command 'taskset -c 0-3 /home/sd_arc/2023.1-linux-hotfix/automatic/venv/bin/python3 -u launch.py --use-ipex --medvram' died with <Signals.SIGSEGV: 11>.
```

**Comment by Disty0** [comment]
Restart the webui.

**Comment by cyatarow** [comment]
This error was fixed after restarting the entire Windows system.
By the way... with token merging enabled, image generation speed is weird.

Results (50 steps, 512x512, DPM++ 2M SDE Karras)
ToMe Disabled: 5.66it/s
ToMe 0.1: 4.42it/s (slowed down)
ToMe 0.3: 5.70it/s (almost the same as the disabled one)
ToMe 0.5: 6.29it/s

**Comment by Disty0** [comment]
I don't know what fixed it but i can't replicate this error anymore.

**Comment by cyatarow** [comment]
OK. Now `scatter add only supports float, bfloat16, int, int64 and double type` error and weird generation speed are gone, and BF16 works fine.
