### ISSUE TITLE
[Issue]: Issue with Threads

### ISSUE THREAD

**Issue by demib72** [vladmandic/automatic#1569]
### Issue Description

Hello, I am having trouble diagnosing the following:

```Create and activate python venv
Launching launch.py...
09:03:10-049060 INFO     Starting SD.Next                                                                 
09:03:10-051895 INFO     Python 3.10.6 on Linux                                                           
09:03:10-055796 INFO     Version: 875d0db1 Sun Jul 2 08:26:51 2023 -0400                                  
09:03:10-815002 INFO     nVidia CUDA toolkit detected                                                     
09:03:11-670033 INFO     Torch 2.0.1+cu118                                                                
09:03:11-741395 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700                                       
09:03:11-756397 INFO     Torch detected GPU: NVIDIA GeForce RTX 2060 VRAM 5918 Arch (7, 5) Cores 30       
09:03:11-765684 WARNING  Modified files: ['webui.sh', 'auto-venv/', 'installer.py1', 'installs/',         
                         'launch.py1']                                                                    
09:03:11-772023 INFO     Enabled extensions-builtin: []                                                   
09:03:11-772792 INFO     Enabled extensions: ['unprompted', 'openOutpaint-webUI-extension',               
                         'sd-webui-roop', 'a1111-sd-webui-tagcomplete', 'booru2prompt', 'batch-face-swap',
                         'sd-webui-3d-open-pose-editor', 'sd-webui-openpose-editor', 'adetailer',         
                         'sd-webui-aspect-ratio-helper', 'sd-dynamic-prompts',                            
                         'Stable-Diffusion-Webui-Civitai-Helper']                                         
09:03:11-774813 INFO     No changes detected: Quick launch active                                         
09:03:11-775819 INFO     Extension preload: 0.0s /home/user/Applications/automatic/extensions-builtin
09:03:11-776847 INFO     Extension preload: 0.0s /home/user/Applications/automatic/extensions        
09:03:11-783442 INFO     Server arguments: ['--medvram']                                                  
No module 'xformers'. Proceeding without it.
09:03:15-819094 INFO     Libraries loaded                                                                 
09:03:15-824095 INFO     Using data path: /home/user/Applications/automatic                          
09:03:15-827752 INFO     Available VAEs: /home/user/Applications/automatic/models/VAE 4              
09:03:15-863281 INFO     Available models: /home/user/Applications/automatic/models/Stable-diffusion 
                         20                                                                               
[-] ADetailer initialized. version: 23.7.1, num models: 8
Loading booru2prompt settings
2023-07-04 09:03:20,255 - roop - INFO - roop v0.0.2
2023-07-04 09:03:20,256 - roop - INFO - roop v0.0.2
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: /home/user/Applications/automatic/extensions/Stable-Diffusion-Webui-Civitai-Helper/setting.json
Civitai Helper: No setting file, use default
(SETUP) Loading Unprompted v9.5.1 by Therefore Games
(SETUP) Initializing Unprompted object...
(SETUP) Loading configuration files...
(SETUP) Logging enabled for the following message types: RESULT,WARNING,ERROR
09:03:21-887126 INFO     Loading UI theme: name=derekzen/stardust style=Dark                              
Exception in thread Thread-5 (create_thumb):
Traceback (most recent call last):
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/ImageFile.py", line 249, in load
    s = read(self.decodermaxblock)
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/PngImagePlugin.py", line 941, in load_read
    cid, pos, length = self.png.read()
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/PngImagePlugin.py", line 178, in read
Loading weights: /home/user/Applications/automatic/models/Stable-diffusion/aZovyaPhotoreal_v2.safet…     length = i32(s)
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/_binary.py", line 85, in i32be
    return unpack_from(">I", c, o)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Applications/automatic/modules/ui_extra_networks.py", line 138, in create_thumb
    img = img.convert('RGB')
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/Image.py", line 933, in convert
    self.load()
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/ImageFile.py", line 256, in load
    raise OSError(msg) from e
OSError: image file is truncated
Loading weights: /home/user/Applications/automatic/models/Stable-diffusion/aZovyaPhotoreal_v2.safet… 
09:03:22-256433 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16                  
                         unet=torch.float16                                                               
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
09:03:23-867562 INFO     Applying scaled dot product cross attention optimization                         
09:03:23-886896 INFO     Embeddings: loaded=23 skipped=0                                                  
09:03:23-887843 INFO     Model loaded in 1.8s (load=0.2s create=0.6s apply=0.6s vae=0.4s)                 
09:03:24-083657 INFO     Model load finished: {'ram': {'used': 9.2, 'total': 31.23}, 'gpu': {'used': 0.61,
                         'total': 5.78}, 'retries': 0, 'oom': 0} cached=0                                 
Exception in thread Thread-9 (create_thumb):
Traceback (most recent call last):
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/ImageFile.py", line 249, in load
    s = read(self.decodermaxblock)
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/PngImagePlugin.py", line 941, in load_read
    cid, pos, length = self.png.read()
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/PngImagePlugin.py", line 178, in read
    length = i32(s)
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/_binary.py", line 85, in i32be
    return unpack_from(">I", c, o)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Applications/automatic/modules/ui_extra_networks.py", line 138, in create_thumb
    img = img.convert('RGB')
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/Image.py", line 933, in convert
    self.load()
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/PIL/ImageFile.py", line 256, in load
    raise OSError(msg) from e
OSError: image file is truncated
Running on local URL:  http://127.0.0.1:7861
09:03:26-860070 INFO     Local URL: http://127.0.0.1:7861/                                                
09:03:26-861600 INFO     Initializing middleware                                                          
09:03:27-425096 INFO     Startup time: 15.6s (torch=1.9s gradio=1.2s libraries=1.0s scripts=4.4s          
                         onchange=1.6s ui=4.4s launch=0.6s app-started=0.1s checkpoint=0.5s)```

I get what the errors are saying, but I can't figure where the threads are being made to figure what Pillow is trying to be used with. I have removed both built-in/user extensions (moved to another folder) and used --safe, same issue.

### Version Platform Description

09:03:10-051895 INFO     Python 3.10.6 on Linux                                                           
09:03:10-055796 INFO     Version: 875d0db1 Sun Jul 2 08:26:51 2023 -0400                                  
09:03:10-815002 INFO     nVidia CUDA toolkit detected                                                     
09:03:11-670033 INFO     Torch 2.0.1+cu118                                                                
09:03:11-741395 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700                                       
09:03:11-756397 INFO     Torch detected GPU: NVIDIA GeForce RTX 2060 VRAM 5918 Arch (7, 5) Cores 30       

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
its trying to create smaller thumbnails from larger model preview images so ui doesn't have to load massive images when displaying extra networks ui. and that is done in a background thread in `modules/ui_extra_networks.py:create_thumb()` for any preview image that doesn't have thumb already created.

i've added some error handling around that, but right now work is in dev so it wont be posted to master until end-of-the-week.
if you want to test, you can switch to `dev` branch, otherwise wait for the next update to `master`.
