### ISSUE TITLE
[Issue]: Gradio HTTP API: ValueError TemplateNotFound: frontend/share.html

### ISSUE THREAD

**Issue by YKefasu** [vladmandic/automatic#1580]
### Issue Description

```
09:21:50-567323 INFO     Starting SD.Next                                       
09:21:50-573514 INFO     Python 3.10.12 on Linux                                
09:21:50-586488 INFO     Version: 45d50bd Wed Jul 5 00:12:07 2023 +0300         
09:21:50-872833 INFO     nVidia CUDA toolkit detected                           
09:21:55-017166 INFO     Torch 2.0.1+cu118                                      
09:21:55-077008 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700             
09:21:55-109994 INFO     Torch detected GPU: Tesla T4 VRAM 15102 Arch (7, 5)    
                         Cores 40                                               
09:21:55-304035 INFO     Enabled extensions-builtin: ['sd-webui-controlnet',    
                         'Lora', 'ScuNET',                                      
                         'stable-diffusion-webui-images-browser',               
                         'sd-extension-system-info', 'clip-interrogator-ext',   
                         'multidiffusion-upscaler-for-automatic1111', 'SwinIR', 
                         'stable-diffusion-webui-rembg', 'sd-artists-ui-tweak', 
                         'LDSR', 'a1111-sd-webui-lycoris',                      
                         'sd-webui-agent-scheduler', 'sd-dynamic-thresholding', 
                         'sd-model-downloader']                                 
09:21:55-309374 INFO     No changes detected: Quick launch active               
09:21:55-317949 INFO     Running in safe mode without user extensions           
09:21:55-322567 INFO     Extension preload: 0.0s                                
                         /content/automatic/extensions-builtin       
09:21:55-351797 INFO     Server arguments: ['--no-hashing --share --no-download --safe']                                              
2023-07-05 09:21:59.346926: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
No module 'xformers'. Proceeding without it.
09:22:03-253564 INFO     Libraries loaded                                       
09:22:03-257639 INFO     Using data path: /content/automatic         
09:22:03-261389 INFO     Available VAEs:                                        
                         /content/automatic/models/VAE 15            
09:22:03-263430 INFO     Available models:                                      
                         /content/automatic/models/Stable-diffusion 1
Model Downloader v1.0.6 fixed
Checking Directories...
all Directories already Created.
09:22:06-199919 INFO     ControlNet v1.1.227                                    
ControlNet v1.1.227
ControlNet preprocessor location: /content/automatic/extensions-builtin/sd-webui-controlnet/annotator/downloads
09:22:06-531361 INFO     ControlNet v1.1.227                                    
ControlNet v1.1.227
Image Browser: ImageReward is not installed, cannot be used.
09:22:07-688451 INFO     Loading UI theme: name=black-orange style=Auto         
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 251, in main
    return templates.TemplateResponse(
  File "/content/automatic/modules/ui.py", line 1209, in template_response
    res = modules.shared.GradioTemplateResponseOriginal(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/usr/local/lib/python3.10/dist-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 257, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 251, in main
    return templates.TemplateResponse(
  File "/content/automatic/modules/ui.py", line 1209, in template_response
    res = modules.shared.GradioTemplateResponseOriginal(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/usr/local/lib/python3.10/dist-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 257, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 251, in main
    return templates.TemplateResponse(
  File "/content/automatic/modules/ui.py", line 1209, in template_response
    res = modules.shared.GradioTemplateResponseOriginal(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/usr/local/lib/python3.10/dist-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 257, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 251, in main
    return templates.TemplateResponse(
  File "/content/automatic/modules/ui.py", line 1209, in template_response
    res = modules.shared.GradioTemplateResponseOriginal(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/usr/local/lib/python3.10/dist-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 257, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 251, in main
    return templates.TemplateResponse(
  File "/content/automatic/modules/ui.py", line 1209, in template_response
    res = modules.shared.GradioTemplateResponseOriginal(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/usr/local/lib/python3.10/dist-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 257, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://201ec44544a540fb66.gradio.live
09:22:17-495353 INFO     Local URL: http://127.0.0.1:7860/                      
09:22:17-496928 INFO     Share URL: https://201ec44544a540fb66.gradio.live      
09:22:17-498007 INFO     Initializing middleware                                
09:22:17-658439 INFO     [AgentScheduler] Task queue is empty                   
09:22:17-659816 INFO     [AgentScheduler] Registering APIs                      
09:22:18-241633 WARNING  Selected checkpoint not found: model.ckpt              
09:22:18-685133 WARNING  Loading fallback checkpoint:                           
                         DreamShaper_6_NoVae_pruned.safetensors                 
Loading weights: /content/automatic/models/Stable-diffusion/DreamSh… 
09:22:18-884117 INFO     Setting Torch parameters: dtype=torch.float16          
                         vae=torch.float16 unet=torch.float16                   
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
09:22:23-167810 ERROR    API error: GET: https://201ec44544a540fb66.gradio.live/
                         {'error': 'ValueError', 'detail': '', 'body': '',      
                         'errors': 'Did you install Gradio from source files?   
                         Share mode only works when Gradio is installed through 
                         the pip package.'}                                     
09:22:23-170335 ERROR    HTTP API: ValueError                                   
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/gradio/routes.py:251 in main         │
│                                                                              │
│   250 │   │   │   │   )                                                      │
│ ❱ 251 │   │   │   │   return templates.TemplateResponse(                     │
│   252 │   │   │   │   │   template,                                          │
│                                                                              │
│ /content/automatic/modules/ui.py:1209 in template_response        │
│                                                                              │
│   1208 │   def template_response(*args, **kwargs):                           │
│ ❱ 1209 │   │   res = modules.shared.GradioTemplateResponseOriginal(*args, ** │
│   1210 │   │   res.body = res.body.replace(b'</head>', f'{head}</head>'.enco │
│                                                                              │
│                           ... 4 frames hidden ...                            │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/jinja2/loaders.py:126 in load        │
│                                                                              │
│   125 │   │   # with the filename and the uptodate function.                 │
│ ❱ 126 │   │   source, filename, uptodate = self.get_source(environment, name │
│   127                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/jinja2/loaders.py:218 in get_source  │
│                                                                              │
│   217 │   │   │   return contents, os.path.normpath(filename), uptodate      │
│ ❱ 218 │   │   raise TemplateNotFound(template)                               │
│   219                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/automatic/modules/middleware.py:41 in log_and_time       │
│                                                                              │
│   40 │   │   │   ts = time.time()                                            │
│ ❱ 41 │   │   │   res: Response = await call_next(req)                        │
│   42 │   │   │   duration = str(round(time.time() - ts, 4))                  │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py:84 in   │
│ call_next                                                                    │
│                                                                              │
│                           ... 15 frames hidden ...                           │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py:807 in   │
│ run                                                                          │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio/routes.py:257 in main         │
│                                                                              │
│   256 │   │   │   │   if blocks.share:                                       │
│ ❱ 257 │   │   │   │   │   raise ValueError(                                  │
│   258 │   │   │   │   │   │   "Did you install Gradio from source files? Sha │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: Did you install Gradio from source files? Share mode only works when
Gradio is installed through the pip package.
09:22:23-544429 INFO     Applying scaled dot product cross attention            
                         optimization                                           
09:22:23-585498 INFO     Embeddings: loaded=9 skipped=0                         
09:22:23-593348 INFO     Model loaded in 4.9s (load=0.2s create=0.8s apply=2.0s 
                         vae=0.9s move=0.9s)                                    
09:22:24-054524 INFO     Model load finished: {'ram': {'used': 7.35, 'total':   
                         12.68}, 'gpu': {'used': 2.15, 'total': 14.75},         
                         'retries': 0, 'oom': 0} cached=0                       
09:22:24-108344 INFO     Startup time: 28.8s (torch=5.4s gradio=0.7s            
                         libraries=1.7s scripts=4.4s ui=2.2s launch=7.6s        
                         app-started=0.3s checkpoint=6.3s)   
```

### Version Platform Description

**### GOOGLE COLAB**

09:21:50-567323 INFO     Starting SD.Next                                       
09:21:50-573514 INFO     Python 3.10.12 on Linux                                
09:21:50-586488 INFO     Version: 45d50bd Wed Jul 5 00:12:07 2023 +0300         
09:21:50-872833 INFO     nVidia CUDA toolkit detected                           
09:21:55-017166 INFO     Torch 2.0.1+cu118                                      
09:21:55-077008 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700             
09:21:55-109994 INFO     Torch detected GPU: Tesla T4 VRAM 15102 Arch (7, 5)    
                         Cores 40 

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by YKefasu** [comment]
extension conflict

**Comment by YKefasu** [comment]
conflicting with https://github.com/richrobber2/canvas-zoom

**Comment by vladmandic** [comment]
i wouldn't even call it a conflict, what extension does is modify Gradio files directly - and that is just EVIL, no other way of putting it.

```python
    # Deleting the existing "templates" folder in the gradio folder, if it exists
    if os.path.exists(destination_dir):
        shutil.rmtree(destination_dir)
    
    # Moving the "templates" folder from the canvasZoom folder to the gradio folder
    shutil.copytree(source_dir, destination_dir)
```
