### ISSUE TITLE
[Issue]: Delete button doesn't delete pictures from gen tab. Agent scheduler again. 

### ISSUE THREAD

**Issue by Deniryer** [vladmandic/automatic#1586]
### Issue Description

Since my previous query was closed I just have to open another one. 12.1 and nightly version of torch gave me same problems which did not happened  before so I uninstalled them, reverted back to 11.8 (meaning fresh install), did a fresh install (meaning I even cleared everting that was cached) of Vlad's fork, went back on a driver, disabled dreambooth (as that was extension that I installed right before it started to happen again) and image browser (which for some reason stopped working that's why I started using infinite image)  just in case. Even got rid of Vlad's fork and installed A1111 only with agent scheduler and it does work fine. 

I still get the errors. It does occur after running couple of tasks, it just seems like it does not clear previously loaded model and hence runs out of memory. Can't pin point when exactly it happens because I'm afk, that's the entire reason why I queue task in a first place, but looking at task history it does seems that it happens when model is suppose to change the same task are supposed to be done (prompt, batch count, seed, parameters) for comparison. 

Also for some reason delete button under normal generation tab stopped working. 

Can't be graphics card, A1111 works fine, but I still prefer this fork over it with all the enchantments and QoL improvements.
Error for delete buttton:
```
'ERROR    gradio call: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\modules\call_queue.py:58 in f                                                                   │
│                                                                                                                      │
│    57 │   │   │   │   pr.enable()                                                                                    │
│ ❱  58 │   │   │   res = func(*args, **kwargs)                                                                        │
│    59 │   │   │   if res is None:                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: delete_files() missing 1 required positional argument: 'index'

```
Error info for agent scheduler: 

```
`RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread MemMon:
06:19:16-632018 ERROR    [AgentScheduler] Task task(2ms58ns1a90lix9) failed: CUDA error: an illegal memory access was
                         encountered
                         CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace
                         below might be incorrect.
                         For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
                         Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "C:\Users\adi17\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:98 in receive                                    │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:93 in receive_nowait                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
WouldBlock

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next                             │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:118 in receive                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
EndOfStream

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\modules\middleware.py:41 in log_and_time                                                        │
│                                                                                                                      │
│   40 │   │   │   ts = time.time()                                                                                    │
│ ❱ 41 │   │   │   res: Response = await call_next(req)                                                                │
│   42 │   │   │   duration = str(round(time.time() - ts, 4))                                                          │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\starlette\middleware\base.py:84 in call_next                             │
│                                                                                                                      │
│                                               ... 27 frames hidden ...                                               │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                                  │
│                                                                                                                      │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                              │
│    464                                                                                                               │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward                            │
│                                                                                                                      │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                                             │
│ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                                     │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
    self.run()
  File "D:\SD\Vlad\automatic\modules\memmon.py", line 60, in run
06:19:16-665550 ERROR    API error: POST: http://127.0.0.1:7860/internal/progress {'error': 'RuntimeError', 'detail':
                         '', 'body': '', 'errors': 'cuDNN error: CUDNN_STATUS_EXECUTION_FAILED'}
06:19:16-666555 ERROR    HTTP API: RuntimeError
    free, _total = self.cuda_mem_get_info()
  File "D:\SD\Vlad\automatic\modules\memmon.py", line 43, in cuda_mem_get_info
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:98 in receive                                    │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:93 in receive_nowait                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
WouldBlock

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next                             │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:118 in receive                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
EndOfStream

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\modules\middleware.py:41 in log_and_time                                                        │
│                                                                                                                      │
│   40 │   │   │   ts = time.time()                                                                                    │
│ ❱ 41 │   │   │   res: Response = await call_next(req)                                                                │
│   42 │   │   │   duration = str(round(time.time() - ts, 4))                                                          │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\starlette\middleware\base.py:84 in call_next                             │
│                                                                                                                      │
│                                               ... 27 frames hidden ...                                               │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                                  │
│                                                                                                                      │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                              │
│    464                                                                                                               │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward                            │
│                                                                                                                      │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                                             │
│ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                                     │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
    return torch.cuda.mem_get_info(index)
06:19:16-702077 INFO     [AgentScheduler] Task queue is empty
  File "D:\SD\Vlad\automatic\venv\lib\site-packages\torch\cuda\memory.py", line 618, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`
```

As to FP8 support I did not have a chance to reply, NV added it to Transformer Engine, Apple has it in CoreML (which draw Things uses) and apart from weight being changed due to conversion to coreML/MetalAPI there's no difference in quality, but weight of a file is significantly smaller and throughput is increased. 

https://developer.nvidia.com/blog/cuda-toolkit-12-0-released-for-general-availability/
https://github.com/NVIDIA/TransformerEngine

But it's your fork & work you'll decide. 

### Version Platform Description

```
'Starting SD.Next
Python 3.10.6 on Windows
Version: 3bcca6f9 Thu Jul 6 02:51:27 2023 +0300
nVidia CUDA toolkit detected
 Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
Disabled extensions-builtin: ['stable-diffusion-webui-images-browser',
                         'sd_dreambooth_extension']
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-rembg', 'SwinIR']
Disabled extensions: ['stable-diffusion-webui-images-browser', 'sd_dreambooth_extension']
Enabled extensions: ['adetailer', 'sd-webui-infinite-image-browsing', 'sd-webui-supermerger']
Verifying requirements
 Verifying packages
nstalling repositories
Installing submodules
Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-rembg', 'SwinIR', 'adetailer', 'sd-webui-infinite-image-browsing',
                         'sd-webui-supermerger']'
```
Firefox 115
7900X.
RTX4090
32GB 6000 CL 36
No OC on CPU, RAM or GPU. 

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i'll investigate, but have to place on backlog until some major work finishes.

**Comment by Deniryer** [comment]
Hopefully it's just a typo or/and whatever you going to work will fix this in the mean time. 

Thank you.

**Comment by vladmandic** [comment]
yeah, i like it, except its not native implemention, its basically a standalone thing just happens to run in a tab.
i don't like image browser as-is as well, but no time to write a better one.
