### ISSUE TITLE
[Issue]: Cannot Import Undefined from pydantic

### ISSUE THREAD

**Issue by luka0611** [vladmandic/automatic#1670]
### Issue Description

I'm getting the error below, everytime i launch Vlad, Also yesterday it was working normally. 

```
`venv "C:\Users\User\automatic\venv\Scripts\Python.exe"
14:32:31-215589 INFO     Python 3.10.11 on Windows
14:32:31-346246 INFO     Version: 98adfb31 Sun Apr 23 11:50:30 2023 -0400
14:32:31-971815 INFO     Latest published version: a02c43a90767a30ed37faf6723199a42f4b3deb0 2023-07-13T16:35:47Z
14:32:31-972817 INFO     Updating Wiki
14:32:34-197857 INFO     nVidia toolkit detected
14:32:38-695082 INFO     Torch 2.0.0+cu118
14:32:38-720809 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
14:32:38-721889 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 VRAM 8191 Arch (8, 6) Cores 46
14:32:38-723891 INFO     Verifying requirements
14:32:38-857715 INFO     No changes detected: Quick launch active
14:32:38-858726 INFO     Setting environment tuning
14:32:38-866175 INFO     Running extension preloading
14:32:38-867175 INFO     Server arguments: []
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\User\automatic\launch.py:100 in <module>                                                │
│                                                                                                  │
│    97 │   setup.log.info(f"Server arguments: {sys.argv[1:]}")                                    │
│    98 │   setup.log.debug('Starting WebUI')                                                      │
│    99 │   logging.disable(logging.INFO)                                                          │
│ ❱ 100 │   import webui                                                                           │
│   101 │   webui.webui()                                                                          │
│   102                                                                                            │
│                                                                                                  │
│ C:\Users\User\automatic\webui.py:21 in <module>                                                  │
│                                                                                                  │
│    18 warnings.filterwarnings(action="ignore", category=UserWarning, module="torchvision")       │
│    19 startup_timer.record("torch")                                                              │
│    20                                                                                            │
│ ❱  21 from modules import import_hook # pylint: disable=W0611,C0411,C0412                        │
│    22 import gradio # pylint: disable=W0611,C0411                                                │
│    23 startup_timer.record("gradio")                                                             │
│    24 errors.install([gradio])                                                                   │
│                                                                                                  │
│ C:\Users\User\automatic\modules\import_hook.py:2 in <module>                                     │
│                                                                                                  │
│    1 import sys                                                                                  │
│ ❱  2 from modules.shared import opts                                                             │
│    3                                                                                             │
│    4 # this will break any attempt to import xformers which will prevent stability diffusion     │
│    5 try:                                                                                        │
│                                                                                                  │
│ C:\Users\User\automatic\modules\shared.py:7 in <module>                                          │
│                                                                                                  │
│     4 import sys                                                                                 │
│     5 import time                                                                                │
│     6                                                                                            │
│ ❱   7 import gradio as gr                                                                        │
│     8 import tqdm                                                                                │
│     9                                                                                            │
│    10 import modules.interrogate                                                                 │
│                                                                                                  │
│ C:\Users\User\automatic\venv\lib\site-packages\gradio\__init__.py:3 in <module>                  │
│                                                                                                  │
│    1 import pkgutil                                                                              │
│    2                                                                                             │
│ ❱  3 import gradio.components as components                                                      │
│    4 import gradio.inputs as inputs                                                              │
│    5 import gradio.outputs as outputs                                                            │
│    6 import gradio.processing_utils                                                              │
│                                                                                                  │
│ C:\Users\User\automatic\venv\lib\site-packages\gradio\components.py:32 in <module>               │
│                                                                                                  │
│     29 from PIL import Image as _Image  # using _ to minimize namespace pollution                │
│     30 from typing_extensions import Literal                                                     │
│     31                                                                                           │
│ ❱   32 from gradio import media_data, processing_utils, utils                                    │
│     33 from gradio.blocks import Block, BlockContext                                             │
│     34 from gradio.documentation import document, set_documentation_group                        │
│     35 from gradio.events import (                                                               │
│                                                                                                  │
│ C:\Users\User\automatic\venv\lib\site-packages\gradio\processing_utils.py:21 in <module>         │
│                                                                                                  │
│    18 import aiofiles                                                                            │
│    19 import numpy as np                                                                         │
│    20 import requests                                                                            │
│ ❱  21 from fastapi import UploadFile                                                             │
│    22 from ffmpy import FFmpeg, FFprobe, FFRuntimeError                                          │
│    23 from PIL import Image, ImageOps, PngImagePlugin                                            │
│    24                                                                                            │
│                                                                                                  │
│ C:\Users\User\automatic\venv\lib\site-packages\fastapi\__init__.py:7 in <module>                 │
│                                                                                                  │
│    4                                                                                             │
│    5 from starlette import status as status                                                      │
│    6                                                                                             │
│ ❱  7 from .applications import FastAPI as FastAPI                                                │
│    8 from .background import BackgroundTasks as BackgroundTasks                                  │
│    9 from .datastructures import UploadFile as UploadFile                                        │
│   10 from .exceptions import HTTPException as HTTPException                                      │
│                                                                                                  │
│ C:\Users\User\automatic\venv\lib\site-packages\fastapi\applications.py:16 in <module>            │
│                                                                                                  │
│    13 │   Union,                                                                                 │
│    14 )                                                                                          │
│    15                                                                                            │
│ ❱  16 from fastapi import routing                                                                │
│    17 from fastapi.datastructures import Default, DefaultPlaceholder                             │
│    18 from fastapi.encoders import DictIntStrAny, SetIntStr                                      │
│    19 from fastapi.exception_handlers import (                                                   │
│                                                                                                  │
│ C:\Users\User\automatic\venv\lib\site-packages\fastapi\routing.py:22 in <module>                 │
│                                                                                                  │
│     19 │   Union,                                                                                │
│     20 )                                                                                         │
│     21                                                                                           │
│ ❱   22 from fastapi import params                                                                │
│     23 from fastapi.datastructures import Default, DefaultPlaceholder                            │
│     24 from fastapi.dependencies.models import Dependant                                         │
│     25 from fastapi.dependencies.utils import (                                                  │
│                                                                                                  │
│ C:\Users\User\automatic\venv\lib\site-packages\fastapi\params.py:4 in <module>                   │
│                                                                                                  │
│     1 from enum import Enum                                                                      │
│     2 from typing import Any, Callable, Dict, Optional, Sequence                                 │
│     3                                                                                            │
│ ❱   4 from pydantic.fields import FieldInfo, Undefined                                           │
│     5                                                                                            │
│     6                                                                                            │
│     7 class ParamTypes(Enum):                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'Undefined' from 'pydantic.fields'
(C:\Users\User\automatic\venv\lib\site-packages\pydantic\fields.py)`

```
### Version Platform Description

Windows 11, Latest Update.

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
your version of pydanic is incorrect. installer should take care of that on `--upgrade`, but if it doesn't, run `--reinstall`

**Comment by vladmandic** [comment]
i've added force requirements check on every app startup.

**Comment by nissansz** [comment]
I have same issue. How to fix? 

ImportError: cannot import name 'Undefined' from 'pydantic.fields'


pydantic                                      2.5.3
pydantic_core                                 2.14.6

**Comment by vladmandic** [comment]
same solution as noted above. and posting on an issue that is closed more than half a year ago is typically not a way to go.

**Comment by nissansz** [comment]
Thank you for reply.
It does not work.

pydantic                                      2.5.3
pydantic_core                                 2.14.6


    from fastapi import FastAPI
  File "D:\Python3.8.8\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "D:\Python3.8.8\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "D:\Python3.8.8\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "D:\Python3.8.8\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (D:\Python3.8.8\lib\site-packages\pydantic\fields.py)

**Comment by vladmandic** [comment]
sdnext does not support pydantic 2.x
and sdnext installer installs correct one.
so uninstall it and let sdnext do its thing. and if its still wrong, check whatever you have that keeps installing wrong one.
and do not post on issue closed 6 months ago!

**Comment by kalilinux-png** [comment]
> Thank you for reply. It does not work.
> 
> pydantic 2.5.3 pydantic_core 2.14.6
> 
> ```
> from fastapi import FastAPI
> ```
> 
> File "D:\Python3.8.8\lib\site-packages\fastapi__init__.py", line 7, in from .applications import FastAPI as FastAPI File "D:\Python3.8.8\lib\site-packages\fastapi\applications.py", line 15, in from fastapi import routing File "D:\Python3.8.8\lib\site-packages\fastapi\routing.py", line 22, in from fastapi import params File "D:\Python3.8.8\lib\site-packages\fastapi\params.py", line 4, in from pydantic.fields import FieldInfo, Undefined ImportError: cannot import name 'Undefined' from 'pydantic.fields' (D:\Python3.8.8\lib\site-packages\pydantic\fields.py)

This Worked for me 
`pip install pydantic==1.10.11`
