### ISSUE TITLE
[Issue]: KeyError: 'sd_backend' after the last upgrade

### ISSUE THREAD

**Issue by nxrighthere** [vladmandic/automatic#1674]
### Issue Description

After the last upgrade I'm getting the following error:
```
No module 'xformers'. Proceeding without it.
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\nxrig\Documents\AutomaticDiffusion\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "C:\Users\nxrig\Documents\AutomaticDiffusion\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "C:\Users\nxrig\Documents\AutomaticDiffusion\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "C:\Users\nxrig\Documents\AutomaticDiffusion\launch.py", line 190, in <module>
    instance = start_server(immediate=True, server=None)
  File "C:\Users\nxrig\Documents\AutomaticDiffusion\launch.py", line 136, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\nxrig\Documents\AutomaticDiffusion\webui.py", line 43, in <module>
    from modules.call_queue import queue_lock, wrap_queued_call, wrap_gradio_gpu_call # pylint: disable=W0611,C0411,C0412
  File "C:\Users\nxrig\Documents\AutomaticDiffusion\modules\call_queue.py", line 8, in <module>
    from modules import shared, progress, errors
  File "C:\Users\nxrig\Documents\AutomaticDiffusion\modules\shared.py", line 754, in <module>
    backend = Backend.DIFFUSERS if opts.data['sd_backend'] == 'diffusers' else Backend.ORIGINAL
KeyError: 'sd_backend'
```
Running `webui.bat` with `--backend original` starts the app just fine.

### Version Platform Description

01:53:57-853081 INFO     Starting SD.Next
01:53:57-857080 INFO     Python 3.10.6 on Windows
01:53:57-892081 INFO     Version: 558b71f0 Fri Jul 14 02:21:52 2023 +0300
01:53:58-346124 INFO     nVidia CUDA toolkit detected
01:53:59-809950 INFO     Torch 2.0.1+cu118
01:53:59-828948 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
01:53:59-830952 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 VRAM 8192 Arch (8, 6) Cores 46
01:53:59-964950 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
01:53:59-972953 INFO     Enabled extensions: ['a1111-sd-webui-tagcomplete']

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
same root cause as #1673, i'll fix tomorrow.
