### ISSUE TITLE
[Issue]: Generation fails when either batchsize or batchcount > 1 using last version.

### ISSUE THREAD

**Issue by drax-xard** [vladmandic/automatic#1720]
### Issue Description

When trying to generate more than one image at a time it fails with the following error: 
```
Traceback (most recent call last):
  File "/home/user/SD/automatic/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/SD/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/user/SD/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/user/SD/automatic/venv/lib/python3.10/site-packages/gradio/components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "/home/user/SD/automatic/modules/ui_tempdir.py", line 61, in pil_to_temp_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "/usr/lib/python3.10/tempfile.py", line 698, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/usr/lib/python3.10/tempfile.py", line 695, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.10/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gradio/tmp7_fzn9dx.png'
```

Yesterday it was working fine, so it's something new I guess.
Using diffuser pipeline, Analog Madness model , the good VAE (using the new diffusers way of folders), all normal settings, nothing fancy.

### Version Platform Description

Version: da11f32d Sun Jul 16 17:58:57 2023 -0400  

Linux Mint
Nvidia RTX 3060 12gb 
Ryzen 5600x
32gb RAM

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Run with --debug and post log leading to error, not just error itself.

**Comment by drax-xard** [comment]
```
Create and activate python venv
Launching launch.py...
21:11:42-229815 INFO     Starting SD.Next                                                                              
21:11:42-232033 INFO     Python 3.10.6 on Linux                                                                        
21:11:42-234142 INFO     Version: da11f32d Sun Jul 16 17:58:57 2023 -0400                                              
21:11:42-622115 DEBUG    Setting environment tuning                                                                    
21:11:42-622896 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False                                  
21:11:42-623498 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True                                        
21:11:42-624108 INFO     nVidia CUDA toolkit detected                                                                  
21:11:42-635519 WARNING  Modified files: ['models/.placeholder', 'models/VAE-approx/model.pt',                         
                         'models/karlo/ViT-L-14_stats.th', 'models']                                                   
21:11:42-638043 DEBUG    Repository update time: Sun Jul 16 18:58:57 2023                                              
21:11:42-638717 DEBUG    Previous setup time: Sun Jul 16 19:51:12 2023                                                 
21:11:42-639358 INFO     Disabled extensions-builtin: ['sd-webui-agent-scheduler', 'sd-extension-aesthetic-scorer',    
                         'stable-diffusion-webui-images-browser', 'sd-webui-controlnet',                               
                         'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris',                        
                         'sd-dynamic-thresholding', 'sd-extension-system-info', 'asymmetric-tiling-sd-webui']          
21:11:42-640144 INFO     Enabled extensions-builtin: ['LDSR', 'clip-interrogator-ext', 'sd-webui-model-converter',     
                         'ScuNET', 'SwinIR', 'stable-diffusion-webui-rembg', 'sd-extension-steps-animation',           
                         'seed_travel', 'Lora']                                                                        
21:11:42-641011 INFO     Disabled extensions: ['sd-webui-agent-scheduler', 'sd-extension-aesthetic-scorer',            
                         'stable-diffusion-webui-images-browser', 'sd-webui-controlnet',                               
                         'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris',                        
                         'sd-dynamic-thresholding', 'sd-extension-system-info', 'asymmetric-tiling-sd-webui']          
21:11:42-641681 INFO     Enabled extensions: ['sd-webui-text2video']                                                   
21:11:42-642202 DEBUG    Latest extensions time: Sun Jul 16 19:42:59 2023                                              
21:11:42-642693 DEBUG    Timestamps: version:1689544737 setup:1689547872 extension:1689547379                          
21:11:42-643222 INFO     No changes detected: Quick launch active                                                      
21:11:42-643679 INFO     Verifying requirements                                                                        
21:11:42-657421 INFO     Extension preload: 0.0s /home/user/SD/automatic/extensions-builtin                            
21:11:42-658004 INFO     Extension preload: 0.0s /home/user/SD/automatic/extensions                                    
21:11:42-663229 DEBUG    Memory used: 0.04 total: 31.25 Collected 0                                                    
21:11:42-664617 DEBUG    Starting module: <module 'webui' from '/home/user/SD/automatic/webui.py'>                     
21:11:42-665868 INFO     Server arguments: ['--debug']                                                                 
21:11:42-675083 DEBUG    Loading Torch                                                                                 
21:11:44-879020 DEBUG    Loading Gradio                                                                                
21:11:45-342773 DEBUG    Loading Modules                                                                               
No module 'xformers'. Proceeding without it.
21:11:45-906949 INFO     Pipeline: Backend.DIFFUSERS                                                                   
21:11:45-907917 DEBUG    Loaded styles: /home/user/SD/automatic/styles.csv 7                                           
21:11:46-619720 DEBUG    Samplers enumerated: ['Default', 'UniPC', 'DDIM', 'DDPM', 'KDPM2', 'KDPM2 a', 'DEIS', 'DPM    
                         1S', 'DPM 2M', 'Euler', 'Euler a', 'Heun', 'PNDM', 'LMSD']                                    
21:11:46-629553 INFO     Libraries loaded                                                                              
21:11:46-630319 DEBUG    Entering start sequence                                                                       
21:11:46-634864 DEBUG    Version: {'app': 'sd.next', 'updated': '2023-07-16', 'hash': 'da11f32d', 'url':               
                         'https://github.com/vladmandic/automatic.git/tree/master'}                                    
21:11:46-635727 INFO     Using data path: /home/user/SD/automatic                                                      
21:11:46-636360 DEBUG    Event loop: <_UnixSelectorEventLoop running=False closed=False debug=False>                   
21:11:46-637002 DEBUG    Entering initialize                                                                           
21:11:46-637630 INFO     Available VAEs: /home/user/SD/automatic/models/VAE 3                                          
21:11:46-638471 DEBUG    Scanning diffusers cache: /home/user/SD/automatic/models/Diffusers                            
                         /home/user/SD/automatic/models/Diffusers 0                                                    
21:11:46-682000 INFO     Available models: /home/user/SD/automatic/models/Stable-diffusion 5                           
21:11:46-700884 DEBUG    Loading scripts                                                                               
21:11:47-664703 DEBUG    Loading Torch                                                                                 
21:11:47-665552 DEBUG    Loading Gradio                                                                                
21:11:47-666055 DEBUG    Loading Modules                                                                               
21:11:47-666520 INFO     Libraries loaded                                                                              
21:11:47-697355 DEBUG    Scripts load: ['clip-interrogator-ext:0.253s', 'Lora:0.127s',                                 
                         'stable-diffusion-webui-rembg:0.459s', 'sd-webui-text2video:0.059s']                          
21:11:47-820419 INFO     Loading UI theme: name=gradio/default style=Dark                                              
21:11:47-822225 DEBUG    Creating UI                                                                                   
21:11:47-830236 DEBUG    Extra networks: checkpoints items=5 subdirs=5                                                 
21:11:47-915631 DEBUG    Extra networks: lora items=169 subdirs=7                                                      
21:11:47-916950 INFO     Extra network created thumbnails: lora 0                                                      
21:11:47-921200 DEBUG    Extra networks: textual inversion items=54 subdirs=5                                          
21:11:47-944305 INFO     Extra network created thumbnails: textual inversion 0                                         
21:11:48-253402 DEBUG    Script: 0.13s ui_tabs                                                                         
                         /home/user/SD/automatic/extensions/sd-webui-text2video/scripts/text2vid.py                    
21:11:48-255623 DEBUG    Extensions list loaded: /home/user/SD/automatic/html/extensions.json                          
Running on local URL:  http://127.0.0.1:7860
21:11:48-478390 INFO     Local URL: http://127.0.0.1:7860/                                                             
21:11:48-479600 DEBUG    Gradio registered functions: 809                                                              
21:11:48-480743 INFO     Initializing middleware                                                                       
21:11:48-485024 DEBUG    Creating API                                                                                  
21:11:48-568302 DEBUG    Scripts setup: ['Alternative:0.007s']                                                         
21:11:48-568873 DEBUG    Scripts components: []                                                                        
21:11:48-569365 DEBUG    Model metadata: /home/user/SD/automatic/metadata.json no changes                              
21:11:48-570475 DEBUG    Diffusers load config: {'low_cpu_mem_usage': True, 'torch_dtype': torch.float16,              
                         'safety_checker': None, 'requires_safety_checker': False, 'load_safety_checker': False,       
                         'variant': 'fp16'}                                                                            
21:11:48-571507 DEBUG    Verifying Torch settings                                                                      
21:11:48-573137 DEBUG    Torch FP16 test passed                                                                        
21:11:48-573823 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False            
21:11:48-574647 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16            
21:11:48-575537 DEBUG    Torch default device: cuda                                                                    
21:11:48-576254 DEBUG    Select checkpoint: model AnalogMadness/analogMadness_v50.safetensors [f968fc436a]             
21:11:48-577124 INFO     Loading diffuser model:                                                                       
                         /home/user/SD/automatic/models/Stable-diffusion/AnalogMadness/analogMadness_v50.safetensors   
HERE1 /home/user/SD/automatic/models/Stable-diffusion/AnalogMadness/analogMadness_v50.safetensors SD1.5EMA
21:11:48-577991 INFO     Loading diffusers VAE: specified in settings: /home/user/SD/automatic/models/VAE/SD1.5EMA     
21:11:48-578800 DEBUG    Diffusers VAE load config: {'low_cpu_mem_usage': False, 'torch_dtype': torch.float16,         
                         'use_safetensors': True, 'variant': 'fp16'}                                                   
21:11:50-624389 DEBUG    Diffusers pipeline: StableDiffusionPipeline                                                   
21:11:50-627710 DEBUG    Diffusers: enable channels last                                                               
21:11:59-629612 INFO     Embeddings: loaded=53 skipped=1                                                               
21:11:59-630509 INFO     Model loaded in 11.1s (load=11.1s)                                                            
21:11:59-831035 DEBUG    gc: collected=6368 device=cuda {'ram': {'used': 4.89, 'total': 31.25}, 'gpu': {'used': 2.59,  
                         'total': 11.76}, 'retries': 0, 'oom': 0}                                                      
21:11:59-832316 INFO     Model load finished: {'ram': {'used': 4.89, 'total': 31.25}, 'gpu': {'used': 2.59, 'total':   
                         11.76}, 'retries': 0, 'oom': 0}                                                               
21:11:59-833704 DEBUG    Diffusers load config: {'low_cpu_mem_usage': True, 'torch_dtype': torch.float16,              
                         'safety_checker': None, 'requires_safety_checker': False, 'load_safety_checker': False,       
                         'variant': 'fp16'}                                                                            
21:11:59-834655 DEBUG    Verifying Torch settings                                                                      
21:11:59-835658 DEBUG    Torch FP16 test passed                                                                        
21:11:59-836453 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False            
21:11:59-837412 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16            
21:11:59-838278 DEBUG    Torch default device: cuda                                                                    
21:12:00-046073 DEBUG    gc: collected=124 device=cuda {'ram': {'used': 4.89, 'total': 31.25}, 'gpu': {'used': 2.59,   
                         'total': 11.76}, 'retries': 0, 'oom': 0}                                                      
21:12:00-047182 INFO     Startup time: 17.4s (torch=2.2s gradio=0.5s libraries=1.3s scripts=1.0s onchange=0.1s         
                         ui-txt2img=0.1s ui-extensions=0.3s launch=0.1s app-started=0.1s checkpoint=11.5s)             
21:12:00-049747 DEBUG    Server alive=True Requests=2 memory used: 4.89 total: 31.25                                   
21:12:15-477389 DEBUG    txt2img:                                                                                      
                         id_task=task(khmgfz021f9r4ty)|prompt=TEST|negative_prompt=|prompt_styles=[]|steps=20|sampler_i
                         ndex=2|latent_index=0|restore_faces=False|tiling=False|n_iter=1|batch_size=2|cfg_scale=7.5|cli
                         p_skip=1|seed=-1.0|subseed=-1.0|subseed_strength=0|seed_resize_from_h=0|seed_resize_from_w=0||
                         height=512|width=512|enable_hr=False|denoising_strength=0.7|hr_scale=2|hr_upscaler=Latent|hr_s
                         econd_pass_steps=20|hr_resize_x=0|hr_resize_y=0|image_cfg_scale=6|diffusers_guidance_rescale=0
                         .7|refiner_denoise_start=0.5|refiner_denoise_end=1|refiner_prompt=|refiner_negative=|override_
                         settings_texts=[]args=(0, False, 'x264', 'blend', 10, 0, 0, False, True, True, True,          
                         'intermediate', 'animation', False, False, 'positive', 'comma', 0, False, False, '', 0, '',   
                         [], 0, '', [], 0, '', [], True, False, False, False, 0, False, False, 4.0, '', 10.0, 'Linear',
                         3, False, 30.0, True, False, False, 0, 0.0, 'Lanczos', 1, True, 0, 0, 0.001, 75, 0.0, False,  
                         True)                                                                                         
21:12:15-536194 INFO     Embeddings: loaded=0 skipped=54                                                               
21:12:15-537355 DEBUG    Script process: ['Steps animation:0.0s']                                                      
21:12:15-538178 DEBUG    Script before-process-batch: ['Steps animation:0.0s']                                         
21:12:15-539011 DEBUG    Script process-batch: ['Steps animation:0.0s']                                                
21:12:15-540680 DEBUG    Sampler: DEIS {'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012,         
                         'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon', 'solver_order': 2,            
                         'thresholding': False, 'sample_max_value': 1.0, 'algorithm_type': 'deis', 'solver_type':      
                         'logrho', 'lower_order_final': True}                                                          
21:12:15-551321 DEBUG    Diffuser pipeline: StableDiffusionPipeline set={'num_inference_steps': 20, 'guidance_scale':  
                         7.5, 'generator': device(type='cuda'), 'output_type': 'np', 'cross_attention_kwargs': {},     
                         'eta': 0.0, 'guidance_rescale': 0.7, 'height': 512, 'width': 512}                             
Progress  3.65it/s ██████████████████████████████████████ 100% 20/20 00:05 00:00
21:12:24-111350 DEBUG    Script postprocess-batch: ['Steps animation:0.0s']                                            
21:12:24-116877 DEBUG    Script postprocess-image: ['Steps animation:0.0s']                                            
21:12:24-117840 DEBUG    Saving image: JPEG /home/user/SD/zOutputs/txt2img-images/2023-07-16/00094-1655730366.jpg (512,
                         512)                                                                                          
21:12:24-123712 DEBUG    Script postprocess-image: ['Steps animation:0.0s']                                            
21:12:24-124597 DEBUG    Saving image: JPEG /home/user/SD/zOutputs/txt2img-images/2023-07-16/00095-1655730367.jpg (512,
                         512)                                                                                          
21:12:24-127530 DEBUG    Script postprocess: ['Steps animation:0.0s']                                                  
21:12:24-128362 DEBUG    Processed: 3 Memory: {'ram': {'used': 6.3, 'total': 31.25}, 'gpu': {'used': 3.01, 'total':    
                         11.76}, 'retries': 0, 'oom': 0} txt                                                           
Traceback (most recent call last):
  File "/home/user/SD/automatic/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/SD/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/user/SD/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/user/SD/automatic/venv/lib/python3.10/site-packages/gradio/components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "/home/user/SD/automatic/modules/ui_tempdir.py", line 61, in pil_to_temp_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "/usr/lib/python3.10/tempfile.py", line 698, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/usr/lib/python3.10/tempfile.py", line 695, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.10/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gradio/tmpfb33p2ec.png'

```

**Comment by vladmandic** [comment]
i cannot reproduce either using 1x1, 1x2, 2x1 or 2x2 batches.
i don't know why is gradio looking for a temp png image when they are already saved as jpeg's.

**Comment by drax-xard** [comment]
Bummer. Is there anything I can do on my end to help you pinpoint the issue?

**Comment by drax-xard** [comment]
Ok, deleting config.json and ui-config.json seems to fix it, at least.
I will try changing some of the settings to see if I can spot which one was borking the thing.

**Comment by vladmandic** [comment]
magic of gradio :(
