### ISSUE TITLE
[Issue]: Failed to start with --use-ipex on Clear Linux*

### ISSUE THREAD

**Issue by they-they-they** [vladmandic/automatic#1750]
### Issue Description

Hi, i tried to follow guide and try SD on CL* but unfortunately its failed to run with log below
i think major problem related to that:
`[W Device.cpp:120] Warning: DPCPP Device count is zero! (function initGlobalDevicePoolState)` but i don't know what problem related to, configuration or code

```
./webui.sh --use-ipex
Create and activate python venv
Setting OneAPI environment
 
:: initializing oneAPI environment ...
   webui.sh: BASH_VERSION = 5.2.15(1)-release
   args: Using "$@" for setvars.sh arguments: --use-ipex
:: advisor -- latest
:: ccl -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: intelpython -- latest
:: ipp -- latest
:: ippcp -- latest
:: ipp -- latest
:: mkl -- latest
:: mpi -- latest
:: pytorch -- latest
:: tbb -- latest
:: vpl -- latest
:: vtune -- latest
:: oneAPI environment initialized ::
 
Launching ipexrun launch.py...
/home/user/Projects/stable-diffusion-automatic/venv/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
2023-07-19 09:29:44,445 - intel_extension_for_pytorch.cpu.launch - WARNING - Neither TCMalloc nor JeMalloc is found in $CONDA_PREFIX/lib or $VIRTUAL_ENV/lib or /.local/lib/ or /usr/local/lib/ or /usr/local/lib64/ or /usr/lib or /usr/lib64 or /home/user/.local/lib/ so the LD_PRELOAD environment variable will not be set. This may drop the performance
2023-07-19 09:29:44,445 - intel_extension_for_pytorch.cpu.launch - INFO - OMP_NUM_THREADS=14
2023-07-19 09:29:44,445 - intel_extension_for_pytorch.cpu.launch - INFO - Using Intel OpenMP
2023-07-19 09:29:44,445 - intel_extension_for_pytorch.cpu.launch - INFO - KMP_AFFINITY=granularity=fine,compact,1,0
2023-07-19 09:29:44,445 - intel_extension_for_pytorch.cpu.launch - INFO - KMP_BLOCKTIME=1
2023-07-19 09:29:44,445 - intel_extension_for_pytorch.cpu.launch - INFO - LD_PRELOAD=/opt/intel/oneapi/intelpython/latest/lib/libiomp5.so:/usr/lib64/libstdc++.so.6.0.30.
2023-07-19 09:29:44,445 - intel_extension_for_pytorch.cpu.launch - INFO - numactl -C 0-13 -m 0 /home/user/Projects/stable-diffusion-automatic/venv/bin/python3 -u launch.py --use-ipex

09:29:44-548890 INFO     Starting SD.Next                                                                              
09:29:44-550947 INFO     Python 3.9.16 on Linux                                                                        
09:29:44-555817 INFO     Version: 57dd6652 Mon Jul 17 19:30:53 2023 +0000                                              
09:29:44-843602 INFO     Latest published version: 0a083c24232e7afa97fe568fd271a0c351400b92 2023-07-19T00:43:30Z       
09:29:44-844602 INFO     Intel OneAPI Toolkit detected                                                                 
09:29:44-858679 WARNING  Modified files: ['config.json.backup']                                                        
09:29:44-864042 INFO     Enabled extensions-builtin: ['sd-dynamic-thresholding', 'stable-diffusion-webui-rembg',       
                         'LDSR', 'sd-webui-controlnet', 'ScuNET', 'multidiffusion-upscaler-for-automatic1111',         
                         'SwinIR', 'clip-interrogator-ext', 'sd-extension-system-info', 'Lora',                        
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser', 'a1111-sd-webui-lycoris']
09:29:44-865323 INFO     Enabled extensions: []                                                                        
09:29:44-865872 INFO     No changes detected: Quick launch active                                                      
09:29:44-866300 INFO     Verifying requirements                                                                        
09:29:44-874335 INFO     Extension preload: 0.0s /home/user/Projects/stable-diffusion-automatic/extensions-builtin   
09:29:44-875114 INFO     Extension preload: 0.0s /home/user/Projects/stable-diffusion-automatic/extensions           
09:29:44-880708 INFO     Server arguments: ['--use-ipex']                                                              
/home/user/Projects/stable-diffusion-automatic/venv/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
[W Device.cpp:120] Warning: DPCPP Device count is zero! (function initGlobalDevicePoolState)
╭───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────╮
│ /home/user/Projects/stable-diffusion-automatic/launch.py:191 in <module>                                          │
│                                                                                                                     │
│   190                                                                                                               │
│ ❱ 191     instance = start_server(immediate=True, server=None)                                                      │
│   192     while True:                                                                                               │
│                                                                                                                     │
│ /home/user/Projects/stable-diffusion-automatic/launch.py:136 in start_server                                      │
│                                                                                                                     │
│   135     installer.log.info(f"Server arguments: {sys.argv[1:]}")                                                   │
│ ❱ 136     module_spec.loader.exec_module(server)                                                                    │
│   137     if args.test:                                                                                             │
│ in exec_module:850                                                                                                  │
│ in _call_with_frames_removed:228                                                                                    │
│                                                                                                                     │
│ /home/user/Projects/stable-diffusion-automatic/webui.py:43 in <module>                                            │
│                                                                                                                     │
│    42 import ldm.modules.encoders.modules # pylint: disable=W0611,C0411,E0401                                       │
│ ❱  43 from modules.call_queue import queue_lock, wrap_queued_call, wrap_gradio_gpu_call # pyli                      │
│    44 from modules.paths import create_paths                                                                        │
│                                                                                                                     │
│ /home/user/Projects/stable-diffusion-automatic/modules/call_queue.py:8 in <module>                                │
│                                                                                                                     │
│     7 from rich import print # pylint: disable=redefined-builtin                                                    │
│ ❱   8 from modules import shared, progress, errors                                                                  │
│     9                                                                                                               │
│                                                                                                                     │
│ /home/user/Projects/stable-diffusion-automatic/modules/shared.py:15 in <module>                                   │
│                                                                                                                     │
│    14 from modules.dml import directml_hijack_init, directml_override_opts                                          │
│ ❱  15 import modules.interrogate                                                                                    │
│    16 import modules.memmon                                                                                         │
│                                                                                                                     │
│ /home/user/Projects/stable-diffusion-automatic/modules/interrogate.py:10 in <module>                              │
│                                                                                                                     │
│     9 from torchvision.transforms.functional import InterpolationMode                                               │
│ ❱  10 from modules import devices, paths, shared, lowvram, modelloader, errors                                      │
│    11                                                                                                               │
│                                                                                                                     │
│ /home/user/Projects/stable-diffusion-automatic/modules/devices.py:247 in <module>                                 │
│                                                                                                                     │
│   246     #Diffusers Float64 (ARC GPUs doesn't support double or Float64):                                          │
│ ❱ 247     if not torch.xpu.has_fp64_dtype():                                                                        │
│   248         CondFunc('torch.from_numpy',                                                                          │
│                                                                                                                     │
│ /home/user/Projects/stable-diffusion-automatic/venv/lib/python3.9/site-packages/intel_extension_for_pytorch/xpu/u │
│ tils.py:110 in has_fp64_dtype                                                                                       │
│                                                                                                                     │
│   109     r"""Returns a bool indicating if the current XPU device supports dtype float64"""                         │
│ ❱ 110     return _C._has_fp64_dtype(device)                                                                         │
│   111                                                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: device_id >= 0 && device_id < num_gpus INTERNAL ASSERT FAILED at 
"/build/intel-pytorch-extension/csrc/gpu/runtime/Device.cpp":355, please report a bug to PyTorch. 
Traceback (most recent call last):
  File "/home/user/Projects/stable-diffusion-automatic/venv/bin/ipexrun", line 8, in <module>
    sys.exit(main())
  File "/home/user/Projects/stable-diffusion-automatic/venv/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 880, in main
    launcher.launch(args)
  File "/home/user/Projects/stable-diffusion-automatic/venv/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 542, in launch
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd_s)
subprocess.CalledProcessError: Command 'numactl -C 0-13 -m 0 /home/user/Projects/stable-diffusion-automatic/venv/bin/python3 -u launch.py --use-ipex' returned non-zero exit status 1.

```

### Version Platform Description

OS: Clear Linux 39630
Python version: 3.10.12
GPU: Arc A770 

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by Disty0** [comment]
Can you run `source /opt/intel/oneapi/setvars.sh && sycl-ls`
Intel drivers doesn't detect your GPU.
