### ISSUE TITLE
[Issue]: Deforum extension no longer works due to disabling of control nets. 

### ISSUE THREAD

**Issue by baardev** [vladmandic/automatic#1766]
### Issue Description

```
Deforum extension for auto1111 webui, v2.4b
Git commit: <p>858c4dd6</p><p>Sun Jul02 2023 13:52</p>

*START OF TRACEBACK*
Traceback (most recent call last):
  File "/home/jw/store/src/automatic/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/run_deforum.py", line 78, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root)
  File "/home/jw/store/src/automatic/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/render.py", line 66, in render_animation
    parseq_adapter = ParseqAdapter(parseq_args, anim_args, video_args, controlnet_args)
  File "/home/jw/store/src/automatic/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/parseq_adapter.py", line 28, in __init__
    self.cn_keys = ParseqControlNetKeysDecorator(self, ControlNetKeys(anim_args, controlnet_args)) if controlnet_args else None
  File "/home/jw/store/src/automatic/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/animation_key_frames.py", line 66, in __init__
    self.schedules[key] = self.fi.get_inbetweens(self.fi.parse_key_frames(getattr(controlnet_args, f"{prefix}_{suffix}")))
AttributeError: 'types.SimpleNamespace' object has no attribute 'cn_1_weight'
*END OF TRACEBACK*
```

As the deform extension is not automatically disabled, like sd-webui-controlnet, is it safe to assume this is an issue with a1111? If so, then deforum should be disabled if the CN is disabled.... or is it a problem for the extension to deal with?

### Version Platform Description

Version
app: automatic.git
updated: 2023-07-18
hash: debec28b
url: https://github.com/vladmandic/automatic.git/tree/master

Platform
arch: x86_64
system: Linux
release: 6.1.38-1-MANJARO
python: 3.10.12
Backend: cuda

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
use correct template - this is clearly extension issue!

and if cn is disabled, deforum should still work, i agree. but that is deforum issue, not a core app issue.
