### ISSUE TITLE
[Issue]: clean install not working, source code string cannot contain null bytes

### ISSUE THREAD

**Issue by cchance27** [vladmandic/automatic#1777]
### Issue Description

I seem to be getting an error on install, i've tried resetting, tried reinstalling, no matter what it always errors out the same way...

```
2023-07-20 23:48:14,167 | sd | ERROR | installer | Error running extension installer: D:\sdnext\extensions-builtin\stable-diffusion-webui-images-browser\install.py
2023-07-20 23:48:14,169 | sd | DEBUG | installer | 
Traceback (most recent call last):
  File "D:\sdnext\extensions-builtin\stable-diffusion-webui-images-browser\install.py", line 8, in <module>
    import ImageReward
  File "D:\sdnext\venv\lib\site-packages\ImageReward\__init__.py", line 1, in <module>
    from .utils import *
  File "D:\sdnext\venv\lib\site-packages\ImageReward\utils.py", line 19, in <module>
    from .ImageReward import ImageReward
  File "D:\sdnext\venv\lib\site-packages\ImageReward\ImageReward.py", line 13, in <module>
    import torch
  File "D:\sdnext\venv\lib\site-packages\torch\__init__.py", line 1187, in <module>
    from .functional import *  # noqa: F403
  File "D:\sdnext\venv\lib\site-packages\torch\functional.py", line 7, in <module>
    import torch.backends.opt_einsum as opt_einsum
  File "D:\sdnext\venv\lib\site-packages\torch\backends\opt_einsum\__init__.py", line 9, in <module>
    import opt_einsum as _opt_einsum  # type: ignore[import]
  File "D:\sdnext\venv\lib\site-packages\opt_einsum\__init__.py", line 5, in <module>
    from . import blas
ValueError: source code string cannot contain null bytes
```

```
2023-07-20 23:48:08,585 | sd | ERROR | installer | Error running extension installer: D:\sdnext\extensions-builtin\clip-interrogator-ext\install.py
2023-07-20 23:48:08,589 | sd | DEBUG | installer | 
Traceback (most recent call last):
  File "D:\sdnext\extensions-builtin\clip-interrogator-ext\install.py", line 7, in <module>
    import clip_interrogator
  File "D:\sdnext\venv\lib\site-packages\clip_interrogator\__init__.py", line 1, in <module>
    from .clip_interrogator import Config, Interrogator, LabelTable, list_caption_models, list_clip_models, load_list
  File "D:\sdnext\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 4, in <module>
    import open_clip
  File "D:\sdnext\venv\lib\site-packages\open_clip\__init__.py", line 1, in <module>
    from .coca_model import CoCa
  File "D:\sdnext\venv\lib\site-packages\open_clip\coca_model.py", line 3, in <module>
    import torch
  File "D:\sdnext\venv\lib\site-packages\torch\__init__.py", line 1187, in <module>
    from .functional import *  # noqa: F403
  File "D:\sdnext\venv\lib\site-packages\torch\functional.py", line 7, in <module>
    import torch.backends.opt_einsum as opt_einsum
  File "D:\sdnext\venv\lib\site-packages\torch\backends\opt_einsum\__init__.py", line 9, in <module>
    import opt_einsum as _opt_einsum  # type: ignore[import]
  File "D:\sdnext\venv\lib\site-packages\opt_einsum\__init__.py", line 5, in <module>
    from . import blas
ValueError: source code string cannot contain null bytes
```

### Version Platform Description

23:47:57-080284 INFO     Starting SD.Next
23:47:57-084299 INFO     Python 3.10.11 on Windows
23:47:57-181849 INFO     Version: db1976b3 Thu Jul 20 15:28:09 2023 -0400
23:47:57-448114 INFO     nVidia CUDA toolkit detected
23:47:57-707558 INFO     Disabled extensions: []
23:47:57-709601 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
23:47:57-718584 INFO     Enabled extensions: []
23:47:57-720596 INFO     Verifying requirements
23:47:57-724761 INFO     Verifying packages
23:47:57-740588 INFO     Verifying repositories
23:48:00-286434 INFO     Verifying submodules
23:48:08-585759 ERROR    Error running extension installer: D:\sdnext\extensions-builtin\clip-interrogator-ext\install.py
23:48:14-167265 ERROR    Error running extension installer:
                         D:\sdnext\extensions-builtin\stable-diffusion-webui-images-browser\install.py
23:48:15-475450 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
23:48:15-477869 INFO     Verifying packages
23:48:15-480907 WARNING  Setup complete with errors: 2
23:48:15-481907 WARNING  See log file for more details: D:\sdnext\sdnext.log
23:48:15-493111 INFO     Extension preload: 0.0s D:\sdnext\extensions-builtin
23:48:15-495119 INFO     Extension preload: 0.0s D:\sdnext\extensions
23:48:15-499976 INFO     Server arguments: []

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
that looks like a broken torch installation. did you try removing venv so it forces packages to be reinstalled?

**Comment by vladmandic** [comment]
any updates?

**Comment by vladmandic** [comment]
closing due to inactivity
