### ISSUE TITLE
[Issue]: Read generation data from prompt doesn't work

### ISSUE THREAD

**Issue by Mourdraug** [vladmandic/automatic#185]
### Issue Description

No matter what I enter into prompt (same thing happens if I leave it empty) I get the following exception:
`Traceback (most recent call last):
  File "D:\Stable-diffusion\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Stable-diffusion\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\Stable-diffusion\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 329`

### Version Platform Description

[58df74c](https://github.com/vladmandic/automatic/commit/58df74cfd50b2160fb9a282876663d9547485a30), Windows 11, Firefox

**Comment by vladmandic** [comment]
i just tried, and cannot reproduce. for example 

> Steps: 10, Sampler: UniPC, CFG scale: 5 Seed: 1243419324, Size: 640x640

and click read generation data button populates all fields correctly.

**Comment by SqueakyZee** [comment]
I was able to reproduce the same error type just with different number "KeyError: 373"
added comments to console log to express timings when error happened. 

Running on windows 11 64 Pro,

Basically, the error only occurred after I changed the gradio_theme setting, then applied that settings change via the button in settings and then restarted the UI via the button in settings without restarting the entire script entirely (via webui.bat). 

There is an error in console as soon as you reload UI, but then it gets to the web UI seemingly-normally, with the new theme active. But after, if you try to use the "Image Info" tab, it lets you upload the photo but the original error as Mourdraug posted occurs once you try to send the data to other fields. 

Once you've hit the "=>Text," etc button, the UI locks up. If you manually refresh, the UI is no longer stuck but the error will repeat if you try to use Image Info again.

Restarting the entire Script via console/bash is the only way I can find to prevent the error, and on full restart, the UI theme is properly updated and you can continue use as normally expected.

<details> 
  <summary>Console Error Log (<i>click to expand</i>)</summary>
  
  ```python
Downloading (…)_schema%400.0.1.json: 100%|████████████████████████████████████████████████| 13.2k/13.2k [00:00<?, ?B/s]

#This is when I selected the new theme and hit "Apply Settings"
Loading theme: ysharma/steampunk


#This is after I clicked the "Restart UI" tab
Traceback (most recent call last):
  File "D:\Users\SqueakyZee\Programs\Automatic1111\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Users\SqueakyZee\Programs\Automatic1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\Users\SqueakyZee\Programs\Automatic1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Users\SqueakyZee\Programs\Automatic1111\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Users\SqueakyZee\Programs\Automatic1111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
WebSocket closed
Server shutdown
Server restart
[AddNet] Updating model hashes...
100%|█████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 383.15it/s]
Loading theme: ysharma/steampunk
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Startup time: 6.9s (scripts=1.3s opts onchange=1.4s ui=3.6s start=0.2s scripts app_started_callback=0.5s)

#This is once I click =>text in the "Image Info" tab
Traceback (most recent call last):
  File "D:\Users\SqueakyZee\Programs\Automatic1111\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Users\SqueakyZee\Programs\Automatic1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\Users\SqueakyZee\Programs\Automatic1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 373
```

</details>

**Comment by vladmandic** [comment]
i'm able to reproduce with those steps, but issue only occurs if "restart ui" was used and goes away if you actually restart server from command prompt. valid issue, but i'd consider it minor impact only as it goes away after you actually restart server. and not easy to track down. i'll put it on my backlog for now.

**Comment by vladmandic** [comment]
there are some remaining issues with read generation data under #153, so i'll track the work there and close this issue.
