### ISSUE TITLE
[Issue]: I can't start webui.bat

### ISSUE THREAD

**Issue by CapoFortuna** [vladmandic/automatic#187]
### Issue Description

When i launch webui.bat i get this error

venv "C:\Users\vaffa\Desktop\automatic-master\venv\Scripts\Python.exe"
Python 3.10.6 on Windows
Error running git with args: log -1 --pretty=format:"%at"
Traceback (most recent call last):
  File "C:\Users\vaffa\Desktop\automatic-master\launch.py", line 88, in <module>
    setup.run_setup()
  File "C:\Users\vaffa\Desktop\automatic-master\setup.py", line 434, in run_setup
    if check_timestamp():
  File "C:\Users\vaffa\Desktop\automatic-master\setup.py", line 388, in check_timestamp
    version_time = int(git('log -1 --pretty=format:"%at"'))
ValueError: invalid literal for int() with base 10: '\nfatal: not a git repository (or any of the parent directories): .git\n'

### Version Platform Description
windows 11

_No response_

**Comment by vladmandic** [comment]
It says "not a git repository" - how did you create your copy?

**Comment by CapoFortuna** [comment]
I downloaded main folder again and now everything works, thanks!
