### ISSUE TITLE
[Issue]: No module named 'tqdm.auto' after installing temporalkit

### ISSUE THREAD

**Issue by bialyjerozy** [vladmandic/automatic#1949]
### Issue Description

After installing temporalnet i can't run automatic1111 anymore. At the end i got "ModuleNotFoundError: No module named 'tqdm.auto'"
I've tried reinstalling whole python, installing and updating "pip install tqdm" and stable diffusion, this is the error after i add temporalnet addon on fresh installation and click restart UI. I'm really stuck, i don't know where is the problem located. I'm not a programmer, so i don't know how i can check it deeper... Please help

venv "C:\diffusion\diff clean\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a
Installing requirements for TemporalKit extension

Launching Web UI with arguments: --xformers --autolaunch
Traceback (most recent call last):
  File "C:\diffusion\diff clean\stable-diffusion-webui\launch.py", line 39, in <module>
    main()
  File "C:\diffusion\diff clean\stable-diffusion-webui\launch.py", line 35, in main
    start()
  File "C:\diffusion\diff clean\stable-diffusion-webui\modules\launch_utils.py", line 390, in start
    import webui
  File "C:\diffusion\diff clean\stable-diffusion-webui\webui.py", line 44, in <module>
    import gradio  # noqa: F401
  File "C:\diffusion\diff clean\stable-diffusion-webui\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\diffusion\diff clean\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 34, in <module>
    from gradio_client import media_data
  File "C:\diffusion\diff clean\stable-diffusion-webui\venv\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "C:\diffusion\diff clean\stable-diffusion-webui\venv\lib\site-packages\gradio_client\client.py", line 24, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
  File "C:\diffusion\diff clean\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\__init__.py", line 322, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Users\bialy\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\diffusion\diff clean\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\hf_api.py", line 35, in <module>
    from huggingface_hub.utils import (
  File "C:\diffusion\diff clean\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\__init__.py", line 18, in <module>
    from . import tqdm as _tqdm  # _tqdm is the module
  File "C:\diffusion\diff clean\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\tqdm.py", line 63, in <module>
    from tqdm.auto import tqdm as old_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
Press any key to continue . . .

[txt.txt](https://github.com/vladmandic/automatic/files/12267156/txt.txt)

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
try deleting `venv` folder so all requirements get reinstalled.

**Comment by bialyjerozy** [comment]
I did what You said, but didn't helped
[txt.txt](https://github.com/vladmandic/automatic/files/12267403/txt.txt)

**Comment by vladmandic** [comment]
i just made some updates and pushed a new version, best would be if you could do a fresh clone.

**Comment by bialyjerozy** [comment]
I think i messed up a bit, i was trying to make it work on this version, but as i can see Yours is different? What version should i use?
https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by vladmandic** [comment]
Which one you want to use is your choice.
I'm not going to go over differences here, they are noted in readme.
