### ISSUE TITLE
[Issue]: Cannot get SDXL working on AMD RX 6700S (Windows)

### ISSUE THREAD

**Issue by jthompson05** [vladmandic/automatic#2010]
### Issue Description

I've set up SDXL for AMD using this tutorial on reddit: https://www.reddit.com/r/StableDiffusion/comments/15brtlp/guide_to_run_sdxl_with_an_amd_gpu_on_windows_11/

I've set up the base model and refiner, but when I try to generate an image I get an error that says `TypeError: 'NoneType' object is not callable`. Can anyone provide any help to fix it?

### Version Platform Description

Windows 11 22H2
Microsoft Edge 117

### Relevant log output

```shell
Using VENV: C:\AI\automatic\venv
12:52:01-568998 INFO     Starting SD.Next
12:52:01-573128 INFO     Python 3.10.11 on Windows
12:52:01-642313 INFO     Version: fce48be4 Mon Aug 14 07:58:42 2023 +0000
12:52:02-016629 INFO     Using DirectML Backend
12:52:02-219770 INFO     Disabled extensions: []
12:52:02-220810 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
12:52:02-222317 INFO     Enabled extensions: []
12:52:02-222317 INFO     No changes detected: Quick launch active
12:52:02-222317 INFO     Verifying requirements
12:52:02-237952 INFO     Verifying packages
12:52:02-237952 INFO     Disabled extensions: []
12:52:02-237952 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
12:52:02-237952 INFO     Enabled extensions: []
12:52:02-255294 INFO     Extension preload: 0.0s C:\AI\automatic\extensions-builtin
12:52:02-255294 INFO     Extension preload: 0.0s C:\AI\automatic\extensions
12:52:02-287494 INFO     Server arguments: ['--use-directml', '--device-id', '0', '--medvram', '--autolaunch']
No module 'xformers'. Proceeding without it.
12:52:12-103734 INFO     Pipeline: Backend.DIFFUSERS
12:52:13-251376 INFO     Libraries loaded
12:52:13-251376 INFO     Using data path: C:\AI\automatic
12:52:13-251376 WARNING  Diffusers disabling uncompatible extension: sd-webui-controlnet
12:52:13-251376 WARNING  Diffusers disabling uncompatible extension: sd-dynamic-thresholding
12:52:13-251376 WARNING  Diffusers disabling uncompatible extension: multidiffusion-upscaler-for-automatic1111
12:52:13-251376 WARNING  Diffusers disabling uncompatible extension: a1111-sd-webui-lycoris
12:52:13-251376 INFO     Available VAEs: C:\AI\automatic\models\VAE 0
12:52:13-268922 INFO     Available models: C:\AI\automatic\models\Stable-diffusion 2
12:52:16-870114 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860
12:52:19-588320 INFO     Local URL: http://127.0.0.1:7860/
12:52:19-588320 INFO     Initializing middleware
12:52:19-698162 INFO     [AgentScheduler] Task queue is empty
12:52:19-699354 INFO     [AgentScheduler] Registering APIs
12:52:20-014681 INFO     GPU high memory utilization: 100% {'ram': {'used': 0.82, 'total': 15.23}, 'gpu': {'used': 0.01,
                         'total': 0.01}, 'retries': 'DirectMLDevice', 'oom': 0}
12:52:20-014681 INFO     Practical GPU memory utilization: 0%
12:52:20-342334 INFO     GPU high memory utilization: 100% {'ram': {'used': 0.82, 'total': 15.23}, 'gpu': {'used': 0.01,
                         'total': 0.01}, 'retries': 'DirectMLDevice', 'oom': 0}
12:52:20-342334 INFO     Practical GPU memory utilization: 0%
12:52:20-719666 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
12:52:20-719666 INFO     Loading diffuser model: C:\AI\automatic\models\Stable-diffusion\sd_xl_refiner_1.0.safetensors
12:53:01-390149 INFO     Embeddings: loaded=0 skipped=0
12:53:01-421436 INFO     Model loaded in 41.1s (load=41.1s) native=1024
12:53:02-586485 INFO     Model load finished: {'ram': {'used': 0.99, 'total': 15.23}, 'gpu': {'used': 6.05, 'total':
                         6.59}, 'retries': 'DirectMLDevice', 'oom': 0}
12:53:02-607257 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
12:53:02-607257 INFO     Loading diffuser refiner: C:\AI\automatic\models\Stable-diffusion\sd_xl_refiner_1.0.safetensors
12:53:44-032536 INFO     Embeddings: loaded=0 skipped=0
12:53:44-069533 INFO     Model loaded in 41.5s (load=41.5s) native=1024
12:53:45-057847 INFO     Model load finished: {'ram': {'used': 6.1, 'total': 15.23}, 'gpu': {'used': 6.05, 'total':
                         6.59}, 'retries': 'DirectMLDevice', 'oom': 0}
12:53:45-057847 INFO     Startup time: 102.7s (torch=7.3s gradio=0.8s libraries=2.8s scripts=3.4s onchange=0.2s
                         ui-settings=0.1s ui-extensions=2.3s launch=0.2s app-started=0.2s checkpoint=85.3s)
12:53:45-073742 INFO     Launching browser
Traceback (most recent call last):
  File "C:\AI\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\AI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\automatic\modules\call_queue.py", line 16, in f
    res = func(*args, **kwargs)
  File "C:\AI\automatic\modules\ui.py", line 221, in update_token_counter
    has_bos_token = tokenizer.bos_token_id is not None
AttributeError: 'NoneType' object has no attribute 'bos_token_id'
Traceback (most recent call last):
  File "C:\AI\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\AI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\automatic\modules\call_queue.py", line 16, in f
    res = func(*args, **kwargs)
  File "C:\AI\automatic\modules\ui.py", line 221, in update_token_counter
    has_bos_token = tokenizer.bos_token_id is not None
AttributeError: 'NoneType' object has no attribute 'bos_token_id'
12:54:55-355130 INFO     Pipeline class changed from StableDiffusionXLImg2ImgPipeline to StableDiffusionXLPipeline
12:54:55-468209 ERROR    Exception: 'NoneType' object is not callable
12:54:55-470214 ERROR    Arguments: args=('task(bnekb2f6ebz0t1i)', 'sports car', '', [], 20, 0, 0, True, False, False,
                         1, 1, 6, 6, 0.7, 1, -1.0, -1.0, 0, 0, 0, 512, 512, False, 0.3, 2, 'Latent', 20, 0, 0, 0.8, '',
                         '', [], 0, False, False, 'positive', 'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '',
                         [], True, False, False, False, 0, False) kwargs={}
12:54:55-474084 ERROR    gradio call: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\AI\automatic\modules\call_queue.py:34 in f                                                                        │
│                                                                                                                      │
│    33 │   │   │   try:                                                                                               │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                      │
│ C:\AI\automatic\modules\txt2img.py:65 in txt2img                                                                     │
│                                                                                                                      │
│   64 │   if processed is None:                                                                                       │
│ ❱ 65 │   │   processed = processing.process_images(p)                                                                │
│   66 │   p.close()                                                                                                   │
│                                                                                                                      │
│ C:\AI\automatic\modules\processing.py:564 in process_images                                                          │
│                                                                                                                      │
│    563 │   │   else:                                                                                                 │
│ ❱  564 │   │   │   res = process_images_inner(p)                                                                     │
│    565 │   finally:                                                                                                  │
│                                                                                                                      │
│ C:\AI\automatic\modules\processing.py:708 in process_images_inner                                                    │
│                                                                                                                      │
│    707 │   │   │   │   from modules.processing_diffusers import process_diffusers                                    │
│ ❱  708 │   │   │   │   x_samples_ddim = process_diffusers(p, p.seeds, p.prompts, p.negative_pro                      │
│    709                                                                                                               │
│                                                                                                                      │
│ C:\AI\automatic\modules\processing_diffusers.py:197 in process_diffusers                                             │
│                                                                                                                      │
│   196 │   refiner_enabled = shared.sd_refiner is not None and p.enable_hr                                            │
│ ❱ 197 │   pipe_args = set_pipeline_args(                                                                             │
│   198 │   │   model=shared.sd_model,                                                                                 │
│                                                                                                                      │
│                                               ... 7 frames hidden ...                                                │
│                                                                                                                      │
│ C:\AI\automatic\venv\lib\site-packages\compel\compel.py:216 in build_conditioning_tensor_for_prompt_object           │
│                                                                                                                      │
│   215 │   │   │   else:                                                                                              │
│ ❱ 216 │   │   │   │   return self._get_conditioning_for_flattened_prompt(prompt), {}                                 │
│   217                                                                                                                │
│                                                                                                                      │
│ C:\AI\automatic\venv\lib\site-packages\compel\compel.py:280 in _get_conditioning_for_flattened_prompt                │
│                                                                                                                      │
│   279 │   │   weights = [x.weight for x in prompt.children]                                                          │
│ ❱ 280 │   │   return self.conditioning_provider.get_embeddings_for_weighted_prompt_fragments(                        │
│   281 │   │   │   text_batch=[fragments], fragment_weights_batch=[weights],                                          │
│                                                                                                                      │
│ C:\AI\automatic\venv\lib\site-packages\compel\embeddings_provider.py:117 in                                          │
│ get_embeddings_for_weighted_prompt_fragments                                                                         │
│                                                                                                                      │
│   116 │   │   │   # handle weights >=1                                                                               │
│ ❱ 117 │   │   │   tokens, per_token_weights, mask = self.get_token_ids_and_expand_weights(frag                       │
│   118 │   │   │   base_embedding = self.build_weighted_embedding_tensor(tokens, per_token_weig                       │
│                                                                                                                      │
│ C:\AI\automatic\venv\lib\site-packages\compel\embeddings_provider.py:268 in get_token_ids_and_expand_weights         │
│                                                                                                                      │
│   267 │   │   │   weights = [1.0]                                                                                    │
│ ❱ 268 │   │   per_fragment_token_ids = self.get_token_ids(fragments, include_start_and_end_mar                       │
│   269 │   │   all_token_ids: List[int] = []                                                                          │
│                                                                                                                      │
│ C:\AI\automatic\venv\lib\site-packages\compel\embeddings_provider.py:211 in get_token_ids                            │
│                                                                                                                      │
│   210 │   │   truncation = self.truncate_to_model_max_length if truncation_override is None el                       │
│ ❱ 211 │   │   token_ids_list = self.tokenizer(                                                                       │
│   212 │   │   │   texts,                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not callable
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
check if this helps: #2007

**Comment by jthompson05** [comment]
> check if this helps: #2007

Thanks for the quick response. Unfortunately, I don't have compel installed: 
```
PS C:\AI\automatic> .\venv\Scripts\activate.bat
PS C:\AI\automatic> pip uninstall compel
WARNING: Skipping compel as it is not installed.
PS C:\AI\automatic>
```

**Comment by vladmandic** [comment]
Powershell misbehaves, you do.
Look at your log trace:

C:\AI\automatic\venv\lib\site-packages\compel\embeddings_provider.py:268 in get_token_ids_and_expand_weights │ │

If you can't uninstall it, delete that folder.

**Comment by jthompson05** [comment]
@vladmandic Thanks, I'm making some progress. I don't see that error anymore. But now I am getting OOM errors when I try to generate an image:
```
Using VENV: C:\AI\automatic\venv
13:49:54-416579 INFO     Starting SD.Next
13:49:54-432212 INFO     Python 3.10.11 on Windows
13:49:54-482200 INFO     Version: fce48be4 Mon Aug 14 07:58:42 2023 +0000
13:49:54-860328 INFO     Using DirectML Backend
13:49:55-000122 INFO     Disabled extensions: ['sd-webui-controlnet', 'sd-dynamic-thresholding',
                         'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']
13:49:55-001356 INFO     Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
13:49:55-008448 INFO     Enabled extensions: []
13:49:55-010175 INFO     No changes detected: Quick launch active
13:49:55-010175 INFO     Verifying requirements
13:49:55-024722 INFO     Verifying packages
13:49:55-024722 INFO     Installing package: git+https://github.com/damian0815/compel
13:50:09-195609 INFO     Disabled extensions: ['sd-webui-controlnet', 'sd-dynamic-thresholding',
                         'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']
13:50:09-196115 INFO     Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
13:50:09-196115 INFO     Enabled extensions: []
13:50:09-209645 INFO     Extension preload: 0.0s C:\AI\automatic\extensions-builtin
13:50:09-209645 INFO     Extension preload: 0.0s C:\AI\automatic\extensions
13:50:09-256529 INFO     Server arguments: ['--use-directml', '--device-id', '0', '--medvram', '--autolaunch']
No module 'xformers'. Proceeding without it.
13:50:23-652297 INFO     Pipeline: Backend.DIFFUSERS
13:50:26-448041 INFO     Libraries loaded
13:50:26-450205 INFO     Using data path: C:\AI\automatic
13:50:26-452151 INFO     Available VAEs: C:\AI\automatic\models\VAE 0
13:50:26-513181 INFO     Available models: C:\AI\automatic\models\Stable-diffusion 3
13:50:30-160001 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860
13:50:33-082635 INFO     Local URL: http://127.0.0.1:7860/
13:50:33-082635 INFO     Initializing middleware
13:50:33-192204 INFO     [AgentScheduler] Task queue is empty
13:50:33-192204 INFO     [AgentScheduler] Registering APIs
13:50:34-029720 INFO     GPU high memory utilization: 100% {'ram': {'used': 0.82, 'total': 15.23}, 'gpu': {'used': 0.01,
                         'total': 0.01}, 'retries': 'DirectMLDevice', 'oom': 0}
13:50:34-029720 INFO     Practical GPU memory utilization: 0%
13:50:34-376038 INFO     GPU high memory utilization: 100% {'ram': {'used': 0.82, 'total': 15.23}, 'gpu': {'used': 0.01,
                         'total': 0.01}, 'retries': 'DirectMLDevice', 'oom': 0}
13:50:34-376038 INFO     Practical GPU memory utilization: 0%
13:50:34-705313 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
13:50:34-710640 INFO     Loading diffuser model: C:\AI\automatic\models\Stable-diffusion\dreamshaper_8.safetensors
13:50:39-924951 INFO     Embeddings: loaded=0 skipped=0
13:50:39-926181 INFO     Model loaded in 5.6s (load=5.6s) native=512
13:50:40-265480 INFO     Model load finished: {'ram': {'used': 1.0, 'total': 15.23}, 'gpu': {'used': 2.07, 'total':
                         2.22}, 'retries': 'DirectMLDevice', 'oom': 0}
13:50:40-586905 INFO     Startup time: 31.3s (torch=10.8s gradio=1.3s libraries=5.1s models=0.1s scripts=3.4s
                         onchange=0.2s ui-txt2img=0.1s ui-settings=0.1s ui-extensions=2.5s launch=0.2s app-started=0.2s
                         checkpoint=7.3s)
13:50:40-590905 INFO     Launching browser
13:51:35-021039 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
13:51:35-027893 INFO     Loading diffuser model: C:\AI\automatic\models\Stable-diffusion\sd_xl_base_1.0.safetensors
13:52:32-637771 INFO     Embeddings: loaded=0 skipped=0
13:52:32-672795 INFO     Model loaded in 57.7s (load=57.7s) native=1024
13:52:34-145126 INFO     Model load finished: {'ram': {'used': 0.78, 'total': 15.23}, 'gpu': {'used': 7.07, 'total':
                         7.47}, 'retries': 'DirectMLDevice', 'oom': 0}
13:54:06-980012 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
13:54:06-983508 INFO     Loading diffuser refiner: C:\AI\automatic\models\Stable-diffusion\sd_xl_refiner_1.0.safetensors
13:54:37-394653 INFO     Embeddings: loaded=0 skipped=0
13:54:37-428021 INFO     Model loaded in 30.5s (load=30.5s) native=1024
13:54:38-791461 INFO     Model load finished: {'ram': {'used': 5.99, 'total': 15.23}, 'gpu': {'used': 7.07, 'total':
                         7.47}, 'retries': 'DirectMLDevice', 'oom': 0}
Progress  2.28s/it ███████▊                                 20% 4/20 00:09 00:36
13:56:55-036710 ERROR    Exception: Could not allocate tensor with 41943040 bytes. There is not enough GPU video memory
                         available!
13:56:55-036710 ERROR    Arguments: args=('task(mgfs0xxqaciwa76)', 'blender', '', [], 20, 0, 0, True, False, False, 1,
                         1, 6, 6, 0.7, 1, -1.0, -1.0, 0, 0, 0, 512, 512, False, 0.3, 2, 'Latent', 20, 0, 0, 0.8, '', '',
                         [], 0, False, False, 'positive', 'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '', [],
                         True, False, False, False, 0, False) kwargs={}
13:56:55-036710 ERROR    gradio call: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\AI\automatic\modules\call_queue.py:34 in f                                                                        │
│                                                                                                                      │
│    33 │   │   │   try:                                                                                               │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                      │
│ C:\AI\automatic\modules\txt2img.py:65 in txt2img                                                                     │
│                                                                                                                      │
│   64 │   if processed is None:                                                                                       │
│ ❱ 65 │   │   processed = processing.process_images(p)                                                                │
│   66 │   p.close()                                                                                                   │
│                                                                                                                      │
│ C:\AI\automatic\modules\processing.py:564 in process_images                                                          │
│                                                                                                                      │
│    563 │   │   else:                                                                                                 │
│ ❱  564 │   │   │   res = process_images_inner(p)                                                                     │
│    565 │   finally:                                                                                                  │
│                                                                                                                      │
│ C:\AI\automatic\modules\processing.py:708 in process_images_inner                                                    │
│                                                                                                                      │
│    707 │   │   │   │   from modules.processing_diffusers import process_diffusers                                    │
│ ❱  708 │   │   │   │   x_samples_ddim = process_diffusers(p, p.seeds, p.prompts, p.negative_pro                      │
│    709                                                                                                               │
│                                                                                                                      │
│ C:\AI\automatic\modules\processing_diffusers.py:214 in process_diffusers                                             │
│                                                                                                                      │
│   213 │   p.extra_generation_params["Eta DDIM"] = shared.opts.eta_ddim if shared.opts.eta_ddim                       │
│ ❱ 214 │   output = shared.sd_model(**pipe_args) # pylint: disable=not-callable                                       │
│   215 │   if shared.state.interrupted or shared.state.skipped:                                                       │
│                                                                                                                      │
│                                               ... 8 frames hidden ...                                                │
│                                                                                                                      │
│ C:\AI\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                                 │
│                                                                                                                      │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                       │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                                              │
│   1502 │   │   # Do not call functions when jit is used                                                              │
│                                                                                                                      │
│ C:\AI\automatic\venv\lib\site-packages\diffusers\models\attention.py:155 in forward                                  │
│                                                                                                                      │
│   154 │   │                                                                                                          │
│ ❱ 155 │   │   attn_output = self.attn1(                                                                              │
│   156 │   │   │   norm_hidden_states,                                                                                │
│                                                                                                                      │
│ C:\AI\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                                 │
│                                                                                                                      │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                       │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                                              │
│   1502 │   │   # Do not call functions when jit is used                                                              │
│                                                                                                                      │
│ C:\AI\automatic\venv\lib\site-packages\diffusers\models\attention_processor.py:322 in forward                        │
│                                                                                                                      │
│    321 │   │   # For standard processors that are defined here, `**cross_attention_kwargs` is e                      │
│ ❱  322 │   │   return self.processor(                                                                                │
│    323 │   │   │   self,                                                                                             │
│                                                                                                                      │
│ C:\AI\automatic\venv\lib\site-packages\diffusers\models\attention_processor.py:1117 in __call__                      │
│                                                                                                                      │
│   1116 │   │   # TODO: add support for attn.scale when we move to Torch 2.1                                          │
│ ❱ 1117 │   │   hidden_states = F.scaled_dot_product_attention(                                                       │
│   1118 │   │   │   query, key, value, attn_mask=attention_mask, dropout_p=0.0, is_causal=False                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Could not allocate tensor with 41943040 bytes. There is not enough GPU video memory available!
```

**Comment by vladmandic** [comment]
Best reach to to community on discord for best settings for your particular hardware.
