### ISSUE TITLE
[Issue]: ImportError: cannot import name 'utils' from partially initialized module 'k_diffusion' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Xerdunits** [vladmandic/automatic#2025]
### Issue Description

I haven't used SD.Next for some time, I just updated everything and get the error attached below. I tried to reinstall it, but to no avail. Are there new requirements or additional steps for the current version I missed? 

### Version Platform Description

Starting SD.Next                                                                                                                                                                        
Python 3.10.12 on Linux                                                                                                                                                                 
Version: 3d914688 Tue Aug 15 05:50:00 2023 +0200                                                                                                                                        
Setting environment tuning                                                                                                                                                              
Torch overrides: cuda=False rocm=False ipex=False diml=False                                                                                                                            
Torch allowed: cuda=True rocm=True ipex=True diml=True                                                                                                                                  
nVidia CUDA toolkit detected                                                                                                                                                            
Package version not found: torch                                                                                                                                                        
Package version not found: torchvision                                                                                                                                                  
Installing package: torch torchvision --index-url https://download.pytorch.org/whl/cu118                                                                                                
Running pip: install --upgrade torch torchvision --index-url https://download.pytorch.org/whl/cu118                                                                                     
Modified files: ['.eslintignore', '.ipynb_checkpoints/', 'cli/simple-img2txt.py', 'cli/simple-txt2txt.py', 'html/logo.png', 'html/logo.svg', 'javascript/logo.png',                     
                         'modules/dml/optimizer/', 'modules/dml/opts.py', 'scripts/detect_extension.py']                                                                                                         
Repository update time: Tue Aug 15 03:50:00 2023                                                                                                                                        
Previous setup time: Thu Aug 17 19:04:31 2023                                                                                                                                           
Disabled extensions: ['sd-webui-lora-block-weight', 'sd-face-editor', 'stable-diffusion-webui-composable-lora', 'sd-webui-prompt-history']                                              
Enabled extensions-builtin: ['LDSR', 'Lora', 'ScuNET', 'SwinIR', 'a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'multidiffusion-upscaler-for-automatic1111',                        
                         'sd-dynamic-thresholding', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg']      
Enabled extensions: ['Stable-Diffusion-Webui-Civitai-Helper', 'a1111-mini-paint', 'a1111-sd-webui-tagcomplete', 'adetailer', 'canvas-zoom', 'civitai-shortcut',                         
                         'prompt-fusion-extension', 'sd-dynamic-prompts', 'sd-model-downloader', 'sd-model-organizer', 'sd-webui-3d-editor', 'sd-webui-e621-prompt', 'sd-webui-infinite-image-browsing',         
                         'sd-webui-inpaint-anything', 'sd-webui-model-converter', 'sd-webui-neutral-prompt', 'sd-webui-prompt-all-in-one', 'sd-webui-regional-prompter', 'sd-webui-stablesr',                    
                         'sd-webui-supermerger', 'sdweb-merge-board', 'stable-diffusion-webui-sonar', 'ultimate-upscale-for-automatic1111']                                                                      
Latest extensions time: Thu Aug 17 18:43:50 2023                                                                                                                                        
Timestamps: version:1692071400 setup:1692299071 extension:1692297830 

### Relevant log output

```shell
19:05:34-098038 INFO     Starting SD.Next                                                                                                                                                                        
19:05:34-106164 INFO     Python 3.10.12 on Linux                                                                                                                                                                 
19:05:34-113785 INFO     Version: 3d914688 Tue Aug 15 05:50:00 2023 +0200                                                                                                                                        
19:05:34-120194 DEBUG    Setting environment tuning                                                                                                                                                              
19:05:34-122207 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False                                                                                                                            
19:05:34-124378 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True                                                                                                                                  
19:05:34-126363 INFO     nVidia CUDA toolkit detected                                                                                                                                                            
19:05:34-127858 DEBUG    Package version not found: torch                                                                                                                                                        
19:05:34-129320 DEBUG    Package version not found: torchvision                                                                                                                                                  
19:05:34-130780 INFO     Installing package: torch torchvision --index-url https://download.pytorch.org/whl/cu118                                                                                                
19:05:34-132477 DEBUG    Running pip: install --upgrade torch torchvision --index-url https://download.pytorch.org/whl/cu118                                                                                     
19:06:56-048201 WARNING  Modified files: ['.eslintignore', '.ipynb_checkpoints/', 'cli/simple-img2txt.py', 'cli/simple-txt2txt.py', 'html/logo.png', 'html/logo.svg', 'javascript/logo.png',                     
                         'modules/dml/optimizer/', 'modules/dml/opts.py', 'scripts/detect_extension.py']                                                                                                         
19:06:56-059071 DEBUG    Repository update time: Tue Aug 15 03:50:00 2023                                                                                                                                        
19:06:56-060662 DEBUG    Previous setup time: Thu Aug 17 19:04:31 2023                                                                                                                                           
19:06:56-062245 INFO     Disabled extensions: ['sd-webui-lora-block-weight', 'sd-face-editor', 'stable-diffusion-webui-composable-lora', 'sd-webui-prompt-history']                                              
19:06:56-064034 INFO     Enabled extensions-builtin: ['LDSR', 'Lora', 'ScuNET', 'SwinIR', 'a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'multidiffusion-upscaler-for-automatic1111',                        
                         'sd-dynamic-thresholding', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg']      
19:06:56-067888 INFO     Enabled extensions: ['Stable-Diffusion-Webui-Civitai-Helper', 'a1111-mini-paint', 'a1111-sd-webui-tagcomplete', 'adetailer', 'canvas-zoom', 'civitai-shortcut',                         
                         'prompt-fusion-extension', 'sd-dynamic-prompts', 'sd-model-downloader', 'sd-model-organizer', 'sd-webui-3d-editor', 'sd-webui-e621-prompt', 'sd-webui-infinite-image-browsing',         
                         'sd-webui-inpaint-anything', 'sd-webui-model-converter', 'sd-webui-neutral-prompt', 'sd-webui-prompt-all-in-one', 'sd-webui-regional-prompter', 'sd-webui-stablesr',                    
                         'sd-webui-supermerger', 'sdweb-merge-board', 'stable-diffusion-webui-sonar', 'ultimate-upscale-for-automatic1111']                                                                      
19:06:56-073970 DEBUG    Latest extensions time: Thu Aug 17 18:43:50 2023                                                                                                                                        
19:06:56-076037 DEBUG    Timestamps: version:1692071400 setup:1692299071 extension:1692297830                                                                                                                    
19:06:56-079451 INFO     No changes detected: Quick launch active                                                                                                                                                
19:06:56-082327 INFO     Verifying requirements                                                                                                                                                                  
19:06:56-084327 DEBUG    Package version not found: addict                                                                                                                                                       
19:06:56-085703 INFO     Installing package: addict                                                                                                                                                              
19:06:56-087091 DEBUG    Running pip: install --upgrade addict                                                                                                                                                   
19:06:57-143748 DEBUG    Package version not found: aenum                                                                                                                                                        
19:06:57-146779 INFO     Installing package: aenum                                                                                                                                                               
19:06:57-149492 DEBUG    Running pip: install --upgrade aenum                                                                                                                                                    
19:06:58-268414 DEBUG    Package version not found: aiohttp                                                                                                                                                      
19:06:58-271521 INFO     Installing package: aiohttp                                                                                                                                                             
19:06:58-274193 DEBUG    Running pip: install --upgrade aiohttp                                                                                                                                                  
19:07:03-543519 DEBUG    Package version not found: anyio                                                                                                                                                        
19:07:03-545650 INFO     Installing package: anyio                                                                                                                                                               
19:07:03-547390 DEBUG    Running pip: install --upgrade anyio                                                                                                                                                    
19:07:04-998864 DEBUG    Package version not found: appdirs                                                                                                                                                      
19:07:05-001969 INFO     Installing package: appdirs                                                                                                                                                             
19:07:05-004661 DEBUG    Running pip: install --upgrade appdirs                                                                                                                                                  
19:07:06-061010 DEBUG    Package version not found: astunparse                                                                                                                                                   
19:07:06-064141 INFO     Installing package: astunparse                                                                                                                                                          
19:07:06-066814 DEBUG    Running pip: install --upgrade astunparse                                                                                                                                               
19:07:07-379093 DEBUG    Package version not found: blendmodes                                                                                                                                                   
19:07:07-382174 INFO     Installing package: blendmodes                                                                                                                                                          
19:07:07-384895 DEBUG    Running pip: install --upgrade blendmodes                                                                                                                                               
19:07:08-663278 DEBUG    Package version not found: clean-fid                                                                                                                                                    
19:07:08-666349 INFO     Installing package: clean-fid                                                                                                                                                           
19:07:08-669052 DEBUG    Running pip: install --upgrade clean-fid                                                                                                                                                
19:07:13-750712 DEBUG    Package version not found: easydev                                                                                                                                                      
19:07:13-753842 INFO     Installing package: easydev                                                                                                                                                             
19:07:13-756537 DEBUG    Running pip: install --upgrade easydev                                                                                                                                                  
19:07:16-432722 DEBUG    Package version not found: extcolors                                                                                                                                                    
19:07:16-435905 INFO     Installing package: extcolors                                                                                                                                                           
19:07:16-438615 DEBUG    Running pip: install --upgrade extcolors                                                                                                                                                
19:07:17-829897 DEBUG    Package version not found: facexlib                                                                                                                                                     
19:07:17-833013 INFO     Installing package: facexlib                                                                                                                                                            
19:07:17-835708 DEBUG    Running pip: install --upgrade facexlib                                                                                                                                                 
19:07:28-534280 DEBUG    Package version not found: filetype                                                                                                                                                     
19:07:28-537398 INFO     Installing package: filetype                                                                                                                                                            
19:07:28-540109 DEBUG    Running pip: install --upgrade filetype                                                                                                                                                 
19:07:29-828529 DEBUG    Package version not found: future                                                                                                                                                       
19:07:29-831653 INFO     Installing package: future                                                                                                                                                              
19:07:29-834324 DEBUG    Running pip: install --upgrade future                                                                                                                                                   
19:07:31-346068 DEBUG    Package version not found: gdown                                                                                                                                                        
19:07:31-349176 INFO     Installing package: gdown                                                                                                                                                               
19:07:31-351857 DEBUG    Running pip: install --upgrade gdown                                                                                                                                                    
19:07:32-983575 DEBUG    Package version not found: gfpgan                                                                                                                                                       
19:07:32-986640 INFO     Installing package: gfpgan                                                                                                                                                              
19:07:32-989346 DEBUG    Running pip: install --upgrade gfpgan                                                                                                                                                   
19:07:43-800375 DEBUG    Package version not found: GitPython                                                                                                                                                    
19:07:43-803543 INFO     Installing package: GitPython                                                                                                                                                           
19:07:43-806214 DEBUG    Running pip: install --upgrade GitPython                                                                                                                                                
19:07:45-681910 DEBUG    Package version not found: httpcore                                                                                                                                                     
19:07:45-685029 INFO     Installing package: httpcore                                                                                                                                                            
19:07:45-687729 DEBUG    Running pip: install --upgrade httpcore                                                                                                                                                 
19:07:47-404805 DEBUG    Package version not found: inflection                                                                                                                                                   
19:07:47-407978 INFO     Installing package: inflection                                                                                                                                                          
19:07:47-410662 DEBUG    Running pip: install --upgrade inflection                                                                                                                                               
19:07:48-993927 DEBUG    Package version not found: jsonmerge                                                                                                                                                    
19:07:48-997064 INFO     Installing package: jsonmerge                                                                                                                                                           
19:07:48-999791 DEBUG    Running pip: install --upgrade jsonmerge                                                                                                                                                
19:07:51-325497 DEBUG    Package version not found: kornia                                                                                                                                                       
19:07:51-328613 INFO     Installing package: kornia                                                                                                                                                              
19:07:51-331290 DEBUG    Running pip: install --upgrade kornia                                                                                                                                                   
19:07:53-511443 DEBUG    Package version not found: lark                                                                                                                                                         
19:07:53-514487 INFO     Installing package: lark                                                                                                                                                                
19:07:53-517157 DEBUG    Running pip: install --upgrade lark                                                                                                                                                     
19:07:55-246829 DEBUG    Package version not found: lmdb                                                                                                                                                         
19:07:55-249956 INFO     Installing package: lmdb                                                                                                                                                                
19:07:55-252672 DEBUG    Running pip: install --upgrade lmdb                                                                                                                                                     
19:07:56-933066 DEBUG    Package version not found: lpips                                                                                                                                                        
19:07:56-936121 INFO     Installing package: lpips                                                                                                                                                               
19:07:56-938756 DEBUG    Running pip: install --upgrade lpips                                                                                                                                                    
19:07:58-611455 DEBUG    Package version not found: omegaconf                                                                                                                                                    
19:07:58-614530 INFO     Installing package: omegaconf                                                                                                                                                           
19:07:58-617273 DEBUG    Running pip: install --upgrade omegaconf                                                                                                                                                
19:08:00-528206 DEBUG    Package version not found: open-clip-torch                                                                                                                                              
19:08:00-531409 INFO     Installing package: open-clip-torch                                                                                                                                                     
19:08:00-534119 DEBUG    Running pip: install --upgrade open-clip-torch                                                                                                                                          
19:08:06-357564 DEBUG    Package version not found: opencv-contrib-python-headless                                                                                                                               
19:08:06-360844 INFO     Installing package: opencv-contrib-python-headless                                                                                                                                      
19:08:06-363725 DEBUG    Running pip: install --upgrade opencv-contrib-python-headless                                                                                                                           
19:08:09-662957 DEBUG    Package version not found: piexif                                                                                                                                                       
19:08:09-666081 INFO     Installing package: piexif                                                                                                                                                              
19:08:09-668765 DEBUG    Running pip: install --upgrade piexif                                                                                                                                                   
19:08:11-557494 DEBUG    Package version not found: psutil                                                                                                                                                       
19:08:11-560615 INFO     Installing package: psutil                                                                                                                                                              
19:08:11-563283 DEBUG    Running pip: install --upgrade psutil                                                                                                                                                   
19:08:13-779365 DEBUG    Package version not found: pyyaml                                                                                                                                                       
19:08:13-782433 INFO     Installing package: pyyaml                                                                                                                                                              
19:08:13-785148 DEBUG    Running pip: install --upgrade pyyaml                                                                                                                                                   
19:08:15-656100 DEBUG    Package version not found: realesrgan                                                                                                                                                   
19:08:15-659234 INFO     Installing package: realesrgan                                                                                                                                                          
19:08:15-661910 DEBUG    Running pip: install --upgrade realesrgan                                                                                                                                               
19:08:17-903182 DEBUG    Package version not found: resize-right                                                                                                                                                 
19:08:17-906292 INFO     Installing package: resize-right                                                                                                                                                        
19:08:17-909007 DEBUG    Running pip: install --upgrade resize-right                                                                                                                                             
19:08:19-868720 DEBUG    Package version not found: rich                                                                                                                                                         
19:08:19-871837 INFO     Installing package: rich                                                                                                                                                                
19:08:19-874470 DEBUG    Running pip: install --upgrade rich                                                                                                                                                     
19:08:21-845404 DEBUG    Package version not found: safetensors                                                                                                                                                  
19:08:21-848573 INFO     Installing package: safetensors                                                                                                                                                         
19:08:21-851329 DEBUG    Running pip: install --upgrade safetensors                                                                                                                                              
19:08:23-813213 DEBUG    Package version not found: scipy                                                                                                                                                        
19:08:23-816328 INFO     Installing package: scipy                                                                                                                                                               
19:08:23-818959 DEBUG    Running pip: install --upgrade scipy                                                                                                                                                    
19:08:25-929798 DEBUG    Package version not found: tb_nightly                                                                                                                                                   
19:08:25-932950 INFO     Installing package: tb_nightly                                                                                                                                                          
19:08:25-935666 DEBUG    Running pip: install --upgrade tb_nightly                                                                                                                                               
19:08:28-760115 DEBUG    Package version not found: toml                                                                                                                                                         
19:08:28-763199 INFO     Installing package: toml                                                                                                                                                                
19:08:28-765825 DEBUG    Running pip: install --upgrade toml                                                                                                                                                     
19:08:30-639897 DEBUG    Package version not found: torchdiffeq                                                                                                                                                  
19:08:30-642987 INFO     Installing package: torchdiffeq                                                                                                                                                         
19:08:30-645720 DEBUG    Running pip: install --upgrade torchdiffeq                                                                                                                                              
19:08:32-576936 DEBUG    Package version not found: voluptuous                                                                                                                                                   
19:08:32-580099 INFO     Installing package: voluptuous                                                                                                                                                          
19:08:32-582763 DEBUG    Running pip: install --upgrade voluptuous                                                                                                                                               
19:08:34-499237 DEBUG    Package version not found: yapf                                                                                                                                                         
19:08:34-502271 INFO     Installing package: yapf                                                                                                                                                                
19:08:34-504924 DEBUG    Running pip: install --upgrade yapf                                                                                                                                                     
19:08:36-410486 DEBUG    Package version not found: scikit-image                                                                                                                                                 
19:08:36-413593 INFO     Installing package: scikit-image                                                                                                                                                        
19:08:36-416275 DEBUG    Running pip: install --upgrade scikit-image                                                                                                                                             
19:08:38-438473 DEBUG    Package version not found: basicsr                                                                                                                                                      
19:08:38-441556 INFO     Installing package: basicsr                                                                                                                                                             
19:08:38-443940 DEBUG    Running pip: install --upgrade basicsr                                                                                                                                                  
19:08:40-523434 DEBUG    Package version not found: fasteners                                                                                                                                                    
19:08:40-526487 INFO     Installing package: fasteners                                                                                                                                                           
19:08:40-529186 DEBUG    Running pip: install --upgrade fasteners                                                                                                                                                
19:08:42-400378 DEBUG    Package version not found: typing-extensions                                                                                                                                            
19:08:42-403546 INFO     Installing package: typing-extensions==4.7.1                                                                                                                                            
19:08:42-406641 DEBUG    Running pip: install --upgrade typing-extensions==4.7.1                                                                                                                                 
19:08:44-505673 DEBUG    Package version not found: antlr4-python3-runtime                                                                                                                                       
19:08:44-508889 INFO     Installing package: antlr4-python3-runtime==4.9.3                                                                                                                                       
19:08:44-512044 DEBUG    Running pip: install --upgrade antlr4-python3-runtime==4.9.3                                                                                                                            
19:08:46-359877 DEBUG    Package version not found: requests                                                                                                                                                     
19:08:46-362947 INFO     Installing package: requests==2.31.0                                                                                                                                                    
19:08:46-365996 DEBUG    Running pip: install --upgrade requests==2.31.0                                                                                                                                         
19:08:48-318394 DEBUG    Package version not found: tqdm                                                                                                                                                         
19:08:48-321460 INFO     Installing package: tqdm==4.65.0                                                                                                                                                        
19:08:48-324478 DEBUG    Running pip: install --upgrade tqdm==4.65.0                                                                                                                                             
19:08:50-375755 DEBUG    Package version not found: accelerate                                                                                                                                                   
19:08:50-378815 INFO     Installing package: accelerate==0.20.3                                                                                                                                                  
19:08:50-381864 DEBUG    Running pip: install --upgrade accelerate==0.20.3                                                                                                                                       
19:08:52-517603 DEBUG    Package version not found: opencv-python-headless                                                                                                                                       
19:08:52-520789 INFO     Installing package: opencv-python-headless==4.7.0.72                                                                                                                                    
19:08:52-523875 DEBUG    Running pip: install --upgrade opencv-python-headless==4.7.0.72                                                                                                                         
19:08:55-767866 DEBUG    Package version not found: diffusers                                                                                                                                                    
19:08:55-770961 INFO     Installing package: diffusers==0.19.3                                                                                                                                                   
19:08:55-773856 DEBUG    Running pip: install --upgrade diffusers==0.19.3                                                                                                                                        
19:08:58-580877 DEBUG    Package version not found: einops                                                                                                                                                       
19:08:58-583967 INFO     Installing package: einops==0.4.1                                                                                                                                                       
19:08:58-587020 DEBUG    Running pip: install --upgrade einops==0.4.1                                                                                                                                            
19:09:00-647520 DEBUG    Package version not found: gradio                                                                                                                                                       
19:09:00-650550 INFO     Installing package: gradio==3.32.0                                                                                                                                                      
19:09:00-653563 DEBUG    Running pip: install --upgrade gradio==3.32.0                                                                                                                                           
19:09:15-662072 DEBUG    Package version not found: huggingface_hub                                                                                                                                              
19:09:15-665203 INFO     Installing package: huggingface_hub==0.16.4                                                                                                                                             
19:09:15-668539 DEBUG    Running pip: install --upgrade huggingface_hub==0.16.4                                                                                                                                  
19:09:17-996333 DEBUG    Package version not found: numexpr                                                                                                                                                      
19:09:17-999434 INFO     Installing package: numexpr==2.8.4                                                                                                                                                      
19:09:18-002423 DEBUG    Running pip: install --upgrade numexpr==2.8.4                                                                                                                                           
19:09:20-451647 DEBUG    Package version not found: numpy                                                                                                                                                        
19:09:20-454502 INFO     Installing package: numpy==1.24.4                                                                                                                                                       
19:09:20-457297 DEBUG    Running pip: install --upgrade numpy==1.24.4                                                                                                                                            
19:09:25-610856 DEBUG    Package version not found: numba                                                                                                                                                        
19:09:25-613908 INFO     Installing package: numba==0.57.1                                                                                                                                                       
19:09:25-616358 DEBUG    Running pip: install --upgrade numba==0.57.1                                                                                                                                            
19:09:28-133962 DEBUG    Package version not found: pandas                                                                                                                                                       
19:09:28-135673 INFO     Installing package: pandas==1.5.3                                                                                                                                                       
19:09:28-137186 DEBUG    Running pip: install --upgrade pandas==1.5.3                                                                                                                                            
19:09:35-536560 DEBUG    Package version not found: protobuf                                                                                                                                                     
19:09:35-539647 INFO     Installing package: protobuf==3.20.3                                                                                                                                                    
19:09:35-542599 DEBUG    Running pip: install --upgrade protobuf==3.20.3                                                                                                                                         
19:09:38-153454 DEBUG    Package version not found: pytorch_lightning                                                                                                                                            
19:09:38-156621 INFO     Installing package: pytorch_lightning==1.9.4                                                                                                                                            
19:09:38-159665 DEBUG    Running pip: install --upgrade pytorch_lightning==1.9.4                                                                                                                                 
19:09:41-944942 DEBUG    Package version not found: transformers                                                                                                                                                 
19:09:41-948062 INFO     Installing package: transformers==4.31.0                                                                                                                                                
19:09:41-951102 DEBUG    Running pip: install --upgrade transformers==4.31.0                                                                                                                                     
19:09:50-308715 DEBUG    Package version not found: tomesd                                                                                                                                                       
19:09:50-311803 INFO     Installing package: tomesd==0.1.3                                                                                                                                                       
19:09:50-314739 DEBUG    Running pip: install --upgrade tomesd==0.1.3                                                                                                                                            
19:09:53-369722 DEBUG    Package version not found: urllib3                                                                                                                                                      
19:09:53-372808 INFO     Installing package: urllib3==1.26.15                                                                                                                                                    
19:09:53-375640 DEBUG    Running pip: install --upgrade urllib3==1.26.15                                                                                                                                         
19:09:56-648938 DEBUG    Package version not found: Pillow                                                                                                                                                       
19:09:56-652041 INFO     Installing package: Pillow==9.5.0                                                                                                                                                       
19:09:56-654965 DEBUG    Running pip: install --upgrade Pillow==9.5.0                                                                                                                                            
19:10:00-560860 DEBUG    Package version not found: timm                                                                                                                                                         
19:10:00-563870 INFO     Installing package: timm==0.6.13                                                                                                                                                        
19:10:00-566411 DEBUG    Running pip: install --upgrade timm==0.6.13                                                                                                                                             
19:10:04-283335 DEBUG    Package version not found: pydantic                                                                                                                                                     
19:10:04-286378 INFO     Installing package: pydantic==1.10.11                                                                                                                                                   
19:10:04-289351 DEBUG    Running pip: install --upgrade pydantic==1.10.11                                                                                                                                        
19:10:07-866063 INFO     Verifying packages                                                                                                                                                                      
19:10:07-869022 DEBUG    Package version not found: clip                                                                                                                                                         
19:10:07-871700 INFO     Installing package: git+https://github.com/openai/CLIP.git                                                                                                                              
19:10:07-873319 DEBUG    Running pip: install --upgrade git+https://github.com/openai/CLIP.git                                                                                                                   
19:10:13-159403 DEBUG    Package version not found: invisible-watermark                                                                                                                                          
19:10:13-160795 INFO     Installing package: git+https://github.com/patrickvonplaten/invisible-watermark.git@remove_onnxruntime_depedency                                                                        
19:10:13-162119 DEBUG    Running pip: install --upgrade git+https://github.com/patrickvonplaten/invisible-watermark.git@remove_onnxruntime_depedency                                                             
19:10:20-515371 DEBUG    Package version not found: onnxruntime                                                                                                                                                  
19:10:20-518455 INFO     Installing package: onnxruntime==1.15.1                                                                                                                                                 
19:10:20-521523 DEBUG    Running pip: install --upgrade onnxruntime==1.15.1                                                                                                                                      
19:10:24-421162 DEBUG    Package version not found: pi_heif                                                                                                                                                      
19:10:24-424253 INFO     Installing package: pi-heif                                                                                                                                                             
19:10:24-426888 DEBUG    Running pip: install --upgrade pi-heif                                                                                                                                                  
19:10:27-678540 DEBUG    Package version not found: compel                                                                                                                                                       
19:10:27-681640 INFO     Installing package: git+https://github.com/damian0815/compel                                                                                                                            
19:10:27-684489 DEBUG    Running pip: install --upgrade git+https://github.com/damian0815/compel                                                                                                                 
19:10:44-439660 DEBUG    Package version not found: tensorflow                                                                                                                                                   
19:10:44-442693 INFO     Installing package: tensorflow==2.13.0                                                                                                                                                  
19:10:44-446028 DEBUG    Running pip: install --upgrade tensorflow==2.13.0                                                                                                                                       
19:11:11-402578 DEBUG    Package version not found: torchsde                                                                                                                                                     
19:11:11-405659 INFO     Installing package: git+https://github.com/google-research/torchsde                                                                                                                     
19:11:11-408540 DEBUG    Running pip: install --upgrade git+https://github.com/google-research/torchsde                                                                                                          
19:11:22-832500 INFO     Disabled extensions: ['sd-webui-lora-block-weight', 'sd-face-editor', 'stable-diffusion-webui-composable-lora', 'sd-webui-prompt-history']                                              
19:11:22-836111 INFO     Enabled extensions-builtin: ['LDSR', 'Lora', 'ScuNET', 'SwinIR', 'a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'multidiffusion-upscaler-for-automatic1111',                        
                         'sd-dynamic-thresholding', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg']      
19:11:22-843027 INFO     Enabled extensions: ['Stable-Diffusion-Webui-Civitai-Helper', 'a1111-mini-paint', 'a1111-sd-webui-tagcomplete', 'adetailer', 'canvas-zoom', 'civitai-shortcut',                         
                         'prompt-fusion-extension', 'sd-dynamic-prompts', 'sd-model-downloader', 'sd-model-organizer', 'sd-webui-3d-editor', 'sd-webui-e621-prompt', 'sd-webui-infinite-image-browsing',         
                         'sd-webui-inpaint-anything', 'sd-webui-model-converter', 'sd-webui-neutral-prompt', 'sd-webui-prompt-all-in-one', 'sd-webui-regional-prompter', 'sd-webui-stablesr',                    
                         'sd-webui-supermerger', 'sdweb-merge-board', 'stable-diffusion-webui-sonar', 'ultimate-upscale-for-automatic1111']                                                                      
19:11:22-851237 INFO     Extension preload: 0.0s /workspace/automatic/extensions-builtin                                                                                                                         
19:11:22-853449 INFO     Extension preload: 0.0s /workspace/automatic/extensions                                                                                                                                 
19:11:22-869286 DEBUG    Memory used: 0.03 total: 125.69 Collected 0                                                                                                                                             
19:11:22-870952 DEBUG    Starting module: <module 'webui' from '/workspace/automatic/webui.py'>                                                                                                                  
19:11:22-872701 INFO     Server arguments: ['-f', '--debug', '--listen', '--insecure']                                                                                                                           
19:11:22-938110 DEBUG    Loading Torch                                                                                                                                                                           
19:11:28-179120 DEBUG    Loading Gradio                                                                                                                                                                          
19:11:29-182273 DEBUG    Loading Modules                                                                                                                                                                         
No module 'xformers'. Proceeding without it.
19:11:30-386378 DEBUG    Reading: /workspace/automatic/config.json len=384                                                                                                                                       
19:11:30-389122 INFO     Pipeline: Backend.ORIGINAL                                                                                                                                                              
19:11:30-390552 DEBUG    Loaded styles: /workspace/automatic/styles.csv 0                                                                                                                                        
Error in sys.excepthook:
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.10/site-packages/rich/traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "/workspace/venv/lib/python3.10/site-packages/rich/traceback.py", line 346, in from_exception
    return cls(
  File "/workspace/venv/lib/python3.10/site-packages/rich/traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "/workspace/automatic/launch.py", line 194, in <module>
    instance = start_server(immediate=True, server=None)
  File "/workspace/automatic/launch.py", line 136, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/automatic/webui.py", line 48, in <module>
    from modules import shared, extensions, extra_networks, ui_tempdir, ui_extra_networks, modelloader
  File "/workspace/automatic/modules/ui_extra_networks.py", line 12, in <module>
    from modules.generation_parameters_copypaste import image_from_url_text
  File "/workspace/automatic/modules/generation_parameters_copypaste.py", line 10, in <module>
    from modules import shared, ui_tempdir, script_callbacks, images
  File "/workspace/automatic/modules/images.py", line 18, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors, paths
  File "/workspace/automatic/modules/sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, sd_samplers_diffusers, shared
  File "/workspace/automatic/modules/sd_samplers_kdiffusion.py", line 4, in <module>
    import k_diffusion.sampling
  File "/workspace/automatic/repositories/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/workspace/automatic/repositories/k-diffusion/k_diffusion/config.py", line 8, in <module>
    from . import augmentation, layers, models, utils
  File "/workspace/automatic/repositories/k-diffusion/k_diffusion/layers.py", line 8, in <module>
    from . import sampling, utils
  File "/workspace/automatic/repositories/k-diffusion/k_diffusion/sampling.py", line 10, in <module>
    from . import utils
ImportError: cannot import name 'utils' from partially initialized module 'k_diffusion' (most likely due to a circular import) (/workspace/automatic/repositories/k-diffusion/k_diffusion/__init__.py)
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
I haven't seen this before. Try deleting repositories folder so it's re-cloned with fresh copy.

**Comment by Xerdunits** [comment]
Thanks, that fixed it 👍
