### ISSUE TITLE
[Issue]:  The system cannot find the path specified: 'stabilityai/stable-diffusion-xl-refiner-1.0'

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#2059]
### Issue Description

After upgrade to Version: 863fa38c  The system cannot find the path to diffusers models.
The path not change and it W:\V\automatic\models\Diffusers
But looks like thar is a mishmash gose there....

Loading diffuser model: stabilityai/stable-diffusion-xl-base-1.0
Loading pipeline components...: 100%|██████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.72it/s]
08:00:30-222969 ERROR    Failed to load diffusers model
08:00:30-224969 ERROR    loading Diffusers model: FileNotFoundError
 Traceback (most recent call last)
W:\V\automatic\modules\sd_models.py:826 in load_diffuser                                                          │
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'stabilityai/stable-diffusion-xl-base-1.0'

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'stabilityai/stable-diffusion-xl-refiner-1.0'
![diffusers](https://github.com/vladmandic/automatic/assets/80190186/bc89c6cc-1b03-4dec-93f3-d910a728baff)

### Version Platform Description

W:\V\automatic>webui.bat --backend diffusers --medvram --experimental --upgrade
Using VENV: W:\V\automatic\venv
07:58:00-087104 INFO     Starting SD.Next
07:58:00-098106 INFO     Python 3.10.7 on Windows
07:58:00-233102 INFO     Version: 863fa38c Wed Aug 23 00:31:43 2023 +0300
07:58:00-869208 INFO     nVidia CUDA toolkit detected

### Relevant log output

```shell
W:\V\automatic>webui.bat --backend diffusers --medvram --experimental --upgrade
Using VENV: W:\V\automatic\venv
07:58:00-087104 INFO     Starting SD.Next
07:58:00-098106 INFO     Python 3.10.7 on Windows
07:58:00-233102 INFO     Version: 863fa38c Wed Aug 23 00:31:43 2023 +0300
07:58:00-869208 INFO     nVidia CUDA toolkit detected
07:58:01-065206 INFO     Verifying requirements
07:58:01-077205 INFO     Verifying packages
07:58:01-080205 INFO     Verifying repositories
07:58:06-569206 INFO     Verifying submodules
07:59:46-696970 ERROR    Error running extension installer: W:\V\automatic\extensions\animator_extension\install.py
07:59:48-524973 ERROR    Error running git: extensions\Mask2Background / pull origin None --rebase --force
07:59:48-526971 ERROR    Local changes detected: check log for details: W:\V\automatic\sdnext.log
08:00:09-088974 INFO     Extensions enabled: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET',
                         'sd-extension-system-info', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR', 'animator_extension',
                         'infinite-zoom-automatic1111-webui', 'Mask2Background', 'sd-face-editor',
                         'sd-webui-aspect-ratio-helper', 'StyleSelectorXL']
08:00:09-093971 INFO     Verifying packages
08:00:09-095974 INFO     Updating Wiki
08:00:10-038971 WARNING  Setup complete with errors: 2
08:00:10-041972 WARNING  See log file for more details: W:\V\automatic\sdnext.log
08:00:10-047971 INFO     Extension preload: 0.0s W:\V\automatic\extensions-builtin
08:00:10-049970 INFO     Extension preload: 0.0s extensions
08:00:10-070972 INFO     Server arguments: ['--backend', 'diffusers', '--medvram', '--experimental', '--upgrade']
No module 'xformers'. Proceeding without it.
08:00:18-004974 WARNING  Unknown settings: ['infzoom_defPrompt']
08:00:18-009974 INFO     Pipeline: Backend.DIFFUSERS
08:00:19-706974 INFO     Libraries loaded
08:00:19-708972 INFO     Using data path:
08:00:19-712974 INFO     Available VAEs: models\VAE items=3
08:00:19-732974 INFO     Available models: models\Stable-diffusion items=14
08:00:22-597971 INFO     Libraries loaded
08:00:23-904971 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860
08:00:27-904970 INFO     Local URL: http://127.0.0.1:7860/
08:00:27-906971 INFO     Initializing middleware
08:00:28-308972 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
08:00:28-312970 INFO     Loading diffuser model: stabilityai/stable-diffusion-xl-base-1.0
Loading pipeline components...: 100%|██████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.72it/s]
08:00:30-222969 ERROR    Failed to load diffusers model
08:00:30-224969 ERROR    loading Diffusers model: FileNotFoundError
┌──────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────┐
│ W:\V\automatic\modules\sd_models.py:826 in load_diffuser                                                          │
│                                                                                                                   │
│    825 │   │   │   return                                                                                         │
│ >  826 │   │   sd_model.sd_model_hash = checkpoint_info.calculate_shorthash() # pylint: disable                   │
│    827 │   │   sd_model.sd_checkpoint_info = checkpoint_info # pylint: disable=attribute-define                   │
│                                                                                                                   │
│ W:\V\automatic\modules\sd_models.py:105 in calculate_shorthash                                                    │
│                                                                                                                   │
│    104 │   def calculate_shorthash(self):                                                                         │
│ >  105 │   │   self.sha256 = hashes.sha256(self.filename, f"checkpoint/{self.name}")                              │
│    106 │   │   if self.sha256 is None:                                                                            │
│                                                                                                                   │
│ W:\V\automatic\modules\hashes.py:47 in sha256                                                                     │
│                                                                                                                   │
│   46 │   hashes = cache("hashes-addnet") if use_addnet_hash else cache("hashes")                                  │
│ > 47 │   sha256_value = sha256_from_cache(filename, title, use_addnet_hash)                                       │
│   48 │   if sha256_value is not None:                                                                             │
│                                                                                                                   │
│ W:\V\automatic\modules\hashes.py:35 in sha256_from_cache                                                          │
│                                                                                                                   │
│   34 │   hashes = cache("hashes-addnet") if use_addnet_hash else cache("hashes")                                  │
│ > 35 │   ondisk_mtime = os.path.getmtime(filename)                                                                │
│   36 │   if title not in hashes:                                                                                  │
│                                                                                                                   │
│ C:\Users\derec\AppData\Local\Programs\Python\Python310\lib\genericpath.py:55 in getmtime                          │
│                                                                                                                   │
│    54 │   """Return the last modification time of a file, reported by os.stat()."""                               │
│ >  55 │   return os.stat(filename).st_mtime                                                                       │
│    56                                                                                                             │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'stabilityai/stable-diffusion-xl-base-1.0'
08:00:30-431973 INFO     Embeddings: loaded=0 skipped=0
08:00:30-434971 INFO     Model loaded in 2.1s (load=2.1s) native=1024
08:00:30-775971 INFO     Model load finished: {'ram': {'used': 1.08, 'total': 31.24}, 'gpu': {'used': 1.39, 'total':
                         24.0}, 'retries': 0, 'oom': 0}
08:00:30-783970 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
08:00:30-788971 INFO     Loading diffuser refiner: stabilityai/stable-diffusion-xl-refiner-1.0
Loading pipeline components...: 100%|██████████████████████████████████████████████████| 5/5 [00:01<00:00,  4.29it/s]
08:00:31-975970 ERROR    Failed to load diffusers model
08:00:31-978972 ERROR    loading Diffusers model: FileNotFoundError
┌──────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────┐
│ W:\V\automatic\modules\sd_models.py:826 in load_diffuser                                                          │
│                                                                                                                   │
│    825 │   │   │   return                                                                                         │
│ >  826 │   │   sd_model.sd_model_hash = checkpoint_info.calculate_shorthash() # pylint: disable                   │
│    827 │   │   sd_model.sd_checkpoint_info = checkpoint_info # pylint: disable=attribute-define                   │
│                                                                                                                   │
│ W:\V\automatic\modules\sd_models.py:105 in calculate_shorthash                                                    │
│                                                                                                                   │
│    104 │   def calculate_shorthash(self):                                                                         │
│ >  105 │   │   self.sha256 = hashes.sha256(self.filename, f"checkpoint/{self.name}")                              │
│    106 │   │   if self.sha256 is None:                                                                            │
│                                                                                                                   │
│ W:\V\automatic\modules\hashes.py:47 in sha256                                                                     │
│                                                                                                                   │
│   46 │   hashes = cache("hashes-addnet") if use_addnet_hash else cache("hashes")                                  │
│ > 47 │   sha256_value = sha256_from_cache(filename, title, use_addnet_hash)                                       │
│   48 │   if sha256_value is not None:                                                                             │
│                                                                                                                   │
│ W:\V\automatic\modules\hashes.py:35 in sha256_from_cache                                                          │
│                                                                                                                   │
│   34 │   hashes = cache("hashes-addnet") if use_addnet_hash else cache("hashes")                                  │
│ > 35 │   ondisk_mtime = os.path.getmtime(filename)                                                                │
│   36 │   if title not in hashes:                                                                                  │
│                                                                                                                   │
│ C:\Users\derec\AppData\Local\Programs\Python\Python310\lib\genericpath.py:55 in getmtime                          │
│                                                                                                                   │
│    54 │   """Return the last modification time of a file, reported by os.stat()."""                               │
│ >  55 │   return os.stat(filename).st_mtime                                                                       │
│    56                                                                                                             │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
FileNotFoundError: [WinError 3] The system cannot find the path specified:
'stabilityai/stable-diffusion-xl-refiner-1.0'
08:00:32-165970 INFO     Embeddings: loaded=0 skipped=0
08:00:32-168971 INFO     Model loaded in 1.4s (load=1.4s) native=1024
08:00:32-518976 INFO     Model load finished: {'ram': {'used': 1.12, 'total': 31.24}, 'gpu': {'used': 1.39, 'total':
                         24.0}, 'retries': 0, 'oom': 0}
08:00:32-526970 INFO     Startup time: 22.4s (torch=5.8s gradio=0.8s libraries=3.0s codeformer=0.1s scripts=3.8s
                         onchange=0.2s ui-txt2img=0.1s ui-img2img=0.1s ui-settings=0.1s ui-extensions=3.5s
                         ui-defaults=0.1s launch=0.2s app-started=0.4s checkpoint=4.2s)
```

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by ShmuelRonen** [comment]
> fixed

Now it's works but with error: ValueError: could not convert string to float: 'task(98j7hpzqpc8d2cm)'



Running on local URL:  http://127.0.0.1:7860
10:46:26-943769 INFO     Local URL: http://127.0.0.1:7860/
10:46:26-945770 INFO     Initializing middleware
10:46:27-344768 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
10:46:27-348768 INFO     Loading diffuser model: stabilityai/stable-diffusion-xl-base-1.0
Loading pipeline components...: 100%|██████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.99it/s]
10:46:29-720769 INFO     Embeddings: loaded=0 skipped=0
10:46:29-723769 INFO     Model loaded in 2.4s (load=2.4s) native=1024
10:46:30-051767 INFO     Model load finished: {'ram': {'used': 1.08, 'total': 31.24}, 'gpu': {'used': 1.39, 'total':
                         24.0}, 'retries': 0, 'oom': 0}
10:46:30-059768 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
10:46:30-062768 INFO     Loading diffuser refiner: stabilityai/stable-diffusion-xl-refiner-1.0
Loading pipeline components...: 100%|██████████████████████████████████████████████████| 5/5 [00:01<00:00,  3.34it/s]
10:46:31-581767 INFO     Embeddings: loaded=0 skipped=0
10:46:31-584767 INFO     Model loaded in 1.5s (load=1.5s) native=1024
10:46:31-931767 INFO     Model load finished: {'ram': {'used': 1.12, 'total': 31.24}, 'gpu': {'used': 1.39, 'total':
                         24.0}, 'retries': 0, 'oom': 0}
10:46:31-940767 INFO     Startup time: 23.5s (torch=5.6s gradio=0.8s libraries=2.4s codeformer=0.1s scripts=4.4s
                         onchange=0.3s ui-txt2img=0.1s ui-img2img=0.1s ui-settings=0.1s ui-extensions=4.3s
                         ui-defaults=0.1s launch=0.2s app-started=0.4s checkpoint=4.6s)
Traceback (most recent call last):
  File "W:\V\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\V\automatic\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "W:\V\automatic\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "W:\V\automatic\venv\lib\site-packages\gradio\components.py", line 742, in preprocess
    return self._round_to_precision(x, self.precision)
  File "W:\V\automatic\venv\lib\site-packages\gradio\components.py", line 704, in _round_to_precision
    return float(num)
ValueError: could not convert string to float: 'task(98j7hpzqpc8d2cm)'
Progress  1.09s/it █████████████████████████████████ 100% 20/20 00:21 00:00 Base

**Comment by vladmandic** [comment]
thats unrelated and looks like a mismatch of info in browser vs server. try closing browser and then restarting sdnext from cli.

**Comment by ShmuelRonen** [comment]
Thanks!!!
