### ISSUE TITLE
[Issue]: Entering text in Prompt fails with backend errors

### ISSUE THREAD

**Issue by gsimard** [vladmandic/automatic#2081]
### Issue Description

Trying to run the SDXL model, simply entering text in the prompt fails with errors, both seen in the GUI and backend.

It seems the tokens cannot be parsed as the tokenizer does not have the expected attributes.

  File "C:\git\sdnext\modules\ui.py", line 219, in update_token_counter
    has_bos_token = tokenizer.bos_token_id is not None
AttributeError: 'NoneType' object has no attribute 'bos_token_id'

![image](https://github.com/vladmandic/automatic/assets/1130218/cf996660-561b-4548-89e9-b38c181cd527)

### Version Platform Description

Windows 10

Running on master branch commit:
Revision: 0f10a9ce636566b86a080ee9dab8e48aa016e8f4
Author: Vladimir Mandic <mandic00@live.com>
Date: 2023-08-26 11:19:35

Browse: Chrome
Version 116.0.5845.111 (Build officiel) (64 bits)

C:\git\sdnext>webui.bat --debug --medvram --safe
Using VENV: C:\git\sdnext\venv
15:50:56-149188 INFO     Starting SD.Next
15:50:56-162544 INFO     Python 3.10.11 on Windows
15:50:56-219023 INFO     Version: 0f10a9ce Sat Aug 26 17:19:35 2023 +0200
15:50:56-548846 INFO     Latest published version: 594f0331fdb158471e75ae175062a04af3f20031 2023-08-26T16:35:50Z
15:50:56-551898 DEBUG    Setting environment tuning
15:50:56-554257 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
15:50:56-556131 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
15:50:56-561028 INFO     nVidia CUDA toolkit detected
15:50:56-785077 DEBUG    Repository update time: Sat Aug 26 11:19:35 2023

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\git\sdnext\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\git\sdnext\venv\lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "C:\git\sdnext\venv\lib\site-packages\gradio\blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\git\sdnext\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\git\sdnext\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\git\sdnext\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\git\sdnext\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\git\sdnext\modules\call_queue.py", line 16, in f
    res = func(*args, **kwargs)
  File "C:\git\sdnext\modules\ui.py", line 219, in update_token_counter
    has_bos_token = tokenizer.bos_token_id is not None
AttributeError: 'NoneType' object has no attribute 'bos_token_id'
```

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
you've loaded refiner model as base model!
