### ISSUE TITLE
[Issue]: Unable to Restart Server

### ISSUE THREAD

**Issue by Gushousekai195** [vladmandic/automatic#2150]
### Issue Description

When I try to restart the server from the settings page, it doesn't work. I get an error message in the cmd and have to exit out from it and start the ui from the cmd again.

### Version Platform Description

Windows 10 v. 20H2

Chrome 116.0.5845.179 (Official Build) (64-bit)

app: automatic.git
updated: 2023-09-07
hash: 21877351
url: https://github.com/vladmandic/automatic.git/tree/master

### Relevant log output

```shell
Server shutdown requested
Traceback (most recent call last):
  File "D:\automatic\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
15:26:52-748959 WARNING  WebSocket closed (ignore asyncio.exceptions.CancelledError)
15:26:54-788806 INFO     Server will restart
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\launch.py:223 in <module>                                                                              │
│                                                                                                                     │
│   222         if not alive:                                                                                         │
│ > 223             if instance.wants_restart:                                                                        │
│   224                 installer.log.info('Server restarting...')                                                    │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: module 'webui' has no attribute 'wants_restart'
Press any key to continue . . .
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by solsol360** [comment]
Tested this with
Python 3.10.9 on Windows
Version: e0d8a924 Thu Sep 7 23:47:24 2023 -0400

and got the same error.

**Comment by vladmandic** [comment]
fixed.
