### ISSUE TITLE
[Issue]: sd-webui-supermerger: AttributeError: 'Namespace' object has no attribute 'opt_channelslast'

### ISSUE THREAD

**Issue by Em1tSan** [vladmandic/automatic#218]
### Issue Description

When trying to merge the models, an error appears at the end of the process:

```
Traceback (most recent call last):
  File "E:\SD\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\SD\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\SD\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\SD\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\SD\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\SD\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\SD\automatic\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 65, in smergegen
    usemodelgen(theta_0,model_a,currentmodel)
  File "E:\SD\automatic\extensions\sd-webui-supermerger\scripts\mergers\model_util.py", line 782, in usemodelgen
    if shared.cmd_opts.opt_channelslast:
AttributeError: 'Namespace' object has no attribute 'opt_channelslast'
```

Enabling or disabling the option "Use channels last as torch memory format" in the settings does not change anything, the error remains.

### Version Platform Description

python: 3.10.10  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.23.0  •  commit: [2b1b75dd](https://github.com/vladmandic/automatic/commit/2b1b75dd12b9bc33eb8ad1f02bb9f026b14032b5)  •  checkpoint: [7ce537a0b7](https://google.com/search?q=7ce537a0b7cca96f6862dda000b0d4054b8b996ae5859ddb2c196211447f99fc)

**Comment by vladmandic** [comment]
Should be a simple fix, ETA tomorrow.

**Comment by vladmandic** [comment]
fixed in dev branch, will publish in ~2h.
