### ISSUE TITLE
[Issue]: webui.bat --debug ....ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by XeonG** [vladmandic/automatic#2285]
### Issue Description

Was going to try this out.. but even with python latest installed I get this 

```
Using VENV: C:\Projects\AI\automatic\venv
Traceback (most recent call last):
  File "C:\Projects\AI\automatic\launch.py", line 8, in <module>
    import installer
  File "C:\Projects\AI\automatic\installer.py", line 12, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Press any key to continue . . .

```

### Version Platform Description

Win10 x64

### Relevant log output

```shell
Using VENV: C:\Projects\AI\automatic\venv
Traceback (most recent call last):
  File "C:\Projects\AI\automatic\launch.py", line 8, in <module>
    import installer
  File "C:\Projects\AI\automatic\installer.py", line 12, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Press any key to continue . . .
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
that seems like an incomplete python installation.
what's the output of:
> python -m pip show pip
> python -m pip show setuptools
