### ISSUE TITLE
[Issue]: Crash on startup using ROCm 5.2

### ISSUE THREAD

**Issue by DaniAndTheWeb** [vladmandic/automatic#2322]
### Issue Description

My GPU requires ROCm 5.2 (torch 1.13.1) to work (Radeon RX 5700XT) and that seems to be causing a crash on startup due to a missing torch._dynamo module. The issue has been introduced with the latest update.

### Version Platform Description

Version: 379fe1f (17-10-2023)
OS: Arch Linux
GPU: Radeon RX 5700XT
Torch: 1.13.1 ROCm 5.2

### Relevant log output

```shell
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/venv/lib/python3.10/site-packages/rich/traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/venv/lib/python3.10/site-packages/rich/traceback.py", line 346, in from_exception
    return cls(
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/venv/lib/python3.10/site-packages/rich/traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/launch.py", line 215, in <module>
    uv, instance = start_server(immediate=True, server=None)
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/launch.py", line 147, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/webui.py", line 22, in <module>
    import modules.sd_samplers
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/modules/sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, sd_samplers_diffusers, shared
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/modules/sd_samplers_kdiffusion.py", line 4, in <module>
    import k_diffusion.sampling
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/repositories/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/repositories/k-diffusion/k_diffusion/config.py", line 8, in <module>
    from . import augmentation, layers, models, utils
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/repositories/k-diffusion/k_diffusion/models/__init__.py", line 3, in <module>
    from .image_transformer_v1 import ImageTransformerDenoiserModelV1
  File "/home/daniandtheweb/Applications/stable-diffusion/automatic/repositories/k-diffusion/k_diffusion/models/image_transformer_v1.py", line 8, in <module>
    import torch._dynamo
ModuleNotFoundError: No module named 'torch._dynamo'
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
lowest supported rocm by torch 2.1 itself is now 5.5.
if you want to use older rocm because your gpu is not supported by newer one, then you need to specify exactly which torch to use with it yourself.
