### ISSUE TITLE
[Issue]: SAVE button throws an error, no saving possible

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#2373]
### Issue Description

Probably related to #2372, but different.

If you click SAVE, the UI gives an error Popup with text "None".
In the log you can see that it cannot read (why read? I want to save!) a file. It wants to read a file that is not there from a folder that is also not there (yet) because it usually creates it when writing a file (I use: Save images to a subdirectory, Directory name pattern [date]). That did work yesterday.

I think that `D:_\\` has a superfluous _ that should not be there. I tried paths like D:\SD\... and D:/SD/... but that doesn't make any difference.

Manually rolling back to images.py from 4 days ago fixes the problem.

### Version Platform Description

b00abc4c
win11 (latest patchlevel)
chrome (latest version)

### Relevant log output

```shell
09:21:30-883145 DEBUG    Filename sanitize: input="D:\SD\images\outputs\2023-10-21\00000-20231021091516-2552042800.webp" parts=('D:\\', 'SD', 'images',
                         'outputs', '2023-10-21', '00000-20231021091516-2552042800')
                         output=D:_\SD\images\outputs\2023-10-21\00000-20231021091516-2552042800.webp
09:21:30-888145 DEBUG    Saving: image="D:_\SD\images\outputs\2023-10-21\00000-20231021091516-2552042800.webp" type=WEBP size=1024x1024
Traceback (most recent call last):
  File "D:\SD\automatic.latest\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\SD\automatic.latest\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\SD\automatic.latest\venv\lib\site-packages\gradio\blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\SD\automatic.latest\venv\lib\site-packages\gradio\blocks.py", line 1332, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "D:\SD\automatic.latest\venv\lib\site-packages\gradio\blocks.py", line 460, in postprocess_update_dict
    prediction_value["value"] = block.postprocess(prediction_value["value"])
  File "D:\SD\automatic.latest\venv\lib\site-packages\gradio\components\file.py", line 241, in postprocess
    return [
  File "D:\SD\automatic.latest\venv\lib\site-packages\gradio\components\file.py", line 244, in <listcomp>
    "name": self.make_temp_copy_if_needed(file),
  File "D:\SD\automatic.latest\venv\lib\site-packages\gradio\components\base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "D:\SD\automatic.latest\venv\lib\site-packages\gradio\components\base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:_\\SD\\images\\outputs\\2023-10-21\\00000-20231021091516-2552042800'
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
its directly related to #2372, so closing as duplicate (yes, symptoms are different, but its part of the same overal issue).
