### ISSUE TITLE
[Extension]: No longer possible to merge LoRa into Checkpoint (SuperMerger ext.)

### ISSUE THREAD

**Issue by antibugsprays** [vladmandic/automatic#2377]
### Issue Description

This was possible in previous versions. Now I get this error: 

```
Plus LoRA start
Loading analogMadness_v40 [0b914c246e]
Loading weights: P:\SD_model_safe\analogMadness_v40.safetensors ------------------------------------ 0.0/2.1 GB -:--:--
Loading weights: models\Lora\newstyle.safetensors --------------------------------------- 0.0/302.2 MB -:--:--
newstyle: Successfully set the ratio [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
newstyle:   0%|                                                                       | 0/264 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "P:\vladnew\automatic\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "P:\vladnew\automatic\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "P:\vladnew\automatic\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "P:\vladnew\automatic\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "P:\vladnew\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "P:\vladnew\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "P:\vladnew\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "P:\vladnew\automatic\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "P:\vladnew\automatic\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 594, in pluslora
    theta_0 = newpluslora(theta_0,filenames,lweis,names, isxl, keychanger)
  File "P:\vladnew\automatic\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 677, in newpluslora
    fullkey = nets.convert_diffusers_name_to_compvis(name,False)
AttributeError: module 'networks' has no attribute 'convert_diffusers_name_to_compvis'
```

HyperTile does not seem to work with LoRa, so I thought merging a LoRa into a checkpoint would enable me to use it, but it is broken now

### Version Platform Description

Win 10, Chrome
Version: app=sd.next updated=2023-10-21 hash=2f1f9974

### URL link of the extension

https://github.com/hako-mikan/sd-webui-supermerger

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed.

**Comment by emersound** [comment]
> fixed.

ok...  cool but how..  having this issue in 2024.

**Comment by emersound** [comment]
File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "G:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 776, in pluslora
    theta_0 = newpluslora(theta_0,filenames,lweis,names, isxl,isv2, keychanger)
  File "G:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 853, in newpluslora
    import scripts.A1111.networks as nets
ModuleNotFoundError: No module named 'scripts.A1111'

Same issue.  not sure what changed.  it just started doing this one day.

**Comment by vladmandic** [comment]
commenting on an issue closed a year ago is never a best approach.
document and create new issue.
