### ISSUE TITLE
[Extension]: Faceswaplab inpainting errors: 'Field' object has no attribute 'before_process'

### ISSUE THREAD

**Issue by bulvinkln** [vladmandic/automatic#2485]
### Issue Description

Hello.

Basic face swap with extension working fine, but while Pre-Inpainting (before swapping) or Post-Inpainting (After swapping) is enabled I have this error:

Failed to apply inpainting to face : 'Field' object has no attribute 'before_process'

Here is my Faceswaplab settings for Pre-Inpainting
<img width="411" alt="image" src="https://github.com/vladmandic/automatic/assets/24629969/465fd1f2-5883-4107-b7e1-11d833e16e45">

### Version Platform Description

Version
app: SD.next
updated: 2023-11-09
hash: baed8728

Platform
arch: AMD64
cpu: AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.12

Torch
2.1.0+cu118 Autocast  half

GPU
device: NVIDIA GeForce RTX 3060 (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8905
driver: 546.01

### Relevant log output

```shell
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:05<00:00,  4.81it/s]
07:46:04-048272 INFO     Processed: images=1 time=5.70 its=4.39 memory={'ram': {'used': 3.71, 'total': 31.92}, 'gpu':
                         {'used': 5.59, 'total': 12.0}, 'retries': 0, 'oom': 0}
07:46:04-052395 INFO     Try to use model : D:\AI\sdnext-portable\models\faceswaplab\inswapper_128.onnx
07:46:04-390985 INFO     will generate 1 images
07:46:04-391994 INFO     Process face 0
07:46:04-393994 INFO     Inpainting face
                         Sampler : Euler a
                         inpainting_denoising_strength : 0.1
                         inpainting_steps : 18

07:46:04-394994 INFO     send faces to image to image
07:46:04-424423 INFO     Denoising prompt : Portrait of a woman
07:46:04-426424 INFO     Denoising strenght : 0.1
07:46:04-427423 ERROR    Failed to apply inpainting to face : 'Field' object has no attribute 'before_process'
Traceback (most recent call last):
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab_inpainting\i2i_pp.py", line 77, in img2img_diffusion
    i2i_processed = processing.process_images(i2i_p)
  File "D:\AI\sdnext-portable\modules\processing.py", line 681, in process_images
    p.scripts.before_process(p)
AttributeError: 'Field' object has no attribute 'before_process'
07:46:04-428423 ERROR    Failed to swap face in postprocess method : 'Field' object has no attribute 'before_process'
Traceback (most recent call last):
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py", line 187, in postprocess
    swapped_images = swapper.process_images_units(
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 823, in process_images_units
    swapped = process_image_unit(model, units[0], image, info, force_blend)
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 730, in process_image_unit
    current_image = img2img_diffusion(
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab_inpainting\i2i_pp.py", line 91, in img2img_diffusion
    raise e
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab_inpainting\i2i_pp.py", line 77, in img2img_diffusion
    i2i_processed = processing.process_images(i2i_p)
  File "D:\AI\sdnext-portable\modules\processing.py", line 681, in process_images
    p.scripts.before_process(p)
AttributeError: 'Field' object has no attribute 'before_process'
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
updated, please test.

**Comment by bulvinkln** [comment]
AttributeError: 'Field' object has no attribute 'alwayson_scripts'
`100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:06<00:00,  4.15it/s]
16:58:17-010152 INFO     Processed: images=1 time=8.50 its=2.94 memory={'ram': {'used': 3.49, 'total': 31.92}, 'gpu':
                         {'used': 4.13, 'total': 12.0}, 'retries': 0, 'oom': 0}
16:58:17-012152 INFO     Try to use model : D:\AI\sdnext-portable\models\faceswaplab\inswapper_128.onnx
16:58:17-322693 INFO     will generate 1 images
16:58:17-323677 INFO     Process face 0
16:58:17-325676 INFO     Inpainting face
                         Sampler : DPM++ 2M
                         inpainting_denoising_strength : 0.1
                         inpainting_steps : 20

16:58:17-327186 INFO     send faces to image to image
16:58:17-369223 INFO     Denoising prompt : Portrait of a woman
16:58:17-370221 INFO     Denoising strenght : 0.1
16:58:17-371222 ERROR    Failed to apply inpainting to face : 'Field' object has no attribute 'alwayson_scripts'
Traceback (most recent call last):
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab_inpainting\i2i_pp.py", line 77, in img2img_diffusion
    i2i_processed = processing.process_images(i2i_p)
  File "D:\AI\sdnext-portable\modules\processing.py", line 738, in process_images
    res = process_images_inner(p)
  File "D:\AI\sdnext-portable\extensions-builtin\sd-webui-controlnet\scripts\batch_hijack.py", line 39, in processing_process_images_hijack
    cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)
  File "D:\AI\sdnext-portable\extensions-builtin\sd-webui-controlnet\scripts\batch_hijack.py", line 184, in get_cn_batches
    units = external_code.get_all_units_in_processing(p)
  File "D:\AI\sdnext-portable\extensions-builtin\sd-webui-controlnet\internal_controlnet\external_code.py", line 203, in get_all_units_in_processing
    return get_all_units(p.scripts, p.script_args)
  File "D:\AI\sdnext-portable\extensions-builtin\sd-webui-controlnet\internal_controlnet\external_code.py", line 212, in get_all_units
    cn_script = find_cn_script(script_runner)
  File "D:\AI\sdnext-portable\extensions-builtin\sd-webui-controlnet\internal_controlnet\external_code.py", line 488, in find_cn_script
    for script in script_runner.alwayson_scripts:
AttributeError: 'Field' object has no attribute 'alwayson_scripts'
16:58:17-373222 ERROR    Failed to swap face in postprocess method : 'Field' object has no attribute 'alwayson_scripts'
Traceback (most recent call last):
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py", line 187, in postprocess
    swapped_images = swapper.process_images_units(
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 823, in process_images_units
    swapped = process_image_unit(model, units[0], image, info, force_blend)
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 730, in process_image_unit
    current_image = img2img_diffusion(
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab_inpainting\i2i_pp.py", line 91, in img2img_diffusion
    raise e
  File "D:\AI\sdnext-portable\extensions\sd-webui-faceswaplab\scripts\faceswaplab_inpainting\i2i_pp.py", line 77, in img2img_diffusion
    i2i_processed = processing.process_images(i2i_p)
  File "D:\AI\sdnext-portable\modules\processing.py", line 738, in process_images
    res = process_images_inner(p)
  File "D:\AI\sdnext-portable\extensions-builtin\sd-webui-controlnet\scripts\batch_hijack.py", line 39, in processing_process_images_hijack
    cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)
  File "D:\AI\sdnext-portable\extensions-builtin\sd-webui-controlnet\scripts\batch_hijack.py", line 184, in get_cn_batches
    units = external_code.get_all_units_in_processing(p)
  File "D:\AI\sdnext-portable\extensions-builtin\sd-webui-controlnet\internal_controlnet\external_code.py", line 203, in get_all_units_in_processing
    return get_all_units(p.scripts, p.script_args)
  File "D:\AI\sdnext-portable\extensions-builtin\sd-webui-controlnet\internal_controlnet\external_code.py", line 212, in get_all_units
    cn_script = find_cn_script(script_runner)
  File "D:\AI\sdnext-portable\extensions-builtin\sd-webui-controlnet\internal_controlnet\external_code.py", line 488, in find_cn_script
    for script in script_runner.alwayson_scripts:
AttributeError: 'Field' object has no attribute 'alwayson_scripts'`

**Comment by vladmandic** [comment]
those two extensions are corrupting `scripts` list. i've made it safe so sdnext itself will not try to execute script if its not valid.
but now the extension itself is trying to execute them and it fails. i really have no idea how/why its corrupting scripts list to start with or why its trying to execute them in such manner, but i cannot spend all the time troubleshooting misbehaved 3rd party extensions.

flagging this as upstream issue.

**Comment by DevilsCrypto** [comment]
Thanks for the fast response @vladmandic , i just pulled latest changes and got the same issue. One solution is of course to checkout a previous version from 7 November.

`git checkout ca7cd437af6fae2a717d83dc51fafb4230fe8a3b`

Then it works again, but if its due to a bad implementation of the 3rd party extensions then we need to wait for them to fix.
