### ISSUE TITLE
Can't run SD after updating Python

### ISSUE THREAD

**Issue by Dartterious** [vladmandic/automatic#2575]
### Issue Description

I've upgraded python from 3.10 to 3.12 and removed the older version. This broke the webui.bat folder and my limited knowledge of code has me stuck. I thought a fresh install of SD might fix the issue but i've receiving the following error 
<img width="728" alt="image" src="https://github.com/vladmandic/automatic/assets/109719059/5d044281-019a-421f-8fdf-a82cb527d953">

Please help. 

### Version Platform Description

Windows 11
Python 3.12

### Relevant log output

```shell
Using python: "C:\Users\adamc\AppData\Local\Programs\Python\Python312\python.exe"
Creating VENV: D:\D Drive SD\automatic\venv
Using VENV: D:\D Drive SD\automatic\venv
Traceback (most recent call last):
  File "D:\D Drive SD\automatic\launch.py", line 10, in <module>
    import installer
  File "D:\D Drive SD\automatic\installer.py", line 12, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Press any key to continue . . .
```

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
Unless it was required, there's no reason to update Python (or pip/git for that matter.)
Uninstall 3.12, and reinstall 3.10.

**Comment by carltg9** [comment]
The current install process will not work with python 3.12 because `setuptools` which provides `pkg_resources` is no longer automatically included in `venv` environments, see https://github.com/python/cpython/issues/95299 and https://docs.python.org/3/whatsnew/3.12.html. I believe you would need to call `pip install setuptools` after the `venv` has been activated in the webui script.

**Comment by brknsoul** [comment]
> call pip install setuptools after the venv has been activated in the webui script.

You can open a cmd prompt in your sd.next folder, then run
`venv\scripts\activate`
and then
`pip install setuptools`

**Comment by songproducer** [comment]
Even after setting to python 3.9.7 I can't run I get:

./webui.sh --debug                           
```

Create and activate python venv
Launching launch.py...
Traceback (most recent call last):
  File "/Users/leotreasure/automatic/launch.py", line 9, in <module>
    import installer
  File "/Users/leotreasure/automatic/installer.py", line 10, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by Grzanka99** [comment]
> There's no reason to update Python (or pip/git for that matter.) Uninstall 3.12, and reinstall 3.10.
> 
> If you really want/need 3.12, delete the venv folder.

Sugestion of uninstalling python3.12 isn't useful... as it's dependency of gnome on fedora for example.

Best way I found

1. Remove venv if exists
2. Install python310 (fedora: dnf install python310)
3. Modify webui.sh PYTHON variable to be python3.10 instead of python3

This way you can use correct version of python and still have newest version if required

**Comment by vladmandic** [comment]
do not modify `webui.sh`!
you can set same env variable before starting it and it will pick it up. but do not change `webui.sh`
and error `ModuleNotFoundError: No module named 'pkg_resources'` basically means python is picking up cached info from venv which is no longer valid. every time you change python version or remove venv, you need to close and reopen shell so its not using cached info.
