### ISSUE TITLE
[Extension]: AnimateDiff runtime error

### ISSUE THREAD

**Issue by Aksolot146** [vladmandic/automatic#2670]
### Issue Description

*What happened?*
Last time Stable Diffusion returns error while trying to make video using AnimateDiff with ControlNet. I never get this error before, but suddenly got it even without updating AnimateDiff (and ControlNet) through Stable Diffusion UI. After updating both extensions this problem disappeared but now it appeared again. My CPU is i5-7400 and GPU - GTX 1050 Ti.

*Error logs*
```
    Traceback (most recent call last):
      File "E:\Program Files\stable-diffusion-portable-main\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\Program Files\stable-diffusion-portable-main\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\modules\img2img.py", line 231, in img2img
        processed = process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args, to_scale=selected_scale_tab == 1, scale_by=scale_by, use_png_info=img2img_batch_use_png_info, png_info_props=img2img_batch_png_info_props, png_info_dir=img2img_batch_png_info_dir)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 290, in hacked_img2img_process_batch_hijack
        return process_images(p)
      File "E:\Program Files\stable-diffusion-portable-main\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 119, in hacked_processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\modules\processing.py", line 868, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\hook.py", line 423, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\modules\processing.py", line 1527, in sample
        samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
      File "E:\Program Files\stable-diffusion-portable-main\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "E:\Program Files\stable-diffusion-portable-main\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "E:\Program Files\stable-diffusion-portable-main\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 269, in mm_cfg_forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "E:\Program Files\stable-diffusion-portable-main\modules\sd_hijack_utils.py", line 26, in __call__
        return self.__sub_func(self.__orig_func, *args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\modules\sd_hijack_unet.py", line 48, in apply_model
        return orig_func(self, x_noisy.to(devices.dtype_unet), t.to(devices.dtype_unet), cond, **kwargs).float()
      File "E:\Program Files\stable-diffusion-portable-main\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\hook.py", line 840, in forward_webui
        raise e
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\hook.py", line 837, in forward_webui
        return forward(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\hook.py", line 565, in forward
        control = param.control_model(x=x_in, hint=hint, timesteps=timesteps, context=context, y=y)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\cldm.py", line 31, in forward
        return self.control_model(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\cldm.py", line 300, in forward
        guided_hint = self.input_hint_block(hint, emb, context)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 102, in forward
        x = layer(x)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions-builtin\Lora\networks.py", line 501, in network_Conv2d_forward
        return originals.Conv2d_forward(self, input)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
        return self._conv_forward(input, self.weight, self.bias)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
        return F.conv2d(input, weight, bias, self.stride,
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper_CUDA___slow_conv2d_forward)
```

*What should have happened?*
It should have rendered a looped 15FPS video using Canny images generated on ControlNet as batch

*How to reproduce this problem*
1) type some prompt in img2img
2) use batch images on Generation folder
3) enable AnimateDiff
4) upload a video with 35 frames / 15FPS
5) save format: GIF, PNG; loop: R-P; no frame interpolation
6) use motion module mm_sd_v15_v2.ckpt
7) enable ControlNet with batch mode
8) use Canny control type and preprocessor

*Command line arguments:*
--opt-sdp-attention --upcast-sampling --no-hashing --always-batch-cond-uncond --lowvram --autolaunch --xformers

### Version Platform Description

*Python version:*
3.10.9

*Stable Diffusion version:*
1.7.0

*ControlNet version:*
1.1.424

*AnimateDiff version:*
1.13.0

*Launched on browser:*
Mozilla Firefox

### URL link of the extension

https://github.com/continue-revolution/sd-webui-animatediff

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by Aksolot146** [comment]
P.S. I reinstalled Stable Diffusion and all extensions (ControlNet and AnimateDiff) and it still doesn't work! 
![help](https://github.com/vladmandic/automatic/assets/71846496/8428651b-f944-4d80-a16e-044f288390d9)

Error logs:
```    Traceback (most recent call last):
      File "E:\Program Files\stable-diffusion-portable-main\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\Program Files\stable-diffusion-portable-main\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\modules\img2img.py", line 231, in img2img
        processed = process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args, to_scale=selected_scale_tab == 1, scale_by=scale_by, use_png_info=img2img_batch_use_png_info, png_info_props=img2img_batch_png_info_props, png_info_dir=img2img_batch_png_info_dir)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 290, in hacked_img2img_process_batch_hijack
        return process_images(p)
      File "E:\Program Files\stable-diffusion-portable-main\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 119, in hacked_processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\modules\processing.py", line 868, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\hook.py", line 435, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\modules\processing.py", line 1527, in sample
        samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
      File "E:\Program Files\stable-diffusion-portable-main\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "E:\Program Files\stable-diffusion-portable-main\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "E:\Program Files\stable-diffusion-portable-main\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 269, in mm_cfg_forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "E:\Program Files\stable-diffusion-portable-main\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\hook.py", line 845, in forward_webui
        raise e
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\hook.py", line 842, in forward_webui
        return forward(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\hook.py", line 570, in forward
        control = param.control_model(x=x_in, hint=hint, timesteps=timesteps, context=context, y=y)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\cldm.py", line 31, in forward
        return self.control_model(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\cldm.py", line 300, in forward
        guided_hint = self.input_hint_block(hint, emb, context)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 102, in forward
        x = layer(x)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "E:\Program Files\stable-diffusion-portable-main\extensions-builtin\Lora\networks.py", line 501, in network_Conv2d_forward
        return originals.Conv2d_forward(self, input)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
        return self._conv_forward(input, self.weight, self.bias)
      File "E:\Program Files\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
        return F.conv2d(input, weight, bias, self.stride,
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper_CUDA___slow_conv2d_forward)```

**Comment by Aksolot146** [comment]
Can reinstalling Windows help me? Update PC specs? Update Python?

**Comment by vladmandic** [comment]
issue is triggered by usage of `--lowvram` - that option moves parts of the model in and out of vram and into ram.
but animatediff + controlnet combination seems not to be aware of that so it runs into issue when one model is in gpu and another in cpu and and torch cannot work in such split-mode.

if you didn't use lowvram, you wouldn't have the issue. but then again, you only have gtx1050, so you'd likely run out of vram if you didn't use lowvram to start with.

i'm affraid there is not much i can do here.
