### ISSUE TITLE
[Issue]: Interrogate batch run fails if single image is not run first

### ISSUE THREAD

**Issue by solsol360** [vladmandic/automatic#2767]
### Issue Description

If you click Interrogate button from Interrogate -> Batch tab, it will give an error AttributeError: 'NoneType' object has no attribute 'config'.

Batch run works ok, if you run Interrogate for a single image first from Interrogate -> Image tab

### Version Platform Description

Python 3.10.11 on Windows
Version: app=sd.next updated=2024-01-13 hash=5fb290f4 url=https://github.com/vladmandic/automatic.git/tree/master
Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows release=Windows-10-10.0.22631-SP0 python=3.10.11

### Relevant log output

```shell
Traceback (most recent call last):
  File "F:\automatic\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "F:\automatic\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "F:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\automatic\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "F:\automatic\modules\ui_interrogate.py", line 126, in batch_process
    shared.log.info(f'Interrogate batch: images={len(files)} mode={mode} config={ci.config}')
AttributeError: 'NoneType' object has no attribute 'config'
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev.
