### ISSUE TITLE
[Issue]: ControlNet 1.1 Nightly not working.

### ISSUE THREAD

**Issue by The-Noble** [vladmandic/automatic#284]
### Issue Description

```
/vlads/automatic/extensions/ControlNet-v1-1-nightly
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
```
There's the error. :)

### Version Platform Description

e6701f5c Wed Apr 19 14:12:19 2023 -0400
Linux
Microsoft Edge.

**Comment by vladmandic** [comment]
this looks like fresh install without full server restart, only quick restart from ui?
