### ISSUE TITLE
Install Issue Win 11 - Titan RTX GPU

### ISSUE THREAD

**Issue by gateway** [vladmandic/automatic#291]
### Issue Description

I set up a new folder ran the git clone and the webui.bat file to run the install, after a while it crapped out on a missing module.. 

```
Creating venv in directory E:\Stable-Diffusion\automatic\venv using python "C:\Users\stiet\AppData\Local\Programs\Python\Python310\python.exe"
venv "E:\Stable-Diffusion\automatic\venv\Scripts\Python.exe"
Python 3.10.8 on Windows
Running setup
Version: e6701f5c Wed Apr 19 14:12:19 2023 -0400
Installing requirements
Installing packages
Installing repositories
Installing submodules
Updating submodules
Extensions enabled: ['LDSR', 'Lora', 'ScuNET', 'SwinIR', 'a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg']
Extensions enabled: []
Setting environment tuning
Server arguments: []
Traceback (most recent call last):
  File "E:\Stable-Diffusion\automatic\launch.py", line 93, in <module>
    import webui
  File "E:\Stable-Diffusion\automatic\webui.py", line 7, in <module>
    from rich import print # pylint: disable=W0622
ModuleNotFoundError: No module named 'rich'
Press any key to continue . . .
```

seems like rich is in the requirements.txt but maybe its called in the wrong order or do you have any thoughts?

### Version Platform Description

Windows 11, Latest Nvidia drivers for Titan RTX.. other things like A1111, etc all work fine..

**Comment by vladmandic** [comment]
what does `pip show rich` says?
did you try to restart it?

**Comment by gateway** [comment]
> 

So I was just giving you what happened on a vanilla first time try to install .. 

When I ran it again it output this data..

```venv "E:\Stable-Diffusion\automatic\venv\Scripts\Python.exe"
09:04:32-327458 INFO     Python 3.10.8 on Windows
09:04:32-531651 INFO     No changes detected: quick launch active
09:04:32-532653 INFO     Setting environment tuning
09:04:58-302846 INFO     Torch 2.0.0+cu118
09:04:58-323869 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
09:04:58-325871 INFO     Torch detected GPU: NVIDIA TITAN RTX VRAM 24576 Arch (7, 5) Cores 72
09:04:58-326872 INFO     Server arguments: []
```

**Comment by gmilandri** [comment]
Can't install as well!

`venv "E:\AI\automatic\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File "E:\AI\automatic\launch.py", line 19, in <module>
    setup.parse_args()
  File "E:\AI\automatic\setup.py", line 446, in parse_args
    from modules.script_loading import preload_extensions
  File "E:\AI\automatic\modules\script_loading.py", line 3, in <module>
    import modules.errors as errors
  File "E:\AI\automatic\modules\errors.py", line 3, in <module>
    from rich import print # pylint: disable=redefined-builtin
ModuleNotFoundError: No module named 'rich'
Press any key to continue . . .`

**Comment by vladmandic** [comment]
Not a fix (I'll look closer for that), but it should work on second start as installer already did it's job by then - can you confirm?

**Comment by kohweiteck** [comment]
> Can't install as well!
> 
> ```
> venv "E:\AI\automatic\venv\Scripts\Python.exe"
> Traceback (most recent call last):
>   File "E:\AI\automatic\launch.py", line 19, in <module>
>     setup.parse_args()
>   File "E:\AI\automatic\setup.py", line 446, in parse_args
>     from modules.script_loading import preload_extensions
>   File "E:\AI\automatic\modules\script_loading.py", line 3, in <module>
>     import modules.errors as errors
>   File "E:\AI\automatic\modules\errors.py", line 3, in <module>
>     from rich import print # pylint: disable=redefined-builtin
> ModuleNotFoundError: No module named 'rich'
> Press any key to continue . . .
> ```

Me too... I am on Windows 11. GPU=RTX3080 16GB VRAM

**Comment by xGeekpower** [comment]
same from fresh download
![2023-04-20 23_07_22-C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/86837667/233545619-308a30c5-b881-4db9-b69f-7567c12ee88b.png)

**Comment by raiden1983** [comment]
> same from fresh download ![2023-04-20 23_07_22-C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/86837667/233545619-308a30c5-b881-4db9-b69f-7567c12ee88b.png) tried to start it again multiple times like advised on comments above and same result.

Same... :(

**Comment by soundtrackgeek** [comment]
Same for me

**Comment by danger-diffusion** [comment]
Same for me on macOS.

**Comment by Cleorious** [comment]
Same error when running webui.bat on an attempt to clean install
tried to pip install rich, then restart my PC but still got the same error no rich module as above.

`PS C:\Users\User> pip show rich
Name: rich
Version: 13.3.4
Summary: Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal
Home-page: https://github.com/Textualize/rich
Author: Will McGugan
Author-email: willmcgugan@gmail.com
License: MIT
Location: c:\users\cleopatracleo\appdata\local\programs\python\python310\lib\site-packages
Requires: markdown-it-py, pygments
Required-by:`

**Comment by claudiodekker** [comment]
Same error here as OP, using cloning https://github.com/vladmandic/automatic/commit/2ddbb6670484ed31120dc7bcdef4c292400e7a27 fresh and running webui.bat:

```
Creating venv in directory C:\Users\claud\Desktop\automatic\venv using python "C:\Users\claud\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
venv "C:\Users\claud\Desktop\automatic\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File "C:\Users\claud\Desktop\automatic\launch.py", line 19, in <module>
    setup.parse_args()
  File "C:\Users\claud\Desktop\automatic\setup.py", line 446, in parse_args
    from modules.script_loading import preload_extensions
  File "C:\Users\claud\Desktop\automatic\modules\script_loading.py", line 3, in <module>
    import modules.errors as errors
  File "C:\Users\claud\Desktop\automatic\modules\errors.py", line 3, in <module>
    from rich import print # pylint: disable=redefined-builtin
ModuleNotFoundError: No module named 'rich'
Press any key to continue . . .

```

- Windows 11 x64
- Python 3.10.11
- Nvidia 3060 TI

**Comment by claudiodekker** [comment]
> what does `pip show rich` says? did you try to restart it?

`WARNING: Package(s) not found: rich`

Seems to be going wrong here:
https://github.com/vladmandic/automatic/blob/2ddbb6670484ed31120dc7bcdef4c292400e7a27/launch.py#L11

**Comment by xGeekpower** [comment]
answer above works I already installed rich but on the root folder and it didnt work but installing on scripts did work
---------------------
![2023-04-21 02_33_47-C__Windows_System32_cmd exe](https://user-images.githubusercontent.com/86837667/233587875-cc219bdf-539a-491c-89fb-dc2b9152855f.png)

**Comment by Cleorious** [comment]
> I cd'ed into the venv/Scripts directory and did a `pip install rich` there. After that, it seems to work (it's currently installing pytorch).

> ## answer above works I already installed rich but on the root folder and it didnt work but installing on scripts did work
> ![2023-04-21 02_33_47-C__Windows_System32_cmd exe](https://user-images.githubusercontent.com/86837667/233587875-cc219bdf-539a-491c-89fb-dc2b9152855f.png)

didn't seem to work on mine, did you previously have rich installed in root? and did you uninstall it first?

**Comment by xGeekpower** [comment]
> didn't seem to work on mine, did you previously have rich installed in root? and did you uninstall it first?

yeah I installed on root first, but I didnt uninstall it I just went and install it again but on scripts folder using CMD

**Comment by jrameken** [comment]
> My uneducated suggestion would be to add an `ensure_base_requirements` step is ran prior to running `parse_args`, and to make sure `rich` is installed there.

Your fix worked on my install, I copied both launch.py and setup.py rom your files and all good. Thanks!

**Comment by raiden1983** [comment]
Now i have this 
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/9402994/233668413-77d76021-1f3f-41db-bb33-1efecd44d6fe.png">

**Comment by Jatilq** [comment]
Moved both apps to another drive did a new pull, install of AutoExpress. Maybe a permissions thing on the ssd it was on. was able to install adetailer no problem.  Now getting this error.

C:\Apps\AutoExpress>flask --app autoexpress run
 * Serving Flask app 'autoexpress'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [20/May/2024 14:55:55] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/stylesheet/sidebar.css HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/js/main.js HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/stylesheet/main.css HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/js/connect.js HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/js/image_drag_and_drop.js HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/js/generate.js HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/js/image_viewer.js HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/stylesheet/toggle.css HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/js/anime_toggle.js HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/stylesheet/image_viewer.css HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/ico/favicon-rounded.png HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/stylesheet/image_and_prompt.css HTTP/1.1" 304 -
127.0.0.1 - - [20/May/2024 14:55:55] "GET /static/ico/favicon-rounded.png HTTP/1.1" 304 -
[autoexpress.modules.logger] [INFO]  SD URL set to: http://127.0.0.1:7860
127.0.0.1 - - [20/May/2024 14:56:12] "POST /receive_data HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2024 14:56:12] "GET /get-loras HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2024 14:56:12] "GET /get-models HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2024 14:56:12] "GET /get-samplers HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2024 14:56:36] "POST /upload HTTP/1.1" 200 -
[autoexpress.modules.logger] [INFO]  Found adetailer extension.
[autoexpress.modules.logger] [INFO]  adetailer extension is enabled.
[autoexpress.modules.logger] [INFO]  Using the following generation parameters:
{'ad_inpaint_width': '832', 'ad_inpaint_height': '1216', 'seed': '1212253171', 'ad_prompt': 'catscore_9, score_8_up, score_7_up,   1 girl, gwen stacy (spider gwen), bed background, shiny skin, sweaty, blush, beautiful face, virgin destroyer sweater, detached sleeves, panties, thighhighs, flowers, solo, delicate and smooth skin, blush, perfect body, highly detailed, glossy lips, posing, solo    <lora:Concept Art Twilight Style SDXL_LoRA_Pony Diffusion V6 XL:0.8> concept art, realistic,  <lora:Expressive_H-000001:0.8>, expressiveH  <lora:sinfully_stylish_SDXL>  <lora:Pony_DetailV1.0> <lora:virgin_destroyer_sweater_v0.1-pony:0.8>', 'ad_negative_prompt': 'score_6, score_5, score_4, 3d', 'ad_steps': '32', 'ad_checkpoint': 'realcartoon3d_v15', 'ad_sampler': 'DPM++ 2M', 'ad_clip_skip': '2', 'ad_cfg_scale': '7', 'ad_denoising_strength': '0.5'}
[2024-05-20 14:56:43,218] ERROR in app: Exception on /generate [POST]
Traceback (most recent call last):
  File "C:\Users\Jatilq\miniconda3\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jatilq\miniconda3\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jatilq\miniconda3\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jatilq\miniconda3\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Apps\AutoExpress\autoexpress\views.py", line 197, in generate
    generate.generate_expressions(
AttributeError: 'function' object has no attribute 'generate_expressions'
127.0.0.1 - - [20/May/2024 14:56:43] "POST /generate HTTP/1.1" 500 -

log file

2024/05/20 14:52:41 [INFO   ]  SD URL set to: http://127.0.0.1:7860
2024/05/20 14:53:25 [ERROR  ]  Could not find adetailer extension
2024/05/20 14:54:42 [INFO   ]  Found adetailer extension.
2024/05/20 14:54:42 [INFO   ]  adetailer extension is enabled.
2024/05/20 14:54:42 [INFO   ]  [36mUsing the following generation parameters:
[0m{'ad_inpaint_width': '832', 'ad_inpaint_height': '1216', 'seed': '1212253171', 'ad_prompt': 'catscore_9, score_8_up, score_7_up,   1 girl, gwen stacy (spider gwen), bed background, shiny skin, sweaty, blush, beautiful face, virgin destroyer sweater, detached sleeves, panties, thighhighs, flowers, solo, delicate and smooth skin, blush, perfect body, highly detailed, glossy lips, posing, solo    <lora:Concept Art Twilight Style SDXL_LoRA_Pony Diffusion V6 XL:0.8> concept art, realistic,  <lora:Expressive_H-000001:0.8>, expressiveH  <lora:sinfully_stylish_SDXL>  <lora:Pony_DetailV1.0> <lora:virgin_destroyer_sweater_v0.1-pony:0.8>', 'ad_negative_prompt': 'score_6, score_5, score_4, 3d', 'ad_steps': '32', 'ad_checkpoint': 'realcartoon3d_v15', 'ad_sampler': 'DPM++ 2M', 'ad_clip_skip': '2', 'ad_cfg_scale': '7', 'ad_denoising_strength': '0.5'}
2024/05/20 14:55:08 [INFO   ]  Found adetailer extension.
2024/05/20 14:55:08 [INFO   ]  adetailer extension is enabled.
2024/05/20 14:55:08 [INFO   ]  [36mUsing the following generation parameters:
[0m{'ad_inpaint_width': '832', 'ad_inpaint_height': '1216', 'seed': '1212253171', 'ad_prompt': 'catscore_9, score_8_up, score_7_up,   1 girl, gwen stacy (spider gwen), bed background, shiny skin, sweaty, blush, beautiful face, virgin destroyer sweater, detached sleeves, panties, thighhighs, flowers, solo, delicate and smooth skin, blush, perfect body, highly detailed, glossy lips, posing, solo    <lora:Concept Art Twilight Style SDXL_LoRA_Pony Diffusion V6 XL:0.8> concept art, realistic,  <lora:Expressive_H-000001:0.8>, expressiveH  <lora:sinfully_stylish_SDXL>  <lora:Pony_DetailV1.0> <lora:virgin_destroyer_sweater_v0.1-pony:0.8>', 'ad_negative_prompt': 'score_6, score_5, score_4, 3d', 'ad_steps': '32', 'ad_checkpoint': 'realcartoon3d_v15', 'ad_sampler': 'DPM++ 2M', 'ad_clip_skip': '2', 'ad_cfg_scale': '7', 'ad_denoising_strength': '0.5'}
2024/05/20 14:56:12 [INFO   ]  SD URL set to: http://127.0.0.1:7860
2024/05/20 14:56:43 [INFO   ]  Found adetailer extension.
2024/05/20 14:56:43 [INFO   ]  adetailer extension is enabled.
2024/05/20 14:56:43 [INFO   ]  [36mUsing the following generation parameters:
[0m{'ad_inpaint_width': '832', 'ad_inpaint_height': '1216', 'seed': '1212253171', 'ad_prompt': 'catscore_9, score_8_up, score_7_up,   1 girl, gwen stacy (spider gwen), bed background, shiny skin, sweaty, blush, beautiful face, virgin destroyer sweater, detached sleeves, panties, thighhighs, flowers, solo, delicate and smooth skin, blush, perfect body, highly detailed, glossy lips, posing, solo    <lora:Concept Art Twilight Style SDXL_LoRA_Pony Diffusion V6 XL:0.8> concept art, realistic,  <lora:Expressive_H-000001:0.8>, expressiveH  <lora:sinfully_stylish_SDXL>  <lora:Pony_DetailV1.0> <lora:virgin_destroyer_sweater_v0.1-pony:0.8>', 'ad_negative_prompt': 'score_6, score_5, score_4, 3d', 'ad_steps': '32', 'ad_checkpoint': 'realcartoon3d_v15', 'ad_sampler': 'DPM++ 2M', 'ad_clip_skip': '2', 'ad_cfg_scale': '7', 'ad_denoising_strength': '0.5'}
2024/05/20 15:00:22 [INFO   ]  Found adetailer extension.
2024/05/20 15:00:22 [INFO   ]  adetailer extension is enabled.
2024/05/20 15:00:22 [INFO   ]  [36mUsing the following generation parameters:
[0m{'ad_inpaint_width': '832', 'ad_inpaint_height': '1216', 'seed': '1212253171', 'ad_prompt': 'Smile', 'ad_negative_prompt': '', 'ad_steps': '32', 'ad_checkpoint': 'realcartoon3d_v15', 'ad_sampler': 'DPM++ 2M', 'ad_clip_skip': '2', 'ad_cfg_scale': '7', 'ad_denoising_strength': '0.5'}
2024/05/20 15:00:44 [INFO   ]  Found adetailer extension.
2024/05/20 15:00:44 [INFO   ]  adetailer extension is enabled.
2024/05/20 15:00:44 [INFO   ]  [36mUsing the following generation parameters:
[0m{'ad_inpaint_width': '832', 'ad_inpaint_height': '1216', 'seed': '1212253171', 'ad_prompt': 'Smile', 'ad_negative_prompt': '.', 'ad_steps': '32', 'ad_checkpoint': 'realcartoon3d_v15', 'ad_sampler': 'DPM++ 2M', 'ad_clip_skip': '2', 'ad_cfg_scale': '7', 'ad_denoising_strength': '0.5'}

**Comment by vladmandic** [comment]
@Jatilq i don't know what this is about, but:
- do not add to closed issues, create new one
- this does not look like sdnext at all

**Comment by Jatilq** [comment]
> @Jatilq i don't know what this is about, but:
> 
> * do not add to closed issues, create new one
> * this does not look like sdnext at all

I didn't even realized I replied here. I thought I was still replying to an issue with https://github.com/deepratnaawale/AutoExpress
First time submitting an issue. I started the issue on another app. Not even sure How it ended up here.
