### ISSUE TITLE
[Issue]: webui-start throws a "Uncaught exception error"

### ISSUE THREAD

**Issue by maraschouche** [vladmandic/automatic#3155]
### Issue Description

Strangest thing, sd.next was working fine- did an update the other day and noticed that the dynamic prompts stopped working sometimes, had to restart sd.next to fix it.
tonight, it happened again, and when I went to restart, it throws this exception

00:05:36-715732 ERROR    Uncaught exception occurred: type=<class 'Exception'> value=You need either charset_normalizer or chardet installed
00:05:36-718735 ERROR    '  File "O:\\data\\gitzeugs\\automatic\\launch.py", line 263, in <module>\n    main()\n'
00:05:36-720737 ERROR    '  File "O:\\data\\gitzeugs\\automatic\\launch.py", line 203, in main\n    installer.check_version()\n'
00:05:36-721738 ERROR    '  File "O:\\data\\gitzeugs\\automatic\\installer.py", line 987, in check_version\n    import requests\n'
00:05:36-722739 ERROR    '  File "O:\\data\\gitzeugs\\automatic\\venv\\lib\\site-packages\\requests\\__init__.py", line 105, in
                         <module>\n    check_compatibility(\n'
00:05:36-723740 ERROR    '  File "O:\\data\\gitzeugs\\automatic\\venv\\lib\\site-packages\\requests\\__init__.py", line 86, in
                         check_compatibility\n    raise Exception("You need either charset_normalizer or chardet installed")\n'

I installed both charset_normalizer and chardet and that didn't fix anything.

git pull tells me I have the latest version
starting with --debug doesn't change anything
renaming config.json's doesn't change the error either

### Version Platform Description

latest version (ran a git pull) updated 5/7/24
Windows 10
Chrome Browser

### Relevant log output

```shell
2024-05-20 00:03:02,741 | sd | INFO | launch | Starting SD.Next
2024-05-20 00:03:02,753 | sd | INFO | installer | Logger: file="O:\data\gitzeugs\automatic\sdnext.log" level=DEBUG size=65 mode=create
2024-05-20 00:03:02,755 | sd | INFO | installer | Python 3.10.6 on Windows
2024-05-20 00:03:02,876 | sd | INFO | installer | Version: app=sd.next updated=2024-05-07 hash=e081f232 branch=master url=https://github.com/vladmandic/automatic/tree/master
2024-05-20 00:03:02,942 | sd | ERROR | installer | Uncaught exception occurred: type=<class 'Exception'> value=You need either charset_normalizer or chardet installed
2024-05-20 00:03:02,945 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\launch.py", line 263, in <module>\n    main()\n'
2024-05-20 00:03:02,947 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\launch.py", line 203, in main\n    installer.check_version()\n'
2024-05-20 00:03:02,948 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\installer.py", line 987, in check_version\n    import requests\n'
2024-05-20 00:03:02,949 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\venv\\lib\\site-packages\\requests\\__init__.py", line 105, in <module>\n    check_compatibility(\n'
2024-05-20 00:03:02,951 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\venv\\lib\\site-packages\\requests\\__init__.py", line 86, in check_compatibility\n    raise Exception("You need either charset_normalizer or chardet installed")\n'
2024-05-20 00:04:08,297 | sd | INFO | launch | Starting SD.Next
2024-05-20 00:04:08,308 | sd | INFO | installer | Logger: file="O:\data\gitzeugs\automatic\sdnext.log" level=INFO size=1590 mode=append
2024-05-20 00:04:08,310 | sd | INFO | installer | Python 3.10.6 on Windows
2024-05-20 00:04:08,430 | sd | INFO | installer | Version: app=sd.next updated=2024-05-07 hash=e081f232 branch=master url=https://github.com/vladmandic/automatic/tree/master
2024-05-20 00:04:08,501 | sd | ERROR | installer | Uncaught exception occurred: type=<class 'Exception'> value=You need either charset_normalizer or chardet installed
2024-05-20 00:04:08,504 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\launch.py", line 263, in <module>\n    main()\n'
2024-05-20 00:04:08,505 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\launch.py", line 203, in main\n    installer.check_version()\n'
2024-05-20 00:04:08,507 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\installer.py", line 987, in check_version\n    import requests\n'
2024-05-20 00:04:08,508 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\venv\\lib\\site-packages\\requests\\__init__.py", line 105, in <module>\n    check_compatibility(\n'
2024-05-20 00:04:08,510 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\venv\\lib\\site-packages\\requests\\__init__.py", line 86, in check_compatibility\n    raise Exception("You need either charset_normalizer or chardet installed")\n'
2024-05-20 00:05:26,998 | sd | INFO | launch | Starting SD.Next
2024-05-20 00:05:27,007 | sd | INFO | installer | Logger: file="O:\data\gitzeugs\automatic\sdnext.log" level=INFO size=3116 mode=append
2024-05-20 00:05:27,010 | sd | INFO | installer | Python 3.10.6 on Windows
2024-05-20 00:05:27,128 | sd | INFO | installer | Version: app=sd.next updated=2024-05-07 hash=e081f232 branch=master url=https://github.com/vladmandic/automatic/tree/master
2024-05-20 00:05:27,193 | sd | ERROR | installer | Uncaught exception occurred: type=<class 'Exception'> value=You need either charset_normalizer or chardet installed
2024-05-20 00:05:27,197 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\launch.py", line 263, in <module>\n    main()\n'
2024-05-20 00:05:27,198 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\launch.py", line 203, in main\n    installer.check_version()\n'
2024-05-20 00:05:27,200 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\installer.py", line 987, in check_version\n    import requests\n'
2024-05-20 00:05:27,201 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\venv\\lib\\site-packages\\requests\\__init__.py", line 105, in <module>\n    check_compatibility(\n'
2024-05-20 00:05:27,203 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\venv\\lib\\site-packages\\requests\\__init__.py", line 86, in check_compatibility\n    raise Exception("You need either charset_normalizer or chardet installed")\n'
2024-05-20 00:05:36,503 | sd | INFO | launch | Starting SD.Next
2024-05-20 00:05:36,514 | sd | INFO | installer | Logger: file="O:\data\gitzeugs\automatic\sdnext.log" level=INFO size=4642 mode=append
2024-05-20 00:05:36,516 | sd | INFO | installer | Python 3.10.6 on Windows
2024-05-20 00:05:36,650 | sd | INFO | installer | Version: app=sd.next updated=2024-05-07 hash=e081f232 branch=master url=https://github.com/vladmandic/automatic/tree/master
2024-05-20 00:05:36,715 | sd | ERROR | installer | Uncaught exception occurred: type=<class 'Exception'> value=You need either charset_normalizer or chardet installed
2024-05-20 00:05:36,718 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\launch.py", line 263, in <module>\n    main()\n'
2024-05-20 00:05:36,720 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\launch.py", line 203, in main\n    installer.check_version()\n'
2024-05-20 00:05:36,721 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\installer.py", line 987, in check_version\n    import requests\n'
2024-05-20 00:05:36,722 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\venv\\lib\\site-packages\\requests\\__init__.py", line 105, in <module>\n    check_compatibility(\n'
2024-05-20 00:05:36,723 | sd | ERROR | installer | '  File "O:\\data\\gitzeugs\\automatic\\venv\\lib\\site-packages\\requests\\__init__.py", line 86, in check_compatibility\n    raise Exception("You need either charset_normalizer or chardet installed")\n'
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this looks like something installed incompatible version of `requests` on your system.
you can bypass this particular check above if you use `--skip-git` command line flag and then hope that installer fixes the incompatible package later during verification process.

if not, you'll need to delete `venv` folder and let installer reinstall everything - and monitor log if some extension installs incorrect package after main installer has completed.

**Comment by maraschouche** [comment]
--skip-git didn't work at all- but deleting and re-downloading venv got me back into sd.next okay.

However, dynamic prompts (wildcards) aren't working at all now- I see the following error in the console, but not the log:
16:49:32-888869 ERROR    Running script process: extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py: ParseException
┌─────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────┐
│ O:\data\gitzeugs\automatic\modules\scripts.py:501 in process                                                                    │
│                                                                                                                                 │
│   500 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_from:script.args_to])              │
│ > 501 │   │   │   │   script.process(p, *args, **kwargs)                                                                        │
│   502 │   │   │   except Exception as e:                                                                                        │
│                                                                                                                                 │
│ O:\data\gitzeugs\automatic\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py:480 in process                 │
│                                                                                                                                 │
│   479 │   │   │                                                                                                                 │
│ > 480 │   │   │   all_prompts, all_negative_prompts = generate_prompts(                                                         │
│   481 │   │   │   │   prompt_generator=generator,                                                                               │
│                                                                                                                                 │
│ O:\data\gitzeugs\automatic\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py:93 in generate_prompts                   │
│                                                                                                                                 │
│    92 │   """                                                                                                                   │
│ >  93 │   all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]                                     │
│    94                                                                                                                           │
│                                                                                                                                 │
│ O:\data\gitzeugs\automatic\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py:67 in generate                      │
│                                                                                                                                 │
│   66 │   │   │                                                                                                                  │
│ > 67 │   │   │   gen = self._context.sample_prompts(template, num_images)                                                       │
│   68 │   │   │   prompts = []                                                                                                   │
│                                                                                                                                 │
│ O:\data\gitzeugs\automatic\venv\lib\site-packages\dynamicprompts\sampling_context.py:119 in sample_prompts                      │
│                                                                                                                                 │
│   118 │   │   │                                                                                                                 │
│ > 119 │   │   │   command = parse(prompt, parser_config=self.parser_config)                                                     │
│   120 │   │   elif isinstance(prompt, Command):                                                                                 │
│                                                                                                                                 │
│ O:\data\gitzeugs\automatic\venv\lib\site-packages\dynamicprompts\parser\parse.py:557 in parse                                   │
│                                                                                                                                 │
│   556 │                                                                                                                         │
│ > 557 │   tokens = get_cached_parser(parser_config).parse_string(                                                               │
│   558 │   │   prompt,                                                                                                           │
│                                                                                                                                 │
│ O:\data\gitzeugs\automatic\venv\lib\site-packages\pyparsing\core.py:1200 in parse_string                                        │
│                                                                                                                                 │
│   1199 │   │   │   │   # catch and re-raise exception from here, clearing out pyparsing internal stack trace                    │
│ > 1200 │   │   │   │   raise exc.with_traceback(None)                                                                           │
│   1201 │   │   else:                                                                                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ParseException: Expected end of text, found '_'  (at char 156), (line:1, col:157)

**Comment by maraschouche** [comment]
Should I put in a separate issue for the dynamic extension?

**Comment by vladmandic** [comment]
best to handle it separately. btw, sd-dynamic-prompts extensions is known to break/fix/break/fix pretty often.
and in the latest sdnext-dev, full functionality of dynamic prompts is pretty much built-in, no need for extension at all (and yes, its compatible with same wildcards files).

**Comment by maraschouche** [comment]
That's great news!  I'll delete and re-install the extension again and wait patiently for the next sdnext

**Comment by vladmandic** [comment]
it should be released later this week.
