### ISSUE TITLE
[Issue]: Error with SD3

### ISSUE THREAD

**Issue by VeteranXT** [vladmandic/automatic#3232]
### Issue Description

Started SD.Next
Picked SD3 sd3_medium.safetensors.
Loaded fine no erros.
Put token key into right place.
Wrote random prompt : rat wearing a hat
Clicked generated...
Throws erorr

### Version Platform Description

Version: app=sd.next updated=2024-06-13 hash=a3ffd478 branch=master
                         url=https://github.com/vladmandic/automatic.git/tree/master ui=main
Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
Python version=3.10.11 platform=Windows
                         bin="E:\Storage\Apps\AI_Geneartor\automatic\venv\Scripts\python.exe"
                         venv="E:\Storage\Apps\AI_Geneartor\automatic\venv"
Extensions: disabled=[]
23:54:11-015396 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']

### Relevant log output

```shell
Traceback (most recent call last):
  File "E:\Storage\Apps\AI_Geneartor\automatic\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\Storage\Apps\AI_Geneartor\automatic\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Storage\Apps\AI_Geneartor\automatic\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "E:\Storage\Apps\AI_Geneartor\automatic\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Storage\Apps\AI_Geneartor\automatic\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Storage\Apps\AI_Geneartor\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\Storage\Apps\AI_Geneartor\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\Storage\Apps\AI_Geneartor\automatic\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "E:\Storage\Apps\AI_Geneartor\automatic\modules\ui_common.py", line 233, in interrogate_booru
    prompt = deepbooru.model.tag(image)
  File "E:\Storage\Apps\AI_Geneartor\automatic\modules\deepbooru.py", line 44, in tag
    res = self.tag_multi(pil_image)
  File "E:\Storage\Apps\AI_Geneartor\automatic\modules\deepbooru.py", line 56, in tag_multi
    pic = images.resize_image(2, pil_image.convert("RGB"), 512, 512)
AttributeError: 'str' object has no attribute 'convert'
```

### Backend

Diffusers

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by VeteranXT** [comment]
it fixed itself by restarting SD.Next
