### ISSUE TITLE
NotADirectory exception when downloading 

### ISSUE THREAD

**Issue by caphector** [vladmandic/automatic#3239]
### Issue Description

The Model downloaded throws an exception when a model name is not supplied when downloading models from CivitAi.

### Version Platform Description

NAME="Linux Mint"
VERSION="21.3 (Virginia)"

### Relevant log output

```shell
11:51:20-609475 INFO     Available models: path="/media/user/SSD/models/Stable-diffusion" items=1 time=0.00
11:51:20-937224 INFO     Model download: name="" url="https://civitai.com/api/download/models/559621" path="" temp="/media/user/SSD/models/Lora/e3b0c442.tmp" resume=55Mb size=217.87Mb

Exception in thread Thread-8 (download_civit_model_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/duncan/ai/automatic/modules/modelloader.py", line 148, in download_civit_model_thread
    os.rename(temp_file, model_file)
NotADirectoryError: [Errno 20] Not a directory: '/media/user/SSD/models/Lora/e3b0c442.tmp' -> '/media/user/SSD/models/Lora/'
```

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev, will release soon.
