### ISSUE TITLE
[Extension]: Getting lots of scripts related errors when using deforum with controlnet

### ISSUE THREAD

**Issue by hithereai** [vladmandic/automatic#326]
### Issue Description

After I fixed the dynamic folder-finder to work with extensions-builtin, I get so many errros when trying to run a simple run with 1 canny model:

```
Reading ControlNet 1 base frame 1 at D:\D-SD\automatic-vlad\outputs/image\Deforum_20230421004921\controlnet_1_inputframes\000000001.jpg
Reading ControlNet 1 mask frame 1 at D:\D-SD\automatic-vlad\outputs/image\Deforum_20230421004921\controlnet_1_maskframes\000000001.jpg
Running script process:
D:\D-SD\automatic-vlad\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ D:\D-SD\automatic-vlad\modules\scripts.py:422 in process                                                             ││                                                                                                                      ││   421 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                   ││ ❱ 422 │   │   │   │   script.process(p, *script_args)                                                                ││   423 │   │   │   except Exception as e:                                                                             │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯TypeError: Script.process() missing 21 required positional arguments: 'enabled', 'method', 'noise_inverse',
'noise_inverse_steps', 'noise_inverse_retouch', 'noise_inverse_renoise_strength', 'noise_inverse_renoise_kernel',
'overwrite_image_size', 'keep_input_size', 'image_width', 'image_height', 'tile_width', 'tile_height', 'overlap',
'tile_batch_size', 'upscaler_index', 'scale_factor', 'control_tensor_cpu', 'enable_bbox_control', 'draw_background', and'causal_layers'
Running script process:
D:\D-SD\automatic-vlad\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ D:\D-SD\automatic-vlad\modules\scripts.py:422 in process                                                             ││                                                                                                                      ││   421 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                   ││ ❱ 422 │   │   │   │   script.process(p, *script_args)                                                                ││   423 │   │   │   except Exception as e:                                                                             │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'vae_to_gpu', 'fast_decoder',
'fast_encoder', 'color_fix', 'encoder_tile_size', and 'decoder_tile_size'
Running script process:
D:\D-SD\automatic-vlad\extensions-builtin\sd-extension-steps-animation\scripts\steps_animation.py: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ D:\D-SD\automatic-vlad\modules\scripts.py:422 in process                                                             ││                                                                                                                      ││   421 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                   ││ ❱ 422 │   │   │   │   script.process(p, *script_args)                                                                ││   423 │   │   │   except Exception as e:                                                                             │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯TypeError: Script.process() missing 11 required positional arguments: 'is_enabled', 'codec', 'interpolation',
'duration', 'skip_steps', 'debug', 'run_incomplete', 'tmp_delete', 'out_create', 'tmp_path', and 'out_path'
Running script process batch:
D:\D-SD\automatic-vlad\extensions-builtin\sd-dynamic-thresholding\scripts\dynamic_thresholding.py: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ D:\D-SD\automatic-vlad\modules\scripts.py:438 in process_batch                                                       ││                                                                                                                      ││   437 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                   ││ ❱ 438 │   │   │   │   script.process_batch(p, *script_args, **kwargs)                                                ││   439 │   │   │   except Exception as e:                                                                             │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯TypeError: Script.process_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale',
'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'powerscale_power'
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  6.26it/s]
Running script before postprocess batch:
D:\D-SD\automatic-vlad\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮


│ D:\D-SD\automatic-vlad\modules\scripts.py:454 in postprocess_batch                                                   │
│                                                                                                                      │
│   453 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                   │
│ ❱ 454 │   │   │   │   script.postprocess_batch(p, *script_args, images=images, **kwargs)                             │
│   455 │   │   │   except Exception as e:                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'
Running script before postprocess batch:
D:\D-SD\automatic-vlad\extensions-builtin\sd-dynamic-thresholding\scripts\dynamic_thresholding.py: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\D-SD\automatic-vlad\modules\scripts.py:454 in postprocess_batch                                                   │
│                                                                                                                      │
│   453 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                   │
│ ❱ 454 │   │   │   │   script.postprocess_batch(p, *script_args, images=images, **kwargs)                             │
│   455 │   │   │   except Exception as e:                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Script.postprocess_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale',
'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'powerscale_power'
Running script postprocess:
D:\D-SD\automatic-vlad\extensions-builtin\sd-extension-steps-animation\scripts\steps_animation.py: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\D-SD\automatic-vlad\modules\scripts.py:446 in postprocess                                                         │
│                                                                                                                      │
│   445 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                   │
│ ❱ 446 │   │   │   │   script.postprocess(p, processed, *script_args)                                                 │
│   447 │   │   │   except Exception as e:                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Script.postprocess() missing 11 required positional arguments: 'is_enabled', 'codec', 'interpolation',
'duration', 'skip_steps', 'debug', 'run_incomplete', 'tmp_delete', 'out_create', 'tmp_path', and 'out_path'
```

### Version Platform Description

Windows 11, rtx 4090, and webui info:
updated: 2023-04-20
hash: 0282832f
url: https://github.com/vladmandic/automatic.git/tree/master

**Comment by vladmandic** [comment]
OK, I'll fix it tomorrow, just checked out.

**Comment by hithereai** [comment]
https://github.com/deforum-art/deforum-for-automatic1111-webui/pull/594

Just merged this so you can test. Without this PR deforum won't show you the CN UI.

**Comment by Djanghost** [comment]
Deforum worked for me lately (didn't test CN then) but now here is what i get when i click on generate :

![deforum](https://user-images.githubusercontent.com/129005283/233691802-3919f66b-6d1a-4552-8387-a13293f40a97.png)

**Comment by hithereai** [comment]
> Deforum worked for me lately (didn't test CN then) but now here is what i get when i click on generate :
> 
> 
> 
> ![deforum](https://user-images.githubusercontent.com/129005283/233691802-3919f66b-6d1a-4552-8387-a13293f40a97.png)
> 
Not related to this issue. It's a sd v1.5 to sd 2. Switch in webui. Open a diff issue?

**Comment by vladmandic** [comment]
There is a master Deforum issue, do not open separate ones.

**Comment by hithereai** [comment]
OK. what I wrote is still relevant though.

**Comment by Djanghost** [comment]
> > Deforum worked for me lately (didn't test CN then) but now here is what i get when i click on generate :
> > ![deforum](https://user-images.githubusercontent.com/129005283/233691802-3919f66b-6d1a-4552-8387-a13293f40a97.png)
> 
> Not related to this issue. It's a sd v1.5 to sd 2. Switch in webui. Open a diff issue?

I agree it has nothing to do with the CN error I just followed vladmandic's recommendations to post. 
I'm not sure I understand on the other hand for SD versions. I only use 1.5 models, renders worked fine two days ago with this repo, unfortunately not anymore. Do you have this error on your side @hithereai when clicking on Generate ?

Thx

**Comment by hithereai** [comment]
> > > Deforum worked for me lately (didn't test CN then) but now here is what i get when i click on generate :
> > > ![deforum](https://user-images.githubusercontent.com/129005283/233691802-3919f66b-6d1a-4552-8387-a13293f40a97.png)
> > 
> > 
> > Not related to this issue. It's a sd v1.5 to sd 2. Switch in webui. Open a diff issue?
> 
> I agree it has nothing to do with the CN error I just followed vladmandic's recommendations to post. I'm not sure I understand on the other hand for SD versions. I only use 1.5 models, renders worked fine two days ago with this repo, unfortunately not anymore. Do you have this error on your side @hithereai when clicking on Generate ?
> 
> Thx

Deforum without CN working perfectly for me on latest versions of all (tested 2 minutes ago). Can't replicate your issue.

**Comment by Djanghost** [comment]
> > > > Deforum worked for me lately (didn't test CN then) but now here is what i get when i click on generate :
> > > > ![deforum](https://user-images.githubusercontent.com/129005283/233691802-3919f66b-6d1a-4552-8387-a13293f40a97.png)
> > > 
> > > 
> > > Not related to this issue. It's a sd v1.5 to sd 2. Switch in webui. Open a diff issue?
> > 
> > 
> > I agree it has nothing to do with the CN error I just followed vladmandic's recommendations to post. I'm not sure I understand on the other hand for SD versions. I only use 1.5 models, renders worked fine two days ago with this repo, unfortunately not anymore. Do you have this error on your side @hithereai when clicking on Generate ?
> > Thx
> 
> Deforum without CN working perfectly for me on latest versions of all (tested 2 minutes ago). Can't replicate your issue.

Thanks for your anwser. Well going to reinstall all a last time

**Comment by Djanghost** [comment]
Finally OK for me after installing newer python version and reinstalled this repo. Didn't test CN yet but i will follow this topic with attention.

**Comment by hithereai** [comment]
Control net is still not working. Waiting for a fix from vlad.

**Comment by hithereai** [comment]
any updates @vladmandic?

**Comment by vladmandic** [comment]
i feel like i'm swimming upstream - with every issue i close, two new ones pop-up, wasn't ready for this thing to go viral. sorry for the delay.

**Comment by hithereai** [comment]
it's just the beginning, buckle up 🥇

**Comment by hithereai** [comment]
@vladmandic Ping. Getting lots of complaints.

**Comment by vladmandic** [comment]
just fixed one installer error (you have a strange name for a default branch), but that's trivial.
can someone write steps to get to runtime errors noted above? i'm not a deforum user, would be faster than me trying different things.

**Comment by hithereai** [comment]
@vladmandic sure, just go to deforum, then controlnet tab, enable ControlNet 1, choose canny preproc and canny model (v1 or 1.1 doesn't matter), and upload a video to the video box (not the mask box). Click run.

**Comment by hithereai** [comment]
![image](https://user-images.githubusercontent.com/121192995/234398281-e4c49420-73f2-4e38-8b48-d9e7b3b6f725.png)

**Comment by vladmandic** [comment]
ok, first pass of the fix. the issue was if something is corrupting always-on script args, it will fail with exception error on whatever happens to be first always-on script when deforum+controlnet run, there was no validation done. i still don't know who is responsible for corrupting `p.script_args`, but at least validation checks will catch it.

new code is posted, i'd appreciate if people more experienced with controlnet+deforum workflows test it. if there are problems, report here and i'll reopen this issue.

**Comment by vladmandic** [comment]
further work needed, tracking in <https://github.com/Mikubill/sd-webui-controlnet/issues/1027>

**Comment by ApoyPH** [comment]
Hi, has anyone experienced this using CN + Deforum?

```
Git commit: ae426f67 (Tue May 23 00:01:02 2023)
Unpacking ControlNet 1 base video
Exporting Video Frames to C:\stable-diffusion-webui\outputs/img2img-images\Deforum_20230524155136\controlnet_1_inputframes...
Trying to extract frames from video with input FPS of 30.0. Please wait patiently.
Extracted 356 frames from video in 1.04 seconds!
Loading 330 input frames from C:\stable-diffusion-webui\outputs/img2img-images\Deforum_20230524155136\controlnet_1_inputframes and saving video frames to C:\stable-diffusion-webui\outputs/img2img-images\Deforum_20230524155136
ControlNet 1 base video unpacked!
Unpacking ControlNet 2 base video
Exporting Video Frames to C:\stable-diffusion-webui\outputs/img2img-images\Deforum_20230524155136\controlnet_2_inputframes...
Trying to extract frames from video with input FPS of 30.0. Please wait patiently.
Extracted 356 frames from video in 0.97 seconds!
Loading 330 input frames from C:\stable-diffusion-webui\outputs/img2img-images\Deforum_20230524155136\controlnet_2_inputframes and saving video frames to C:\stable-diffusion-webui\outputs/img2img-images\Deforum_20230524155136
ControlNet 2 base video unpacked!
Saving animation frames to:
C:\stable-diffusion-webui\outputs/img2img-images\Deforum_20230524155136
Animation frame: 0/330
Seed: 253936846
Prompt: neon lights cyberpunk girl dancing
Neg Prompt: nsfw, nude
Not using an init image (doing pure txt2img)
╭─────┬───┬───────┬─────┬────┬────┬────╮
│Steps│CFG│Denoise│Angle│Zoom│Tr X│Tr Y│
├─────┼───┼───────┼─────┼────┼────┼────┤
│ 25  │7.0│   0   │  0  │ 1  │ 0  │ 0  │
╰─────┴───┴───────┴─────┴────┴────┴────╯
Reading ControlNet 1 base frame #0 at C:\stable-diffusion-webui\outputs/img2img-images\Deforum_20230524155136\controlnet_1_inputframes\000000000.jpg
Reading ControlNet 2 base frame #0 at C:\stable-diffusion-webui\outputs/img2img-images\Deforum_20230524155136\controlnet_2_inputframes\000000000.jpg
Error running process: C:\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 13 required positional arguments: 'enabled', 'multiply', 'weight', 'understand', 'layers', 'apply_to', 'start_steps', 'max_steps', 'up', 'up_aa', 'down', 'down_aa', and 'intp'

100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:19<00:00,  1.25it/s]
Error running postprocess: C:\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py6 [00:17<37:02,  1.33it/s]
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 445, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 13 required positional arguments: 'enabled', 'multiply', 'weight', 'understand', 'layers', 'apply_to', 'start_steps', 'max_steps', 'up', 'up_aa', 'down', 'down_aa', and 'intp'

```

everything works fine, CN works on txt2img and img2img, Deforum works without CN, Deforum works with CN but it seems CN is not working with Deforum.

**Comment by vladmandic** [comment]
this is all related how Deforum creates params to pass to ControlNet - and it corrupts them.
Per Deforum author, a major rehaul is pending on Deforum side and should be sometimes soon.
See <https://github.com/deforum-art/sd-webui-deforum/pull/636>

**Comment by hithereai** [comment]
> this is all related how Deforum creates params to pass to ControlNet - and it corrupts them. Per Deforum author, a major rehaul is pending on Deforum side and should be sometimes soon. See [deforum-art/sd-webui-deforum#636](https://github.com/deforum-art/sd-webui-deforum/pull/636)

Actually I pushed that refactor already - but comp forgot to address the issue with built in always-on scripts/ extens. Will make it a priority.

**Comment by herhu** [comment]
![Screenshot 2023-05-30 at 11 25 38](https://github.com/vladmandic/automatic/assets/48290810/7c0e38e7-65e5-4882-9aba-881a327cb87b)

i have similar problem , any suggestion about how to fix it ?

**Comment by vladmandic** [comment]
closing due to lack of any updates.
