### ISSUE TITLE
[Issue]: Clean install fails on Windows

### ISSUE THREAD

**Issue by claudiodekker** [vladmandic/automatic#331]
### Issue Description

After cloning https://github.com/vladmandic/automatic/commit/2ddbb6670484ed31120dc7bcdef4c292400e7a27 fresh and running webui.bat:

```
Creating venv in directory C:\Users\claud\Desktop\automatic\venv using python "C:\Users\claud\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
venv "C:\Users\claud\Desktop\automatic\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File "C:\Users\claud\Desktop\automatic\launch.py", line 19, in <module>
    setup.parse_args()
  File "C:\Users\claud\Desktop\automatic\setup.py", line 446, in parse_args
    from modules.script_loading import preload_extensions
  File "C:\Users\claud\Desktop\automatic\modules\script_loading.py", line 3, in <module>
    import modules.errors as errors
  File "C:\Users\claud\Desktop\automatic\modules\errors.py", line 3, in <module>
    from rich import print # pylint: disable=redefined-builtin
ModuleNotFoundError: No module named 'rich'
Press any key to continue . . .

```

### Version Platform Description

- Windows 11 x64
- Python 3.10.11
- Nvidia 3060 TI

**Comment by kohweiteck** [comment]
This is repeated issues requests on #291 .Mark posts as closed and post it here

**Comment by claudiodekker** [comment]
Thanks!
