### ISSUE TITLE
[Issue] Model > Civitai Search error.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#3327]
Searching using Model > Civitai search results in;

```
12:24:46-604281 DEBUG    CivitAI search: name="dreamshaper" tag=none
                         url="https://civitai.com/api/v1/models?limit=25&Sort=Newest&types=Checkpoint&query=dreamshaper"
                         status=200
Traceback (most recent call last):
  File "E:\sdmaster\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\paul_\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\paul_\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\paul_\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\sdmaster\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\sdmaster\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\sdmaster\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "E:\sdmaster\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\sdmaster\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\sdmaster\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\sdmaster\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\sdmaster\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "E:\sdmaster\modules\ui_models.py", line 435, in civit_search_model
    body = r.json()
  File "E:\sdmaster\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Version/OS Stuff:

```
Python version=3.10.11 platform=Windows bin="E:\sdmaster\venv\Scripts\python.exe"
venv="E:\sdmaster\venv"
Version: app=sd.next updated=2024-07-09 hash=c909c118 branch=master
url=https://github.com/vladmandic/automatic/tree/master ui=main
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
release=Windows-10-10.0.19045-SP0 python=3.10.11
```

**Comment by vladmandic** [comment]
fixed in dev, will refresh master as well.
