### ISSUE TITLE
[Issue]: RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by TheBlueSky** [vladmandic/automatic#342]
### Issue Description

I am using the latest code from the repository as of this writing (2ddbb6670484ed31120dc7bcdef4c292400e7a27) with Python 3.10.11 on Windows.

I do not have an Nvidia GPU on my laptop (Intel Core i7-8650U with Intel UHD Graphics 620 and Radeon RX 540 Series).

I changed the settings to enable `Use full precision for model (--no-half)`, `Use full precision for VAE (--no-half-vae)`, and `Precision type` to `Full`, but I got `RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'` error.

Then I changed `Device precision type` to `FP32`, but got the same error. Also, when I disabled `Allow TF16 reduced precision math ops`.

Note that I can run Automatic1111 when I provide the following argument: `--skip-torch-cuda-test --precision full --no-half`.

Can someone help me understand what I am missing?

### Version Platform Description

Windows 11 22H2
Python 3.10.11
Repository commit 2ddbb6670484ed31120dc7bcdef4c292400e7a27
PC Intel Core i7-8650U with Intel UHD Graphics 620 and Radeon RX 540 Series

**Comment by vladmandic** [comment]
this is an example of a well written issue - short, up to a point, all info provided, wish more were like this :)
i'll try to reproduce and if i can, fix will be ready shortly. if not, i'll have some more questions/tests for you.

**Comment by vladmandic** [comment]
first issue is that sdp does not work without cuda, so i'll need to add code to auto-disable sdp for cpu-only environments
but you can manually set doggettx and that one works for cpu. i'll follow-up on this as its annoying.

second issue is that xformers is trying to load itself if its present on the system even if it cannot work. 
you can uninstall xformers (`pip uninstall xformers`) and set env variable `XFORMERS_PACKAGE=none` so they don't get reinstalled. i'll follow-up on this as its annoying.

third issue is with multidiffusion upscaler that simply fails on initialization on cpu only systems even if its not enabled
go to extensions, and uncheck it from list.
created issue <https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/142> to track that

and after those 3 steps, it works.

i'll rename the issue to track more generic use on cpu only systems and follow-up on each issue.

**Comment by vladmandic** [comment]
fixed first and second issue, waiting for extension author to update the last remaining one.

**Comment by TheBlueSky** [comment]
Thank you @vladmandic for your quick response.
I will try the latest code and your recommendation about Tiled Diffusion and will report beck.

**Comment by TheBlueSky** [comment]
Yesterday's error has gone, but now I am getting the following error (regardless of whether `Allow TF16 reduced precision math ops` is checked or not or `Device precision type` set to `FP32` or `FP16`):
```
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs: query : shape=(1, 6656, 1, 512) (torch.float32) key : shape=(1, 6656, 1, 512) (torch.float32) value : shape=(1, 6656, 1, 512) (torch.float32) attn_bias : <class 'NoneType'> p : 0.0 `cutlassF` is not supported because: device=cpu (supported: {'cuda'}) `flshattF` is not supported because: device=cpu (supported: {'cuda'}) dtype=torch.float32 (supported: {torch.float16, torch.bfloat16}) max(query.shape[-1] != value.shape[-1]) > 128 `tritonflashattF` is not supported because: device=cpu (supported: {'cuda'}) dtype=torch.float32 (supported: {torch.float16, torch.bfloat16}) max(query.shape[-1] != value.shape[-1]) > 128 triton is not available `smallkF` is not supported because: max(query.shape[-1] != value.shape[-1]) > 32 unsupported embed per head: 512
```

**Comment by vladmandic** [comment]
did you disable "multidiffusion upscaler" extension?
also, i need longer traceback to see where this error is raised.

**Comment by TheBlueSky** [comment]
> did you disable "multidiffusion upscaler" extension?
Yes I did.

> also, i need longer traceback to see where this error is raised.
No worries, I will get you the console output or the logs.

**Comment by phaylali** [comment]
same issue , a different error
`RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'`
it works fine in a1111 with  `--skip-torch-cuda-test --precision full --no-half`

**Comment by TheBlueSky** [comment]
I got the latest code from the repo, and now I am getting the same error as @phaylali; `RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'`.

```
Traceback (most recent call last):
  File "C:\Users\Essam\Desktop\vlad.automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Essam\Desktop\vlad.automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\Essam\Desktop\vlad.automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Essam\Desktop\vlad.automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Essam\Desktop\vlad.automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Essam\Desktop\vlad.automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Essam\Desktop\vlad.automatic\extensions-builtin\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 922, in change_dir
    img_dir, img_path_depth = pure_path(img_dir)
  File "C:\Users\Essam\Desktop\vlad.automatic\extensions-builtin\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 264, in pure_path
    match = re.search(r" \[(\d+)\]$", path)
  File "C:\Users\Essam\AppData\Local\Programs\Python\Python310\lib\re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "C:\Users\Essam\Desktop\vlad.automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Essam\Desktop\vlad.automatic\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\Essam\Desktop\vlad.automatic\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\Essam\Desktop\vlad.automatic\venv\lib\site-packages\gradio\components.py", line 567, in preprocess
    return self._round_to_precision(x, self.precision)
  File "C:\Users\Essam\Desktop\vlad.automatic\venv\lib\site-packages\gradio\components.py", line 529, in _round_to_precision
    return float(num)
ValueError: could not convert string to float: 'task(nbegckniwdojzd2)'
```

Commit: 4cb46d5400b04491ae9e70d992ca0019d48942a9
Precision type: Full
Device precision type: FP32
Use full precision for model (--no-half): Enabled
Use full precision for VAE (--no-half-vae): Enabled
Allow TF32 math ops: Enabled
Allow TF16 reduced precision math ops: Disabled
multidiffusion-upscaler-for-automatic1111 extension: Disabled

**Comment by hugoddjing** [comment]
The sam error on my linux system:
(vlad) localhost:~/automatic$ ./webui.sh --use-cpu all --listen

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on hugo user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
07:19:52-200260 INFO     Python 3.10.9 on Linux                                                                                                                                                                
07:19:52-354357 INFO     Version: 24531398 Tue Apr 25 19:36:41 2023 -0400                                                                                                                                      
07:19:53-434675 INFO     Setting environment tuning                                                                                                                                                            
07:19:53-440536 INFO     Using CPU-only Torch                                                                                                                                                                  
07:19:56-084185 INFO     Torch 2.0.0+cu117                                                                                                                                                                     
07:19:56-086793 WARNING  Torch repoorts CUDA not available                                                                                                                                                     
07:19:56-089430 INFO     Verifying requirements                                                                                                                                                                
07:19:56-138706 INFO     No changes detected: Quick launch active                                                                                                                                              
07:19:56-142171 INFO     Running extension preloading                                                                                                                                                          
07:19:56-144571 INFO     Server arguments: ['--use-cpu', 'all', '--listen']                                                                                                                                    
No module 'xformers'. Proceeding without it.
Available models: /home/hugo/automatic/models/Stable-diffusion 1
ControlNet v1.1.112
ControlNet v1.1.112
Loading theme: black-orange
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Checkpoint model.ckpt not found; loading fallback chilloutmix_NiPrunedFp32Fix.safetensors 
Loading weights: /home/hugo/automatic/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.3 GB -:--:--
Creating model from config: /home/hugo/automatic/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Scaled dot product cross attention is not available on CPU
Embeddings loaded:  (0)
Model loaded in 3.2s (load=0.8s create=1.3s apply=0.5s vae=0.5s)
Startup time: 18.5s (torch=4.8s gradio=2.1s libraries=1.2s codeformer=0.2s scripts=4.3s ui=1.9s start=0.3s scripts app_started_callback=0.2s checkpoint=3.4s)

**gradio call: RuntimeError**
╭───── Traceback (most recent call last) ──────╮
│ /home/hugo/automatic/modules/call_queue.py:58 in f 
│    57 │   │   │   │   pr.enable() 
│ ❱  58 │   │   │   res = list(func(*args, **kwargs)) 
│    59 │   │   │   if shared.cmd_opts.profile:
│ /home/hugo/automatic/modules/call_queue.py:38 in f
│    37 │   │   │   try: 
│ ❱  38 │   │   │   │   res = func(*args, **kwargs) 
│    39 │   │   │   finally:
│             ... 20 frames hidden ...       
│ /home/hugo/automatic/venv/lib/python3.10/site-packages/torch/nn/modules/normalization.py:190 in forward                                                                                                                                                                                                                               
│   189 │   def forward(self, input: Tensor) -> Tensor: 
│ ❱ 190 │   │   returnF.layer_norm(
│   191 │   │   │   input, self.normalized_shape, self.weight, self.bias, self.eps)  
│ /home/hugo/automatic/venv/lib/python3.10/site-packages/torch/nn/functional.py:2515 in layer_norm                                                                                                                                                                                                                                                     
│   2514 │   │   )  
│ ❱ 2515 │   return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.c                                                                                                      
│   2516
**RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'**

**Comment by phaylali** [comment]
I just switched to linux to try if it's gonna work better, and it is exactly as [hugoddjing](https://github.com/hugoddjing) said

**Comment by TheBlueSky** [comment]
I have not changed anything on my system, as far as I can tell, but I am able to generate images through the UI and the API.

A couple of days ago I decided to give it another shot, updated the code, and generated an image using a custom model I downloaded. It worked, so I thought that the issue with the Stable Diffusion 1.5 model, but then I generated an image using it and it worked too.

So, now I do not know what the issue was.

The images I generated through the UI and the API used for example `revAnimated_v122` and `v1-5-pruned-emaonly`, and the VAE `vae-ft-mse-840000-ema-pruned`.

**Comment by wbh1129** [comment]
I can report success as well. However, it memory leaks like crazy. On Auto's repo it would only use ~7gb of RAM. Here it starts at ~7gb but then increases to ~14gb once I generate anything.

I am on Linux. I tried `LD_PRELOAD`ing tcmalloc but it wasn't any help. However, I did notice this in the log:

`INFO Torch 2.0.0+cu117`

Looking into it further, this doesn't seem correct: https://github.com/vladmandic/automatic/blob/3c7273e17af6fe1e9741166dda8a3f3819f4fec2/installer.py#L214

[Pytorch suggests](https://pytorch.org/get-started/locally/): `torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu`

I will try installing the CPU version of Pytorch and see if it helps any.

Also shouldn't this check to make sure the platform isn't Linux? https://github.com/vladmandic/automatic/blob/3c7273e17af6fe1e9741166dda8a3f3819f4fec2/installer.py#L208

**Comment by vladmandic** [comment]
Can you run with `--debug`? It will print memory stats on each completion, best way to check for memory leaks.

**Comment by wbh1129** [comment]
> Can you run with `--debug`? It will print memory stats on each completion, best way to check for memory leaks.

Sure, this is all I got:

`INFO Processed: 1 Memory: {'ram': {'used': 5.69, 'total': 15.6}} txt`

I also installed `torch=2.0.0+cpu` but it didn't help.

**Comment by vladmandic** [comment]
It prints that on end of every generate, so you can try and see if there are leaks.

**Comment by wbh1129** [comment]
```
Processed: 1 Memory: {'ram': {'used': 5.05, 'total': 15.6}} txt
Processed: 1 Memory: {'ram': {'used': 6.55, 'total': 15.6}} txt
Processed: 1 Memory: {'ram': {'used': 6.55, 'total': 15.6}} txt
Processed: 1 Memory: {'ram': {'used': 6.47, 'total': 15.6}} txt
Processed: 1 Memory: {'ram': {'used': 6.24, 'total': 15.6}} txt
```

However, I measured it using 11.5GB by comparing RAM usage before/after closing the webui.

**Comment by wbh1129** [comment]
Disabling all extensions fixes it. Trying to narrow it down to see which extension is causing problems.

**Comment by wbh1129** [comment]
Okay, finally narrowed it down. It's both `Lora` and `a1111-sd-webui-lycoris`, each seems to contribute to about half of the waste.

**Comment by vladmandic** [comment]
oh, wow. and your prompt does not reference lora or lyco?

**Comment by wbh1129** [comment]
> oh, wow. and your prompt does not reference lora or lyco?

No not at all. I was just prompting "test"

>can you share actual data? size of the leak will help me to find it.

In total, 7.1gb leaked according to memray. These appear to be the offenders:

https://github.com/vladmandic/automatic/blob/4dc5941912cc78bbe986a0c1fcdba6d7b194ab4d/extensions-builtin/Lora/lora.py#L275

https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/blob/ce584a0ff863de98233ee135dcc17f2fb44703c3/lycoris.py#L671

**Comment by vladmandic** [comment]
that is very useful.

> In total, 7.1gb leaked according to memray. These appear to be the offenders:

i meant per generation, not total since total can be anything depending on the number of operations performed.

btw, lycoris leaks in the same way as lora as it started as lora code, so i guess it inherited its problems as well :(

**Comment by wbh1129** [comment]
> > In total, 7.1gb leaked according to memray. These appear to be the offenders:
> 
> i meant per generation, not total since total can be anything depending on the number of operations performed.

I mean it allocates 7.1gb once and then never frees it. It doesn't increase with the generations.

**Comment by vladmandic** [comment]
7.1gb is red herring, that is torch pre-allocating maximum memory that may be needed for a model. its not actually leaking or even being fully used as model with use up-to that ammount.

but there is a memory leak and your `memray` nudged me in a right direction for sure!
> 390.238MB (0.71 %) lora_apply_weights  /home/vlado/dev/automatic/extensions-builtin/a1111-sd-webui-lycoris/../../extensions-builtin/Lora/lora.py:275
> 390.238MB (0.71 %) lyco_apply_weights  /home/vlado/dev/automatic/extensions-builtin/a1111-sd-webui-lycoris/lycoris.py:671

i've fixed it in `lora` module as that is built-in and and submitted a pr to be fixed in `lyco` module:
<https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/pull/20>
(if i made changes to `lyco` directly, it would get out-of-sync and future updates would not be possible)

**Comment by wbh1129** [comment]
Sweet, thank you for looking into this!

**Comment by vladmandic** [comment]
difference +/-10% are ok. difference 8min vs 1min are not ok, that is not a difference between linux and windows, that indicates that its using a completely different backend. and i've looked in your previous posts, you have AMD GPU and ROCm only exists on linux - AMD did not yet release a Windows version. so on Linux, you're actually using your GPU (clearly seen in console startup messages near very top) and on Windows you're basically using CPU only.

you said you don't have GPU, but Ryzen 5600G has integrated APU - its a low-end AMD GPU, but its still a GPU

```log
20:23:46-510748 INFO     AMD toolkit detected                            
20:23:47-352610 INFO     Torch 2.0.0+rocm5.4.2                           
20:23:48-240964 INFO     Torch backend: AMD ROCm HIP 5.4.22803-474e8620  
20:23:48-242409 INFO     Torch detected GPU: AMD Radeon Graphics VRAM 512 Arch (10, 3) Cores 3   
```

**Comment by phaylali** [comment]
> difference +/-10% are ok. difference 8min vs 1min are not ok, that is not a difference between linux and windows, that indicates that its using a completely different backend. and i've looked in your previous posts, you have AMD GPU and ROCm only exists on linux - AMD did not yet release a Windows version. so on Linux, you're actually using your GPU (clearly seen in console startup messages near very top) and on Windows you're basically using CPU only.
> 
> you said you don't have GPU, but Ryzen 5600G has integrated APU - its a low-end AMD GPU, but its still a GPU
> 
> ```log
> 20:23:46-510748 INFO     AMD toolkit detected                            
> 20:23:47-352610 INFO     Torch 2.0.0+rocm5.4.2                           
> 20:23:48-240964 INFO     Torch backend: AMD ROCm HIP 5.4.22803-474e8620  
> 20:23:48-242409 INFO     Torch detected GPU: AMD Radeon Graphics VRAM 512 Arch (10, 3) Cores 3   
> ```
> 

Yes I definitely see ROCm there in the console everytime i run it , torch+rocm , so I understand from what you say is that on windows it is using 0 vram from the APU , only the cpu , whereas in linux it is using the 512mb of the ryzen 5600G and probably being helped by the 16G of swap I have and 16G of ram , which explains the massive speed difference,  (even tho i use the flag use-cpu all in the launch command?) But i guess it's gonna ignore my command and search for a GPU or an integrated graphics anyways and prioritize that , so for an AMD APU user , especially in my case , linux is a much better option for now until I get the GPU (I'm eying the rtx 3060 12G , do you think it's the best gpu for ai considering future proofing and price per value?)
