### ISSUE TITLE
[Issue]: elevation request (video to video, controlnet)

### ISSUE THREAD

**Issue by spoonsc2** [vladmandic/automatic#3448]
### Issue Description

Using Control, video2video, faceswap - it generates but then hangs requesting elevation (presumably to previewer, even though I turn previewer off) - as below

### Version Platform Description

Windows, AMD 7900xtx, 7800x3d

### Relevant log output

```shell
08:03:04-097517 INFO     Save: image="outputs\control\00227-realisticVisionV60B1_v51HyperVAE-.png" type=PNG width=240
                         height=256 size=87131
08:03:04-138927 INFO     Control: pipeline units=0 process=0 time=503.82 init=0.00 proc=499.38 ctrl=4.44 outputs=114
08:03:04-207216 INFO     Save video: file="outputs\video\00008-realisticVisionV60B1_v51HyperVAE-.mp4" frames=114
                         duration=5 fourcc=mp4v size=262188
Traceback (most recent call last):
  File "E:\SD Next\automatic\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\SD Next\automatic\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\SD Next\automatic\venv\lib\site-packages\gradio\blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\SD Next\automatic\venv\lib\site-packages\gradio\blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "E:\SD Next\automatic\venv\lib\site-packages\gradio\components\video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "E:\SD Next\automatic\venv\lib\site-packages\gradio\components\video.py", line 332, in _format_video
    and not processing_utils.video_is_playable(video)
  File "E:\SD Next\automatic\venv\lib\site-packages\gradio\processing_utils.py", line 514, in video_is_playable
    output = probe.run(stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "E:\SD Next\automatic\venv\lib\site-packages\ffmpy.py", line 101, in run
    self.process = subprocess.Popen(
  File "C:\Program Files\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 740] The requested operation requires elevation
08:04:00-271596 DEBUG    Server: alive=True jobs=1 requests=1397 uptime=1139 memory=2.61/30.99 backend=Backend.DIFFUSERS
                         state=idle
```

### Backend

Original

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
sdnext creates a video and then it returns it to `gradio` to display in ui.
gradio internally uses `ffmpy` for video processing and it uses `ffprobe` utility (that ships with ffmpeg).
elevation request happens because windows detects that either ownership or permissions of ffmpeg/ffprobe are not the same user - so its really up to you to make sure that ffmpeg/ffprobe are installed correctly, by the same user that runs sdnext and in path.
