### ISSUE TITLE
[Extension]: Controlnet extension crashes SD.Next when installed and backend="original"

### ISSUE THREAD

**Issue by anothertal3** [vladmandic/automatic#3477]
### Issue Description

I'm trying to switch from an older version of SD.Next to the most recent one. To keep my current workflow alive I need the "original" backend and Controlnet (I'm accessing it via API).

During the discussion in https://github.com/vladmandic/automatic/discussions/3397 I noticed that application crashes and was able to pinpoint it onto the controlnet extension.

It's pretty easy to reproduce:
1. Ensure that control net is not installed
2. Switch SD.Next backend to "original"
3. Restart application -> all is fine
4. Install "https://github.com/Mikubill/sd-webui-controlnet" via manual install (is in list as well, but this is more explicit)

Reverting is then only possible by manually editing the `config.json`.

The log shows the following entry on start:
```
12:30:00-983678 INFO     Extension: script='extensions\sd-webui-controlnet\scripts\api.py' ControlNet preprocessor
                         location: f:\sd.next\extensions\sd-webui-controlnet\annotator\downloads
12:30:01-095392 INFO     Extension: script='extensions\sd-webui-controlnet\scripts\controlnet.py' Warning: ControlNet
                         failed to load SGM - will use LDM instead.
12:30:01-105543 INFO     Extension: script='extensions\sd-webui-controlnet\scripts\hook.py' Warning: ControlNet failed
                         to load SGM - will use LDM instead.
12:30:01-147262 INFO     UI theme: type=Standard name="black-orange"
12:30:03-545151 ERROR    Calling script: extensions\sd-webui-controlnet\scripts\controlnet.py/ui: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ f:\sd.next\modules\scripts.py:295 in wrap_call                                                     │
│                                                                                                                      │
│   294 │   try:                                                                                                       │
│ ❱ 295 │   │   res = func(*args, **kwargs)                                                                            │
│   296 │   │   return res                                                                                             │
│                                                                                                                      │
│ f:\sd.next\extensions\sd-webui-controlnet\scripts\controlnet.py:307 in ui                          │
│                                                                                                                      │
│    306 │   │   │   │   │   │   │   │   │   │   elem_classes=['cnet-unit-tab']):                                      │
│ ❱  307 │   │   │   │   │   │   │   │   group, state = self.uigroup(f"ControlNet-{i}", is_img2img, elem_id_tabname, p │
│    308 │   │   │   │   │   │   │   │   ui_groups.append(group)                                                       │
│                                                                                                                      │
│ f:\sd.next\extensions\sd-webui-controlnet\scripts\controlnet.py:246 in uigroup                     │
│                                                                                                                      │
│    245 │   │   group.render(tabname, elem_id_tabname, is_img2img)                                                    │
│ ❱  246 │   │   group.register_callbacks(is_img2img)                                                                  │
│    247 │   │   unit_state = group.render_and_register_unit(tabname, is_img2img)                                      │
│                                                                                                                      │
│ f:\sd.next\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:958 in regi │
│                                                                                                                      │
│    957 │   │   """                                                                                                   │
│ ❱  958 │   │   self.register_send_dimensions(is_img2img)                                                             │
│    959 │   │   self.register_webcam_toggle()                                                                         │
│                                                                                                                      │
│ f:\sd.next\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:533 in regi │
│                                                                                                                      │
│    532 │   │   )                                                                                                     │
│ ❱  533 │   │   self.send_dimen_button.click(                                                                         │
│    534 │   │   │   fn=send_dimensions,                                                                               │
│                                                                                                                      │
│ f:\sd.next\venv\lib\site-packages\gradio\events.py:174 in __call__                                 │
│                                                                                                                      │
│   173 │   │                                                                                                          │
│ ❱ 174 │   │   dep, dep_index = self.trigger.set_event_trigger(                                                       │
│   175 │   │   │   self.event_name,                                                                                   │
│                                                                                                                      │
│ f:\sd.next\venv\lib\site-packages\gradio\blocks.py:287 in set_event_trigger                        │
│                                                                                                                      │
│    286 │   │   │   "inputs": [block._id for block in inputs],                                                        │
│ ❱  287 │   │   │   "outputs": [block._id for block in outputs],                                                      │
│    288 │   │   │   "backend_fn": fn is not None,                                                                     │
│                                                                                                                      │
│ f:\sd.next\venv\lib\site-packages\gradio\blocks.py:287 in <listcomp>                               │
│                                                                                                                      │
│    286 │   │   │   "inputs": [block._id for block in inputs],                                                        │
│ ❱  287 │   │   │   "outputs": [block._id for block in outputs],                                                      │
│    288 │   │   │   "backend_fn": fn is not None,                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute '_id'
```

When trying to access the UI via browser the following is displayed:
```
12:30:42-744300 INFO     MOTD: N/A
Traceback (most recent call last):
  File "f:\sd.next\venv\lib\site-packages\gradio\routes.py", line 507, in predict
    output = await route_utils.call_process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "f:\sd.next\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "f:\sd.next\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "f:\sd.next\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
TypeError: update_token_counter() missing 2 required positional arguments: 'text' and 'steps'
Traceback (most recent call last):
  File "f:\sd.next\venv\lib\site-packages\gradio\routes.py", line 507, in predict
    output = await route_utils.call_process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "f:\sd.next\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "f:\sd.next\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "f:\sd.next\modules\ui.py", line 483, in reference_submit
    if '@' not in model: # diffusers
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "f:\sd.next\venv\lib\site-packages\gradio\routes.py", line 507, in predict
    output = await route_utils.call_process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "f:\sd.next\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "f:\sd.next\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "f:\sd.next\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 198, in f
    raise Exception("Invalid call")
Exception: Invalid call
12:30:44-377865 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
```

Afterwards the loading indicator keeps spinning and the UI is not loading.

### Version Platform Description

```
12:29:36-302411 INFO     Starting SD.Next
12:29:36-304409 INFO     Logger: file="f:\sd.next\sdnext.log" level=INFO size=22227919 mode=append
12:29:36-305455 INFO     Python version=3.10.11 platform=Windows
                         bin="f:\sd.next\venv\Scripts\python.exe"
                         venv="f:\sd.next\venv"
12:29:36-429296 INFO     Version: app=sd.next updated=2024-09-13 hash=e7ec07f9 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
12:29:36-848274 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
12:29:36-849348 INFO     HF cache folder: C:\Users\user\.cache\huggingface\hub
12:29:36-858094 INFO     nVidia CUDA toolkit detected: nvidia-smi present
12:29:36-954850 INFO     Verifying requirements
12:29:36-957854 WARNING  Package version mismatch: timm 0.6.7 required 0.9.16
12:29:36-958854 INFO     Install: package="timm==0.9.16" mode=pip
12:29:40-081092 INFO     Verifying packages
12:29:40-082098 INFO     Startup: standard
12:29:40-082098 INFO     Verifying submodules
12:29:52-615787 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-rembg', 'a1111-sd-webui-tagcomplete',
                         'adetailer', 'sd-dynamic-prompts', 'sd-webui-controlnet']
```

### URL link of the extension

https://github.com/Mikubill/sd-webui-controlnet

### URL link of the issue reported in the extension repository

https://github.com/Mikubill/sd-webui-controlnet/issues/3060

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
just fixed in latest dev branch.

**Comment by anothertal3** [comment]
Insane reaction time as always. Thank you very much, looking forward to the release.

**Comment by vladmandic** [comment]
likely in less than a week.

**Comment by anothertal3** [comment]
I noticed the one or two new releases and the behavior remained unchanged for now. 

This is expected, I assume? The code has intentionally not been merged yet, correct?

**Comment by vladmandic** [comment]
no, not yet, slight delay, but likely in the next day or two.
