### ISSUE TITLE
[Issue]: ModuleNotFoundError

### ISSUE THREAD

**Issue by fabiobtex** [vladmandic/automatic#348]
Installed yesterday, it was working normally, today has an update. Doesn't start anymore, no extra extensions installed  

### Issue Description

venv "D:\Vlad\automatic\venv\Scripts\Python.exe"
14:10:20-543359 INFO     Python 3.10.6 on Windows
14:10:20-587873 INFO     No changes detected: quick launch active
14:10:20-589874 INFO     Setting environment tuning
14:10:20-590873 INFO     Server arguments: []
Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\Vlad\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "D:\Vlad\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "D:\Vlad\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "D:\Vlad\automatic\launch.py", line 99, in <module>
    import webui
  File "D:\Vlad\automatic\webui.py", line 21, in <module>
    from modules import import_hook # pylint: disable=W0611,C0411,C0412
  File "D:\Vlad\automatic\modules\import_hook.py", line 2, in <module>
    from modules.shared import opts
  File "D:\Vlad\automatic\modules\shared.py", line 230, in <module>
    default_checkpoint = list_checkpoint_tiles()[0] if len(list_checkpoint_tiles()) > 0 else "model.ckpt"
  File "D:\Vlad\automatic\modules\shared.py", line 192, in list_checkpoint_tiles
    import modules.sd_models # pylint: disable=W0621
  File "D:\Vlad\automatic\modules\sd_models.py", line 19, in <module>
    import tomesd
ModuleNotFoundError: No module named 'tomesd'

**Comment by Panchvzluck** [comment]
It should have installed tomesd when installing the requeriments.

You can install tomesd manually in the meanwhile with

.\venv\Scripts\activate
pip install tomesd

**Comment by AlUlkesh** [comment]
Same thing just happened to me.

**Comment by AlUlkesh** [comment]
I wonder if the empty line is a problem?
https://github.com/vladmandic/automatic/blob/57204b3d702b7586c789dbad1e1e3bd85746d81e/requirements.txt#L51-L53

**Comment by vladmandic** [comment]
modefied installer, hopefully its fixed.
