### ISSUE TITLE
[Issue]: Prompts do not carry over when sending image to Control

### ISSUE THREAD

**Issue by Gushousekai195** [vladmandic/automatic#3509]
### Issue Description

When I click the -> Control button to send an generated image to the Control tab, the Prompt and Negative Prompt do not carry over. The boxes just say Error.

### Version Platform Description

15:58:13-331835 INFO     Starting SD.Next
15:58:13-335824 INFO     Logger: file="D:\AI\SDNext\sdnext.log" level=INFO size=132994 mode=append
15:58:13-337819 INFO     Python: version=3.11.5 platform=Windows bin="D:\AI\SDNext\venv\Scripts\python.exe"
                         venv="D:\AI\SDNext\venv"
15:58:13-478446 INFO     Version: app=sd.next updated=2024-10-23 hash=0d332ca7 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
15:58:14-063882 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.11.5
15:58:14-088910 INFO     CUDA: nVidia toolkit detected
15:58:14-232162 INFO     Verifying requirements
15:58:14-237149 INFO     Verifying packages
15:58:14-270061 INFO     Extensions: disabled=[]
15:58:14-272055 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\AI\SDNext\venv\Lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\SDNext\venv\Lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\SDNext\venv\Lib\site-packages\gradio\blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\SDNext\venv\Lib\site-packages\gradio\blocks.py", line 1303, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\SDNext\venv\Lib\site-packages\gradio\blocks.py", line 1278, in validate_outputs
    raise ValueError(
ValueError: An event handler didn't receive enough output values (needed: 5, received: 4).
Wanted outputs:
    [textbox, textbox, slider, number, checkbox]
Received outputs:
    ["Prompt", "Negative Prompt", 50, 2117637511.0]
```

### Backend

Original

### UI

Standard

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
reproduced and fixed in dev branch, will refresh master soon.
