### ISSUE TITLE
[Extension]: Depthmap script not installing.

### ISSUE THREAD

**Issue by bbecausereasonss** [vladmandic/automatic#3559]
### Issue Description

Trying to install the Depthmap sacript extension.

Error:

2024-11-01 20:36:39,114 | sd | DEBUG | installer | Extension installer: C:\Users\xxxx\Deep\automatic\extensions\stable-diffusion-webui-depthmap-script\install.py
2024-11-01 20:37:16,101 | sd | ERROR | installer | Extension installer error: C:\Users\xxxx\Deep\automatic\extensions\stable-diffusion-webui-depthmap-script\install.py
2024-11-01 20:37:16,102 | sd | DEBUG | installer | 
Package: ['packaging'] 'NoneType' object has no attribute 'working_set'

Package: ['timm'] 'NoneType' object has no attribute 'working_set'

Package: ['matplotlib'] 'NoneType' object has no attribute 'working_set'

Package: ['trimesh'] 'NoneType' object has no attribute 'working_set'

Package: ['numba'] 'NoneType' object has no attribute 'working_set'

Package: ['vispy'] 'NoneType' object has no attribute 'working_set'

Package: ['rembg'] 'NoneType' object has no attribute 'working_set'

Package: ['moviepy'] 'NoneType' object has no attribute 'working_set'

Package: ['transforms3d'] 'NoneType' object has no attribute 'working_set'

Package: ['diffusers'] 'NoneType' object has no attribute 'working_set'

Package: ['imageio'] 'NoneType' object has no attribute 'working_set'

Package: ['networkx'] 'NoneType' object has no attribute 'working_set'

Traceback (most recent call last):

  File "C:\Users\xxxx\Deep\automatic\extensions\stable-diffusion-webui-depthmap-script\install.py", line 55, in <module>

    launch.run_pip('install install "networkx==2.5"', "networkx requirement for depthmap script")

  File "C:\Users\xxxx\Deep\automatic\launch.py", line 123, in run_pip

    return run(f'"{sys.executable}" -m pip {pkg} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")

  File "C:\Users\xxxx\Deep\automatic\launch.py", line 86, in run

    raise RuntimeError(f"""{errdesc or 'Error running command'}: {command} code: {result.returncode}

RuntimeError: Couldn't install networkx requirement for depthmap script: "C:\Users\xxxx\Deep\automatic\venv\Scripts\python.exe" -m pip install install "networkx==2.5" --prefer-binary code: 1

ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install
[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: C:\Users\xxxx\Deep\automatic\venv\Scripts\python.exe -m pip install --upgrade pip

2024-11-01 20:37:16,227 | sd | INFO | installer | Extension installed packages: stable-diffusion-webui-depthmap-script ['decorator==4.4.2', 'freetype-py==2.5.1', 'hsluv==5.0.4', 'imageio-ffmpeg==0.5.1', 'moviepy==1.0.2', 'proglog==0.1.10', 'transforms3d==0.4.2', 'trimesh==4.5.1', 'vispy==0.14.3']
2024-11-01 20:37:16,356 | sd | DEBUG | installer | Extension installer: C:\Users\xxxx\Deep\automatic\extensions\uddetailer\install.py
2024-11-01 20:43:24,169 | sd | INFO | installer | Extension installed packages: uddetailer ['aliyun-python-sdk-core==2.16.0', 'aliyun-python-sdk-kms==2.16.5', 'cffi==1.17.1', 'crcmod==1.7', 'cryptography==43.0.3', 'filelock==3.14.0', 'jax==0.4.35', 'jaxlib==0.4.35', 'jmespath==0.10.0', 'mediapipe==0.10.18', 'ml-dtypes==0.5.0', 'mmcv==2.1.0', 'mmdet==3.3.0', 'mmengine==0.8.5', 'mmyolo==0.6.0', 'model-index==0.1.11', 'opencv-contrib-python==4.10.0.84', 'opendatalab==0.0.10', 'openmim==0.3.9', 'openxlab==0.1.2', 'opt-einsum==3.4.0', 'ordered-set==4.1.0', 'oss2==2.17.0', 'prettytable==3.12.0', 'pycocotools==2.0.8', 'pycparser==2.22', 'pycryptodome==3.21.0', 'pytz==2023.4', 'pywin32==308', 'requests==2.28.2', 'rich==13.4.2', 'setuptools==60.2.0', 'shapely==2.0.6', 'sounddevice==0.5.1', 'tabulate==0.9.0', 'termcolor==2.5.0', 'terminaltables==3.1.10', 'tqdm==4.65.2']
2024-11-01 20:43:24,172 | sd | INFO | installer | Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg', '--sd-webui-ar-plusplus', 'Automatic1111-Geeky-Remb', 'extra-network-side-panel-for-a1111', 'sd-civitai-browser-plus', 'sd-webui-cardmaster', 'sd-webui-incantations', 'sd-webui-udav2', 'Stable-Diffusion-Webui-Civitai-Helper', 'stable-diffusion-webui-depthmap-script', 'stupid-nsfw-card-blur-a1111', 'uddetailer']

### Version Platform Description

Win11

### URL link of the extension

https://github.com/thygate/stable-diffusion-webui-depthmap-script

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
since extension author doesn't seem like he's actively maintaining it (large number of open issues and no updates for months), i cannot keep this opened here.
