### ISSUE TITLE
[Issue]: Object not found when using merge extension.

### ISSUE THREAD

**Issue by wkdtjs** [vladmandic/automatic#364]
### Issue Description

https://github.com/ashen-sensored/sd-webui-runtime-block-merge.git

This program or

https://github.com/bbc-mc/sdweb-merge-block-weighted-gui.git

If use this program

Traceback (most recent call last):
  File "D:\vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\vladmandic\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\vladmandic\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\vladmandic\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\vladmandic\automatic\extensions\sd-webui-runtime-block-merge\scripts\runtime_block_merge.py", line 475, in handle_modelB_load
    load_flag = shared.UNetBManager.load_modelB(modelB, force_cpu_checkbox, slALL)
AttributeError: 'NoneType' object has no attribute 'load_modelB'

The above message appears.

I've been looking for 2 hours to see where the problem occurs, but I don't know.

### Version Platform Description

latest version, windows 11, rtx 3060 ti

**Comment by vladmandic** [comment]
have you solved the issue? i see you opened and closed it.
