### ISSUE TITLE
[Issue]: Will not start after update

### ISSUE THREAD

**Issue by usigg3** [vladmandic/automatic#379]
### Issue Description

Restarted  the application today. Has been working fine last week. I don't even get a version number...
Today I get:
venv "E:\vwebui\automatic\venv\Scripts\Python.exe"
16:49:34-533717 INFO     Python 3.10.6 on Windows
16:49:34-601253 INFO     No changes detected: quick launch active
16:49:34-602250 INFO     Setting environment tuning
16:49:34-602622 INFO     Server arguments: []
Error in sys.excepthook:
Traceback (most recent call last):
  File "E:\vwebui\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "E:\vwebui\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "E:\vwebui\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "E:\vwebui\automatic\launch.py", line 99, in <module>
    import webui
  File "E:\vwebui\automatic\webui.py", line 21, in <module>
    from modules import import_hook # pylint: disable=W0611,C0411,C0412
  File "E:\vwebui\automatic\modules\import_hook.py", line 2, in <module>
    from modules.shared import opts
  File "E:\vwebui\automatic\modules\shared.py", line 232, in <module>
    default_checkpoint = list_checkpoint_tiles()[0] if len(list_checkpoint_tiles()) > 0 else "model.ckpt"
  File "E:\vwebui\automatic\modules\shared.py", line 192, in list_checkpoint_tiles
    import modules.sd_models # pylint: disable=W0621
  File "E:\vwebui\automatic\modules\sd_models.py", line 19, in <module>
    import tomesd
ModuleNotFoundError: No module named 'tomesd'

### Version Platform Description

Windows 11, RTX 2060 6 GB. It does not show the version on upstart, see above. If it helps it was updated about an hour ago...

**Comment by vladmandic** [comment]
it says, `16:49:34-601253 INFO No changes detected: quick launch active`, but `requirements.txt` has been updated.
can you check your `requirements.txt` contains `tomesd`?
try forcing `webui --upgrade` so requirements are checked/parsed and not skipped.

**Comment by vladmandic** [comment]
i've just moved requirements check to be absolute regardless of quick or not. should fix this issue.

**Comment by usigg3** [comment]
Thanks, I'll try it, not at my PC right now.

Den lör 22 apr. 2023 17:31Vladimir Mandic ***@***.***> skrev:

**Comment by usigg3** [comment]
Now it works :-)
Had to do a manual git pull since it claimed no changes detected... Strange...
