### ISSUE TITLE
[Issue]: AttributeError: 'NoneType' object has no attribute 'process_texts'

### ISSUE THREAD

**Issue by biship** [vladmandic/automatic#382]
### Issue Description

I did not get this error yesterday. 
I get this error today after git pull to: Version: f2014ecf Sat Apr 22 11:30:55 2023 -0400
Windows 11 x64

 ```
PS D:\Downloads\apps\automatic> ./webui.bat
venv "D:\Downloads\apps\automatic\venv\Scripts\Python.exe"
11:42:57-503622 INFO     Python 3.10.10 on Windows
11:42:57-573436 INFO     Version: f2014ecf Sat Apr 22 11:30:55 2023 -0400
11:42:58-029904 INFO     Updating Wiki
11:42:59-307773 INFO     nVidia toolkit detected
11:43:05-800308 INFO     Torch 2.0.0+cu118
11:43:05-829407 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8800
11:43:05-832419 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82
11:43:05-834942 INFO     Installing requirements
11:43:05-941282 INFO     Running setup
11:43:05-942280 INFO     Installing packages
11:43:05-943286 INFO     Installing repositories
11:43:06-192067 INFO     Installing submodules
11:43:10-078161 INFO     Updating submodules
11:43:21-570776 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
11:43:55-482394 INFO     Extensions enabled: ['Stable-Diffusion-Webui-Civitai-Helper', 'stable-diffusion-webui-wildcards']
11:43:56-712148 INFO     Setting environment tuning
11:43:56-718189 INFO     Running extension preloading
11:43:56-719697 INFO     Server arguments: []
Unloading xFormers
Available models: D:\Downloads\apps\stable-diffusion-webui\models\Stable-diffusion 58
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\Downloads\apps\automatic\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Loading theme: gradio/default
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Loading weights: D:\Downloads\apps\stable-diffusion-webui\models\Stable-diffusion\Degenerate_chilloutV1.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/5.7 GB -:--:--
Creating model from config: D:\Downloads\apps\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Traceback (most recent call last):
  File "D:\Downloads\apps\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Downloads\apps\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\Downloads\apps\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Downloads\apps\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Downloads\apps\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Downloads\apps\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Downloads\apps\automatic\modules\call_queue.py", line 16, in f
    res = func(*args, **kwargs)
  File "D:\Downloads\apps\automatic\modules\ui.py", line 235, in update_token_counter
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "D:\Downloads\apps\automatic\modules\ui.py", line 235, in <listcomp>
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "D:\Downloads\apps\automatic\modules\sd_hijack.py", line 235, in get_prompt_lengths
    _, token_count = self.clip.process_texts([text])
AttributeError: 'NoneType' object has no attribute 'process_texts'
Loading weights: D:\Downloads\apps\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/334.7 MB -:--:--
Applying scaled dot product cross attention optimization
Embeddings loaded:  (0)
Model loaded in 19.7s (load=0.6s create=0.4s apply=14.1s vae=1.4s move=0.7s embeddings=2.4s)
Startup time: 45.2s (torch=6.6s gradio=4.4s libraries=3.0s models=0.9s codeformer=0.3s gfpgan=0.1s scripts=6.1s ui=3.5s start=0.2s scripts app_started_callback=0.1s checkpoint=20.1s)
 ```

**Comment by biship** [comment]
May be related to my Lora's not being found.
Settings:
````Path to directory with Lora network(s): D:\Downloads\apps\stable-diffusion-webui\models\Lora````
(all Loras are in that folder).
However, in Extra networks (Lora Tab) in the "From Text" tab, they are not found:
````
Nothing here. Add some content to the following directories:
D:\Downloads\apps\stable-diffusion-webui\models\Lora````

**Comment by vladmandic** [comment]
no, its not related to lora.
this is almost like you tried to type something in the prompt before model was fully loaded/ready.

> AttributeError: 'NoneType' object has no attribute 'process_texts'

can you confirm your browser is closed and this happens on server start alone?

**Comment by biship** [comment]
Yes, my bad. I was too eager to generate something. 
It works fine now when I wait until "Startup time" is displayed.
This issue is solved - thanks!

Want me to open a new issue for the Lora problem?

**Comment by biship** [comment]
um never mind. The loras are found now after a restart. Weird.
