### ISSUE TITLE
[Issue]: Restarting UI duplicates upscalers in upscaler dropdown

### ISSUE THREAD

**Issue by SoraEnkai** [vladmandic/automatic#388]
### Issue Description

Version: 4cb46d54 Sat Apr 22 13:33:11 2023 -0400
Started happening today, a few commits ago, i think.

This was tested again on freshly cloning the repo and installing it, no extra changes, just applying config, then clicking `Restart UI`
![image](https://user-images.githubusercontent.com/39128897/233801270-786bfa50-699c-41d5-b624-99b5bcd28b89.png)

Clicking `Restart UI` duplicates it again.

Error in console:
```Traceback (most recent call last):
  File "D:\AI_STUFF\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI_STUFF\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\AI_STUFF\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI_STUFF\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI_STUFF\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
WebSocket closed (ignore asyncio.exceptions.CancelledError)

### Version Platform Description

Windows 11, Chrome, latest version.

**Comment by vladmandic** [comment]
Yes. Known. Tracking all such issues due to server restart from UI separately. Closing this issue.

**Comment by SoraEnkai** [comment]
Thanks, my bad didn't see it in issues, but i see that it's discussions instead, will be following that.
