### ISSUE TITLE
[Issue]: After changing a setting and restarting the UI, some functions cause the UI to crash

### ISSUE THREAD

**Issue by Nrgte** [vladmandic/automatic#419]
### Issue Description

I'm running the latest version from HEAD.

So far functions that have been affected:

- Read generation parameters
Error message:
Traceback (most recent call last):
  File "F:\Projects\SDvladmatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Projects\SDvladmatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\Projects\SDvladmatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 331

- Process image tab -> Insert an image and click on text.
Error message: Same as above.

So far only restarting the web ui seems to solve the issue. Otherwise the UI is completly frozen and unresponsive.

**Comment by vladmandic** [comment]
see #224
