### ISSUE TITLE
[Issue]: Using Image Browser to send images crashes the WEBUI

### ISSUE THREAD

**Issue by nasiri** [vladmandic/automatic#444]
### Issue Description

I get following error when trying to send images from the Image Viewer:
```
caught (in promise) TypeError: Cannot set properties of undefined (setting 'props')
    at _t (Blocks.svelte:255:8)
    at no (Blocks.svelte:370:4)
    at Ls.e.$$.update (Blocks.svelte:357:5)
    at Ar (index.37b24c07.js:4:1810)
    at Xt (index.37b24c07.js:4:1560)
```

After that i need to restart the window, otherwise no clicks on any buttons work anymore.

**Comment by nasiri** [comment]
my bad. seemed to be needed to restart the webui.bat
