### ISSUE TITLE
[Issue]: Error when using: Read generation parameters from prompt or last generation if prompt is empty into user interface

### ISSUE THREAD

**Issue by rosenius** [vladmandic/automatic#451]
### Issue Description

When trying to use the button (Read generation parameters from prompt or last generation if prompt is empty into user interface) nothting happens in the UI and an error shows up in the console.

`Traceback (most recent call last):
  File "D:\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 331`

After that error you have to reload the interface otherwise when you generate the live preview will show up but when done the last generation (if any) or the logo will show up.

### Version Platform Description

Version: 5b9187d3 Mon Apr 24 10:30:23 2023 -0400
The error is consistent between Edge and Chrome

**Comment by rosenius** [comment]
The error indeed disappears after a clean restart. Sorry for testing enough and also not reading up before posting my issue.

Thank you for your super quick reply and thanks for all the work you put in to this..

**Comment by StableInfo** [comment]
Hello vlad, whats the difference betwen fresh resart of webUI and server restart from ui? I am not sure I get it. Are server restarts reated to extensions? How do I ensure my UI is "private"? I see the mention of "server" a lot and it kinda bothered me

**Comment by vladmandic** [comment]
Good questions, but why ask here, it's not related at all. And if i answer here, it's going to be burried and nobody will be able to find answers if they search for them.

**Comment by StableInfo** [comment]
Do you recommand me to open a chat post for it? Or another location
