### ISSUE TITLE
[Issue]: An error occurs when using the Merge Block Weighted extension.

### ISSUE THREAD

**Issue by toyxyz** [vladmandic/automatic#461]
### Issue Description

An error occurs when using the Merge Block Weighted extension.

https://github.com/bbc-mc/sdweb-merge-block-weighted-gui

====================================================================
#### Merge Block Weighted ####
  model_0    : PhotoRealistic\Basil_mix_fixed.safetensors
  model_1    : Illustration\pastelmix.safetensors [fa818fcf2c]
  base_alpha : 0
  output_file: G:\SD_Model\Ckpt\bw-merge-PhotoRealistic_Basil_mix_fixed-Illustration_pastelmix-0-half.ckpt
  weights    : 1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1
  skip ids   : 0 : 0:None, 1:Skip, 2:Reset
loading PhotoRealistic\Basil_mix_fixed.safetensors
Traceback (most recent call last):
  File "C:\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\automatic\extensions\sdweb-merge-block-weighted-gui\scripts\mbw\ui_mbw.py", line 172, in onclick_btn_do_merge_block_weighted
    result, ret_message = merge(weights=_weights, model_0=model_A, model_1=model_B, allow_overwrite=chk_allow_overwrite,  File "C:\automatic\extensions\sdweb-merge-block-weighted-gui\scripts\mbw\merge_block_weighted.py", line 54, in merge
    theta_0 = load_model(model_0, device)
  File "C:\automatic\extensions\sdweb-merge-block-weighted-gui\scripts\mbw\merge_block_weighted.py", line 51, in load_model
    return sd_models.read_state_dict(model_file, map_location=_device)
TypeError: read_state_dict() got an unexpected keyword argument 'map_location'

### Version Platform Description

window 10, edge
Version: 85798f63 Mon Apr 24 12:34:49 2023 -0400

**Comment by vladmandic** [comment]
extension [sdweb-merge-block-weighted-gui](https://github.com/bbc-mc/sdweb-merge-block-weighted-gui) wants to control where is model loaded (ram or vram), i don't allow that. extension should not have that level of control.
but i'll add param to keep extension happy, its just going to be ignored.
fixed, will post update in ~1h.

**Comment by toyxyz** [comment]
> extension [sdweb-merge-block-weighted-gui](https://github.com/bbc-mc/sdweb-merge-block-weighted-gui) wants to control where is model loaded (ram or vram), i don't allow that. extension should not have that level of control. but i'll add param to keep extension happy, its just going to be ignored. fixed, will post update in ~1h.

Thank you! Now it works fine.
