### ISSUE TITLE
[Issue]: Restarting UI and recalling last prompt makes it unresponsive.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [vladmandic/automatic#497]
### Issue Description

I make extension changes (any) and press the "Apply and Restart UI" button and this error appears in the console window...

```
Traceback (most recent call last):
  File "F:\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "F:\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
WebSocket closed (ignore asyncio.exceptions.CancelledError)
Server shutdown
Server restart
```
Everything appears to continue working until I press the icon to recall the last prompt parameters and nothing happens. The console window then shows:

```
Traceback (most recent call last):
  File "F:\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 331
```

Most things in the UI then stop responding until I do a complete restart of the software. 

### Version Platform Description

Version: 058666f9 Tue Apr 25 14:58:35 2023 -0400
Windows 11
Chrome

The problem is not specific to this version, I just hadn't gotten around to logging the problem for a few days.

**Comment by vladmandic** [comment]
see #224, closing for now.
