### ISSUE TITLE
[Issue]:  Process image (sent to text) error.

### ISSUE THREAD

**Issue by bbecausereasonss** [vladmandic/automatic#508]
### Issue Description

Throwing in an image that was created with a custom ckpt and 2 loras'. Getting PNG info, hitting send to text, UI is freezing /w error in the CLI.

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Startup time: 8.0s (models=0.1s scripts=0.8s vae=0.1s opts onchange=0.2s ui=6.5s start=0.1s scripts
app_started_callback=0.1s)
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\vdrut\Deep\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\xxxx\Deep\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 331
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\xxxx\Deep\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\xxxx\Deep\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 331
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\xxxx\Deep\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\vdrut\Deep\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 331

### Version Platform Description

Latest Commit, Win11, Chrome

**Comment by vladmandic** [comment]
does #224 apply?
