### ISSUE TITLE
[Issue]: Sending image from "Process Image" to txt2img hangs the entire interface

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#552]
### Issue Description

This happens sporadically, and as the title implies, after I process and image to extract its data and send it to text2img, the interface becomes completely unresponsive.

In the console I get the error:

Traceback (most recent call last):
  File "G:\stable-diffusion-vladmandic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-diffusion-vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "G:\stable-diffusion-vladmandic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 356
Traceback (most recent call last):
  File "G:\stable-diffusion-vladmandic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-diffusion-vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "G:\stable-diffusion-vladmandic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 356

### Version Platform Description

Version: 2023-04-26; Browser: Firefox latest

**Comment by vladmandic** [comment]
did you use restart server from ui feature? is the issue present on clean server restart?

**Comment by mark-wd** [comment]
Sure, have a look: [](https://imgur.com/a/mLvD4TU)

If I drag-and-drop into "Process image" and attempt to send it to another area using the buttons below the image, the interface hangs.

Win 11/Firefox

**Comment by craftycreeper** [comment]
I have the same issue, on Windows 10, Chrome.  Example image attached, but it doesn't seem to matter what image I use.

[00021-4159521254-(masterpiece), landscape, mountains, river.zip](https://github.com/vladmandic/automatic/files/11349867/00021-4159521254-.masterpiece.landscape.mountains.river.zip)  (zipped just in case github strips metadata).

I see a similar error in the console window:
```
Traceback (most recent call last):
  File "E:\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 335
```
I also see this in the browser console:
![image](https://user-images.githubusercontent.com/1297013/235055156-8d6b086d-1a5a-4c0b-84e1-36e1828a3cd2.png)

This affects the Text->, Image->, and Inpaint-> buttons on the Process Image tab as well as the Image Browser.  Once the issue kicks in the UI stops responding to any clicks anywhere on the screen.

**Comment by franciscocabral** [comment]
Same error with this image:
![00007-3991565818-Abraham Lincoln working as a Bartender in a Rave_](https://user-images.githubusercontent.com/4059355/235055731-5cdfe846-6efd-4d0f-a3fb-c1517c44ba97.jpg)


![image](https://user-images.githubusercontent.com/4059355/235055748-0330917d-0726-44de-820b-db3682011aa2.png)

**Comment by vladmandic** [comment]
@mark-wd, @franciscocabral, @craftycreeper 
Big majority of `KeyError` errors are related to #224 in general, that's why I've asked if that feature was used prior to your problems or does the problem occur on fresh server start.

**Comment by craftycreeper** [comment]
> @mark-wd, @franciscocabral, @craftycreeper Big majority of `KeyError` errors are related to #224 in general, that's why I've asked if that feature was used prior to your problems or does the problem occur on fresh server start.

Aha.  Yep, it appears that it does not happen for me after a totally fresh start.  I guess I had restarted to load an extension and didn't realize.

**Comment by vladmandic** [comment]
closing for now as its tracked under #224 which is a larger issue. if there are reoccurences of this problem even with fresh server start, let me know and i'll reopen the issue.
