### ISSUE TITLE
[Issue]: Incompatible with the extension sd-webui-bilingual-localization

### ISSUE THREAD

**Issue by bailob** [vladmandic/automatic#563]
### Issue Description

Return error:

```
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/venv/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/automatic/modules/ui.py", line 344, in refresh
    refresh_method()
  File "/automatic/extensions/sd-webui-bilingual-localization/scripts/bilingual_localization_helper.py", line 26, in <lambda>
    shared.opts.add_option("bilingual_localization_file", shared.OptionInfo("None", "Localization file (Please leave `User interface` - `Localization` as None)", gr.Dropdown, lambda: {"choices": ["None"] + list(localization.localizations.keys())}, refresh=lambda: localization.list_localizations(shared.cmd_opts.localizations_dir), section=BL_SECTION))
AttributeError: 'Namespace' object has no attribute 'localizations_dir'
```

Seems automatic didn't have a localizations_dir object. I also didn't find a localization folder in the repo and no original localization option in the Settings - User interface section.  So is the automatic didn't support changing interface localization yet?

**Comment by vladmandic** [comment]
@tkiikt thanks!
closing.
