### ISSUE TITLE
[Issue?]: ValueError: 2 is not in list

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#594]
### Issue Description

When I send an image to img2img, push some settings and start generating to make a new variant, I get this error:

Traceback (most recent call last):
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\gradio\components.py", line 1203, in preprocess
    return self.choices.index(x)
ValueError: 2 is not in list

Any suggestions why this is happening? 😶

### Version Platform Description

Win10, Firefox 106
17:49:54-147631 INFO     Version: 57241e25 Fri Apr 28 09:28:59 2023 -0400

**Comment by vladmandic** [comment]
unfortunately the traceback is too short to show where error originated.
i've just made some blind changes that may help, can you update repo and retry?
if issue still exists, please list exact steps exactly and if possible, upload the image you've used.

**Comment by Woisek** [comment]
OK, will watch it, thanks!

**Comment by vladmandic** [comment]
i've identified one more code path that could in theory lead to this and pushed a fix.
if issue persists, update here and i'll reopen.

**Comment by Woisek** [comment]
Thanks!
