### ISSUE TITLE
[Issue]: error with gradio incorrect javascript handler.

### ISSUE THREAD

**Issue by tigers2020** [vladmandic/automatic#689]
### Issue Description

so, in the morning was fine, and sometime today the performance went down 14it/s to 2it/s.
I thought I did something wrong, and I delete everything and clone again from git, fresh install venv. and I am getting this errors. 
---------------------------------------------
```
`Using VENV: C:\Users\hyper\webUI\Vladmandic\automatic\venv
22:21:47-410786 INFO     Python 3.10.11 on Windows
22:21:47-845048 INFO     Version: eaea88a4 Mon May 1 21:03:08 2023 -0400
22:21:48-206283 INFO     Setting environment tuning
22:21:48-209810 INFO     nVidia CUDA toolkit detected
22:21:50-009153 INFO     Torch 2.0.0+cu118
22:21:50-026938 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
22:21:50-028443 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24563 Arch (8, 9) Cores 128
22:21:50-029446 INFO     Verifying requirements
22:21:50-128678 INFO     No changes detected: Quick launch active
22:21:50-129680 INFO     Running extension preloading
22:21:50-130682 INFO     Server arguments: ['--theme=dark', '--autolaunch']
No module 'xformers'. Proceeding without it.
Checkpoint not found: None
Available models: C:\Users\hyper\webUI\Vladmandic\automatic\models\Stable-diffusion 0
Download the default model? (y/N) y
Downloading: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors" to C:\Users\hyper\webUI\Vladmandic\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 3.97G/3.97G [01:42<00:00, 41.7MB/s]
ControlNet v1.1.125
ControlNet v1.1.125
Loading theme: black-orange
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Checkpoint model.ckpt not found; loading fallback v1-5-pruned-emaonly.safetensors
Loading weights: C:\Users\hyper\webUI\Vladmandic\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors ━  -…
Creating model from config: C:\Users\hyper\webUI\Vladmandic\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Calculating sha256: C:\Users\hyper\webUI\Vladmandic\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa
Applying scaled dot product cross attention optimization
Embeddings loaded:  (0)
Model loaded in 11.4s (load=0.8s create=0.9s hash=4.5s apply=2.2s vae=1.6s move=1.3s embeddings=0.1s)
Startup time: 214.3s (torch=3.7s gradio=1.7s libraries=1.0s models=171.3s codeformer=0.1s scripts=21.2s ui=3.2s
start=0.3s scripts app_started_callback=0.1s checkpoint=11.8s)
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.99it/s]
 60%|█████████████████████████████████████████████████▏                                | 12/20 [00:04<00:02,  2.79it/s]Traceback (most recent call last):
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1133, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1120, in validate_inputs
    raise ValueError(
ValueError: An event handler (ranking_filter_settings) didn't receive enough input values (needed: 3, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [number, number, radio]
Received inputs:
    []
Traceback (most recent call last):
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1133, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1120, in validate_inputs
    raise ValueError(
ValueError: An event handler didn't receive enough input values (needed: 1, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [number]
Received inputs:
    []
Traceback (most recent call last):
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1133, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1120, in validate_inputs
    raise ValueError(
ValueError: An event handler didn't receive enough input values (needed: 1, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [number]
Received inputs:
    []
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.50it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.53it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.24it/s]
Traceback (most recent call last):
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1133, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1120, in validate_inputs
    raise ValueError(
ValueError: An event handler (ranking_filter_settings) didn't receive enough input values (needed: 3, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [number, number, radio]
Received inputs:
    []
Traceback (most recent call last):
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1133, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1120, in validate_inputs
    raise ValueError(
ValueError: An event handler didn't receive enough input values (needed: 1, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [number]
Received inputs:
    []
Traceback (most recent call last):
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1133, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1120, in validate_inputs
    raise ValueError(
ValueError: An event handler didn't receive enough input values (needed: 1, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [number]
Received inputs:
    []```

---------------------------------------------------------------------

even from fresh install, benchmark shows 1.4~2.7it/s.

oh, and the when I do --ckpt="C:\Users\hyper\webUI\models", I am getting `PermissionError: [Errno 13] Permission denied: 'C:\Users\hyper\webUI\models'`


### Version Platform Description

_No response_

**Comment by vladmandic** [comment]
See #675 - it's a top pinned issue for a reason.

**Comment by tigers2020** [comment]
the performance is back. but still I am getting errors after benchmarking.

```
Traceback (most recent call last):
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1133, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1120, in validate_inputs
    raise ValueError(
ValueError: An event handler (ranking_filter_settings) didn't receive enough input values (needed: 3, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [number, number, radio]
Received inputs:
    []
Traceback (most recent call last):
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1133, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1120, in validate_inputs
    raise ValueError(
ValueError: An event handler didn't receive enough input values (needed: 1, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [number]
Received inputs:
    []
Traceback (most recent call last):
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1133, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\Users\hyper\webUI\Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1120, in validate_inputs
    raise ValueError(
ValueError: An event handler didn't receive enough input values (needed: 1, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [number]
Received inputs:
    []
```

**Comment by vladmandic** [comment]
Can you either rename and reopen this issue or create a new one for those errors, I'll take a look tomorrow

**Comment by vladmandic** [comment]
> oh, and the when I do --ckpt="C:\Users\hyper\webUI\models", I am getting `PermissionError: [Errno 13] Permission denied: 'C:\Users\hyper\webUI\models'`

`--ckpt` should point to specific model FILE, not folder
if you want to point to model FOLDER, use `--models-dir`

btw, i cannot reproduce gradio issues - it almost looks like browser cache did not get cleared and updated when server was upgraded to use new gradio.
is that issue still persisting? just as a test, can you try on a second browser?

**Comment by vladmandic** [comment]
Original issue is resolved. If there are Gradio issues still occurring, please create a new issue.
