### ISSUE TITLE
[Issue]: Memory Error when loading models

### ISSUE THREAD

**Issue by zedmango** [vladmandic/automatic#755]
### Issue Description

When loading models, I get various memory errors. Many cannot be loaded at all, and some can only be loaded some of the time, but give errors most of the time.

For instance, when trying to load Cyberrealistic, I get the following:

```
Loading weights: C:\Users\J\AI Art\vlad\automatic\models\Stable-diffusion\cyberrealistic_v20.safetensors ━━━━ 5.7… 0:00:…                                                                                                              GB
SystemError: deallocated bytearray object has exported buffers
MemoryError
thread '<unnamed>' panicked at 'Python API call failed', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\pyo3-0.18.2\src\err\mod.rs:790:5
Loading weights: C:\Users\J\AI Art\vlad\automatic\models\Stable-diffusion\cyberrealistic_v20.safetensors ━━━━ 5.7… 0:00:…                                                                                                              GB
Traceback (most recent call last):
  File "C:\Users\J\AI Art\vlad\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\J\AI Art\vlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\Users\J\AI Art\vlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\J\AI Art\vlad\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\J\AI Art\vlad\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\J\AI Art\vlad\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\J\AI Art\vlad\automatic\modules\ui.py", line 1402, in <lambda>
    fn=lambda value, k=k: run_settings_single(value, key=k),
  File "C:\Users\J\AI Art\vlad\automatic\modules\ui.py", line 1253, in run_settings_single
    if not opts.set(key, value):
  File "C:\Users\J\AI Art\vlad\automatic\modules\shared.py", line 512, in set
    self.data_labels[key].onchange()
  File "C:\Users\J\AI Art\vlad\automatic\modules\call_queue.py", line 16, in f
    res = func(*args, **kwargs)
  File "C:\Users\J\AI Art\vlad\automatic\webui.py", line 162, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "C:\Users\J\AI Art\vlad\automatic\modules\sd_models.py", line 439, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "C:\Users\J\AI Art\vlad\automatic\modules\sd_models.py", line 244, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "C:\Users\J\AI Art\vlad\automatic\modules\sd_models.py", line 227, in read_state_dict
    pl_sd = safetensors.torch.load(buffer)
  File "C:\Users\J\AI Art\vlad\automatic\venv\lib\site-packages\safetensors\torch.py", line 288, in load
    flat = deserialize(data)
pyo3_runtime.PanicException: Python API call failed
```

When trying to load amIReal, I get the following:

```
Loading weights: C:\Users\J\AI Art\vlad\automatic\models\Stable-diffusion\amIReal_V2.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.3 GB -:--:--
10:11:19-706505 ERROR    loading model: C:\Users\J\AI Art\vlad\automatic\models\Stable-diffusion\amIReal_V2.safetensors: MemoryError
╭───────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────╮
│ C:\Users\J\AI Art\vlad\automatic\modules\sd_models.py:226 in read_state_dict                                                                                                                 │
│                                                                                                                                                                                              │
│   225 │   │   │   │   if extension.lower() == ".safetensors":                                                                                                                                │
│ ❱ 226 │   │   │   │   │   buffer = f.read()                                                                                                                                                  │
│   227 │   │   │   │   │   pl_sd = safetensors.torch.load(buffer)                                                                                                                             │
│                                                                                                                                                                                              │
│ C:\Users\J\AI Art\vlad\automatic\venv\lib\site-packages\rich\progress.py:237 in read                                                                                                         │
│                                                                                                                                                                                              │
│    236 │   def read(self, size: int = -1) -> bytes:                                                                                                                                          │
│ ❱  237 │   │   block = self.handle.read(size)                                                                                                                                                │
│    238 │   │   self.progress.advance(self.task, advance=len(block))                                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
MemoryError
Loading weights: C:\Users\J\AI Art\vlad\automatic\models\Stable-diffusion\amIReal_V2.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 GB 0:00:00
10:11:28-047520 INFO     Creating model from config: C:\Users\J\AI Art\vlad\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Calculating model hash: C:\Users\J\AI Art\vlad\automatic\models\Stable-diffusion\amIReal_V2.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 GB 0:00:00
10:11:33-530202 ERROR    changing setting sd_model_checkpoint to amIReal_V2.safetensors: RuntimeError
╭───────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────╮
│ C:\Users\J\AI Art\vlad\automatic\modules\shared.py:512 in set                                                                                                                                │
│                                                                                                                                                                                              │
│   511 │   │   │   try:                                                                                                                                                                       │
│ ❱ 512 │   │   │   │   self.data_labels[key].onchange()                                                                                                                                       │
│   513 │   │   │   except Exception as e:                                                                                                                                                     │
│                                                                                                                                                                                              │
│ C:\Users\J\AI Art\vlad\automatic\modules\call_queue.py:16 in f                                                                                                                               │
│                                                                                                                                                                                              │
│    15 │   │   with queue_lock:                                                                                                                                                               │
│ ❱  16 │   │   │   res = func(*args, **kwargs)                                                                                                                                                │
│    17                                                                                                                                                                                        │
│                                                                                                                                                                                              │
│                                                                                   ... 10 frames hidden ...                                                                                   │
│                                                                                                                                                                                              │
│ C:\Users\J\AI Art\vlad\automatic\venv\lib\site-packages\torch\nn\modules\module.py:820 in _apply                                                                                             │
│                                                                                                                                                                                              │
│    819 │   │   │   with torch.no_grad():                                                                                                                                                     │
│ ❱  820 │   │   │   │   param_applied = fn(param)                                                                                                                                             │
│    821 │   │   │   should_use_set_data = compute_should_use_set_data(param, param_applied)                                                                                                   │
│                                                                                                                                                                                              │
│ C:\Users\J\AI Art\vlad\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1001 in <lambda>                                                                                          │
│                                                                                                                                                                                              │
│   1000 │   │   """                                                                                                                                                                           │
│ ❱ 1001 │   │   return self._apply(lambda t: t.half() if t.is_floating_point() else t)                                                                                                        │
│   1002                                                                                                                                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 3276800 bytes.
```

### Version Platform Description

Version: 6f976c35 Tue May 2 21:30:31 2023 -0400

Windows 11, Firefox

**Comment by vladmandic** [comment]
what is your system? pretty much all errors are about not enough memory (and we're talking about system ram, not vram).
also, i've improved memory handling a bit in the latest version, please update and try again.

**Comment by zedmango** [comment]
Thank you for the quick response. I just did a git pull. 

Version: c470f399 Thu May 4 16:55:41 2023 -0400

I have 16GB system RAM, i7 Intel processor, RTX 3050 Ti with 4GB VRAM.

This fixed a lot of the problems. I can now load most models - 20 out of 23 will load at least sometimes. 

I still can't ever load the largest ones like CyberRealistic (5GB) and DreamShaper (7GB), and some of the other large ones load inconsistently - sometimes it crashes when I try to load, and sometimes the models load.

I'm not sure the crash is the same issue I originally reported - I am now not getting the tracebacks as reported above, but rather it just crashes.

**Comment by vladmandic** [comment]
can you run with `webui --debug` flag, it will print memory stats at each step of model loading?

but at the end, if dreamshaper (for example) is 7gb and you only have 4gb vram, even if running in fp16, it still may not work as there is always some reserved memory.

**Comment by zedmango** [comment]
ok, just did another git pull and added --debug flag to webui.bat

Version: 22e58809 Sat May 6 08:51:23 2023 -0400

All 23 models now seem to work perfectly. I was able to load them all without error and could not replicate the problem from before, even with the 7GB DreamShaper model! Thank you!
