### ISSUE TITLE
[Issue]: 2 Module 'tensorflow' has no attribute 'io'

### ISSUE THREAD

**Issue by Elgokoo** [vladmandic/automatic#820]
### Issue Description

The "automatic" doesn't work anymore for  reasons I tried to resolve by reinstall but didn't resolve it because of these 2 reasons below ( following the log):

1/ AttributeError: module 'tensorflow' has no attribute 'io'
2/ 2023-05-08 23:18:21,699 | ERROR | D:\artAI\Vladiffusion\installer.py | Error running extension installer: D:\artAI\Vladiffusion\extensions-builtin\clip-interrogator-ext\install.py

2023-05-08 23:17:55,696 | INFO | D:\artAI\Vladiffusion\installer.py | Starting SD.Next
2023-05-08 23:17:55,700 | INFO | D:\artAI\Vladiffusion\installer.py | Python 3.10.6 on Windows
2023-05-08 23:17:55,787 | DEBUG | D:\artAI\Vladiffusion\installer.py | Git 2.39.1.windows.1
2023-05-08 23:17:56,138 | INFO | D:\artAI\Vladiffusion\installer.py | Version: 22e58809 Sat May 6 08:51:23 2023 -0400
2023-05-08 23:17:56,545 | INFO | D:\artAI\Vladiffusion\installer.py | Latest published version: 4d9fab49848700de2814939228c842b2e0add24d 2023-05-08T15:56:59Z
2023-05-08 23:17:56,547 | INFO | D:\artAI\Vladiffusion\installer.py | Setting environment tuning
2023-05-08 23:17:56,550 | INFO | D:\artAI\Vladiffusion\installer.py | nVidia CUDA toolkit detected
2023-05-08 23:17:56,939 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: torch 2.0.0+cu118
2023-05-08 23:17:56,940 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: torchvision 0.15.1+cu118
2023-05-08 23:17:56,940 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: torchaudio 2.0.1+cu118
2023-05-08 23:17:58,356 | INFO | D:\artAI\Vladiffusion\installer.py | Torch 2.0.0+cu118
2023-05-08 23:17:58,376 | INFO | D:\artAI\Vladiffusion\installer.py | Torch backend: nVidia CUDA 11.8 cuDNN 8700
2023-05-08 23:17:58,378 | INFO | D:\artAI\Vladiffusion\installer.py | Torch detected GPU: NVIDIA GeForce RTX 3070 Laptop GPU VRAM 8192 Arch (8, 6) Cores 40
2023-05-08 23:17:58,380 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: tensorflow 2.12.0
2023-05-08 23:17:58,380 | INFO | D:\artAI\Vladiffusion\installer.py | Verifying requirements
2023-05-08 23:17:58,382 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: addict 2.4.0
2023-05-08 23:17:58,382 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: aenum 3.1.11
2023-05-08 23:17:58,382 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: aiohttp 3.8.4
2023-05-08 23:17:58,382 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: anyio 3.6.2
2023-05-08 23:17:58,383 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: appdirs 1.4.4
2023-05-08 23:17:58,383 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: astunparse 1.6.3
2023-05-08 23:17:58,384 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: basicsr 1.4.2
2023-05-08 23:17:58,384 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: bitsandbytes 0.35.0
2023-05-08 23:17:58,384 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: blendmodes 2022
2023-05-08 23:17:58,384 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: clean-fid 0.1.29
2023-05-08 23:17:58,384 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: easydev 0.12.1
2023-05-08 23:17:58,385 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: extcolors 1.0.0
2023-05-08 23:17:58,385 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: facexlib 0.2.5
2023-05-08 23:17:58,385 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: filetype 1.2.0
2023-05-08 23:17:58,385 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: font-roboto 0.0.1
2023-05-08 23:17:58,385 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: fonts 0.0.3
2023-05-08 23:17:58,386 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: future 0.18.3
2023-05-08 23:17:58,386 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: gdown 4.6.3
2023-05-08 23:17:58,386 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: gfpgan 1.3.8
2023-05-08 23:17:58,386 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: GitPython 3.1.31
2023-05-08 23:17:58,386 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: httpcore 0.15.0
2023-05-08 23:17:58,386 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: inflection 0.5.1
2023-05-08 23:17:58,386 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: jsonmerge 1.8.0
2023-05-08 23:17:58,387 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: kornia 0.6.7
2023-05-08 23:17:58,387 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: lark 1.1.2
2023-05-08 23:17:58,388 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: lmdb 1.4.0
2023-05-08 23:17:58,388 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: lpips 0.1.4
2023-05-08 23:17:58,388 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: numpy 1.23.3
2023-05-08 23:17:58,388 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: omegaconf 2.3.0
2023-05-08 23:17:58,389 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: open-clip-torch 2.16.0
2023-05-08 23:17:58,389 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: opencv-contrib-python 4.7.0.72
2023-05-08 23:17:58,389 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: piexif 1.1.3
2023-05-08 23:17:58,389 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: Pillow 9.4.0
2023-05-08 23:17:58,389 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: psutil 5.9.4
2023-05-08 23:17:58,390 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: pyyaml 6.0
2023-05-08 23:17:58,390 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: realesrgan 0.3.0
2023-05-08 23:17:58,391 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: requests 2.28.2
2023-05-08 23:17:58,391 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: resize-right 0.0.2
2023-05-08 23:17:58,391 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: rich 13.3.3
2023-05-08 23:17:58,391 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: safetensors 0.2.6
2023-05-08 23:17:58,391 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: scipy 1.10.0
2023-05-08 23:17:58,392 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: tb_nightly 2.13.0a20230410
2023-05-08 23:17:58,392 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: toml 0.10.2
2023-05-08 23:17:58,392 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: torch 2.0.0+cu118
2023-05-08 23:17:58,392 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: torchdiffeq 0.2.3
2023-05-08 23:17:58,392 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: torchsde 0.2.5
2023-05-08 23:17:58,393 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: torchvision 0.15.1+cu118
2023-05-08 23:17:58,393 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: voluptuous 0.13.1
2023-05-08 23:17:58,393 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: yapf 0.32.0
2023-05-08 23:17:58,393 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: scikit-image 0.19.2
2023-05-08 23:17:58,393 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: tqdm 4.65.0
2023-05-08 23:17:58,394 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: accelerate 0.18.0
2023-05-08 23:17:58,394 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: opencv-python 4.7.0.72
2023-05-08 23:17:58,394 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: diffusers 0.16.1
2023-05-08 23:17:58,394 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: einops 0.4.1
2023-05-08 23:17:58,394 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: gradio 3.28.1
2023-05-08 23:17:58,394 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: numexpr 2.8.4
2023-05-08 23:17:58,394 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: pandas 1.5.3
2023-05-08 23:17:58,394 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: protobuf 3.20.3
2023-05-08 23:17:58,395 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: pytorch_lightning 1.9.4
2023-05-08 23:17:58,395 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: transformers 4.26.1
2023-05-08 23:17:58,395 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: timm 0.6.13
2023-05-08 23:17:58,395 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: tomesd 0.1.2
2023-05-08 23:17:58,396 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: urllib3 1.26.15
2023-05-08 23:17:58,442 | DEBUG | D:\artAI\Vladiffusion\installer.py | Repository update time: Sat May  6 13:51:23 2023
2023-05-08 23:17:58,442 | INFO | D:\artAI\Vladiffusion\installer.py | Running setup
2023-05-08 23:17:58,443 | DEBUG | D:\artAI\Vladiffusion\installer.py | Args: {'config': 'D:\\artAI\\Vladiffusion\\config.json', 'medvram': False, 'lowvram': False, 'ckpt': None, 'vae': None, 'data_dir': 'D:\\artAI\\Vladiffusion', 'models_dir': 'models', 'allow_code': False, 'share': False, 'insecure': False, 'use_cpu': [], 'listen': False, 'port': 7860, 'freeze': False, 'auth': None, 'authfile': None, 'autolaunch': False, 'api_auth': None, 'api_log': False, 'device_id': None, 'cors_origins': None, 'cors_regex': None, 'tls_keyfile': None, 'tls_certfile': None, 'tls_selfsign': None, 'server_name': None, 'no_hashing': False, 'no_download': False, 'profile': False, 'disable_queue': False, 'f': False, 'ui_settings_file': 'D:\\artAI\\Vladiffusion\\config.json', 'ui_config_file': 'D:\\artAI\\Vladiffusion\\ui-config.json', 'hide_ui_dir_config': False, 'theme': None, 'disable_console_progressbars': True, 'disable_safe_unpickle': True, 'lowram': False, 'disable_extension_access': False, 'api': True, 'debug': False, 'reset': False, 'upgrade': False, 'use_ipex': False, 'use_directml': False, 'skip_update': False, 'skip_requirements': False, 'skip_extensions': False, 'skip_git': False, 'experimental': False, 'test': False, 'version': False, 'ignore': False}
2023-05-08 23:17:58,443 | INFO | D:\artAI\Vladiffusion\installer.py | Installing packages
2023-05-08 23:17:58,444 | DEBUG | D:\artAI\Vladiffusion\installer.py | Package version found: clip 1.0
2023-05-08 23:17:58,444 | INFO | D:\artAI\Vladiffusion\installer.py | Installing repositories
2023-05-08 23:17:58,811 | INFO | D:\artAI\Vladiffusion\installer.py | Installing submodules
2023-05-08 23:18:00,982 | DEBUG | D:\artAI\Vladiffusion\installer.py | Submodules list: 514511d7260635e0eb7b67cabcbce2a484387a97 extensions-builtin/a1111-sd-webui-lycoris (heads/main)
 9e6bbd9b8931bbe869a8e28e7005b0e13c2efff0 extensions-builtin/clip-interrogator-ext (heads/main)
+97fcc2ce5da0805edc00c490c88663884b54e38e extensions-builtin/multidiffusion-upscaler-for-automatic1111 (sd-webui-v1.1.0-6-g97fcc2c)
 5d3465c4b2d5dacfdd6caa38b71b23b4f88401c0 extensions-builtin/sd-dynamic-thresholding (heads/master)
 896b6aa034127e8064ae5fdd6370f351e0755475 extensions-builtin/sd-extension-aesthetic-scorer (heads/main)
+79de908d19a3e3128e7defd023b30e1a9d065e3e extensions-builtin/sd-extension-steps-animation (heads/main)
+21d204a502ddf90e5191802d4673e8df5b1ab4ef extensions-builtin/sd-extension-system-info (heads/main)
+c9c8ca6eee86e0fa4dec9f5e62a5f34e38ae1707 extensions-builtin/sd-webui-controlnet (heads/main)
 d19e28168268b0f2f50c8a5b7a4fa0a0d9b42b8c extensions-builtin/sd-webui-model-converter (heads/main)
 4bc8b2f10d5c12958f48b67ad23fb445aff074df extensions-builtin/seed_travel (heads/main)
+e535ea6aea2356a13da3e0452b92b3d68861f539 extensions-builtin/stable-diffusion-webui-images-browser (heads/main)
 64821f04767b04b92ac157f3c02f28d269dba5d8 extensions-builtin/stable-diffusion-webui-rembg (heads/master)
+3b1af3f1a63b858af8c12662cbae70654229e327 modules/lora (v0.6.3-32-g3b1af3f)
 8b47a5349b59efac812664c5732c6e3947a6fec7 modules/lycoris (heads/main)
+d420606fc4f9735aa0a4d31f6e5ef18429508ab9 wiki (heads/master)
2023-05-08 23:18:02,875 | INFO | D:\artAI\Vladiffusion\installer.py | Updating submodules
2023-05-08 23:18:04,242 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/a1111-sd-webui-lycoris / main
2023-05-08 23:18:04,931 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/clip-interrogator-ext / main
2023-05-08 23:18:05,577 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/multidiffusion-upscaler-for-automatic1111 / main
2023-05-08 23:18:06,219 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/sd-dynamic-thresholding / master
2023-05-08 23:18:06,969 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/sd-extension-aesthetic-scorer / main
2023-05-08 23:18:07,782 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/sd-extension-steps-animation / main
2023-05-08 23:18:08,472 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/sd-extension-system-info / main
2023-05-08 23:18:09,249 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/sd-webui-controlnet / main
2023-05-08 23:18:10,029 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/sd-webui-model-converter / main
2023-05-08 23:18:11,079 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/seed_travel / main
2023-05-08 23:18:11,914 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/stable-diffusion-webui-images-browser / main
2023-05-08 23:18:12,829 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: extensions-builtin/stable-diffusion-webui-rembg / master
2023-05-08 23:18:13,587 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: modules/lora / main
2023-05-08 23:18:14,456 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: modules/lycoris / main
2023-05-08 23:18:15,309 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: wiki / master
2023-05-08 23:18:16,501 | INFO | D:\artAI\Vladiffusion\installer.py | Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
2023-05-08 23:18:16,554 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\a1111-sd-webui-lycoris / main
2023-05-08 23:18:17,313 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\clip-interrogator-ext / main
2023-05-08 23:18:17,927 | DEBUG | D:\artAI\Vladiffusion\installer.py | Running extension installer: D:\artAI\Vladiffusion\extensions-builtin\clip-interrogator-ext / D:\artAI\Vladiffusion\extensions-builtin\clip-interrogator-ext\install.py
**2023-05-08 23:18:21,699 | ERROR | D:\artAI\Vladiffusion\installer.py | Error running extension installer: D:\artAI\Vladiffusion\extensions-builtin\clip-interrogator-ext\install.py**
2023-05-08 23:18:21,700 | DEBUG | D:\artAI\Vladiffusion\installer.py | 
Traceback (most recent call last):

  File "D:\artAI\Vladiffusion\extensions-builtin\clip-interrogator-ext\install.py", line 7, in <module>

    import clip_interrogator

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\clip_interrogator\__init__.py", line 1, in <module>

    from .clip_interrogator import Interrogator, Config

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\clip_interrogator\clip_interrogator.py", line 12, in <module>

    from blip.models.blip import blip_decoder, BLIP_Decoder

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\blip\models\blip.py", line 12, in <module>

    from .med import BertConfig, BertModel, BertLMHeadModel

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\blip\models\med.py", line 39, in <module>

    from transformers.modeling_utils import (

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 83, in <module>

    from accelerate import __version__ as accelerate_version

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\__init__.py", line 3, in <module>

    from .accelerator import Accelerator

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\accelerator.py", line 37, in <module>

    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\tracking.py", line 42, in <module>

    from torch.utils import tensorboard

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>

    from .writer import FileWriter, SummaryWriter  # noqa: F401

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>

    from ._embedding import (

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>

    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")

  File "C:\Users\elgokoo\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__

    return getattr(load_once(self), attr_name)

AttributeError: module 'tensorflow' has no attribute 'io'

2023-05-08 23:18:21,747 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\multidiffusion-upscaler-for-automatic1111 / main
2023-05-08 23:18:22,451 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\sd-dynamic-thresholding / master
2023-05-08 23:18:23,239 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\sd-extension-aesthetic-scorer / main
2023-05-08 23:18:23,977 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\sd-extension-steps-animation / main
2023-05-08 23:18:24,756 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\sd-extension-system-info / main
2023-05-08 23:18:25,408 | DEBUG | D:\artAI\Vladiffusion\installer.py | Running extension installer: D:\artAI\Vladiffusion\extensions-builtin\sd-extension-system-info / D:\artAI\Vladiffusion\extensions-builtin\sd-extension-system-info\install.py
2023-05-08 23:18:25,719 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\sd-webui-controlnet / main
2023-05-08 23:18:26,443 | DEBUG | D:\artAI\Vladiffusion\installer.py | Running extension installer: D:\artAI\Vladiffusion\extensions-builtin\sd-webui-controlnet / D:\artAI\Vladiffusion\extensions-builtin\sd-webui-controlnet\install.py
2023-05-08 23:18:27,105 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\sd-webui-model-converter / main
2023-05-08 23:18:27,919 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\seed_travel / main
2023-05-08 23:18:28,703 | DEBUG | D:\artAI\Vladiffusion\installer.py | Running extension installer: D:\artAI\Vladiffusion\extensions-builtin\seed_travel / D:\artAI\Vladiffusion\extensions-builtin\seed_travel\install.py
2023-05-08 23:18:29,375 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\stable-diffusion-webui-images-browser / main
2023-05-08 23:18:30,076 | DEBUG | D:\artAI\Vladiffusion\installer.py | Running extension installer: D:\artAI\Vladiffusion\extensions-builtin\stable-diffusion-webui-images-browser / D:\artAI\Vladiffusion\extensions-builtin\stable-diffusion-webui-images-browser\install.py
2023-05-08 23:18:30,722 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\extensions-builtin\stable-diffusion-webui-rembg / master
2023-05-08 23:18:31,644 | DEBUG | D:\artAI\Vladiffusion\installer.py | Running extension installer: D:\artAI\Vladiffusion\extensions-builtin\stable-diffusion-webui-rembg / D:\artAI\Vladiffusion\extensions-builtin\stable-diffusion-webui-rembg\install.py
2023-05-08 23:18:32,412 | INFO | D:\artAI\Vladiffusion\installer.py | Extensions enabled: []
2023-05-08 23:18:32,413 | INFO | D:\artAI\Vladiffusion\installer.py | Updating Wiki
2023-05-08 23:18:32,461 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\wiki / master
2023-05-08 23:18:33,131 | DEBUG | D:\artAI\Vladiffusion\installer.py | Setting branch: D:\artAI\Vladiffusion\wiki\origin-wiki / master
2023-05-08 23:18:33,773 | WARNING | D:\artAI\Vladiffusion\installer.py | Setup complete with errors (1)
2023-05-08 23:18:33,775 | WARNING | D:\artAI\Vladiffusion\installer.py | See log file for more details: setup.log
2023-05-08 23:18:33,776 | INFO | D:\artAI\Vladiffusion\installer.py | Running extension preloading
2023-05-08 23:18:33,781 | INFO | D:\artAI\Vladiffusion\launch.py | Server arguments: []
2023-05-08 23:18:33,782 | DEBUG | D:\artAI\Vladiffusion\launch.py | Starting WebUI

### Version Platform Description

Windows 10

**Comment by vladmandic** [comment]
try running this to get more info:

```shell
venv\Scripts\activate

pip show torch
pip show tensorflow
pip show tensorboard

python
from torch.utils import tensorboard
exit()
```

**Comment by Elgokoo** [comment]
I have reinstalled the full package by cloning the full Git , so problem resolved
