### ISSUE TITLE
[Issue]: An event handler error when updating extensions

### ISSUE THREAD

**Issue by solsol360** [vladmandic/automatic#869]
### Issue Description

After extensions tab rework when I click "Update installed extensions" i get errors:

Traceback (most recent call last):
  File "D:\automatic\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1313, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1151, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1138, in validate_inputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough input values (needed: 4, got: 2).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [html, textbox, textbox, dropdown]
Received inputs:
    ["task(rge0frlqbrmruco)", "[]"]

Restarted the service, but problem persist.

### Version Platform Description

Python 3.10.9 on Windows
Version: 7921cc2b Thu May 11 11:30:03 2023 -0400
Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10239 Arch (8, 6) Cores 68

**Comment by solsol360** [comment]
I disabled all user installed extensions and now update gives:
Traceback (most recent call last):
  File "D:\automatic\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1313, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1151, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1138, in validate_inputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough input values (needed: 4, got: 2).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [html, textbox, textbox, dropdown]
Received inputs:
    ["task(csq7swjh84pgrky)", "["SD-CN-Animation","sd-dynamic-prompts","canvas-zoom","ultimate-upscale-for-automatic1111","sd-webui-aspect-ratio-helper"]"]

**Comment by vladmandic** [comment]
fixed.
