### ISSUE TITLE
[Issue]: RuntimeError: unexpected EOF, expected 3004407 more bytes. The file might be corrupted

### ISSUE THREAD

**Issue by demib72** [vladmandic/automatic#892]
### Issue Description

Hello, I am not normally the the type to make issue tickets. There is another ticket that might be related, but it has been closed. I have recently installed automatic and looking to make use of controlnet. The program downloads https://huggingface.co/lllyasviel/Annotators/resolve/main/body_pose_model.pth just fine. But then it spits out this:

Traceback (most recent call last):
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/gradio/blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/Applications/automatic/extensions-builtin/sd-webui-controlnet/scripts/controlnet.py", line 478, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b, json_pose_callback=json_acceptor.accept)
  File "/home/user/Applications/automatic/extensions-builtin/sd-webui-controlnet/scripts/processor.py", line 248, in run_model
    return remove_pad(self.model_openpose(
  File "/home/user/Applications/automatic/extensions-builtin/sd-webui-controlnet/annotator/openpose/__init__.py", line 258, in __call__
    poses = self.detect_poses(oriImg, include_hand, include_face)
  File "/home/user/Applications/automatic/extensions-builtin/sd-webui-controlnet/annotator/openpose/__init__.py", line 202, in detect_poses
    self.load_model()
  File "/home/user/Applications/automatic/extensions-builtin/sd-webui-controlnet/annotator/openpose/__init__.py", line 138, in load_model
    self.face_estimation = Face(face_modelpath)
  File "/home/user/Applications/automatic/extensions-builtin/sd-webui-controlnet/annotator/openpose/face.py", line 325, in __init__
    self.model.load_state_dict(torch.load(face_model_path))
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/user/Applications/automatic/auto-venv/lib/python3.10/site-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 3004407 more bytes. The file might be corrupted.

I have tried manually downloading it and copying over my existing copy of the file, same result. Tried looking for the source of the runtime, but haven't had any luck.

### Version Platform Description

Version: aad2a533 Tue May 9 17:27:23 2023 -0400
OS: Pop OS

**Comment by vladmandic** [comment]
quick question - what is the output of `ls -la extensions-builtin/sd-webui-controlnet/annotator/downloads/openpose/`

**Comment by demib72** [comment]
I honestly just purged the folder and tried again to get it to work, so it likely was a directory permissions issue. When I input the command I get the following:

drwxrwxr-x 2 username username      4096 May 12 14:30 .
drwxrwxr-x 9 username username      4096 May 12 14:24 ..
-rw------- 1 username username 209267595 May 12 14:27 body_pose_model.pth
-rw------- 1 username username 153718792 May 12 14:30 facenet.pth
-rw------- 1 username username 147341049 May 12 14:29 hand_pose_model.pth

**Comment by demib72** [comment]
Just to understand so I don't waste time in the future, why would directory permissions be the cause? The files downloaded were always the same size.

**Comment by Gerkinfeltser** [comment]
Thank you @demib72, removing the `extensions-builtin/sd-webui-controlnet/annotator/downloads/openpose/` stuff did the trick for me as well!
