### ISSUE TITLE
[Extension]: mov2mov generate throw exception

### ISSUE THREAD

**Issue by WhatAKitty** [vladmandic/automatic#945]
### Issue Description

```
23:01:41-059578 ERROR    gradio call: AttributeError
╭───────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────╮
│ /Users/xuqiang/Work/devTools/automatic/modules/call_queue.py:59 in f                                                                         │
│                                                                                                                                              │
│    58 │   │   │   │   pr.enable()                                                                                                            │
│ ❱  59 │   │   │   res = list(func(*args, **kwargs))                                                                                          │
│    60 │   │   │   if shared.cmd_opts.profile:                                                                                                │
│                                                                                                                                              │
│ /Users/xuqiang/Work/devTools/automatic/modules/call_queue.py:38 in f                                                                         │
│                                                                                                                                              │
│    37 │   │   │   try:                                                                                                                       │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                                            │
│    39 │   │   │   │   progress.record_results(id_task, res)                                                                                  │
│                                                                                                                                              │
│ /Users/xuqiang/Work/devTools/automatic/extensions/sd-webui-mov2mov/scripts/mov2mov.py:228 in mov2mov                                         │
│                                                                                                                                              │
│   227 │                                                                                                                                      │
│ ❱ 228 │   if shared.cmd_opts.enable_console_prompts:                                                                                         │
│   229 │   │   print(f"\nmov2mov: {prompt}", file=shared.progress_print_out)                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'enable_console_prompts'
Traceback (most recent call last):
  File "/Users/xuqiang/Work/devTools/automatic/venv/lib/python3.10/site-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/xuqiang/Work/devTools/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/xuqiang/Work/devTools/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1206, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/Users/xuqiang/Work/devTools/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1181, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 4).
Wanted outputs:
    [gallery, video, textbox, html, html]
Received outputs:
    [None, "", "", "<div class='error'>AttributeError: &#x27;Namespace&#x27; object has no attribute &#x27;enable_console_prompts&#x27;</div><div class='performance'><p class='time'>Time taken: 0.02s</p></div>"]

```

### Version Platform Description

mov2mov: master
vlad: master

### URL link of the extension

https://github.com/Scholar01/sd-webui-mov2mov

**Comment by vladmandic** [comment]
i hate when extensions try to read unnecessary and internal variables from core repo, in this case `enable_console_prompts`.
but ok, i've added it to silly compatibility list that this repo maintains, fixed.
