### ISSUE TITLE
[Extension]: CLIP Interrogator isn't working

### ISSUE THREAD

**Issue by sergiohzph** [vladmandic/automatic#997]
### Issue Description

Last night I was using this extension for quite a while, it was working fine, now it throws error.
![image](https://github.com/vladmandic/automatic/assets/132315597/cb556a83-4dd5-427d-a38b-f596aae94d0b)

```
Loading CLIP Interrogator 0.5.4...
load checkpoint from D:\Software\Stable Diffusion\vladmandic's A1111\models\BLIP\model_base_caption_capfilt_large.pth
Loading CLIP model...
Loaded CLIP model and data in 5.22 seconds.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\extensions-builtin\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 127, in image_to_prompt
    prompt = interrogate(image, mode)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\extensions-builtin\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 103, in interrogate
    prompt = ci.interrogate(image, caption=caption)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 256, in interrogate
    flaves = merged.rank(image_features, self.config.flavor_intermediate_count)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 399, in rank
    for chunk_idx in tqdm(range(num_chunks), disable=self.config.quiet):
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 383, in __new__
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 68, in __init__
AttributeError: module 'sys' has no attribute 'setcheckinterval'
Exception ignored in: <function tqdm.__del__ at 0x0000024F48696E60>
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 764, in __del__
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 994, in close
AttributeError: 'tqdm' object has no attribute 'disable'
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\extensions-builtin\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 127, in image_to_prompt
    prompt = interrogate(image, mode)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\extensions-builtin\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 103, in interrogate
    prompt = ci.interrogate(image, caption=caption)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 256, in interrogate
    flaves = merged.rank(image_features, self.config.flavor_intermediate_count)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 399, in rank
    for chunk_idx in tqdm(range(num_chunks), disable=self.config.quiet):
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 383, in __new__
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 68, in __init__
AttributeError: module 'sys' has no attribute 'setcheckinterval'
Exception ignored in: <function tqdm.__del__ at 0x0000024F48696E60>
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 764, in __del__
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 994, in close
AttributeError: 'tqdm' object has no attribute 'disable'
Loading CLIP model...
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\extensions-builtin\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 125, in image_to_prompt
    load(clip_model_name)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\extensions-builtin\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 69, in load
    ci.load_clip_model()
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 101, in load_clip_model
    self.clip_model, _, self.clip_preprocess = open_clip.create_model_and_transforms(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\open_clip\factory.py", line 308, in create_model_and_transforms
    model = create_model(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\open_clip\factory.py", line 145, in create_model
    model = load_openai_model(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\open_clip\openai.py", line 56, in load_openai_model
    model_path = download_pretrained_from_url(get_pretrained_url(name, 'openai'), cache_dir=cache_dir)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\open_clip\pretrained.py", line 365, in download_pretrained_from_url
    with tqdm(total=int(source.headers.get("Content-Length")), ncols=80, unit='iB', unit_scale=True) as loop:
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 383, in __new__
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 68, in __init__
AttributeError: module 'sys' has no attribute 'setcheckinterval'
Exception ignored in: <function tqdm.__del__ at 0x0000024F48696E60>
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 764, in __del__
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 994, in close
AttributeError: 'tqdm' object has no attribute 'disable'
Loading CLIP model...
Downloading (…)ip_pytorch_model.bin: 100%|████████████████████████████████████████| 3.94G/3.94G [00:51<00:00, 76.4MB/s]
Failed to download https://huggingface.co/pharma/ci-preprocess/resolve/main/ViT-H-14_laion2b_s32b_b79k_artists.safetensors
module 'sys' has no attribute 'setcheckinterval'
Exception ignored in: <function tqdm.__del__ at 0x0000024F48696E60>
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 764, in __del__
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 994, in close
AttributeError: 'tqdm' object has no attribute 'disable'
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\extensions-builtin\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 125, in image_to_prompt
    load(clip_model_name)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\extensions-builtin\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 69, in load
    ci.load_clip_model()
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 128, in load_clip_model
    self.artists = LabelTable(artists, "artists", self.clip_model, self.tokenize, config)
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 327, in __init__
    for chunk in tqdm(chunks, desc=f"Preprocessing {desc}" if desc else None, disable=self.config.quiet):
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 383, in __new__
  File "D:\Software\Stable Diffusion\vladmandic's A1111\venv\lib\site-packages\tqdm\_tqdm.py", line 68, in __init__
AttributeError: module 'sys' has no attribute 'setcheckinterval'
```

### Version Platform Description

`Version: 8350b93a Mon May 15 09:32:20 2023 -0400`
OS: Windows 11
Browser: Microsoft Edge

### URL link of the extension

https://github.com/pharmapsychotic/clip-interrogator-ext

**Comment by vladmandic** [comment]
i don't think this has to do with extension at all, it looks like something downgraded core packages - likely some other extension.
can you run `webui --reinstall` and check?

**Comment by vladmandic** [comment]
huh, numpy is also totally wrong version - i wonder what installed all those incorrect packages.
you can either do fresh install or run `reinstall` couple of times so it can fix it, but given how deep this rathole goes, fresh install may be best. you've installed something that totally corrupted required package versions.

**Comment by vladmandic** [comment]
ony one i've used from the list is inspiration and i know that one doesn't cause problems. the rest, i haven't ever try.

**Comment by vladmandic** [comment]
@sergiohzph just wondering if you have any updates?

**Comment by naturevie02** [comment]
Hello, 

I write in this issue because i have a very similar problem than @sergiohzph. 

When i launch the webuser.bat everything is loaded normaly i can open up the url ans stable diffusion, then if i try to type something in the prompt, i have a red message saying "error" then i have the following message in the command prompt webuser.bat (which is very the same than @sergiohzph ), i precise that everything worked well something like 2 week ago, i havent change anything since so i don't know why i have this error and wondering if someone could help me ?

![Capture](https://github.com/vladmandic/automatic/assets/134331821/6c108d1b-64ed-4ac9-a30a-dedeff5a176f)

**Comment by vladmandic** [comment]
You have wrong package `clip`.
I don't know who or how it got installed, but remove it and installer will automatically install correct one.

**Comment by naturevie02** [comment]
@vladmandic thank you for your answer, i have tried to delete the "clip" folder in \stable-diffusion-webui\venv\Lib\site-packages\ then launch the installer and i have this following error. The most weard is as you can see, it is notified that "clip" is installing and it doesnt block at this point. If i go look in \stable-diffusion-webui\venv\Lib\site-packages\ the "clip" folder has not been created despite it said the contrary in the installation. Have youn an idea ? Thank you for your help !
![Capture2](https://github.com/vladmandic/automatic/assets/134331821/9becad40-8d69-4d03-925c-ec947cbe647d)

**Comment by vladmandic** [comment]
that is really strange.
lets try to do it manually?

```shell
venv\Scripts\activate
pip uninstall clip
pip install git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
pip show clip
```

**Comment by naturevie02** [comment]
@vladmandic hello, i tried your idea, so,  this time i could have launched stable diffusion and get the url (i didn't have the previous error where clip wasn't found( the clip folder is present, pip show clip respond well)) but unfortunatly, i still have the same error than the beginning, thank you again for your help !
![Capture](https://github.com/vladmandic/automatic/assets/134331821/965f57db-241b-440f-a851-429bdd91629f)

**Comment by naturevie02** [comment]
hello, here the 2 capture of pip show clip and the commands, thanks again
![Capture3](https://github.com/vladmandic/automatic/assets/134331821/6f71ccfc-9288-4c94-a7ab-2681548987b0)
![Capture4](https://github.com/vladmandic/automatic/assets/134331821/17b5f25e-bddd-4c6c-8bcc-c9c30852da5f)
